### ISSUE TITLE
How to using miraclecast in arch linux

### ISSUE THREAD

**Issue by ljbhander** [albfan/miraclecast#10]
I install a arch linux system to test it.
Follow the steps https://github.com/albfan/miraclecast.

First i test the wifi and environment

iw list:
Supported interface modes:
* IBSS
* managed
* AP
* AP/VLAN
* monitor
* mesh point
* P2P-client
* P2P-GO

[root@nbpt res]# ./res/test_viewer.sh 
testing plugins required:

test udpsrc... (passed)
test rtpjitterbuffer... (passed)
test rtpmp2tdepay... (passed)
test tsdemux... (passed)
test h264parse... (passed)
test avdec_h264... (passed)
test autovideosink... (passed)

everything installed

[root@nbpt res]#

I set the res/miracle-wifi.sh with the propriety wifi device name.
I add some lines at the end of res/wpa.conf:
network={
ssid="TP-LINK_6122"
psk="nbpt5200"
}

Then:
res/miracle-wifi.sh
miracle-dhcp --netdev wls35u1(My wifi device name)
miracle-wifid &

[root@nbpt nbpt]# miracle-sinkctl 
[ADD] Link: 3
[miraclectl] # list
LINK INTERFACE FRIENDLY-NAME

3 wls35u1 nbpt

LINK PEER-ID FRIENDLY-NAME CONNECTED

0 peers and 1 links listed.
[miraclectl] # run 3
now running on link 3
[miraclectl] # list
LINK INTERFACE FRIENDLY-NAME

3 wls35u1 nbpt

LINK PEER-ID FRIENDLY-NAME CONNECTED

0 peers and 1 links listed.
[ADD] Peer: 6a:76:4f:b4:c2:75@3 (here use my phone to mirror, My pc did recognize my phone)
[miraclectl] # help
Available commands:
list List all objects
show Show detailed object information
run Run sink on given link
bind Like 'run' but bind the link name to run when it is hotplugged
quit Quit program
help Print help
[miraclectl] # show 3
Link=3
InterfaceIndex=3
InterfaceName=wls35u1
FriendlyName=nbpt
P2PScanning=1
WfdSubelements=000600111c4400c8
[miraclectl] # list
LINK INTERFACE FRIENDLY-NAME

3 wls35u1 nbpt

LINK PEER-ID FRIENDLY-NAME CONNECTED 
3 6a:76:4f:b4:c2:75@3 Sink-B4C275 no

1 peers and 1 links listed.
[miraclectl] #
[REMOVE] Peer: 6a:76:4f:b4:c2:75@3
[miraclectl] # 
But finally my phone(Sony z1) not connected my pc, 
Is there some steps should to do?

**Comment by albfan** [comment]
At this point your mobile should detect your pc as a target for mirroring
its screen on pc.

Process of pairing may vary from mobile to mobile, but once paired you
should see a gstreamer window with your mobile screen mirrored on pc.
Congratulations!

`miracle-wifctl` acts on inverse direction: Pc-> mobile. But there's no
service implemented yet. You can launch

    connect <peer> pbc
    connect <peer> display
    connect <peer> keypad 1111

on it to see different starts of pairing but after that nothing useful will
happen.

**Comment by ljbhander** [comment]
I have test for 2 phones, sony z1 and sunsang G3813, but both connect failed.

I download a android app called "Miracast Player" , install it in a tablat and run it as a miracast server.
Then the sony z1 and sunsang G3813 could connect it.

Is there my environment still have mistake or my step loss some ?
My arch linux is download from http://mirror.metrocast.net/archlinux/iso/2015.03.01/.
I install the i686 platform.

May i known your pc environment or your test phone type?

**Comment by thopiekar** [comment]
Haven't tested it on my own, but I read that in case you have Lollipop installed there is a commandline tool for this. You won't have to install an app, as it is shipped with the ROM by default.
Well, but I can be wrong..

**Comment by albfan** [comment]
systemd is so actively that something seems broken for miraclecast

I will check last known configuration working with "Arch Rollback machine"

https://wiki.archlinux.org/index.php/Arch_Rollback_Machine

and provide a exact environment to chek miraclecast

miraclecast is known to work on systemd 213 which was installed on arch linux around 2014/06 - 2014/07

**Comment by albfan** [comment]
This package should help to install without headaches

https://aur.archlinux.org/packages/systemd-kdbus/

also I have updated miraclecast

https://aur.archlinux.org/packages/miraclecast-github/

Maintain that is an endless feature, so I will close this issue. Expect those AUR packages to be updated from time to time
