### ISSUE TITLE
wpa_supplicant does not support wifi-display on Fedora 23

### ISSUE THREAD

**Issue by foamboarder** [albfan/miraclecast#101]
I'm getting the following error when running miracle-wifid:
WARNING: supplicant: wpa_supplicant does not support wifi-display (supplicant_status_fn() in ../../../src/wifi/wifid-supplicant.c:1768)

This is similar to #50, but I'm on Fedora release 23. I'm also using wpa_supplicant v2.4. Per test-hardware-capabilities.sh, my device supports P2P as well.

**Comment by foamboarder** [comment]
Closing this issue as I have switched over to Ubuntu instead

**Comment by albfan** [comment]
Well, If you have fedora avaliable yet, check if you did install dbus policy

**Comment by jdieter** [comment]
Just to leave a record, I've checked this and Fedora's wpa_supplicant doesn't have CONFIG_WIFI_DISPLAY enabled.  I've rebuilt wpa_supplicant with that flag enabled, and I've now at least reached the point where miraclecast is showing up on my phone's Cast screen as a sink.

**Comment by albfan** [comment]
Good to know. Any detail instructions?

**Comment by jdieter** [comment]
I've submitted a patch to fix it at https://bugzilla.redhat.com/show_bug.cgi?id=1395682.  Hopefully, it will get into Fedora 24+.
