### ISSUE TITLE
Fixing install of dbus policy and AUR package

### ISSUE THREAD

**Issue by tiberiomoliveira** [albfan/miraclecast#107]
Hi,

I was trying to install the miracast on arch linux but the following error showed up:
`install: cannot stat '/home/tiberio/Downloads/aur/builds/miraclecast/src/../org.freedesktop.miracle.conf': No such file or directory`
Looking at the path it's easy to see that the '..' is not right as the file _org.fredesktop.miracle.conf_ is inside the _src_ path. Thus, the last line of the package() script block of the file PKGBUILD, instead of having:
`install -Dm644 "$srcdir/../org.freedesktop.miracle.conf"...`
it will have:
`install -Dm644 "$srcdir/org.freedesktop.miracle.conf"...`
and now I can install the miracast successfully.

Tears.

**Comment by albfan** [comment]
That was a recent cobtribution, but I can see that file on `$srcdir/..` See:

https://github.com/albfan/aur-miraclecast

Maybe it would be better to use just `$startdir`. How did you download aur package?

Can you test this and report results?

    $ git clone  https://aur.archlinux.org/miraclecast.git
    $ cd miraclecast
    $ makepkg -si

**Comment by tiberiomoliveira** [comment]
You are right, definitely the file is on `$srcdir/..`.
Maybe because I have my `BUILDDIR` set on `makepkg.conf`, and yes, I've used the same commands you are asking me to test. I will try to disable the `BUILDDIR` and see what happens.

**Comment by albfan** [comment]
Definitely something to work on. That file is really on miraclecast sources  (res/ directory) and in aur package is just a static file ( hard to maintain)

Do you want to provide a PR here and on albfan/aur-miraclecast? Read this for automake and cmake configuration:

- http://stackoverflow.com/questions/8442824/cmake-rpm-installing-a-file-in-etc-init-d
- http://stackoverflow.com/questions/7190492/configuration-files-and-log-files-installation-with-automake

Seems that is a standard way to install on etc/:

https://github.com/systemd/systemd/blob/master/autogen.sh#L39

**Comment by tiberiomoliveira** [comment]
Yes, I can do this, as soon as I get some spare time I will do it.

**Comment by grawity** [comment]
`$startdir` is obsolete and should not be used. As long as files are mentioned in `sources=()`, makepkg will always symlink them to `$srcdir/`.
