### ISSUE TITLE
ubuntu PC dosen't show any mirroring

### ISSUE THREAD

**Issue by zwqaoy** [albfan/miraclecast#109]
hello
follow your step,  the android phone connect the Ubuntu PC success, and show the following log:

[PROV] Peer: ba:64:91:cd:28:77@3 Type: pbc PIN: 
[GO NEG] Peer: ba:64:91:cd:28:77@3 Type: pbc PIN: 
[PROV] Peer: ba:64:91:cd:28:77@3 Type: pbc PIN: 
[CONNECT] Peer: ba:64:91:cd:28:77@3
now running on peer ba:64:91:cd:28:77@3
NOTICE: SINK connected

and then, the Ubuntu PC doesn't show anything,  so i will try to use command of "miracle-gst -p 1991",  it is failure also, and the log as follow:

running: /usr/bin/gst-launch-1.0 -v udpsrc port=1991 caps="application/x-rtp, media=video" ! rtpjitterbuffer latency=100 ! rtpmp2tdepay ! tsdemux ! queue max-size-buffers=0 max-size-time=0 ! h264parse ! avdec_h264 ! videoconvert ! autovideosink 
WARNING: erroneous pipeline: no element "tsdemux

thanks
@albfan

**Comment by albfan** [comment]
Did you check all gst plugins are installed. Check with test-viewer.sh on res/ directory.

**Comment by zwqaoy** [comment]
hello

thanks very much, this issue is solved after install the gst plugins.

thaks

**Comment by albfan** [comment]
A long postponed task is to add that check to `configure` or `cmake` and warn before this happen.

As doc says: ``
