### ISSUE TITLE
Add per user config file

### ISSUE THREAD

**Issue by albfan** [albfan/miraclecast#113]
Use

https://github.com/ndevilla/iniparser 

Or similar to parse, add and save config, even on the fly from ctls.

Use `~/.miraclecast` as default file

**Comment by grawity** [comment]
Since miraclecast already depends on glib, it could use [GKeyFile](https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html) as the ini parser.

There's also ini_parse from ding-libs. (I've seen some projects, i.e. gss-proxy, claim that iniparser is poor-quality.)

As for the default path, [g_get_user_config_dir()](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-user-config-dir) please; enough of the dotfile litter.

**Comment by albfan** [comment]
I was looking glib doc and though it was only a ini parser. it allows to edit and modify - great- so is a much better choose.

About config file, I must confess I love dotfile litter. I'm agreed it is garbage, and `XDG_CONFIG_HOME` dir and normal files are prettier, but feel like `~/.config/miraclecast/config` is more obscure than `~/.miraclecast`. At least both files should be supported in a first implementation.

Some simple goals to implement:

- configure log level for miracle-wifid and miracle-sinkctl
- configure execution (port, uibc, resolution)
- configure external player (replace predefined variables as `$PORT` or `$IP` would be needed) It will be used in `launch_player()` function
- configure autorun (see `cmd_bind()` and `bound_link` variable)

**Comment by albfan** [comment]
- Use `~/.config/miraclecastrc` as filepath.
- follow https://github.com/joehakimrahme/Agros/wiki/Parsing-the-conf-file-with-GLib as tutorial
- implement upon external-player, a feature is already implemented
- implement an autocommand (like run 3 for miracle-sinkctl) or log-level
- allow to overwrite config file (for testing config, etc...)

**Comment by albfan** [comment]
https://github.com/albfan/miraclecast/tree/wip/ini-files is an inital implementation

As miracle-wifid needs to run with sudo, file `/root/.miraclecast` or `/root/.config/miraclecastrc` with this contents

```
[wifid]
log-level=trace
```

will config log level to trace

when run with sudo, there's a `SUDO_USER` env to find normal user behind sudo, but something like polkit is a better solution #185

**Comment by derekdai** [comment]
How about [GSettings](https://developer.gnome.org/gio/stable/GSettings.html) in glib?

**Comment by albfan** [comment]
Open an issue about that, and provide an implementation (with config for external player). In focus in simplest way to config miraclecast, but gsettings can be useful too.

**Comment by albfan** [comment]
Implementation is done. Override default config file is left apart as it implies a deeper refactor

wiki section for this feature is created https://github.com/albfan/miraclecast/wiki/Configuration
