### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13

### ISSUE THREAD

**Issue by Hans-Maulwurf** [albfan/miraclecast#116]
When I start 'sudo miracle-wifid' I get this error

ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:898)

Is there something missing in my system?

**Comment by albfan** [comment]
Did you install dbus policy?

check if `/etc/dbus-1/system.d/org.freedesktop.miracle.conf` exists. It should be installed by `sudo make install` on lastest commits. if you use cmake, remove CMakeCache.txt because if it is older, install instructions will not be updated (quirks of cmake).

**Comment by Hans-Maulwurf** [comment]
I used yaourt to install it from the aur. but this file seems to be missing on my filesystem. but when I reinstall the aur-package, it says
`Eingetragene backup Datei nicht im Paket : etc/dbus-1/system.d/org.freedesktop.miracle.conf`
which means the file even does not exists in the package

**Comment by albfan** [comment]
You are right. I have fixed aur miraclecast project.

https://github.com/albfan/aur-miraclecast/commit/1f548b27c558d1189304599d0184d133ee91c532

aur package is updated too.

Feel free to submit PR on albfan/aur-miraclecast if you detect another problem and you find a solution. We can discuss there.

**Comment by albfan** [comment]
Is it solved now? close this issue if so

**Comment by Hans-Maulwurf** [comment]
this error is solved now, yes. but i followed ur instructions at the readme (and the linked comment "using as peer") but how do I get my screen mirrored to the TV?

I stop NetworkManager.service, start miracle-wifid and then miracle-wifictl. there i use link, list, p2p-scan and connect (to my TV). the TV and the terminal say: connected. But how do i stream the content of my monitor to the TV? in your linked comment, you give a line with vlc, but when I execute this line, nothing happenes.

**Comment by albfan** [comment]
Great then. Close this and see #4 for an epic issue. The Q&D there works, but is not implemented yet.

**Comment by WillemPi3** [comment]
I have to update miraclecast after every reboot to avoid this error.

**Comment by albfan** [comment]
@WillemPi3 if you have several miracle-wifid running this could happen as first one takes dbus control and the others cannot. Check if that's the problem

**Comment by WillemPi3** [comment]
@albfan that was indeed the case. Thanks!

**Comment by trietend** [comment]
/etc/dbus-1/system.d/org.freedesktop.miracle.conf wasn't created at my kali using autotools.
I had no problems using cmake.

**Comment by albfan** [comment]
@trietend It should install https://github.com/albfan/miraclecast/blob/master/res/Makefile.am#L5

clean all:

$ ./autogen.sh g && make distclean
$ ./autogen.sh g && make && make install

and try again

**Comment by trietend** [comment]
this works thanks :)
