### ISSUE TITLE
Testing miraclecast on Virtual machines

### ISSUE THREAD

**Issue by albfan** [albfan/miraclecast#12]
By now it's not possible because virtual machine card emulation does not support AP mode (That supposition could be mistaken).

**Comment by thopiekar** [comment]
After starting wpa_supplicant and using wpa_gui to scan the area I get this:
```
Could not set interface ra0 flags (UP): Operation not permitted
WEXT: Could not set interface 'ra0' UP
ra0: Failed to initialize driver interface
Failed to add interface ra0
ra0: Cancelling scan request
ra0: Cancelling authentication timeout
```

It seems that VirtualBox does no connect directly to the USB port, something seems to get lost.

**Comment by htimsda** [comment]
Albfan, 

Were you able to get miraclecast working on a virtual machine?

**Comment by albfan** [comment]
Internal cards are emulated on virtualbox with a driver with no wifi direct capabilities.

I have no usb with wifi direct to check.

**Comment by albfan** [comment]
Seems there's a way to get this working with docker

https://twitter.com/_TheMoses_/status/736881059246133248

We are looking to share a prebuilt image with miraclecast installed. That should ease testing and evolving miraclecast

**Comment by albfan** [comment]
My mistake. Docker is not a virtual machine at all, but a container, based on lxc (linux containers https://linuxcontainers.org/) So I will open another issue #198 as I'm getting more comfortable with containers.

For virtual machines, an usb dongle with p2p capabilities should be enough as I said
