### ISSUE TITLE
Connexion Fail - Unhandled wpas-event

### ISSUE THREAD

**Issue by jonalbertini** [albfan/miraclecast#122]
Sometimes, the connexion fail, because of a GO-NEG-FAILLURE event .
it must be a negotiation fail at connexion. 
maybe an handler on wifid-supplicant.c for the event : 
P2P-GO-NEG-FAILLURE
to auto retry Negotiations or drop connexion and restart listening

**Comment by albfan** [comment]
That would be great. Another step to increase stability

**Comment by jonalbertini** [comment]
I've just also got another one on connexion :
P2P-INVITATION-RECEIVED
have you any source of information on events we can get ? 
some doc on Wi-fi P2P ?

**Comment by jonalbertini** [comment]
P2P-INVITATION-RECIEVED is a Group invitation, A response need to be given in less than 100 millisecond or it will be take as a fail. 
(cf: [Wi-Fi Peer-to-Peer (P2P) Technical Specification Version 1.5](https://www.wi-fi.org/download.php?file=/sites/default/files/private/Wi-Fi_P2P_Technical_Specification_v1.5.pdf) page 49) 
I don't really understand this "Group" thing but working on it.

**Comment by albfan** [comment]
Wifi direct works without AP. The "nets" ate called groups and some device acts as owner of group.

This are messages managed

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L1415
