### ISSUE TITLE
Is it possible to cast screen behind a router?

### ISSUE THREAD

**Issue by jurgenhaas** [albfan/miraclecast#126]
I'm using a desktop without wifi and it's connected to a router which itself is then connected to wifi-direct enabled TVs. Is it possible to cast my desktop screen to one or many of those TVs? And help would be much appreciated.

**Comment by albfan** [comment]
I guess no. Is everything connected through cable, isn't it? If that is correct: Your TVs are not in a permanent state looking for video input stream. Only your wifi direct is searching for new connections, and once paired, through miracast protocol get the details of how to do it.

**Comment by jurgenhaas** [comment]
Well, the TV is connected via Wifi to the router and the PC is connected to the same router via cable.

**Comment by albfan** [comment]
When devices are in same network maybe TLDS could work

http://www.infoworld.com/article/2615053/wide-area-networking/wi-fi-alliance-starts-certifying-tunnel-technology-for-better-wireless-performa.html
http://www.wi-fi.org/downloads-registered-guest/20120808_TDLS_White_Paper_FINAL_0.pdf/29686

but is not implemented. We can start trying to send ad TLDS discovery and see what happens. Are you avaliable to test this?

**Comment by jurgenhaas** [comment]
@albfan I'd be happy to test and report on this. I'm technical savvy but this sort of stuff is outside of my knowledge area and experience. So if you told me what to test, I'd be able to do that. My OS is Linux (Ubuntu 16.04) and yes, the router, TV and PC are all in the same network.

**Comment by albfan** [comment]
Sure. I wil prepare a branch which start device handshake with a TLDS discovery message and let's see if TVs answer in some way.

**Comment by albfan** [comment]
Are you still interested on this?

**Comment by jurgenhaas** [comment]
Yes I am.

**Comment by albfan** [comment]
Seems microsoft expanded miracast protocol to allow screen mirroring on local network

https://msdn.microsoft.com/library/mt796768.aspx

I'm just reading the spec. Didn't know what is needed to implement it on linux machines

**Comment by jurgenhaas** [comment]
Never mind, in the meantime I started using Google Chromecast which is doing quite a lot of what's important to my use cases.

**Comment by albfan** [comment]
Someday, let's close this by now

**Comment by z0rb** [comment]
Hi! Has this feature been addressed? My chip is RTL8821CE and the hardware test shows `Sorry, wlp3s0 do not support P2P`. Don't know if that is a driver issue. I was wondering if that would still be the case going through a router.

**Comment by cshorler** [comment]
This led me here!
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-mice/9598ca72-d937-466c-95f6-70401bb10bdb?redirectedfrom=MSDN

Will start by trying to inspect beacon frames with wireshark from my blu ray player (which can be a miracast sink)

**Comment by tnrs** [comment]
> Sure. I wil prepare a branch which start device handshake with a TLDS discovery message and let's see if TVs answer in some way.

So what? Does anybody have already done smth on that?

**Comment by Servail** [comment]
Any news on the feature?

**Comment by albfan** [comment]
Someboby needs to share a wireshark capture for some device that accept this.

Por send a PR that replaces wifi direct with negotiation over infraestructura as the doc says

Or find any open implementation to inspect

**Comment by albfan** [comment]
Hmm, https://help.airtame.com/hc/en-us/categories/15003639565597-Airtame-App
