### ISSUE TITLE
Trying to Install on 16.04.1 Ubuntu Studio

### ISSUE THREAD

**Issue by blrsmalxndr** [albfan/miraclecast#127]
libsystemd is not found.

Checking for module 'libsystemd'
  No package 'libsystemd' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:26 (pkg_check_modules)

Configuring incomplete, errors occurred!
See also "/home/nohbody/Downloads/miraclecast-master/CMakeFiles/CMakeOutput.log".

Using Cmake, if you need the output log, let me know. 
Also, systemd = 229
Will let you know if i get it working

**Comment by albfan** [comment]
This has an easy fix. Ubuntu don't distribute headers by default with its packages so normally each package has a dev package with headers to be used in other projects.

I guess for systemd you need to install libsystemd-dev:

    $ sudo apt-get install libsystemd-dev

Repeat with each missing packages

**Comment by blrsmalxndr** [comment]
Actually looking through different things, it was my fault. 
Deleted folder, restarted from scratch, (once i had dependencies)

sudo apt-get install libreadline6 libreadline6-dev

is what finally fixed it for me, along with a couple other dependencies that were missing. . . I'll comment if i can find exactly which ones they were (or if you know a useful linux command to tell me what's been installed recently)

**Comment by blrsmalxndr** [comment]
Now though (not the same problem)
nohbody@nohbody:~$ ~/Downloads/miraclecast-master/res/test-viewer.sh
testing plugins required:

test udpsrc...
	gst plugin "udpsrc" not available
test rtpjitterbuffer...
	gst plugin "rtpjitterbuffer" not available
test rtpmp2tdepay...
	gst plugin "rtpmp2tdepay" not available
test tsdemux...
	gst plugin "tsdemux" not available
test h264parse...
	gst plugin "h264parse" not available
test avdec_h264...
	gst plugin "avdec_h264" not available
test autovideosink...
	gst plugin "autovideosink" not available

Some plugins required for visualization are missed

Try installing packages "gst-plugins-bad, gst-plugins-base, gst-plugins-base-libs, gst-plugins-good, gst-plugins-ugly, gst-libav, gstreamer".

If that fails too, try:

$ vlc rtp://@:1991
i have tried every gstreamer plugin i can, all of them are already installed and up to date.
video codecs are installed and up to date. . .
gstreamer version is 1.8.2. 
:/ hdmi port on this laptop is broken, so would love to get this working. . . 

also though, is it possible to stream something from the inet, then cast it to a TV with this? (guess i should ask before I get any further)

**Comment by blrsmalxndr** [comment]
I'll close this issue, but on #119 if they're having problems, I'd suggest 

sudo apt install gstreamer1.0-*

That's what fixed it for me. :D
