### ISSUE TITLE
Italian guide to Miraclecast

### ISSUE THREAD

**Issue by ZaneCEO** [albfan/miraclecast#129]
Hi,
this is to inform who may be interested that my ITALIAN guide to Miraclecast is ready: [Miracast e Ubuntu: guida a Miraclecast per Linux](https://turbolab.it/htpc-807/miracast-ubuntu-guida-miraclecast-linux-515).

If you find it useful, could you please link it from the wiki/docs? Thanks!

**Comment by albfan** [comment]
Cool!. I have tweeted about it.

https://twitter.com/TurboLabIt/status/780148403674177536?s=09

If you have in markdown style we can add here too (better in english)

**Comment by ZaneCEO** [comment]
Great, thanks for your tweet. Unfortunately I cannot translate it now, but the [english-autotranslated test](https://translate.google.com/translate?sl=it&tl=en&js=y&prev=_t&hl=it&ie=UTF-8&u=https%3A%2F%2Fturbolab.it%2Fhtpc-807%2Fmiracast-ubuntu-guida-miraclecast-linux-515&edit-text=) could be useful to someone looking for a place to start.

**Comment by albfan** [comment]
Feel free to propose any wiki page about external references.
