### ISSUE TITLE
Systemd 229, ubuntu 16.04  No package 'libsystemd'

### ISSUE THREAD

**Issue by a11g0rhythm** [albfan/miraclecast#131]
hi,
when I try to compile:
 cmake ..
-- Checking for module 'libsystemd'
--   No package 'libsystemd' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:26 (pkg_check_modules)

I have installed libsystemd0

**Comment by albfan** [comment]
You need to install [libsystemd-dev](http://packages.ubuntu.com/xenial/libsystemd-dev). In ubuntu dev packages (ones that have header files) are separated from binary packages (ones that have programs or libraries). You can check showing [file list](http://packages.ubuntu.com/xenial/amd64/libsystemd-dev/filelist) its only header and man pages.

Don't hesitate to ask anything else until you get it compiled, installed and working, but remember to close this whenever you get success.

**Comment by midi1996** [comment]
to just point out, for new ubuntu installs (I tried over ubuntu 16.04 with gnome), run this to get all the needed packages:
````
sudo apt install git ubuntu-restricted-extras check gstreamer1.0 libglib2.0-dev libreadline-dev libudev-dev libsystemd-dev libusb-dev cmake build-essential
````

**Comment by albfan** [comment]
Is this solved? Please close it if it is

**Comment by a11g0rhythm** [comment]
Yes, thanks for respond, installation succeeded, but wifi card don't have functionality :(
