### ISSUE TITLE
Is there any plan to port this application for yocto build system?

### ISSUE THREAD

**Issue by chinlin0924** [albfan/miraclecast#132]
Hi 
It would be great if you can have a layer for building this app on yocto project.

regards,
chinlin

**Comment by albfan** [comment]
Do you have links related to do it? It should be an easy task but I know nothing about yocto package managing and distro releases

Let me know how can I help on this

**Comment by albfan** [comment]
All seems to be here:

https://wiki.yoctoproject.org/wiki/How_do_I#Q:_How_do_I_put_my_recipe_into_Yocto.3F
https://wiki.yoctoproject.org/wiki/Building_your_own_recipes_from_first_principles

These guides show even how to config an emulator using qemu, so it is not needed even to have any real embedded hardware.

Little dense, but interesting to see:
https://www.youtube.com/watch?v=zNLYanJAQ3s

Definetely I would put focus on these and try to create a recipe for miraclecast

**Comment by chinlin0924** [comment]
great & thank you for this info.


2016-10-08 13:30 GMT+08:00 Alberto Fanjul <notifications@github.com>:

**Comment by albfan** [comment]
I'm not 100% sure of this, but seems openwrt acts like a package repository:

https://github.com/openwrt/packages/pulls

and the tool to manage packages is [opkg](https://wiki.openwrt.org/doc/techref/opkg)

So open an issue there (or a PR using a fork of these repo with your progress building a package) is the way to start this journey to add miraclecast to yocto project. I never did a yocto recipe, but I can guide you through the boring details, seems (with all the differences) that you only need to:

- create something similar to a [PKGBUILD for archlinux](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=miraclecast) fork of this repo
- create a PR on openwrt using your fork of miraclecast
- Let its maintainers to test it an get accepted (merged) (I will do the same too when is ready)

**Comment by albfan** [comment]
Done! https://github.com/OSSystems/meta-miracast/tree/master/recipes-miracast/miraclecast

**Comment by chinlin0924** [comment]
great job!!


2017-04-16 5:13 GMT+08:00 Alberto Fanjul <notifications@github.com>:
