### ISSUE TITLE
ERROR: supplicant: HUP on dhcp-comm socket

### ISSUE THREAD

**Issue by zhsj** [albfan/miraclecast#137]
Sorry I don't have much knowledge about wpasupplicant. I want to test this project on my laptop. When I try to connect my phone, the miracle-wifid shows these errors:

[0077.650574] ERROR: supplicant: HUP on dhcp-comm socket on p2p-wlp58s0-0 (supplicant_group_comm_fn() in /home/zsj/Workspaces/c/miraclecast/src/wifi/wifid-supplicant.c:247)
[0078.216380] ERROR: supplicant: HUP on supplicant socket of wlp58s0 (supplicant_global_fn() in /home/zsj/Workspaces/c/miraclecast/src/wifi/wifid-supplicant.c:2145)
[0078.216433] ERROR: supplicant: wpas (pid:2724) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in /home/zsj/Workspaces/c/miraclecast/src/wifi/wifid-supplicant.c:2315)

The hardware is Broadcom  BCM4350(Dell XPS13)
The software is Linux 4.7.8(Debian Testing) and wpasupplicant 2.6
My phone is Nexus 6.

**Comment by albfan** [comment]
First stop network manager and kill any existing wpa_suplicant running (we are working on avoid this)

    $ sudo systemctl stop NetworkManager
    $ sudo killall wpa_supplicant

Then try again

**Comment by zhsj** [comment]
@albfan I do have stopped other wpa_supplicant. Same errors. Anything else I can try?

**Comment by albfan** [comment]
Can you post the entire logs here:

    $ sudo miracle-wifid --log-level trace |& tee wifid.log
    $ sudo miracle-sinkctl --log-level trace |& sink.log
    $ sudo journal -f |& tee journal.log

Collect `wifid.log`, `sink.log` and `journal.log` and upload here, let's see what's happening

**Comment by zhsj** [comment]
@albfan, in journal log, I find the reason that causes "HUP on dhcp-comm". miracle-dhcp is not in system path.

However I still can't test miracle successfully. But I think this issue can be closed.

**Comment by albfan** [comment]
Don't worry about change issue subject reopen and resolve your problem. How did you install miraclecast?

    $ ./autogen.sh g && make && make check && sudo make install

or

   $ cmake .  && make && make check && sudo make install

Or you didn't install it at all?

**Comment by zhsj** [comment]
I didn't install it. And I fix this error by installing it...

**Comment by albfan** [comment]
Well done. I will cahnge subject to help other people in same situation

**Comment by albfan** [comment]
We should check that file exists before launch it, to give a correct warning

**Comment by ezerbib** [comment]
I had same issue and fix it by adding $prefix/bin in my PATH
could you add a log error in HUP message such as check miracle_dhcp in your PATH?

**Comment by albfan** [comment]
@ezerbib how is it possible that $prefix/bin is not on your PATH?. You should install miraclecast so it ends in your path.

Can you post here your PATH and how you install miraclecast?

execution logs without adding $prefix/bin to path will help to add that warning too
