### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name

### ISSUE THREAD

**Issue by ateek** [albfan/miraclecast#138]
Hi , first of all  great job , i really appreciate the effort you did in this project 
,  i'm using your arcarm image your posted before on issue #100 
Link : https://drive.google.com/open?id=0B6La7AoEnzRBQy04S0ZBMXF2R28

still i can discover the raspberry Pi and i can connect to it , however its only less than 2 seconds the miraclecast disconnect , 

when I run this command :  "sudo miracle-wifid --log-level trace"

i got this 

```
INFO: miracle-wifid - revision 1.0 Jul 23 2016 09:48:15
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in wifid-dbus.c:898)
DEBUG: exiting.. (main() in wifid.c:569)
```

**Comment by albfan** [comment]
Connecting and reconnecting is not working well yet.

See last comments on https://github.com/albfan/miraclecast/issues/100#issuecomment-237152709 about bring down wifi interface if there's any.

Collect log messages if you can and post here if that don't work, see [FAQ](https://github.com/albfan/miraclecast/wiki/FAQ)

**Comment by albfan** [comment]
any report or test better on #100, ok?
