### ISSUE TITLE
What is the screen mirroring technology?

### ISSUE THREAD

**Issue by xirigid** [albfan/miraclecast#140]
I mean how to get the screen mirroring? Then display the image via the wifi-display.

**Comment by albfan** [comment]
I'm glad to help. What is your exact environment (source device and operative system, target device and operative system, kind of screen mirroring: screencast, video reproduction, need source be interactive? mouse keyboard)

**Comment by xirigid** [comment]
At prestent, I want to make a project of target software to receive the
screen from source operating system(linux, windows, android), because these
systems have the miracast as source, except linux.
Howwver, I found thar these systems' miracast work not well. So I want to
make a project for source later.

If linux is a source, how can I get the screen mirroring?
If windows is a source, how can I get the screen mirroring?
If android is a source, how can I get the screen mirroring?

Are there differences for getting screen mirroring from different operating
system? And are there some documents for getting screen mirroring?

About establishing RTSP, reading the WiFi Display Technical Specification
is ok?

Thanks for your help!

**Comment by albfan** [comment]
Read README.md for detailed instructions. Android to linux works out of the box. #4 for work as source. Windows to linux is almost working from wip/windows-fix branch. Raspberry pi is working on arch arm. This is project is more advanced than you expected I think. All spec is implemented

**Comment by xirigid** [comment]
Thank you very much!!!

**Comment by xirigid** [comment]
which is the source code file for getting screen mirroring?

**Comment by albfan** [comment]
hahaha, ¿All the project? You must be more explicit about your doubts. In general

https://github.com/albfan/miraclecast/wiki/Internals
