### ISSUE TITLE
cannot find LIBSYSTEMD221 (compiling against 215)

### ISSUE THREAD

**Issue by pcmerioles609** [albfan/miraclecast#141]
Good day! I am trying to build miraclecast in Jessie following this :
[https://github.com/albfan/miraclecast/issues/66](url)

I make-installed systemd221 from here :
[https://www.freedesktop.org/software/systemd/systemd-221.tar.xz](url)

But I am having problems when executing :
`$ sudo miracle-wifid`
with the the error stating :
> LIBSYSTEM221 not found ... required by miracle-wifid

I followed your guidelines as per :
[https://github.com/albfan/miraclecast/issues/68](url)
but I couldn't seem to be able to remove the default systemd215 on Jessie.

Am I missing some important step on installing systemd?
Building on system215 leads to this :
[https://github.com/albfan/miraclecast/issues/21](url)

Thanks! :+1:

**Comment by albfan** [comment]
Is this for a raspberry? I give up and use arch arm and you have a image ready to use on issue #100 See there was changes on systemd on version 219 (look for 219 branch)

You can try early stages of the project (it starts using systemd 213) but didn't work so well.

**Comment by pcmerioles609** [comment]
That figures. All Raspberry Pi issues seems to point to the same direction.
Well, archarm it is. Thank you for being quick! :+1:
