### ISSUE TITLE
Monitor Portrait mode

### ISSUE THREAD

**Issue by negativeOne1** [albfan/miraclecast#144]
Hi there,
is there a way to create a gstreamer window for protrait mode monitors? --res only allows for landscape resolutions, right?

**Comment by albfan** [comment]
If you turn your phone to landscape/portrait, magic comes alive. Try it and let me know your thoughs. Do you want a fixed landscape mirroring? I think there's no such option on miracast implementation, maybe you want to implement first extension on miraclecast? See it only would work between to devices with an implementation aware of that (that means between two miraclecast)

**Comment by mkey2000** [comment]
Well, I have an APP which works fixed in Portrait mode, no Landscape needed, I just wanted to have it shown on the screen (standard pc widescreen monitor). My plan was to rotate the screen and because Phone and Monitor share the same ratio I could use the maximum amount of screen area for my demonstration, without having black borders.

**Comment by albfan** [comment]
Problem is that black borders are from source itself, so you need to rotate and crop yourself

You can do adding these filters:
 
- https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-videoflip.html
- https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-videocrop.html

here:

https://github.com/albfan/miraclecast/blob/master/res/miracle-gst#L78

or here if you plan to use uibc

https://github.com/albfan/miraclecast/blob/master/res/gstplayer#L87

Would be great to implement #113 to allow this to be customizable or at least add an option to add more filters. That would be done here:

https://github.com/albfan/miraclecast/blob/8272978d0259c6231a4fbff84044b789c16adf54/src/ctl/sinkctl.c#L426

which option would come from command line:

https://github.com/albfan/miraclecast/blob/8272978d0259c6231a4fbff84044b789c16adf54/src/ctl/sinkctl.c#L778

Is up to you to implemented just for you or send a PR

Don't hesitate to share info about your "demonstration" I promise to tweet about it

**Comment by albfan** [comment]
You did it finally? any media avaliable?

**Comment by albfan** [comment]
Hope you get it working, try with vanilla miraclecast and reopen if you have captures of what is going wrong to fix it
