### ISSUE TITLE
miracle-sinkctl can't form a P2P wifi network

### ISSUE THREAD

**Issue by jdieter** [albfan/miraclecast#145]
I'm trying to get this working on Fedora 24.  As I mentioned in issue #101, I had to rebuild wpa_supplicant, but I'm still hitting issues forming the P2P network.  There is a 10-15 second delay before the line that says P2P-GROUP-FORMATION-FAILURE.  The relevant logs (with trace enabled for both wpa-supplicant and miraclecast):

<pre>
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: <3>P2P-DEVICE-FOUND c2:ee:fb:21:03:e8 p2p_dev_addr=c2:ee:fb:21:03:e8 pri_dev_type=10-0050F204-5 name='Android_b0c1' config_methods=0x188 dev_capab=0x25 group_capab=0x0 wfd_dev_info=0x00101c440032 new=1
DEBUG: peer: new peer: c2:ee:fb:21:03:e8 @ wlp4s0 (peer_new() in wifid-peer.c:52)
INFO: peer: add peer: c2:ee:fb:21:03:e8
DEBUG: peer: peer c2:ee:fb:21:03:e8 @ wlp4s0 started (peer_supplicant_started() in wifid-peer.c:162)
DEBUG: supplicant: requesting data for new peer c2:ee:fb:21:03:e8 (supplicant_event_p2p_device_found() in wifid-supplicant.c:962)
TRACE: wpa: raw message: c2:ee:fb:21:03:e8
pri_dev_type=10-0050F204-5
device_name=Android_b0c1
manufacturer=OnePlus
model_name=A0001
model_number=A0001
serial_number=8d61830b
config_methods=0x188
dev_capab=0x25
group_capab=0x0
level=-61
age=0
listen_freq=2462
wps_method=not-ready
interface_addr=00:00:00:00:00:00
member_in_go_dev=00:00:00:00:00:00
member_in_go_iface=00:00:00:00:00:00
go_neg_req_sent=0
go_state=unknown
dialog_token=0
intended_addr=00:00:00:00:00:00
country=LB
oper_freq=0
req_config_methods=0x0
flags=[REPORTED]
status=0
invitation_reqs=0
ext_listen_period=500
ext_listen_interval=500
wfd_subelems=00000600101c440032

TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: <3>P2P-PROV-DISC-PBC-REQ c2:ee:fb:21:03:e8 p2p_dev_addr=c2:ee:fb:21:03:e8 pri_dev_type=10-0050F204-5 name='Android_b0c1' config_methods=0x188 dev_capab=0x25 group_capab=0x0
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: <3>P2P-GO-NEG-REQUEST c2:ee:fb:21:03:e8 dev_passwd_id=4 go_intent=0
DEBUG: supplicant: GO Negotiation Request from c2:ee:fb:21:03:e8 (supplicant_event_p2p_go_neg_request() in wifid-supplicant.c:1065)
DEBUG: supplicant: connect to c2:ee:fb:21:03:e8 via pbc/(null) (supplicant_peer_connect() in wifid-supplicant.c:739)
TRACE: wpa: raw message: <3>P2P-FIND-STOPPED 
DEBUG: supplicant: p2p-scanning stopped on wlp4s0 (supplicant_event_p2p_find_stopped() in wifid-supplicant.c:904)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: <3>P2P-GO-NEG-SUCCESS role=GO freq=2412 ht40=0 peer_dev=c2:ee:fb:21:03:e8 peer_iface=c6:ee:fb:21:03:e8 wps_method=PBC
DEBUG: supplicant: set STA-MAC for c2:ee:fb:21:03:e8 from <none> to c6:ee:fb:21:03:e8 (via GO-NEG-SUCCESS) (supplicant_event_p2p_go_neg_success() in wifid-supplicant.c:1195)
TRACE: wpa: raw message: IFNAME=p2p-wlp4s0-0 <3>AP-ENABLED 
TRACE: wpa: raw message: IFNAME=p2p-wlp4s0-0 <3>CTRL-EVENT-CONNECTED - Connection to 76:e5:43:c2:d2:2c completed [id=0 id_str=]
TRACE: wpa: raw message: IFNAME=p2p-wlp4s0-0 <3>WPS-PBC-ACTIVE 
TRACE: wpa: raw message: <3>P2P-GROUP-FORMATION-FAILURE 
DEBUG: supplicant: peer Android_b0c1 connection failed (supplicant_event_p2p_group_formation_failure() in wifid-supplicant.c:1305)
TRACE: wpa: raw message: <3>P2P-GROUP-REMOVED p2p-wlp4s0-0 GO reason=FORMATION_FAILED
DEBUG: supplicant: stray P2P-GROUP-REMOVED: <3>P2P-GROUP-REMOVED p2p-wlp4s0-0 GO reason=FORMATION_FAILED (supplicant_event_p2p_group_removed() in wifid-supplicant.c:1287)
TRACE: wpa: raw message: IFNAME=p2p-wlp4s0-0 <3>AP-DISABLED 
DEBUG: supplicant: unhandled wpas-event: IFNAME=p2p-wlp4s0-0 <3>AP-DISABLED  (supplicant_event() in wifid-supplicant.c:1483)
DEBUG: supplicant: sent P2P_FIND to wpas on wlp4s0 (supplicant_p2p_start_scan() in wifid-supplicant.c:2020)
TRACE: wpa: raw message: IFNAME=p2p-wlp4s0-0 <3>CTRL-EVENT-DISCONNECTED bssid=76:e5:43:c2:d2:2c reason=3 locally_generated=1
TRACE: wpa: raw message: OK

DEBUG: supplicant: p2p-scanning now active on wlp4s0 (supplicant_p2p_find_fn() in wifid-supplicant.c:1901)
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
TRACE: wpa: raw message: IFNAME=wlp4s0 <3>CTRL-EVENT-SCAN-STARTED 
</pre>

**Comment by jdieter** [comment]
And it's working now.  No idea what change.  I'll reopen if I can replicate this.

**Comment by albfan** [comment]
Maybe a restart or similar. Good job @jdieter
