### ISSUE TITLE
Miraclecast on Raspberry Pi2 running on Ubuntu MATE 16.04

### ISSUE THREAD

**Issue by pcmerioles609** [albfan/miraclecast#146]
Good day!

I have been trying to build miraclecast on Ubuntu MATE but I am getting the error:
> command failed: No such device (-19)
> cannot find physical device for wlan0

when running the script `./test-hardware-capabilities.sh`
whereas running the same script on archarm shows that the same device supports p2p

running `./miracle-sinkctl` produces no links.

Do you think I am missing drivers? Wi-fi is working normally though.
Any ideas? Thanks!

**Comment by albfan** [comment]
Add 

    set -xv

in this line 

https://github.com/albfan/miraclecast/blob/master/res/test-hardware-capabilities.sh#L2

And try again. -that's to enable trace and debug on script-

I'm supposing this script has some incompatibilities with your system. Running like that we will see where is the error.

**Comment by pcmerioles609** [comment]
Good day!

This is the result of the script:

[LOGS.zip](https://github.com/albfan/miraclecast/files/585427/LOGS.zip)

I also included the log trace of `miracle-wifid`. Are instructions in
[https://github.com/albfan/miraclecast/wiki/FAQ](url)
updated? My `miracle-wifid` log doesn't seem to have the correct output.

Thanks!

**Comment by albfan** [comment]
log says it recognizes correctly you have eth0 and wlan0 and wlan0 is wireless, but then

    $ iw dev wlan0 info

fails because iw do not recognize the device

Can you post here the output of iw list?:

    $ iw list

That's to see the names of your devices for iw

**Comment by pcmerioles609** [comment]
Yeah. It does return
> command failed : No such device(-19)

and `$iw list` returns nothing.

I am currently searching for driver problems but I might be getting the problem wrong.
If your have any ideas why `$iwconfig` works but `$iw list` doesn't, please let me know.

Thanks!

**Comment by albfan** [comment]
Try this tweaks

http://superuser.com/questions/1049960/iw-and-some-of-its-commands-do-not-return-any-output

**Comment by pcmerioles609** [comment]
Hi! Good day!

It seems the problem was something about kernel or driver not found.
The link you provided allowed me to install `firmware-realtek` but it returns error:
> cannot find linux headers 4.1.17-v7+

But then I noticed that 4.1 kernel is not the newest one (fresh install of Ubuntu MATE 16.04) so I did:
`$sudo rpi-update` and reboot.

`$iw list` and `$iw dev wlan0 info` now show the expected results and  `./test-hardware-capabilities` now states that P2P is supported!

But I am having the same problem I had with Archarm. After executing:
`$sudo miracle-wifid`
`$sudo miracle-sinkctl`
`$>run 3`

My phone cannot see `miraclecast` when I am searching for Screen Mirroring (using Xperia Z).
I am now trying to test different phones, but this phone sees `miraclecast` when I am on Ubuntu 16.04 desktop.

Here are some excerpts from the logs:
> device_name=Xperia Z_35ca   // so I believe it does see my phone
> wps_method=not-ready          // not very sure if this is the problem

Other than that, I see no other errors. Do you have an idea what might be the problem? I have attached the necessary log files for reference.

I really appreciate your support.
Thanks!
[LOGS.zip](https://github.com/albfan/miraclecast/files/588907/LOGS.zip)

**Comment by albfan** [comment]
journal.log shows your networkmanager trying to start wpa_supplicant again. disable it with 

    $ sudo systemctl stop NetworkManager

and try again

**Comment by pcmerioles609** [comment]
Hi! Thank you for your reply.

I have tried stopping NetworkManager but the result is the same.
I have tested it on two more phones, LG G3 and Samsung Galaxy S3, but still the same.

I am now trying some fixes on enabling ad hoc mode on my RTL8188 chipset WiFi dongle.
That might be the problem why the phones cannot see the RPi as an access point.

Also, soon I'll get my hands on some new dongles and the RPi3.
I will update as soon as I get new findings.

Thank you!

**Comment by albfan** [comment]
If you have NetworkManager stopped, maybe results are the same but maybe problems are different.

Post logs again, from as many devices as you want

**Comment by albfan** [comment]
Sony xperia Z? http://www.ekoob.com/screen-mirroring-miracast-sony-xperia-z-12431/ seems the device do not support miracast

Samsung galaxy S3 don't have support too

LG has something called smartshare that I guess is propietary

I think that's the problem. If you find device that is miracast certified, please reopen
