### ISSUE TITLE
Miracle-wifid tells that my driver doesn't support p2p, but test-hardware-capabilities.sh tells it supports

### ISSUE THREAD

**Issue by victorcrimea** [albfan/miraclecast#147]
I'm using Dell XPS 15 (9550) with Broadcom BCM43602 card served by brcmfmac driver. 
When I running res/test-hardware-capabilites.sh script it tells: wlp2s0 supports P2P. 
But when I'm trying to run miracle-wifid it throws a warning:
WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in /home/victorcrimea/projects/miraclecast/src/wifi/wifid-supplicant.c:1682)
And obviosly nothing works afterwards :(
What is the possible reason of the problem?
In fact: miracast is working well with Windows 10 both as a receiver and as a transmitter, so it's supposed to be driver/software issue.

**Comment by victorcrimea** [comment]
There is a overview of brcmfmac driver [https://wireless.wiki.kernel.org/en/users/drivers/brcm80211](https://wireless.wiki.kernel.org/en/users/drivers/brcm80211)
And there described that it supports p2p.

**Comment by albfan** [comment]
What distro are you using? Important info:

    $ systemctl -version
    $ wpa_supplicant --version

**Comment by victorcrimea** [comment]
Ubuntu 16.04 
root@XPS-15-9550:/home/victorcrimea# systemctl --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

root@XPS-15-9550:/home/victorcrimea# wpa_supplicant -v
wpa_supplicant v2.4
Copyright (c) 2003-2015, Jouni Malinen <j@w1.fi> and contributors

**Comment by albfan** [comment]
Everythins seems ok. Please post here logs as described in https://github.com/albfan/miraclecast/wiki/FAQ

**Comment by victorcrimea** [comment]
[xps15-miraclecast.zip](https://github.com/albfan/miraclecast/files/597555/xps15-miraclecast.zip)
I havn't journal command, I supposed you mean journalctl. And there is also should be tee in second command.

**Comment by victorcrimea** [comment]
Already addded tee to FAQ page on wiki.

**Comment by albfan** [comment]
Dod you kill actual wpa_supplicant? Miraclecast reuses existing process if avaliable but that wpa_supplicant will not fit with miraclecast requirements. If that's the case, shutdown networkmanager service as it tries to restart wpa_supplicant if something kills it

**Comment by victorcrimea** [comment]
My fault. I haven't killed them. Now I definitely killed network manager and wpa_supplicant with res/kill-wpa.sh.
[miraclecast.zip](https://github.com/albfan/miraclecast/files/598056/miraclecast.zip)

**Comment by albfan** [comment]
This line on journal.log

    Failed to create interface p2p-dev-wlp2s0: -16 (Device or resource busy)

tells your system is using that interface in some process.

check for running `miracle-wifid` or `wpa_supplicant` with `ps -ef | grep <whatever>` and shutdown interface

    $ ifconfig p2p-dev-wlp2s0 down

Restarting does the trick too but it's nastier

**Comment by albfan** [comment]
Give it another try if you want. stopping network manager after a reboot should be enough to have interfaces ready for miraclecast. (We are working to improve the way final users use it)
