### ISSUE TITLE
move instructions to wiki

### ISSUE THREAD

**Issue by albfan** [albfan/miraclecast#15]
README.md is becoming huge. Lot of its information is valuable but all at same time becomes messy.

Move to different pages:

- compile and install instructions
- usage instructions

**Comment by keyser84** [comment]
Certainly not top priority, but it would be helpful to have a page with devices that are confirmed to work. I tried with different devices but was not successful. I thought of buying a cheap USB adapter to get it working, but not sure which one is working.
