### ISSUE TITLE
Archarm on RPi3 -- Failed to send Action Frame

### ISSUE THREAD

**Issue by pcmerioles609** [albfan/miraclecast#153]
Hi! Good day!

I just got my RPi3 today and I installed you archarm image.
 (I will get back on #146 once I get miraclecast running)

I did `sudo pacman -Syu` and `yaourt miraclecast` to it but it seems wifid fails on handshaking.
`sudo journalctl -f` shows that:
> kernel : brcmfmac : brcmf_p2p_send_action_frame : Failed to send Action Frame(retry 1)
> miracle-wifid-wlan0-3[625]: P2P-GO-NEG_FAILURE status=-1 

There are many other errors that I see in journal.log but I honestly do not know what causes this.
Are there any settings I might have missed?
I ensured that no supplicant exists before running wifid.

I appreciate your help. Thank you!
[LOGS.zip](https://github.com/albfan/miraclecast/files/606249/LOGS.zip)

**Comment by pcmerioles609** [comment]
Hi! 

I do not know if it is the problem but when I changed the GPU_RAM in boot/config.txt , the action frame error is not appearing anymore. But now, it seems it seems DHCP has a problem.

Might I have missed some settings in archarm?
Here are the new logs :
[LOGS.zip](https://github.com/albfan/miraclecast/files/608474/LOGS.zip)

**Comment by albfan** [comment]
How do you came to known you need to change that? Any motivation or documentation refers to do so?

**Comment by albfan** [comment]
You get the "no ifname on AP-STA-CONNECTED". Use the option `--use-dev` on `miracle-wifid` to workaround that.

**Comment by pcmerioles609** [comment]
Hi! Good day.

That must have solved the problem but it now it shows the error :
>KNOTICE: HUP/ERR on socket
>KERROR: cannot connect to remote host (111): Connection refused  

Here are the logs:
[LOGS.zip](https://github.com/albfan/miraclecast/files/619059/LOGS.zip)

**Comment by pcmerioles609** [comment]
Hi! Good day.

Using `--use-dev` fixed the problem for Xperia Z. The 
> Failed to send Action Frame
error is still intermittent but most of the time Screen Mirroring works.

On the other hand, LG G3 is still stuck in the following error:
> KNOTICE: HUP/ERR on socket
> KERROR: cannot connect to remote host (111): Connection refused

But I believe that is for another issue.
I consider this issue solved.
Thanks!

**Comment by albfan** [comment]
Great, we need to dig on that HUP anyway
