### ISSUE TITLE
tried to start miracled with no success, no error messages

### ISSUE THREAD

**Issue by pavlix** [albfan/miraclecast#156]
Just wanted to try running it and then see what's missing in my system  but apparently even that didn't work out well.

    mole miraclecast # miracled
    mole miraclecast # miracled --log-level 9
    INFO: miracled - revision 1.0 Nov 26 2016 11:46:29
    DEBUG: exiting.. (main() in miracled.c:155)

**Comment by albfan** [comment]
`miracled` is just a supposed manager for all mirackecast stuff but wss left unimplemented by former maintainer

https://github.com/albfan/miraclecast/blob/master/src/miracled.c#L54

We are not in the iteration to implement it. I have to write a roadmap with related issues needed to be solved prior to do this one.

Check README.md for instructions to use miraclecast
