### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by mauro1998** [albfan/miraclecast#157]
I'm having problems to build the project, i'm following the steps bellow:

`git clone git@github.com:albfan/miraclecast.git`
`cd miraclecast`
`mkdir build && cd build`
`cmake ..`: 'Build files have been written to: /home/mauro/Downloads/miraclecast/build'

Then I try:
`make`

But at 56% of building I get the following error:

`/home/mauro/Downloads/miraclecast/src/ctl/ctl-cli.c:37:30: fatal error: readline/history.h: No such file or directory`
`compilation terminated.`
`src/ctl/CMakeFiles/miracle-wifictl.dir/build.make:62: recipe for target 'src/ctl/CMakeFiles/miracle-wifictl.dir/ctl-cli.c.o' failed`
`make[2]: *** [src/ctl/CMakeFiles/miracle-wifictl.dir/ctl-cli.c.o] Error 1`
`CMakeFiles/Makefile2:321: recipe for target 'src/ctl/CMakeFiles/miracle-wifictl.dir/all' failed`
`make[1]: *** [src/ctl/CMakeFiles/miracle-wifictl.dir/all] Error 2`
`Makefile:127: recipe for target 'all' failed`
`make: *** [all] Error 2`

- What should I do to fix this?

I don't know so much about linux, i'm using Elementary OS and want to mirror my screen to my LG SmartTV (miracast) but cannot find anything to get it work. Reading over there I found this Miraclecast project but not sure if this is what I need. Could anyone help me please?

**Comment by derekdai** [comment]
Run
```
sudo apt-get install libreadline-dev
```

Currently, you can run your laptop as the sink (the receiving side), not the source (the sending side), see #4.

**Comment by mauro1998** [comment]
Ok that fixed the problem. Thanks.
I'm running those commands without any idea what it does.
There is nothing "user-friendly" yet?, will this feature be implemented?
or do you know another alternative to achieve what I want?

**Comment by albfan** [comment]
Different problems, different issues, ok?
