### ISSUE TITLE
Device gets added to sinkctl, but nothing shows up on the phone

### ISSUE THREAD

**Issue by mosajjal** [albfan/miraclecast#159]
Hi. I don't know if it's a common problem or I'm just making a rookie mistake but I installed miraclecast on OrangePi Lite and I have problems getting it to work. 

here's my setup:

first, I started `wifid`, then `sinkctl` (with run on 3 and both with trace loglevel) and then `journalctl -f` to see my logs 

![image](https://cloud.githubusercontent.com/assets/10158936/21100262/5a60e628-c088-11e6-8423-a79d876f47a1.png)

but after searching for a wireless display from my phone, nothing shows up, but it's MAC address will appear on `sinkctl`. after a while `sinkctl` removes it from its peers and nothing happens. 

here are my logs:

[wifid.log](http://pastebin.com/FLBHczsf)
[journalctl.log](http://pastebin.com/sxJ2WwFY)
[sink.log](http://pastebin.com/AzC1D6yD)

systemctl -version output:

```
systemd 230
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

any help is appreciated.

**Comment by albfan** [comment]
Did you stop network manager first? although you kill wpa_suplicant it could try to start it again.

See https://github.com/albfan/miraclecast/issues/100#issuecomment-242630127

**Comment by mosajjal** [comment]
yes, the `NetworkManager` service is stopped. `pgrep wpa` shows 0 processes open as well. this is a screenshot of my console before running `wifid`:

![image](https://cloud.githubusercontent.com/assets/10158936/21103294/14bdf818-c097-11e6-8260-ea802859fccc.png)

as you can see, there's no `wpa_supplicant` process.

Interestingly, the device gets added to `sinkctl` and then gets removed after 20/30 seconds.

**Comment by mosajjal** [comment]
pinging...

**Comment by albfan** [comment]
I see a systemd-networkd on journal.log. in the end you have another controller trying to configure your wifi interface.

Hint: when interface is called wlan it is normally a wifi wireless standard interface. When it contains p2p is a p2p connection

Try to stop any network service before usong miraclecast

**Comment by mosajjal** [comment]
Hi. Still working on this. Got your RPi 3 image and booted it up. Still the same problem. I got a question now, can `miracle-wifid` be run with an existing `wpa_supplicant` process? I want to debug `wpa_supplicant` and apparently I can't do it with the current setup.

**Comment by mosajjal** [comment]
also on your comment, should my interface be renamed from `wlan0` when running miracle-wifid?

**Comment by albfan** [comment]
interface can have whatever name, but wpa_supplicant suffixes it with p2p when it has wifi direct enabled. That's only a hint about wpa_supplicant is correctly setup.

normally existing wpa_supplicant is not enabled with p2p, and by now, miraclecast communicates with wpa_supplicant by socket, that's why you cannot use existing wpa_supplicant.

here's the configuration miraclecast uses:

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L2588

but you can always compile wpa_supplicant with debug info and attach to it to debug it.

Let me know if you have any problem and I will try to help

I will try to upload a screencast from boot with a succesful session to show you how it should work

**Comment by mosajjal** [comment]
I've made some progress regarding debug. This error pops up in wpa_supplicant whenever my device wants to get connected to `miraclecast`. 

`ignore scan data without p2p device info or p2p device id`

NOTE: As I mentioned above, the device shows up in `miracle-sinkctl`, but miraclecast won't show up on my phone.

I've also tried changing `wifid-supplicant.c`, changing config_methods etc. didn't help.

**Comment by albfan** [comment]
Check if `--use-dev` option helps on miracle-wifid. I have to share a correct session to allow you to compare

**Comment by mosajjal** [comment]
I'm investigating it further more. Looks like `WFD_SUBELEM_SET` is not doing its job when setting WFD IEs. This line in particular:

```
Jan 07 08:10:52 alarmpi miracle-wifid-wlan0-2[773]: wlan0: Control interface command 'WFD_SUBELEM_SET 0'
```
Can I see the string being sent to wpa_supplicant? I'll try and re-create it using wpa_cli and see what's wrong. By the way, I've used both realtek 8188CUS and realtek 8189FTV as wifi chips.

**Comment by albfan** [comment]
Any progress? Can I close this issue?

**Comment by mosajjal** [comment]
Yes, it turns out it was the wifi chip's problem. Changing the wifi chip fixed the issue. Although I'm moving to Airplay rather than Miracast altogether mostly because of compatibility with almost every device.
