### ISSUE TITLE
Feature request : please support xrandr or extend desktop

### ISSUE THREAD

**Issue by ytrezq** [albfan/miraclecast#162]
Currently, Miraclecast can only be used for screen mirroring : I mean in the case of Xorg that you can’t use the Miracast connected screen to display something differently than the first one.
This implies an other thing : for example, if I have crt display limited to 1024×768 then I won’t be able to display 1080p on the 1080p television.

**Comment by albfan** [comment]
Miracast just fixes some standars to use between two or more devices. See #4 for unimplemented feature (miraclecast as source) that will let you understand how to play around with miraclecast.

**Comment by ytrezq** [comment]
Yes, like ʜᴅᴍɪ. Concerning #4 do you mean it‘s co each application to support sending sending their video output by using Miraclecast as a library ?

**Comment by albfan** [comment]
Didn't understand completely you question. You can stream out anything you want using miracast spec. Default implementations on phones stream out source screen because they use miracast for screen mirroring

See #172 to understand how to use miraclecast to source whatever you want

**Comment by ytrezq** [comment]
@albfan : I simply mean an Xorg module is required for doing this by connecting screens through Miracast : ![](http://wiki.x2go.org/lib/exe/fetch.php/news:xinerama.png?w=600&tok=fa23af)

On Microsoft Windows®, you simply use ⊞+p

**Comment by albfan** [comment]
Take a look at #172. You can do what you want when you implement the source

**Comment by ytrezq** [comment]
@albfan : so again, do you mean that for getting what I’m wanting, I need to use a code editor and a toolchain ?

**Comment by albfan** [comment]
If you want to split a stream in 3 screens or whatever you need to customize miracle-gst.sh which takes the stream and outputs it (by default in a window) all the boilerplate part (negotiation, handshaking, stream) is done by miraclecast

**Comment by ytrezq** [comment]
@albfan : how do I tell Xorg to use a sceen resolution that match the one offered by the multiple displays ?
