### ISSUE TITLE
no link interface

### ISSUE THREAD

**Issue by fberier** [albfan/miraclecast#163]
Hi Alberto,

I've just install miraclecast. Make and install procees went well.
When I launch miracle-wifid, I've got no message, and no link interface is visible in the list of miracle-sinkctl.
Attached log file of wifid
[wifid.log.txt](https://github.com/albfan/miraclecast/files/696609/wifid.log.txt)

Thank you for your support.
Regards
Frederic B

**Comment by albfan** [comment]
Please upload all log files to get support https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support

Know your system (distro and version) is nice too

**Comment by fberier** [comment]
here are the logs 
[miraclecast-master.zip](https://github.com/albfan/miraclecast/files/705149/miraclecast-master.zip)
Thanks for your advice
Frederic

**Comment by albfan** [comment]
See this log line:

> DEBUG: ignored device: wlp1s0 (manager_add_udev_link() in ../../../src/wifi/wifid.c:116)

You can look for it on code:

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid.c#L116

I'm pretty sure you didn't enable RELY_UDEV feature

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid.c#L109

so you're passing a `-i` option

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid.c#L503

that do not match with the one your system has

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid.c#L112

(which is wlp1s0)

You don't need to specify a `-i` option except you have more than one wifi interface and want to select one of them.

You can check the names for your interfaces with:

    $ ls -1 /sys/class/net/

if you want to know which of them are wireless it must have a file "wireless" inside them

You can check easily that doing:

    $ . res/miracle-utils.sh
    $ find_wireless_network_interfaces

No magic here see

https://github.com/albfan/miraclecast/blob/master/res/miracle-utils.sh#L23

Is just a helper for boilerplate checks

for me it outputs:

    wlp3s0

That means that I have my card on pci bus 3 slot 0, seems yours is on pci 1.

More info here:

https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

**Comment by fberier** [comment]
Thank you Alberto.
I recompiled it **without** udev configure option, and it works great!
