### ISSUE TITLE
Package libudev and libsystemd not installed

### ISSUE THREAD

**Issue by DarknesGaming** [albfan/miraclecast#164]
Every time I use "../configure", everything goes well, until it says that packages "libudev" and "libsystemd" are not installed.
These packages do not exist, according to Ubuntu 16.10 (Yakkety Yak). Packages "libudev1" and "libsystemd0" do exist, already installed, and are on the latest version.
Where do I go to edit the "PKG_CONFIG_PATH"?

**Comment by albfan** [comment]
Ubuntu divide packages in binary, develop and debug (sometimes). To provide a develop package normally you need to add "-dev" to required package, for debug add "-dbg"

- http://packages.ubuntu.com/yakkety/libudev-dev
- http://packages.ubuntu.com/yakkety/libsystemd-dev

See those packages depends on packages you mention (libsystemd0 and libudev1)

install libsystemd and libudev develop packages with (as root):

    # apt-get install libudev-dev libsystemd-dev

Normally:

    $ sudo apt-get install libudev-dev libsystemd-dev

Seems there's no debug packages for this ones, so I guess debug info is included in dev packages.

**Comment by DarknesGaming** [comment]
Why didn't I think of this? I did this for a bunch of other packages.
Oops.

**Comment by DarknesGaming** [comment]
I haven't used the command line in a long time (which is about 2 months). I'm a Linux/macOS/Windows user, although I hate Windows because of how bloated and slow it is.

**Comment by albfan** [comment]
If that resolve your problem please close issue

**Comment by visbs** [comment]
even after installing the above command i am getting the same error 

--------------------------------------------------------
sudo apt-get install libudev-dev libsystemd-dev
--------------------------------------------------------
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsystemd-dev is already the newest version (237-3ubuntu10.9).
libudev-dev is already the newest version (237-3ubuntu10.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by albfan** [comment]
@visbs you didn't mention the error itself, paste all the output and let's see the problem

**Comment by visbs** [comment]
checking pkg-config is at least version 0.9.0... yes
checking for DEPS... no
configure: error: Package requirements (libwfd libudev libsystemd-daemon >= 208) were not met:

No package 'libsystemd-daemon' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEPS_CFLAGS
and DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.


but i have installed libsystemd-dev using the same command which u have suggested above.

**Comment by albfan** [comment]
@visbs the way a distro split a program may vary

Error is telling you a problem with libsystemd-daemon, so on Debian like system (Ubuntu is one of them) the device package should be:

https://packages.debian.org/sid/libsystemd-daemon-dev

You should follow errors on configure output, as it manages the details for every distro it runs on.

**Comment by visbs** [comment]
thanks for that @albfan  but now my wifi card is not recognised after sudo miracle-sinkctl &
i am using usb wifi adapter

**Comment by albfan** [comment]
@visbs that's unrelated with this issue. Please open a new one

**Comment by corradocampisano** [comment]
after having installed **libudev-dev** and **libsystemd-dev**, looks like **libreadline-dev** is required too:

```
checking readline/readline.h usability... no
checking readline/readline.h presence... no
checking for readline/readline.h... no
configure: error: GNU readline not found
```
so:
`apt install libreadline-dev`
fixes that too

**Comment by albfan** [comment]
@corradocampisano https://github.com/albfan/miraclecast/wiki/FAQ#ubuntu-requirements
