### ISSUE TITLE
Can someone help me set up Display-Sink

### ISSUE THREAD

**Issue by mjmeans** [albfan/miraclecast#165]
So I know almost nothing about Linux. I have an RPi that I booted with NOOBS and selected Raspian. I used the following commands to set up the WiFi:
```	
sudo wget https://dl.dropboxusercontent.com/u/80256631/install-wifi -O /usr/bin/install-wifi
sudo chmod +x /usr/bin/install-wifi
sudo install-wifi -c   //to make sure the 8188eu device is found
sudo install 8188eu    //to install the 8188eu device
sudo reboot
```
I am able to connect to te internet through the WiFi dongle, so that driver at least is working. I would like to make the RPi automatically boot into Display-Sink full screen without any UI, keyboard or any other UI. Automatically accept any Miracast connections and display the cast video full screen.

How do I do this? I'm looking for step by step instructions. Assume I know nothing at all about Linux. (I don't even know how to open up and use a text editor in Linux).

**Comment by albfan** [comment]
I cannot make this work for raspbian as systemd is too old on that distro, miraclecast needs systemd > 220.

Things may have changed since then.

Read #66 for raspberri pi I and #100 for a succesful install on a raspberry pi 3
