### ISSUE TITLE
Cannot connect to Microsoft Wireless Display Adapter v2

### ISSUE THREAD

**Issue by janhicken** [albfan/miraclecast#166]
Hi,

I'm using Arch Linux with Kernel 4.8.13 and the latest miraclecast r230. I'm trying to connect to a Microsoft Wireless Display Adapter v2 connected to a Samsung TV with my notebook. I'm able to find the device using p2p-scan but a connection fails (see [these](https://github.com/albfan/miraclecast/files/721859/logs.zip) logfiles I've produced).

Cheers

**Comment by albfan** [comment]
Check wip/windows-fix branch. It should connect properly but is not mature yet to merge
