### ISSUE TITLE
Maximize Gstreamer output window

### ISSUE THREAD

**Issue by pcmerioles609** [albfan/miraclecast#167]
Hi! Good day!

I have been playing with miraclecast running on RPI3 for a month now but I cannot seem to find how to maximize the gstreamer output window.

At first I thought the resolution is set by the Android phone so I updated Android's wfdconfig.xml but resolution is still the same.

Now, I saw in the code that the supported resolution is only 800x600.
Is that a limitation? Is there a way that the gstreamer window start out maximized directly by code?

Thank you!

**Comment by midi1996** [comment]
you need to add `--res` to your `miracle-sinkctl` options, it gotta look like this `--res default,CEA,00000100` (to check the resolutions and possible sizes, check `--help`).

**Comment by albfan** [comment]
A screenshot would help to understand the problem @pcmerioles609. Maybe you can add a mockup with what you want to see on screen (a fullscreen window with black bars somewhere to fit different sink screen or whatever)

**Comment by albfan** [comment]
Please add a screenshot of what you see now and what you want to see instead to get progress on this issue. If you manage to resolve this please close this issue

**Comment by albfan** [comment]
now `--external-player` option is avaliable something like https://github.com/albfan/miraclecast/commit/74b3e97083035f037a8556c3b5c679f67dadad60#diff-e50333667268649cfca37aded33133ddR215 should be enough. I will close this once that implementation is avaliable on master
