### ISSUE TITLE
Local helper are not distribution-independent

### ISSUE THREAD

**Issue by thopiekar** [albfan/miraclecast#17]
While looking at
```
thopiekar@hp:/usr/share/miraclecast$ cat miracle-wifi.sh 
./kill-wpa.sh

echo starting wpa_supplicant for miraclecast
sudo wpa_supplicant -dd -B -iwlp3s0 -Dnl80211 -c wpa.conf
```

I noticed that these scripts won't work on Ubuntu, as the first wifi-adapter is not called wlp3s0. After all the patches on Ubuntu's systemd it won't rename the network-devices and leave wlan0 as it is.

**Comment by albfan** [comment]
I have a rewrite for ubuntu which let's you choose device. Let me review it an push.

**Comment by albfan** [comment]
I think this 1287ce7a should work
