### ISSUE TITLE
Can I use miraclecast in Mint ?

### ISSUE THREAD

**Issue by YitzhakStone** [albfan/miraclecast#170]

**Comment by albfan** [comment]
I was sure I was answered this question before

https://gitter.im/albfan/miraclecast?at=58897b99519afee26bb2ea6b

Follow that instructions:

Is theorically possible but systemd avaliable in linux mint is old and it could be unstable

**Comment by albfan** [comment]
Hope that info guide you to try miraclecast, Can I close this issue?

**Comment by YitzhakStone** [comment]
I'll try later. You can close this. Thanks!
