### ISSUE TITLE
Raspberry pi 2 Ubuntu-mate 1604 with a TL-W722N

### ISSUE THREAD

**Issue by valinoberry** [albfan/miraclecast#173]
I need help! 

What have I done. on a new fresh system: systemctl --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

./test-hardware-capabilities.sh 
wlx8416f915e4a9 supports P2P

sudo apt-get install glib* git vlc build-essential bison flex cmake automake libsystemd-dev libudev-dev libreadline-dev libgstreamer1.0-dev gstreamer1.0 libtool
 git clone https://github.com/albfan/miraclecast.git
 cd miraclecast/
 ./autogen.sh
 mkdir build
 cd build
 ../configure --prefix=/usr/local #avoid --prefix for a standard install
 make -j8
 sudo cp ../res/org.freedesktop.miracle.conf /etc/dbus-1/system.d/
 sudo make install

./write-udev-rule.sh 
choose device to use with miraclecast:
1) enxb827eb211681
2) wlx8416f915e4a9
3) exit
#? 2
Provide order to udev rule (default 10): 10
...Press enter to finish (sorry, don't know why. It is related with sudo tee)

file /etc/udev/rules.d/10-network.rules writed
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="84:16:f9:15:e4:a9", NAME="wlx8416f915e4a9", TAGS+="miracle"
valino@berry:~/miraclecast/res$ 

sudo systemctl stop Network.service
Failed to stop Network.service: Unit Network.service not loaded.

sudo killall wpa_supplicant

 sudo service network-manager stop

sudo miracle-wifid --wpa-bindir /sbin &
[1] 5885
valino@berry:~/miraclecast/res$ miracle-wifid: unrecognized option '--wpa-bindir

 sudo miracle-wifid &
[1] 5906

 sudo miracle-sinkctl --uibc
[ADD] Link: 3
[miraclectl] # 

[miraclectl] # list
  LINK INTERFACE                FRIENDLY-NAME                 
     3 wlx8416f915e4a9          berry                         

  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 

 0 peers and 1 links listed.

sudo ./normal-wifi.sh 
[sudo] password for valino: 
killing existing wpa_supplicant connection
choose device for normal connection:
1) enxb827eb211681
2) wlx8416f915e4a9
3) exit
#? 2
starting wpa_supplicant for normal connection
Successfully initialized wpa_supplicant
Failed to open config file '/run/network/wpa_supplicant_wlx8416f915e4a9.conf', error: No such file or directory
Failed to read or parse configuration '/run/network/wpa_supplicant_wlx8416f915e4a9.conf'.

 $ sudo journalctl -f |& tee journal.log
    $ sudo miracle-wifid --log-level trace |& tee wifid.log
    $ sudo miracle-sinkctl --log-level trace |& tee sink.log

[journal.log.zip](https://github.com/albfan/miraclecast/files/779612/journal.log.zip)
[sink.log.zip](https://github.com/albfan/miraclecast/files/779613/sink.log.zip)
[wifid.log.zip](https://github.com/albfan/miraclecast/files/779614/wifid.log.zip)

thank you

**Comment by albfan** [comment]
See info on #100 (mostly valid although for rapberri pi 3) for more info. I will review this as soon as possible

**Comment by valinoberry** [comment]
I cannt find the misstake pleace help

**Comment by albfan** [comment]
Looking at your tries you execute too much I guess.

After stop network manager you need to kill all running instances of wpa_supplicant. (kill-wpa.sh can help with that but is just simple as do: 

    $ killall wpa_supplicant
)

Then you need to execute this commands to provide log

check system logs
    $ sudo journalctl -f |& tee journal.log

run miraclecast wifi daemon
    $ sudo miracle-wifid --log-level trace |& tee wifid.log

run miraclecast sink controller
    $ sudo miracle-sinkctl --log-level trace |& tee sink.log

Execute each one on different terminal as you need to interact with miracle-sinkctl

That should work

**Comment by valinoberry** [comment]
valino@berry:~$ sudo miracle-wifid --log-level trace |& tee wifid.log
INFO: miracle-wifid - revision 1.0 Feb 15 2017 16:37:35
DEBUG: friendly-name from local hostname: berry (manager_read_name() in ../../../src/wifi/wifid.c:370)
DEBUG: link: new link: wlx8416f915e4a9 (3) (link_new() in ../../../src/wifi/wifid-link.c:71)
DEBUG: supplicant: new supplicant for wlx8416f915e4a9 (supplicant_new() in ../../../src/wifi/wifid-supplicant.c:2087)
INFO: link: add link: wlx8416f915e4a9
INFO: link: manage link wlx8416f915e4a9
DEBUG: supplicant: start supplicant of wlx8416f915e4a9 (supplicant_start() in ../../../src/wifi/wifid-supplicant.c:2613)
DEBUG: supplicant: spawn supplicant of wlx8416f915e4a9 (supplicant_spawn() in ../../../src/wifi/wifid-supplicant.c:2462)
INFO: supplicant: wpa_supplicant found: /sbin/wpa_supplicant
INFO: supplicant: wpas spawned as pid:8746
DEBUG: supplicant: open supplicant of wlx8416f915e4a9 (supplicant_open() in ../../../src/wifi/wifid-supplicant.c:2253)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: p2p_device_address=84:16:f9:15:e4:a9
p2p_state=IDLE
wifi_display=1
ifname=wlx8416f915e4a9
address=84:16:f9:15:e4:a9

DEBUG: supplicant: local p2p-address is: 84:16:f9:15:e4:a9 (supplicant_status_fn() in ../../../src/wifi/wifid-supplicant.c:1807)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: OK

TRACE: wpa: raw message: FAIL

TRACE: wpa: raw message: OK

DEBUG: link: link wlx8416f915e4a9 started (link_supplicant_started() in ../../../src/wifi/wifid-link.c:287)
TRACE: wpa: raw message: FAIL

**Comment by albfan** [comment]
you need to upload the files that commads generates:

wifi.log
sink.log
journal.log

They are the complete log for a try

**Comment by valinoberry** [comment]
[journal.log.zip](https://github.com/albfan/miraclecast/files/793673/journal.log.zip)
[sink.log.zip](https://github.com/albfan/miraclecast/files/793676/sink.log.zip)
[wifid.log.zip](https://github.com/albfan/miraclecast/files/793677/wifid.log.zip)

**Comment by valinoberry** [comment]
im see jet the peer but i cant connet

**Comment by valinoberry** [comment]
you can close it.

the problem was the device

**Comment by valinoberry** [comment]
but i have a question. is it possible to use the wifi stick at the same time as miracleclast and access point? And for the security. can i do that connect **only** with pin or to at a fix mac adresse

**Comment by albfan** [comment]
You can select connection method on connect command in miracle-sinkctl

Here are the avaliable methods

https://github.com/albfan/miraclecast/blob/36be37ed8b87643cefd03b4ed1d32e192af19899/src/ctl/wifictl.c#L252

About use at same time for access point I'm working on it (trying to delegate that task on NetworManager) the idea is to open two interfaces on wpa_supplicant
