### ISSUE TITLE
miracast as source to Doogee P1 miracast projector

### ISSUE THREAD

**Issue by MrMEEE** [albfan/miraclecast#174]
Hi

I have connection to my Doogee P1 miracast projector working.. 

```
mj@falcon ~ $ sudo miracle-wifictl                                                                                                                                        
[sudo] adgangskode for mj:                                                                                                                                                
[ADD] Link: 3
[miraclectl] # select 3
link 3 selected
[miraclectl] # p2p-scan
[ADD] Peer: e2:76:d0:8f:54:79@3
[miraclectl] # connect e2:76:d0:8f:54:79@3
[CONNECT] Peer: e2:76:d0:8f:54:79@3
[miraclectl] # list
  LINK INTERFACE                FRIENDLY-NAME                 
     3 wlp3s0                   falcon                        

  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 
     3 e2:76:d0:8f:54:79@3      DOOGEE_P1_BOkJ70               yes       

 1 peers and 1 links listed.
```

But nothing appears on the screen...

I have tried running:

```
mj@falcon ~/Download/miraclecast/res $ LANG=en ./miracle-gst 
running: /usr/bin/gst-launch-1.0 -v udpsrc port= caps="application/x-rtp, media=video" ! rtpjitterbuffer latency=100 ! rtpmp2tdepay ! tsdemux ! queue max-size-buffers=0 max-size-time=0 ! h264parse ! avdec_h264 ! videoconvert ! autovideosink 
WARNING: erroneous pipeline: could not set property "port" in element "udpsrc0" to "caps="application/x-rtp,"
```

I have tried setting a port:

```
mj@falcon ~/Download/miraclecast/res $ LANG=en ./miracle-gst -p 8400
running: /usr/bin/gst-launch-1.0 -v udpsrc port=8400 caps="application/x-rtp, media=video" ! rtpjitterbuffer latency=100 ! rtpmp2tdepay ! tsdemux ! queue max-size-buffers=0 max-size-time=0 ! h264parse ! avdec_h264 ! videoconvert ! autovideosink 
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
/GstPipeline:pipeline0/GstUDPSrc:udpsrc0.GstPad:src: caps = "application/x-rtp\,\ media\=\(string\)video\,\ clock-rate\=\(int\)1\,\ encoding-name\=\(string\)MP2T"
/GstPipeline:pipeline0/GstRtpJitterBuffer:rtpjitterbuffer0.GstPad:sink: caps = "application/x-rtp\,\ media\=\(string\)video\,\ clock-rate\=\(int\)1\,\ encoding-name\=\(string\)MP2T"
Setting pipeline to PLAYING ...
/GstPipeline:pipeline0/GstRtpJitterBuffer:rtpjitterbuffer0.GstPad:src: caps = "application/x-rtp\,\ media\=\(string\)video\,\ clock-rate\=\(int\)1\,\ encoding-name\=\(string\)MP2T"
New clock: GstSystemClock
/GstPipeline:pipeline0/GstRtpMP2TDepay:rtpmp2tdepay0.GstPad:src: caps = "video/mpegts\,\ packetsize\=\(int\)188\,\ systemstream\=\(boolean\)true"
/GstPipeline:pipeline0/GstTSDemux:tsdemux0.GstPad:sink: caps = "video/mpegts\,\ packetsize\=\(int\)188\,\ systemstream\=\(boolean\)true"
/GstPipeline:pipeline0/GstRtpMP2TDepay:rtpmp2tdepay0.GstPad:sink: caps = "application/x-rtp\,\ media\=\(string\)video\,\ clock-rate\=\(int\)1\,\ encoding-name\=\(string\)MP2T"
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:05.955334892
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```

But nothing on the screen???

It works from my mobile phone....

Any ideas???

Regards

Martin

**Comment by albfan** [comment]
Can you add logs following instructions on wiki FAQ?

Let's see what's hapoening on sink log

**Comment by MrMEEE** [comment]
[miralog.tar.gz](https://github.com/albfan/miraclecast/files/783314/miralog.tar.gz)

**Comment by MrMEEE** [comment]
I have updated with log-files?? any ideas??

**Comment by derekdai** [comment]
miracle-wifid can help you to create WiFi P2P group and it runs miracle-dhcp to request (as dhcp client) or assign IP (as dhcp server), no more no less.

For establishing the WFD session (to cast you video wirelessly), you need to do more. First, create RTSP connection (TCP based) between source (sender, encoder) and sink (reciver, decoder) on top of newly created P2P network, then negotiate RTP ports and capabilities about display, audio, video, after that, you send stream with gstreamer, ffmpeg or vlc to the RTP port. You don't choose random port and send stream to, that's not how WFD working.

**Comment by MrMEEE** [comment]
Hmmm...

Any documentation on how to do the second part?? I'm a little lost here...

On the Android device i'm connecting to, there running a Miracast app, which works perfectly when I cast from my phone..

**Comment by derekdai** [comment]
Hi @MrMEEE:

In #172, I implemented part of source side spec, maybe you can try it.

**Comment by albfan** [comment]
@MrMEEE default port for miracast is 7236. On miraclecast (I should change that) 1991 is used. Check if #115 fix is related with your problem

**Comment by MrMEEE** [comment]
@derekdai Can you specify how to test your source side stuff????

**Comment by albfan** [comment]
@MrMEEE you can run as source on that wip and use https://play.google.com/store/apps/details?id=jp.ddo.pgnishikawa.wfdsinkemu as sink

**Comment by MrMEEE** [comment]
@albfan Could you give some more specific instructions on howto run as source (step-by-step)... ??

Sorry??

**Comment by albfan** [comment]
Sure. Beta testers are always welcome. See that is a wip, so there wil be dragons

1) checkout wip/source-impl
2) Compile (I think cmake compilation will work
3) Start miracle-wifid
4) run miracle-wifictl
5) use hep to see commands 
 https://github.com/albfan/miraclecast/blob/04a1ec8aa3f791dc276dab827df8968cf87e0c47/src/ctl/wifictl.c#L333
6) Start a p2p-scan so your sink can see you
7) start a request from sink to stream content
8) Use connect from your source so you accept the sink request

On https://github.com/albfan/miraclecast/tree/wip/source-impl/demo you have a vala project to compile a GUI to control source @derekdai can give you more details of its use

**Comment by MrMEEE** [comment]
Hi

I have checked out wip/source-impl, and did a "cmake ." and "make" in the root of the folder..

I have connected with miracle-wifictl with:
select 4
p2p-scan
connect <mac-address>

I'm unsure on 7 and 8.. the miracast app is running on the sink, and waiting for an input from the source.. What now???

I can't get the demo project to compile.. "cmake ." gives me:

mj@falcon:~/Download/miraclecast/wip-source/miraclecast-wip-source-impl/demo$ cmake .
CMake Error at CMakeLists.txt:19 (pkg_check_modules):
  Unknown CMake command "pkg_check_modules".


-- Configuring incomplete, errors occurred!
See also "/home/mj/Download/miraclecast/wip-source/miraclecast-wip-source-impl/demo/CMakeFiles/CMakeOutput.log".

Any ideas... maybe @derekdai ??

**Comment by albfan** [comment]
Update branch. I just fixed `pgk_check_modules` problem

Oh I say it incorrectly:

It is supossed that after p2p_scan you should see sink and connect to them. It is not the case?

**Comment by MrMEEE** [comment]
Ok.. I'll test..

Yes, it gives me the sink, and I can connect.. but nothing is streamed from the computer.. probably because I need to stream something (the screen as an example).. but I don't know how to do that.. I have tried with the gst-launch, but nothing happens...

**Comment by MrMEEE** [comment]
Hmmm...

mj@falcon:~/Download/miraclecast/wip-source/miraclecast-wip-source-impl/demo$ sudo ./miracle-wfdctl -p e2:76:d0:8f:54:79 -i wlp61s0
miracle-wfdctl: no display name specified by -d, use DISPLAY environment variable instead
miracle-wfdctl: no display authority specified by -x, use XAUTHORITY environment variable instead
miracle-wfdctl: no wfd_subelems specified by -w, use '000600111c4400c8' instead
miracle-wfdctl: failed to cast to wireless display: no such wireless adapter: wlp61s0

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp60s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether d4:81:d7:69:87:65 brd ff:ff:ff:ff:ff:ff
3: wlp61s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 9c:b6:d0:65:f0:6d brd ff:ff:ff:ff:ff:ff
4: vmnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:50:56:c0:00:01 brd ff:ff:ff:ff:ff:ff
    inet 172.16.214.1/24 brd 172.16.214.255 scope global vmnet1
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fec0:1/64 scope link 
       valid_lft forever preferred_lft forever
5: vmnet8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:50:56:c0:00:08 brd ff:ff:ff:ff:ff:ff
    inet 192.168.135.1/24 brd 192.168.135.255 scope global vmnet8
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fec0:8/64 scope link 
       valid_lft forever preferred_lft forever
6: enxe8ea6a159196: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether e8:ea:6a:15:91:96 brd ff:ff:ff:ff:ff:ff
    inet 192.168.20.203/24 brd 192.168.20.255 scope global dynamic enxe8ea6a159196
       valid_lft 2438sec preferred_lft 2438sec
    inet6 fe80::ced1:52c3:93c6:6f23/64 scope link 
       valid_lft forever preferred_lft forever
7: vpn0: <POINTOPOINT,MULTICAST,NOARP> mtu 1406 qdisc pfifo_fast state DOWN group default qlen 500
    link/none 
8: p2p-wlp61s0-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 9e:b6:d0:65:f0:6d brd ff:ff:ff:ff:ff:ff
    inet 192.168.49.73/24 scope global p2p-wlp61s0-0
       valid_lft forever preferred_lft forever


Have also tried:

mj@falcon:~/Download/miraclecast/wip-source/miraclecast-wip-source-impl/demo$ sudo ./miracle-wfdctl -p e2:76:d0:8f:54:79 -i p2p-wlp61s0-0
miracle-wfdctl: no display name specified by -d, use DISPLAY environment variable instead
miracle-wfdctl: no display authority specified by -x, use XAUTHORITY environment variable instead
miracle-wfdctl: no wfd_subelems specified by -w, use '000600111c4400c8' instead
miracle-wfdctl: failed to cast to wireless display: no such wireless adapter: p2p-wlp61s0-0

Any ideas??

**Comment by albfan** [comment]
stream screen is supposed to happen here 

https://github.com/albfan/miraclecast/blob/wip/source-impl/demo/wfdctl.vala#L374

**Comment by MrMEEE** [comment]
So basically when I run the connect command???

**Comment by derekdai** [comment]
Hi @MrMEEE, you can try the latest version in my repository
https://github.com/derekdai/miraclecast

With latest version, there are two daemon - miracle-wifid and miracle-dispd, and you run `miracle-wfdctl` (no sudo needed) to project your screen, when the WFD session established, `miracle-wfdctl` launches `gstencoder` to encode and streams to sink.

You can get all the log with the following command
```
$ sudo journalctl -umiracle-* -f
```

Currently, the `miracle-dispd` and `gstencoder` only project screen with 1080p@30 (hardcoded), I am figuring out how to better support variety combination of resolutions+h264 profiles+h264 levels.

**Comment by MrMEEE** [comment]
@derekdai When trying to connect through miracle-wifictl (backend miracle-wifid).. I get a short black screen, followed by a failure on the device... Log is here: https://pastebin.com/CBZ5t36u

I guess this is because miracle-dispd need to be running???
If I have both miracle-wifid and miracle-dispd running, and connect through miracle-wifictl.. I end up with the error:

[miraclectl] # select 3
link 3 selected
[miraclectl] # p2p-scan
[ADD] Peer: e2:76:d0:8f:54:79@3
[miraclectl] # connect e2:76:d0:8f:54:79@3
[FAIL] Peer: e2:76:d0:8f:54:79@3 Reason: group owner negotiation failed
[REMOVE] Peer: e2:76:d0:8f:54:79@3


in miracle-wifictl.. logfile for miracle-wifid is here: https://pastebin.com/Ekf3W2iB

Nothing on the device...

I'm unsure on howto use miracle-wfdctl

If I run it (miracle-wifid and miracle-dispd running).. I get:

mj@falcon:~$ miracle-wfdctl -p e2:76:d0:8f:54:79 -i wlp61s0
miracle-wfdctl: peer-mac=e2:76:d0:8f:54:79
miracle-wfdctl: display=:0
miracle-wfdctl: authority=/tmp/xauth-1000-_0
miracle-wfdctl: interface=wlp61s0
miracle-wfdctl: wfd_subelemens=000600001c4400c8
miracle-wfdctl: monitor-num=0
miracle-wfdctl: wait for peer 'e2:76:d0:8f:54:79'...



miracle-wfdctl: failed to cast to wireless display: timeout to wait for property Connected change
miracle-wfdctl: Bye

Logfile for wifid: https://pastebin.com/xZp8rUJ0

**Comment by MrMEEE** [comment]
I also tried with the app you metioned.. but it seems like it attaches to the wrong interface: https://play.google.com/store/apps/details?id=jp.ddo.pgnishikawa.wfdsinkemu

mj@falcon:~/Download/miraclecast/wip-source/miraclecast-wip-source-impl/src/ctl$ sudo ./miracle-wifictl 
[ADD] Link: 3
[miraclectl] # select 3
link 3 selected
[miraclectl] # p2p-scan
[ADD] Peer: e2:76:d0:8f:d4:79@3
[ADD] Peer: e2:76:d0:8f:54:79@3
[miraclectl] # connect e2:76:d0:8f:54:79@3
[miraclectl] # connect e2:76:d0:8f:d4:79@3

Nothing happens

**Comment by derekdai** [comment]
@MrMEEE after you installed miraclecast from my repository, two systemd services and two dbus services can be found in you system, named `miracle-wifid` and `miracle-dispd`, both are run as root. Then you run `miracle-dispctl` to project your screen to sink (the two services will be launched by dbus automatically). For example
```
$ miracle-dispctl -h
Usage:
  miracle-dispctl [OPTION...]

Help Options:
  -h, --help                                  Show help options
  --help-all                                  Show all help options
  --help-gapplication                         Show GApplication options

Application Options:
  -i, --interface=WNIC name                   name of wireless network interface
  -w, --wfd-subelems=device info subelems     device infomation.  default: 000600001c4400c8
  -p, --peer-mac=peer MAC                     MAC address of target peer
  -x, --authority=display authority           authority to capture from display. default: XAUTHORITY environment variable
  -d, --display=display name                  display name.	default: DISPLAY environment variable
  -m, --monitor-num=monitor number            monitor number.  default: -1, primary monitor
  -a, --audio-device=audio device name        pulseaudio device name
  -b, --dont-borrow=don't borrow WNIC         do not acquire the ownership of WNIC before using it
  -r, --dont-return=don't release WNIC        do not release the ownership of WNIC after using it

$ G_MESSAGES_DEBUG=all miracle-dispctl -p 00:50:56:c0:00:08 -i wlx18a6f71ec0b4
```

`miracle-dispctl` will acquire the ownership of `wlx18a6f71ec0b4` from the Network Manager and assign it to `miracle-wifid` (a temporary solution to co-exist with NM), then it tells `wifid` to start P2P scanning, wait for the peer `00:50:56:c0:00:08` appearing, check if it is a WFD sink, initiate P2P grouping with the sink, and then tell `dispd` wait for WFD session request from sink.

`dispd` then wait for RTSP connection request from sink, exchange caps with sink, establish WFD session, and finally, start `gstencoder` to project your screen.

`miracle-wifictl`, `mircle-sinkctl`, 'miracle-dispctl` are three control front-ends, you use it for different purpose.

`miracle-wifictl` controls `miracle-wifid` to scan peers and initiate P2P grouping, then you use the newly created P2P device as normal wireless NIC.

`miracle-sinkctl` act just like `miracle-wifictl`, but it further implements WFD sink side functionalities.

`miracle-dispctl` controls `miracle-dispd` and `miracle-wifid`, to provides WFD source side functionalities.

**Comment by albfan** [comment]
@derekdai, can you add a WIP section on https://github.com/albfan/miraclecast/wiki/Internals and add all that comment info there?

Link it to PR #172 too

**Comment by derekdai** [comment]
@albfan done

**Comment by wdv4758h** [comment]
@derekdai where can I find the `miracle-dispctl` command ? I build the miraclecast from your branch, but I can't find the command. Do I miss something or it's still not implemented yet ?

**Comment by albfan** [comment]
@wdv4758h I guess it is miracle-wfdctl

https://github.com/derekdai/miraclecast/blob/master/res/CMakeLists.txt#L55

@derekdai fix https://github.com/albfan/miraclecast/wiki/miracle-dispctl accordingly

**Comment by wdv4758h** [comment]
@albfan thx, it's `miracle-wfdctl` 👍 

However, I still encounter problem with `miracle-wfdctl` .

@derekdai error message on `miracle-wifid`:

```
[0765.675653] ERROR: supplicant: syscall failed (-22): Invalid argument (supplicant_group_free() in /home/wdv4758h/zone/miraclecast/src/wifi/wifid-supplicant.c:190)
[0765.675769] DEBUG: supplicant: killing DHCP-process pid:21851.. (supplicant_group_free() in /home/wdv4758h/zone/miraclecast/src/wifi/wifid-supplicant.c:198)
```

I'm trying to figure out what it pass to underneath library.

**Comment by albfan** [comment]
Please post logs as suggested on https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support

Normally those messages mean some problem with spawned process (lack of any needed program or similar)

@wdv4758h What OS are you using) (distro and version, systemd version)

**Comment by MrMEEE** [comment]
@albfan I still can't get it to work.. I have started the miracle-wifid and miracle-dispd services (systemctl start <service>).. 

running:

mj@falcon:~/Download/derek/miraclecast-master/build$ sudo G_MESSAGES_DEBUG=all miracle-dispctl -p e2:76:d0:8f:54:79 -i enxe8ea6a159196 
miracle-dispctl: peer-mac=e2:76:d0:8f:54:79
miracle-dispctl: display=:0
miracle-dispctl: authority=/tmp/xauth-1000-_0
miracle-dispctl: interface=enxe8ea6a159196
miracle-dispctl: wfd_subelemens=000600001c4400c8
miracle-dispctl: monitor-num=0
** INFO: dispctl.vala:284: connecting to wifid...
** INFO: dispctl.vala:295: connecting to nm...
** INFO: dispctl.vala:306: connecting to dispd...
** INFO: dispctl.vala:317: fetching from wifid...
** INFO: dispctl.vala:164: found wireless interface: wlp61s0
** INFO: dispctl.vala:322: fetching from nm...
** INFO: dispctl.vala:327: fetching from wfd...
miracle-dispctl: failed to cast to wireless display: no such wireless adapter: enxe8ea6a159196
miracle-dispctl: failed to release ownership of wnic: no such wireless adapter: enxe8ea6a159196
miracle-dispctl: Bye

And with the "normal" interface:

mj@falcon:~/Download/derek/miraclecast-master/build$ G_MESSAGES_DEBUG=all miracle-dispctl -p e2:76:d0:8f:54:79 -i wlp61s0miracle-dispctl: peer-mac=e2:76:d0:8f:54:79
miracle-dispctl: display=:0
miracle-dispctl: authority=/tmp/xauth-1000-_0
miracle-dispctl: interface=wlp61s0
miracle-dispctl: wfd_subelemens=000600001c4400c8
miracle-dispctl: monitor-num=0
** INFO: dispctl.vala:284: connecting to wifid...
** INFO: dispctl.vala:295: connecting to nm...
** INFO: dispctl.vala:306: connecting to dispd...
** INFO: dispctl.vala:317: fetching from wifid...
** INFO: dispctl.vala:164: found wireless interface: wlp61s0
** INFO: dispctl.vala:322: fetching from nm...
** INFO: dispctl.vala:327: fetching from wfd...
** INFO: dispctl.vala:337: NetworkManager is releasing ownership of wlp61s0...
** INFO: dispctl.vala:355: wifid is acquiring ownership of wlp61s0...
** INFO: dispctl.vala:374: wait for P2P supporting status...
** INFO: dispctl.vala:379: start P2P scanning...
miracle-dispctl: wait for peer 'e2:76:d0:8f:54:79'...
** INFO: dispctl.vala:176: peer added: e2:76:d0:8f:54:79@3 (DOOGEE_P1_BOkJ70)
** INFO: dispctl.vala:188: sink added: e2:76:d0:8f:54:79@3
** INFO: dispctl.vala:422: forming P2P group with e2:76:d0:8f:54:79 (DOOGEE_P1_BOkJ70)...
miracle-dispctl: failed to cast to wireless display: timeout to wait for property Connected change
** INFO: dispctl.vala:581: wifid is releasing ownership of wlp61s0...
** INFO: dispctl.vala:425: failed to form P2P group: lost
** INFO: dispctl.vala:588: NetworkManager is acquiring ownership of wlp61s0...
miracle-dispctl: Bye

sometimes it also gives:

mj@falcon:~/Download/derek/miraclecast-master/build$ G_MESSAGES_DEBUG=all miracle-dispctl -p e2:76:d0:8f:54:79 -i wlp61s0
miracle-dispctl: peer-mac=e2:76:d0:8f:54:79
miracle-dispctl: display=:0
miracle-dispctl: authority=/tmp/xauth-1000-_0
miracle-dispctl: interface=wlp61s0
miracle-dispctl: wfd_subelemens=000600001c4400c8
miracle-dispctl: monitor-num=0
** INFO: dispctl.vala:284: connecting to wifid...
** INFO: dispctl.vala:295: connecting to nm...
** INFO: dispctl.vala:306: connecting to dispd...
** INFO: dispctl.vala:317: fetching from wifid...
** INFO: dispctl.vala:164: found wireless interface: wlp61s0
** INFO: dispctl.vala:322: fetching from nm...
** INFO: dispctl.vala:327: fetching from wfd...
** INFO: dispctl.vala:337: NetworkManager is releasing ownership of wlp61s0...
** INFO: dispctl.vala:355: wifid is acquiring ownership of wlp61s0...
miracle-dispctl: failed to cast to wireless display: link wlp61s0 has no P2P supporting
** INFO: dispctl.vala:581: wifid is releasing ownership of wlp61s0...
** INFO: dispctl.vala:588: NetworkManager is acquiring ownership of wlp61s0...
miracle-dispctl: Bye

**Comment by MrMEEE** [comment]
mj@falcon:~/Download/derek/miraclecast-master/build$ iwconfig 
wlp61s0   IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=30 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
vmnet1    no wireless extensions.

vmnet8    no wireless extensions.

enp60s0   no wireless extensions.

lo        no wireless extensions.

enxe8ea6a159196  no wireless extensions.

**Comment by trietend** [comment]
Hey all,
i tried connecting to Microsoft Display Adapter. The connection could be established. In wireshark i could see, that the adapter tries to open a TCP-Connection on standard RTSP port 554 several times, but always gets a reset.
I think I'm using miracle-wfdctl in a wrong way or to the wrong time. I tried to launch it before, during and after connection establishment.
Any suggestions what I could try?
```
sudo miracle-wifid --log-level trace -i wlan1 |& tee wifid.log

sudo miracle-wifictl --log-level trace |& tee wifictl.log
[miraclectl] # select 5 
[miraclectl] # p2p-scan
[miraclectl] # connect 9a:5f:d3:be:19:f6@5

miracle-wfdctl -i wlan1 -p 9a:5f:d3:be:19:f6 |& tee wfdctl.log
```

[logs.zip](https://github.com/albfan/miraclecast/files/1064178/logs.zip)

**Comment by albfan** [comment]
@trietend microsoft extends miracast protocol and needs a bunch of responses to specific microsoft features

See #136 and related branch

https://github.com/albfan/miraclecast/tree/wip/windows-fix

**Comment by derekdai** [comment]
> miracle-dispctl: failed to cast to wireless display: timeout to wait for property Connected change

@MrMEEE sometimes, wpa_supplicant timed out to form a P2P group with no reason, you can try more times to see if the situation changes.

The second possibility will be the firewall blocks DHCP request from sink, just turn the firewall off or change the default policy of the P2P interface to ACCEPT.

Post your dispd and wifid log here will be helpful.

> mj@falcon:~/Download/derek/miraclecast-master/build$ iwconfig

you can run `sudo iw list` instead to check the more detailed capabilities of your WNIC.

**Comment by trietend** [comment]
@albfan The Microsoft Display Adapter is a sink device. It looks like it's based on an embeded linux, so i don't know if I really need the fix. It is also posible to cast the screen of an android device with the buildin functionalities. I don't know if the extended protocol is implement in android, but I don't think so.

Should I try a auto merge of wip/source-impl and wip/windows-fix?
Or is the demo path of the wip/source-impl independent so I could copy this into wip/windows-fix?
Or do you think it's not posible to merge them at the moment?

**Comment by albfan** [comment]
As this is for an specific device @trietend, please open a different issue and wheter it works or not upload logs, so we can help you if that don't work or can be used as guide dor other extrrnal devices

**Comment by albfan** [comment]
Let's keep all these tries on #4
