### ISSUE TITLE
How to handle IDR request?

### ISSUE THREAD

**Issue by derekdai** [albfan/miraclecast#175]
Hi:

I am dealing with an issue that is, once start playing, Mi TV (sink) will keep sending me (source) wfd-idr-request (even I reply it with 'not implemented').

I use gstreamer to encode video. Tried vaapih264enc and x264enc elements, the same result. Any idea?

**Comment by albfan** [comment]
I guess you need to answer 0

https://msdn.microsoft.com/en-us/library/mt242344.aspx

**Comment by derekdai** [comment]
I think wfd_idr_request_capability is part of Microsoft's WFD extension.

**Comment by derekdai** [comment]
Since I can't found enough information on this issue, I will close this issue and try to solve it latter by myself.

**Comment by albfan** [comment]
Derek it is totally the opposite, I much prefer open issues about things rounding my mind, and add info to them when I found doc or possible solutions. That allow people looking for same questions to find this work in progress, and maybe implement a partial or total solution.

Anyway: Why add a response:

    wfd_idr_request_capability: 0

do not work to solve this?

**Comment by derekdai** [comment]
OK, I will reopen the issue.

Although wfd_idr_request_capability is part of Microsoft's WFD extension, if the sink won't terminate the RTSP connection because it doesn't know the request, I will add it.

**Comment by albfan** [comment]
take a look at wip/windows-fix. That branch works with windows 10 miracast implementation at least (there's an known lag at start I have to resolve, but after a while it works)

**Comment by derekdai** [comment]
Got it.

**Comment by derekdai** [comment]
According to this document
https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-WFDPE/[MS-WFDPE]-150630.docx

The `wfd_idr_request_capability` is send from source to sink to check the caps of sink whether or not it will send `idr_request`, but we can't ask sink not to send it. I think currently, the only choice is to reply `idr_request` with `OK` but done nothing.

**Comment by albfan** [comment]
> Since the purpose of the RTSP M13 message is to request that the Wi-Fi Display Source generate an instantaneous decoder refresh (IDR) picture ...

I think your sink thinks you have idr_request capabilities

Is supposed it ask your for your capabilities on M3 message and you need to reply with 

wfd_idr_request_capability: 0

to avoid it to ask for that instantaneous decoder refresh

Can you put the rtsp messages from a session here?

**Comment by albfan** [comment]
@derekdai I think you find why wip/windows-fix gets a undefined black screen at start

https://github.com/albfan/miraclecast/blob/wip/windows-fix/src/ctl/ctl-sink.c#L111

I have to try replying 0 to avoid source expects sink to request idr (can wait to try it!)

**Comment by albfan** [comment]
I tested a windows connection with latest changes on master and is working.

Right now is a fixed key:value extension (not sure if something needs to be dynamic/calculated at some point)

I suppose this fixed with that
