### ISSUE TITLE
stream player not opening

### ISSUE THREAD

**Issue by albfan** [albfan/miraclecast#179]
`miracle-sinkctl` needs to be run as superuser (sudo) to access dbus managed object

src/ctl/ctl-wifi.c:1103

but that makes player running by it run as superuser too. Recently there's some change in *nix systems that disable access to other users to the xsession if they not start it. That makes Gtk/Gdk GStreamer fail to start from superuser (at least in my machine)

That denied access to xsession makes sense, but there must be a way to share it with users you designate on purpose

**Comment by albfan** [comment]
The command to share that access is: `xhost +si:localuser:root`

if you want to have that enabled by default on every restart add this to `~/.profile`

```
if [ -n "$DISPLAY" -a -z "$SSH_CLIENT" ]; then
    xhost +si:localuser:root
fi
```

**Comment by derekdai** [comment]
Hi albfan:

In my branch, I solve this problem by setting DISPLAY and XAUTHORITY as temporary solution (bad for thread safty). This way, both video and audio work fine.

And, if you wish to grant normal user to access wifid via DBus, try this patch
https://github.com/derekdai/miraclecast/commit/cb821562ede15942ef9f7604f626034d7547e736

In the future, we can integrate polkit and check user credential in service side (eg. wiifd) to do detailed access control.

**Comment by albfan** [comment]
that would be really the way to go (fine grain access) Can you open an issue about that?

**Comment by albfan** [comment]
I did it myself #185. @derekdai please provide solutions there
