### ISSUE TITLE
Using systemd service method to apply wpa.conf

### ISSUE THREAD

**Issue by thopiekar** [albfan/miraclecast#18]
While looking for an alternative for restarting wpa_supplicant, I read this part of the archlinux wiki ( https://wiki.archlinux.org/index.php/WPA_supplicant#At_boot_.28systemd.29 ).
Would it be save to have our wpa.conf installed somewhere, eg. /usr/share/miraclecast/wpa.conf, and link eg. /etc/wpa_supplicant/wpa_supplicant-wlan0.conf to it?
Or is our wpa.conf only working with miraclecast or wifi-direct?

**Comment by albfan** [comment]
By now it's only a manual configuration not compatible with internet access. That's why it is a simple file on res/. But I have a modification to allow to open files from another path. Maybe it's time to upload

**Comment by albfan** [comment]
By now 38d92c8 is the finest approach to ease change wireless configuration. I'm sure it doesn't work on all distros but leads a way to deal with wpa_supplicant.

If you find a way to keep various configs for an interface please provide an example. by now I will close this issue.
