### ISSUE TITLE
port to meson

### ISSUE THREAD

**Issue by albfan** [albfan/miraclecast#180]
To be with the cool kids, Build miraclecast with meson

**Comment by otavio** [comment]
Meson?

**Comment by albfan** [comment]
http://mesonbuild.com/
https://en.wikipedia.org/wiki/Meson_build_system

@otavio as you can see in GNOME is getting a lot of traction 

This is what I get from ac_converter.py

```
$ <meson-git-clone>/tools/ac_converter.py configure.ac 
cc = meson.get_compiler('c')
cdata = configuration_data()
check_headers = [
]

foreach h : check_headers
  if cc.has_header(h.get(1))
    cdata.set(h.get(0), 1)
  endif
endforeach

check_functions = [
]

foreach f : check_functions
  if cc.has_function(f.get(1), prefix : f.get(2))
    cdata.set(f.get(0), 1)
  endif
endforeach


configure_file(input : 'config.h.meson',
  output : 'config.h',
  configuration : cdata)
```
cmake2meson.py shows even worst results.

I guess I have to do all by hand.

https://github.com/mesonbuild/meson/wiki/Porting-from-autotools

**Comment by derekdai** [comment]
I almost done it, only two meson files to go.

**Comment by albfan** [comment]
Cool, if you open a PR, maybe @TingPing (gnome-builder dev) can help us to review port

**Comment by derekdai** [comment]
No problem, but I have to finish some higher priority tasks, maybe next week.

**Comment by albfan** [comment]
It is almost done!

https://github.com/derekdai/miraclecast/commit/579b76f334662228674bafd2e269dbe5aba28949

Well done Derek!

**Comment by derekdai** [comment]
Thank you, @albfan, for inviting @TingPing to review my meson works, I learn a lot from him.

**Comment by derekdai** [comment]
I've done migration from cmake to meson, @albfan, please help to review it, thanks!
https://github.com/albfan/miraclecast/pull/192

**Comment by albfan** [comment]
Add code review comments on it @derekdai

**Comment by albfan** [comment]
Checkout @TingPing comments on review

**Comment by albfan** [comment]
Done!

https://github.com/albfan/miraclecast/commit/6b5907ad458d410cea53c799056c81f36a2c8cd7

More info here:

https://github.com/albfan/miraclecast/wiki/Building
