### ISSUE TITLE
provide routing service if we run as GO

### ISSUE THREAD

**Issue by derekdai** [albfan/miraclecast#190]
Most entry level wireless PHYs can't run in multiple mode simultaneously, once switched to P2P mode, no Internet any more. So, if we are GO and runing a DHCP service plus a wired connection, why not route for our peer?

**Comment by albfan** [comment]
This is the kind of things we should dekegate on nm or connman. Better integrate with them than poorly reimplement ourselves.

As usual, before reach that point wip are welcomed

**Comment by derekdai** [comment]
You are right, let nm or connman do it.
