### ISSUE TITLE
Do I need to pay a licensing or certification fee to the Wi-Fi Alliance to use this?

### ISSUE THREAD

**Issue by eligrey** [albfan/miraclecast#194]
I won't be mentioning Miracast anywhere in my app or app description. Should I expect to be sued by the Wi-Fi Alliance if I use this in a paid Android app?

**Comment by albfan** [comment]
I think is the opposite, but I'm not a lawyer. wifi miracast is an specification, so you can reimplement it yourself. If you want them to certificate your device as miracast compatible then maybe you should, but that's just a commercial enhancement, not a functional requirement

**Comment by eligrey** [comment]
Cool, thanks Alberto.
