### ISSUE TITLE
Requested 'libsystemd > 219' but version of systemd is 219

### ISSUE THREAD

**Issue by danielres** [albfan/miraclecast#195]
Hi,

I'm trying to compile Miraclecast on ubuntu 15.04 vivid.
Unfortunately, on `../configure`, compilation stops with this error:

`Requested 'libsystemd > 219' but version of systemd is 219`

Any advice on how to proceed ?

Thank you

**Comment by albfan** [comment]
Some interface changes was made on systemd 219 that break compatibility. There's a branch systemd-219 for that

https://github.com/albfan/miraclecast/blob/systemd-219/configure.ac#L47

That should work.

There was several fixes that can be rebased onto that branch if you find it do not perform smoothly. But shoud build and run at least

Keep me informed from your progress

**Comment by albfan** [comment]
Please reopen if have any problem
