### ISSUE TITLE
can't start Miraclecast on Ubuntu 15.04

### ISSUE THREAD

**Issue by danielres** [albfan/miraclecast#196]
I managed to compile Miraclecast on Ubuntu 15.04 using the systemd-219 branch and to shutdown the network manager using `sudo service NetworkManager stop`

The doc says next step should be:
`sudo miracle-wifid &`

Unfortunately, this results in follwing error:

```
[1] 8309
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in ../../../src/wifi/wifid-dbus.c:898)
[1]  + 8309 exit 13    sudo miracle-wifid
```

Any idea how to proceed ?
Thanks

**Comment by albfan** [comment]
I just cherry picked https://github.com/albfan/miraclecast/commit/84d602793db4c070a8be3c43441fc58309d2e356 as many ones forget to install dbus policy

Reinstall and all should work
