### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in wifid-dbus.c:902)

### ISSUE THREAD

**Issue by loyalpartner** [albfan/miraclecast#20]
when i run `sudo miracle-wifid`

i get this error
```
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in wifid-dbus.c:902)
```

**Comment by albfan** [comment]
You need to run wpa_supplicant with ap mode on. See miracle-wifi.sh on res/ directory

Also take a look to install steps in README.md

**Comment by loyalpartner** [comment]
tks, but i get another error !!- -
```
res|master⚡ ⇒ ./kill-wpa.sh
killing actual wpa_supplicant connection
res|master⚡ ⇒ sudo rm /run/wpa_supplicant/ -rf
res|master⚡ ⇒ ./miracle-wifi.sh
killing actual wpa_supplicant connection
starting wpa_supplicant for miraclecast
wpa_supplicant v2.1
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf 'wpa.conf' driver 'nl80211' ctrl_interface 'N/A' bridge 'N/A'
Configuration file 'wpa.conf' -> '/home/lee/src/miraclecast/res/wpa.conf'
Reading configuration file '/home/lee/src/miraclecast/res/wpa.conf'
ctrl_interface='/run/wpa_supplicant'
ap_scan=1
device_name='my-device'
config_methods='pbc'
rfkill: initial event: idx=0 type=1 op=0 soft=0 hard=0
rfkill: initial event: idx=1 type=2 op=0 soft=0 hard=0
rfkill: initial event: idx=2 type=1 op=0 soft=0 hard=0
rfkill: initial event: idx=4 type=2 op=0 soft=0 hard=0
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Using driver-based off-channel TX
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 3 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x1b77d70
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=0104
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=040a
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=040b
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=040c
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=040d
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=090a
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=090b
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=090c
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=090d
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=0409506f9a09
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=7f506f9a09
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=0801
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=06
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=0a07
nl80211: Register frame type=0xd0 nl_handle=0x1b77d70 match=0a11
netlink: Operstate: ifindex=3 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=CN
nl80211: 2402-2482 @ 40 MHz 20 mBm
nl80211: 5735-5835 @ 40 MHz 30 mBm
nl80211: 57240-59400 @ 2160 MHz 28 mBm
nl80211: 59400-63720 @ 2160 MHz 44 mBm
nl80211: 63720-65880 @ 2160 MHz 28 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: 9c:4e:36:18:e0:2c
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=4 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=3 (wlan0) alg=0 addr=(nil) key_idx=5 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: State: DISCONNECTED -> INACTIVE
wlan0: WPS: UUID based on MAC address: b7541e60-83b5-5993-80d4-135c8e847fee
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
wlan0: Added interface wlan0
wlan0: State: INACTIVE -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=3 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Daemonize..

res|master⚡ ⇒ sudo miracle-wifid
[sudo] password for lee:
ERROR: supplicant: execution of wpas (/usr/bin/wpa_supplicant) not possible: No such file or directory (supplicant_spawn() in wifid-supplicant.c:2398)
ERROR: link: cannot start supplicant on wlan0 (link_set_managed() in wifid-link.c:149)
```

**Comment by albfan** [comment]
I guess you are on a distro where wpa_supplicant is not on expected path

For those cases there's a `--wpa-bindir` option. 

e. g.

On Ubuntu wpa_supplicant  is on `/sbin/wpa_supplicant ` so this option should be

    $ sudo miracle-wifid --wpa-bindir /sbin

**Comment by loyalpartner** [comment]
i do it,  i get this warning.
```
res|master⚡ ⇒ sudo miracle-wifid --wpa-bindir /sbin/
WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in wifid-supplicant.c:1657)
WARNING: supplicant: wpa_supplicant does not support wifi-display (supplicant_status_fn() in wifid-supplicant.c:1748)
```
i run the command ` sudo miracle-sinkctl `
```
res|master⚡ ⇒ sudo miracle-sinkctl 
[ADD] Link: 3
[miraclectl] # run 3
ERROR: cannot change p2p-scanning state on link 3 to 1: Invalid argument (ctl_link_set_p2p_scanning() in ctl-wifi.c:671)
now running on link 3
```

**Comment by keyser84** [comment]
I got the same warnings (also on Ubuntu 15.04). Check for supported modes of the wireless device:
`$ iw list`
Then search for **Supported interface modes**. In my case there are no P2P modes in the list. But there are P2P entries in **Supported TX/RX frame types**. As wpa_supplicant is running in AP mode, maybe that's enough?

wifi-display is supported by wpa_supplicant since v2.0 but there were some more recent changes to P2P functionalities (see [changelog](http://w1.fi/cgit/hostap/plain/wpa_supplicant/ChangeLog)). Which wpa_supplicant version is required?

**Comment by albfan** [comment]
Checking your device capabilities is a prior step to use miraclecast. So if have added a script checker

[test-wifi-capabilities.sh](https://github.com/albfan/miraclecast/blob/master/res/test-wifi-capabilities.sh)

I will polish it later. https://github.com/albfan/miraclecast/issues/22

wpa_supplicant 2.x should be enough.

**Comment by loyalpartner** [comment]
i rebuild wpa_supplicant v2.4 and im sure i have enabel wifi-display and p2p option.
i run `iw list` i got
```
....
        Supported RX frame types:
                 * IBSS: 0x40 0xb0 0xc0 0xd0
                 * managed: 0x40 0xd0
                 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * mesh point: 0xb0 0xc0 0xd0
                 * P2P-client: 0x40 0xd0
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * P2P-device: 0x40 0xd0
....
```
when i run `sudo miracle-wifid --wpa-bindir /usr/local/sbin/' it warning me
```
WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in wifid-supplicant.c:1657)
```
so my driver is not support p2p,right?

thanks for your help!

**Comment by albfan** [comment]
It's your device (usb or card) the one that do not support P2P. relevant section to check on `iw list` is **Supported interface modes**

As said, you can check with that script prior mentioned. It was created adhoc for this issue, as it is becoming recurrent.

When #22 is closed I will add it to README.md as prerrequisite

**Comment by keyser84** [comment]
I am using a *Netis WF2120* with *rtl8192cu* driver.

The script for testing the WiFi capabilities gives me: `wlan3 supports P2P`
But *miracle-wifid* gives me again these warnings that P2P and wifi-display are not supported.
In *miracle-sinkctl*, I can execute `run 4` without getting an error: `now running on link 4` (which corresponds to the wlan3 interface).
But I cannot find any devices when searching from CyanongenMod 11. I tried with the built-in screencasting app (Settings - Display & lights - Cast screen) and with the official Chromecast app.

What is going wrong there? How can I debug this?

**Comment by albfan** [comment]
Seeing #24 and that error on exit I guess you haven't configured wpa_supplicant. If your device is not told to work on Wi-fi Direct mode it will not discover other peers.

If manual configuration for wpa_supplicant seems hard, try [miracle-wifi.sh](https://github.com/albfan/miraclecast/blob/master/res/miracle-wifi.sh)

I will change README.md to document script helpers on res/ directory. Please provide feedback if something does'nt work or can be improved

**Comment by albfan** [comment]
On #23 you say you don not see any device to execute run command. Here you say you can launch it. What is your use case?

Please see issues as separate problems. people will come here for:

ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in wifid-dbus.c:902)

Don't hesitate to open another issue. I will delete these ones to avoid misguide others

**Comment by albfan** [comment]
You have the tester finished. Now it must say your device is not compatible.

> Sorry, <wifi-interface> do not support P2P

Before close this issue I want to be sure on this: have you added dbus policy for miraclecast?

**Comment by loyalpartner** [comment]
@albfan i run test-wifi-capabilities.sh and getSorry, <wifi-interface> do not support P2P.

I dont know , please tell me the way to make sure it.

**Comment by albfan** [comment]
It's telling your dongle or card do not support WiFi-Direct. It's a hardware issue. You cannot configure anything to solve it. Check your hardware specs to   comfirm it.

What is your wifi device model?

**Comment by loyalpartner** [comment]
Intel 2200 BGN

**Comment by albfan** [comment]
I cannot find doc about that card. Let us know if you make any progress.

**Comment by 275288698** [comment]
@albfan 
hi albfan !
     our team meet the almost same question as  'loyalpartner "  but  our  error code 
is 13:
#sudo  run miracle-wifid 
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:902)
?
here is the env:
   ubuntu 15.04,  systemd 221.  

and if we change the code sd_bus_default_system( ) to sd_bus_default_user( ) , this problem will solve , but another question is coming :  permission deny for the later code .

**Comment by albfan** [comment]
Your device is managed by system, you can see it with

    $ ps -ef | grep wpa_supplicant

on a fresh boot.

You cannot manage your device as normal user.

If you use [dfeet](https://wiki.gnome.org/action/show/Apps/DFeet?action=show&redirect=DFeet) to monitor dbus calls you can see it is on system tab not on session tab

**Comment by 275288698** [comment]
yes , i know  i can't run it with  normal user.  but when i run it under root :
#sudo  run miracle-wifid    
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:902)


so why  run it  by root  return 13? (and the linux error code is :
EACCES   13   Permission denied), i am confused....

**Comment by albfan** [comment]
Check you have added all the Requirements:

I think you miss [add dbus policy](https://github.com/albfan/miraclecast/blame/master/README.md#L27)

**Comment by mcgyver83** [comment]
Same issue on Ubuntu 15.04
test-viewer.sh says  passed for all and test-wifi-capabilities.sh  say that the card wlan0 supports P2P.

I run ./kill-wpa.sh and after
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in wifid-dbus.c:902)

**Comment by albfan** [comment]
I guess you would be interested on 

https://github.com/albfan/miraclecast/issues/32#issuecomment-134294785

Maybe you call twice the miracle wifi daemon?
