### ISSUE TITLE
Miraclecast crash when source disconnect

### ISSUE THREAD

**Issue by tomerf** [albfan/miraclecast#200]
When miraclecast works as a sink and a client disconnect while streaming it causes the wpas process to timeout, sending a HUP message to the supplicant process, which response by killing the wpas process and trying to restart it.
However, the wpas process fails to start again and just causes miraclecast to stop working.

Example (from #148):
https://github.com/albfan/miraclecast/files/925943/log2_succ.txt
```
TRACE: wpa: raw message: IFNAME=p2p-wlp3s0-0 <3>CTRL-EVENT-DISCONNECTED bssid=ae:bc:32:bd:cc:fd reason=3 locally_generated=1
ERROR: supplicant: HUP on supplicant socket of wlp3s0 (supplicant_global_fn() in ../../../src/wifi/wifid-supplicant.c:2161)
ERROR: supplicant: wpas (pid:12962) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in ../../../src/wifi/wifid-supplicant.c:2331)
DEBUG: supplicant: terminating wpas (pid:12962) (supplicant_failed() in ../../../src/wifi/wifid-supplicant.c:2346)
DEBUG: supplicant: close supplicant of wlp3s0 (supplicant_close() in ../../../src/wifi/wifid-supplicant.c:2310)
DEBUG: peer: peer 36:fc:ef:c9:a9:59 @ wlp3s0 stopped (peer_supplicant_stopped() in ../../../src/wifi/wifid-peer.c:172)
DEBUG: peer: free peer: 36:fc:ef:c9:a9:59 @ wlp3s0 (peer_free() in ../../../src/wifi/wifid-peer.c:90)
INFO: peer: remove peer: 36:fc:ef:c9:a9:59
DEBUG: link: link wlp3s0 stopped (link_supplicant_stopped() in ../../../src/wifi/wifid-link.c:297)
DEBUG: supplicant: spawn supplicant of wlp3s0 (supplicant_spawn() in ../../../src/wifi/wifid-supplicant.c:2478)
INFO: supplicant: wpa_supplicant found: /sbin/wpa_supplicant
INFO: supplicant: wpas spawned as pid:13016
ERROR: supplicant: wpas (pid:13016) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in ../../../src/wifi/wifid-supplicant.c:2331)
DEBUG: supplicant: terminating wpas (pid:13016) (supplicant_failed() in ../../../src/wifi/wifid-supplicant.c:2346)
DEBUG: supplicant: close supplicant of wlp3s0 (supplicant_close() in ../../../src/wifi/wifid-supplicant.c:2310)
DEBUG: caught SIGCHLD for 13016, reaping child (manager_signal_fn() in ../../../src/wifi/wifid.c:178)
```

Test system: Ubuntu 17.04 on MacBook Pro with miraclecast, LG G3 phone (builtin miracast).
Steps to reproduce:
1. Install and launch miraclecast:
`sudo miraclecast-wifid --use-dev --log-level TRACE`
2. Run miracle-sinkctl and scan for sources:
```
sudo miracle-sinkctl
run 2
```
3. Open miracast settings on phone and connect to miraclecast.
4. Wait for screen mirroring to appear, verify it work
5. Turn miracast off on phone

Additional info:
I added a log message and verified the code reach a timeout on wpas_timer_fn():
https://github.com/albfan/miraclecast/blob/master/src/shared/wpas.c#L1524

**Comment by albfan** [comment]
Any suggestion for a better way to handle this situation? When source disconnects if left the interface busy and there's no way to recover it (on a raspberry pi for example) except reboot

**Comment by albfan** [comment]
I will consider this, do some tests and try to improve disconnect managing
