### ISSUE TITLE
configure: error: Package requirements (libudev libsystemd > 219) were not met:

### ISSUE THREAD

**Issue by sijokwork** [albfan/miraclecast#203]
Hi,
when I try to compile: the following error's are getting ,
host system ubuntu trusty 14.04 , little help on this appreciated .
thanks 

Miracast/miraclecast$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc option to accept ISO C99... -std=gnu99
checking for ar... ar
checking the archiver (ar) interface... ar
checking for a sed that does not truncate output... /bin/sed
checking whether ln -s works... yes
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for gawk... (cached) gawk
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc -std=gnu99... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... yes
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for cos in -lm... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for DEPS... no
configure: error: Package requirements (libudev libsystemd > 219) were not met:

No package 'libudev' found
No package 'libsystemd' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEPS_CFLAGS
and DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details

**Comment by albfan** [comment]
Old ubuntu are based on sysvinit, but miraclecast systemd to work.

You should use ubuntu 15 at least (and compile your own systemd with kdbus) or use ubuntu 16

More info in https://github.com/albfan/miraclecast#ubuntu

**Comment by sijokwork** [comment]
Ok ,Thanks for the reply , 
I gonna upgrade and make try for miraclecast compile once again ...

**Comment by sijokwork** [comment]
done with ubuntu 16 
thanks for your support

**Comment by albfan** [comment]
Cool.

**Comment by TiboQc** [comment]
Ubuntu 17.10, same error...

**Comment by albfan** [comment]
@TiboQc, in Ubuntu you need to install dev package, systemd-dev or libsystemd-dev (using apt-get)

**Comment by TiboQc** [comment]
Thanks @albfan.
Seems to work now (`sudo miracle-sinkctl` enters the `[miraclectl] # ` console mode). My phone can't see the laptop yet (even though it supports Miracast, being LG V30). I'll look around a bit more and post a thread if I can't work it out.

**Comment by albfan** [comment]
@TiboQc sure!

**Comment by konjoon** [comment]
I am using lubuntu 18.04 and during compiling, I encounterd the following message.

checking for cos in -lm... yes
../configure: line 13644: syntax error near unexpected token `DEPS,'
../configure: line 13644: `PKG_CHECK_MODULES(DEPS, libudev libsystemd > 219)'

**Comment by konjoon** [comment]
Would you check what the problem is for the following message?
The message came out during  running "../autogen.sh g."
I am using lubuntu 18.

=======
checking for cos in -lm... yes
../configure: line 13644: syntax error near unexpected token `DEPS,'
../configure: line 13644: `PKG_CHECK_MODULES(DEPS, libudev libsystemd > 219)'
======

**Comment by albfan** [comment]
@konjoon I think that means you miss the pkg-config package. I think there's a meta package called build-essential that install a bunch of devel packages for you on ubuntu. You have a detailed list of needed packages in wiki FAQ: https://github.com/albfan/miraclecast/wiki/FAQ#ubuntu-requirements
