### ISSUE TITLE
miraclecast output a black window

### ISSUE THREAD

**Issue by mihuyo** [albfan/miraclecast#205]
Hi,
I run `miracle-sinkctl --uibc` but just output black window, my htc e9 connected fine 

**sink.log**

```
NOTICE: SINK connected
DEBUG: INCOMING: OPTIONS * RTSP/1.0
Date: Tue, 16 May 2017 09:07:04 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 1
Require: org.wfa.wfd1.0


 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
Public: "org.wfa.wfd1.0, GET_PARAMETER, SET_PARAMETER"
CSeq: 1


 (sink_handle_options() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:49)
DEBUG: OUTGOING: OPTIONS * RTSP/1.0
Require: org.wfa.wfd1.0
CSeq: 1


 (sink_handle_options() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:72)
DEBUG: INCOMING: RTSP/1.0 200 OK
Date: Tue, 16 May 2017 09:07:04 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 1
Public: org.wfa.wfd1.0, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER


 (sink_req_fn() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:28)
DEBUG: INCOMING: GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Tue, 16 May 2017 09:07:04 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 2
Content-Type: text/parameters
Content-Length: 104

wfd_content_protection
wfd_video_formats
wfd_audio_codecs
wfd_client_rtp_ports
wfd_uibc_capability

 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
Content-Length: 324
Content-Type: text/parameters
CSeq: 2

wfd_content_protection: none
wfd_video_formats: 00 00 03 10 0000001f 00000003 00000000 00 0000 0000 10 none none
wfd_audio_codecs: AAC 00000007 00
wfd_client_rtp_ports: RTP/AVP/UDP;unicast 1991 0 mode=play
wfd_uibc_capability: input_category_list=GENERIC;generic_cap_list=Mouse,SingleTouch;hidc_cap_list=none;port=none

 (sink_handle_get_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:136)
DEBUG: INCOMING: SET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Tue, 16 May 2017 09:07:04 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 3
Content-Type: text/parameters
Content-Length: 380

wfd_video_formats: 00 00 02 02 00000002 00000000 00000000 00 0000 0000 00 none none
wfd_audio_codecs: AAC 00000001 00
wfd_uibc_capability: input_category_list=GENERIC;generic_cap_list=SingleTouch;hidc_cap_list=none;port=5100
wfd_uibc_setting: enable
wfd_presentation_URL: rtsp://192.168.49.1/wfd1.0/streamid=0 none
wfd_client_rtp_ports: RTP/AVP/UDP;unicast 1991 0 mode=play

 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 3


 (sink_handle_set_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:227)
DEBUG: Got URL: rtsp://192.168.49.1/wfd1.0/streamid=0
 (sink_handle_set_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:246)
[miraclectl] # DEBUG: UIBC port: 5100
 (sink_handle_set_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:268)
DEBUG: uibc setting: enable
 (sink_handle_set_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:290)
SINK set resolution 720x480
DEBUG: INCOMING: SET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Tue, 16 May 2017 09:07:04 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 4
Content-Type: text/parameters
Content-Length: 27

wfd_trigger_method: SETUP

 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 4


 (sink_handle_set_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:227)
DEBUG: OUTGOING: SETUP rtsp://192.168.49.1/wfd1.0/streamid=0 RTSP/1.0
Transport: RTP/AVP/UDP;unicast;client_port=1991
CSeq: 2


 (sink_handle_set_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:327)
DEBUG: INCOMING: RTSP/1.0 200 OK
Date: Tue, 16 May 2017 09:07:04 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 2
Session: 888357957;timeout=60
Transport: RTP/AVP/UDP;unicast;client_port=1991;server_port=53562


 (sink_setup_fn() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:151)
DEBUG: OUTGOING: PLAY rtsp://192.168.49.1/wfd1.0/streamid=0 RTSP/1.0
Session: 888357957
CSeq: 3


 (sink_setup_fn() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:180)
DEBUG: INCOMING: RTSP/1.0 200 OK
Date: Tue, 16 May 2017 09:07:04 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 3
Session: 888357957;timeout=60
Range: npt=now-


 (sink_req_fn() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:28)
DEBUG: INCOMING: GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Tue, 16 May 2017 09:07:59 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 5
Session: 888357957


 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 5


 (sink_handle_get_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:136)
DEBUG: INCOMING: GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Tue, 16 May 2017 09:08:54 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 6
Session: 888357957


 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 6


 (sink_handle_get_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:136)
DEBUG: INCOMING: GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Tue, 16 May 2017 09:09:49 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 7
Session: 888357957


 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 7


 (sink_handle_get_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:136)
DEBUG: INCOMING: GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Tue, 16 May 2017 09:10:44 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 8
Session: 888357957


 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 8


 (sink_handle_get_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:136)
DEBUG: INCOMING: GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Tue, 16 May 2017 09:11:39 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 9
Session: 888357957


 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 9


 (sink_handle_get_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:136)
DEBUG: INCOMING: GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Tue, 16 May 2017 09:12:34 +0000
Server: stagefright/1.2 (Linux;Android 5.0.2)
CSeq: 10
Session: 888357957


 (sink_handle() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:340)
DEBUG: OUTGOING: RTSP/1.0 200 OK
CSeq: 10


 (sink_handle_get_parameter() in /home/fangliang/miraclecast-master/src/ctl/ctl-sink.c:136)
```

**test-viewer.sh**

```
testing plugins required:

test udpsrc... (passed)
test rtpjitterbuffer... (passed)
test rtpmp2tdepay... (passed)
test tsdemux... (passed)
test h264parse... (passed)
test avdec_h264... (passed)
test autovideosink... (passed)

everything installed
```

any ideas?

**Comment by albfan** [comment]
Recently changes on permissions on gstreamer broke the run from root. Meanwhile we solve it try applying this workaround to share your xsession with root https://github.com/albfan/miraclecast/issues/183#issuecomment-291012571

**Comment by mihuyo** [comment]
I tried again But it still doesn't work，Are there any other mistakes?

**Comment by albfan** [comment]
Upload a zip with all the needed logs https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support. In any of them we should see the problem

**Comment by mihuyo** [comment]
[log.zip](https://github.com/albfan/miraclecast/files/1011498/log.zip)

**Comment by mihuyo** [comment]
Hi，
I have upload the log, The `journal.log` seem to have some problems here, `XDG_RUNTIME_DIR not set in the environment` and `va_openDriver() returns -1`  Can you give me some advice
Thanks

**Comment by albfan** [comment]
- UIBC is not working.

```
5月 19 00:00:09 fangliang-Inspiron-5535 miracle-sinkctl-gst[2185]: DEBUG: player command: uibc-viewer 192.168.49.1 5100 -d 3 -a -p 1991 -r 720x480 (launch_player() in /home/fangliang/project/miraclecast-master/src/ctl/sinkctl.c:446)
5月 19 00:00:09 fangliang-Inspiron-5535 miracle-sinkctl-gst[2185]: 2185
5月 19 00:00:09 fangliang-Inspiron-5535 miracle-sinkctl-gst[2185]: INFO: server 192.168.49.1 port 5100
5月 19 00:00:09 fangliang-Inspiron-5535 miracle-sinkctl-gst[2185]: ERROR connecting: Connection refused
```

Remove `--uibc` by now.

- lib_va openDriver returns -1: 

https://askubuntu.com/questions/248732/why-does-libva-return-an-error-while-trying-to-init-intel-gm965-driver. I think your laptop do not support it. You can try a different gstreamer setup now miracle-sink support external player. To check if that would work use 

    --external-player` miracle-vlc

if you have vlc avaliable. Is a wrapper provided by miraclecast around vlc for this kind of situations. You should see scrreen mirroring on vlc

**Comment by albfan** [comment]
Any progress?

**Comment by mihuyo** [comment]
oh,I'm sorry I have some other things for some time, and I'll try again tomorrow

**Comment by mihuyo** [comment]
It should be the gm965 chipset problem. I tried to compile miraclecast on another computer. but there are other problems. when I run `sudo miracle-wifid &` 
WARNING `supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in /home/fangliang/project/miraclecast-master/src/wifi/wifid-supplicant.c:1698)`
but run `./test-hardware-capabilities.sh`
`wlan0 supports P2P`

**journal.log**
`Failed to create interface p2p-dev-wlan0: -16 (Device or resource busy)`
how to solve this problem?
[journal.log.zip](https://github.com/albfan/miraclecast/files/1047210/journal.log.zip)

**Comment by albfan** [comment]
There are wireless interfaces running.

Check with ifconfig

Brinng them down first. Miraclecast do not work multimode yet

**Comment by mihuyo** [comment]
How exactly should I do it? Run the `PS -ef | grep wpa_supplicant` but no other process

**Comment by albfan** [comment]
$ sudo ifconfig

If you see wlan0 (or anything different from lo or eth0) do:

    $sudo ifconfig wlan0 down

That stops your busy device

Try miraclecast again

**Comment by mihuyo** [comment]
run `$ sudo ifconfig`

`enxb827eb3a0758 Link encap:Ethernet  HWaddr b8:27:eb:3a:07:58  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:185 errors:0 dropped:0 overruns:0 frame:0
          TX packets:185 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:13829 (13.8 KB)  TX bytes:13829 (13.8 KB)

wlan0     Link encap:Ethernet  HWaddr b8:27:eb:6f:52:0d  
          inet addr:192.168.1.241  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::1eab:35dc:e3a9:5a90/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:259 errors:0 dropped:36 overruns:0 frame:0
          TX packets:82 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:70336 (70.3 KB)  TX bytes:12232 (12.2 KB)`

`$ sudo ifconfig wlan0 down`
`$ sudo kill -9 $(ps -ef | grep wpa_supplican[t] | awk '{print $2}')`
`$ sudo miracle-wifid &`
`WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in /home/fangliang/project/miraclecast-master/src/wifi/wifid-supplicant.c:1698)`

It doesn't seem to work. anyideas?
[journal.log.zip](https://github.com/albfan/miraclecast/files/1049572/journal.log.zip)
[wifid.log.zip](https://github.com/albfan/miraclecast/files/1049573/wifid.log.zip)

**Comment by albfan** [comment]
I added this one to FAQ

https://github.com/albfan/miraclecast/wiki/FAQ#bring-down-wifi-interfaces

**Comment by mihuyo** [comment]
network can't stop. when I run `$ sudo systemctl stop network`
`Failed to stop network.service: Unit network.service not loaded.
`

**Comment by albfan** [comment]
@mihuyo I suppose you first try don't work because of hardware.

Your second try (in other computer) has different problems. Please open a different issue for that
