### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in wifid-dbus.c:899)

### ISSUE THREAD

**Issue by bobscyes** [albfan/miraclecast#206]
When I run "miracle-wifid &" it shows error as title

**Comment by bobscyes** [comment]
sudo miracle-wifid --log-level trace

INFO: miracle-wifid - revision 1.0 May 20 2017 21:56:55
DEBUG: friendly-name from local hostname: musicalai (manager_read_name() in /home/longfei/miraclecast/src/wifi/wifid.c:370)
DEBUG: link: new link: wlxac9e17781e84 (3) (link_new() in /home/longfei/miraclecast/src/wifi/wifid-link.c:71)
DEBUG: supplicant: new supplicant for wlxac9e17781e84 (supplicant_new() in /home/longfei/miraclecast/src/wifi/wifid-supplicant.c:2103)
INFO: link: add link: wlxac9e17781e84
INFO: link: manage link wlxac9e17781e84
DEBUG: supplicant: start supplicant of wlxac9e17781e84 (supplicant_start() in /home/longfei/miraclecast/src/wifi/wifid-supplicant.c:2629)
DEBUG: supplicant: spawn supplicant of wlxac9e17781e84 (supplicant_spawn() in /home/longfei/miraclecast/src/wifi/wifid-supplicant.c:2478)
INFO: supplicant: wpa_supplicant found: /sbin/wpa_supplicant
INFO: supplicant: wpas spawned as pid:7345
DEBUG: supplicant: open supplicant of wlxac9e17781e84 (supplicant_open() in /home/longfei/miraclecast/src/wifi/wifid-supplicant.c:2269)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: p2p_device_address=ac:9e:17:78:1e:84
p2p_state=IDLE
wifi_display=1
ifname=wlxac9e17781e84
address=ac:9e:17:78:1e:84

DEBUG: supplicant: local p2p-address is: ac:9e:17:78:1e:84 (supplicant_status_fn() in /home/longfei/miraclecast/src/wifi/wifid-supplicant.c:1823)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: OK

TRACE: wpa: raw message: FAIL

TRACE: wpa: raw message: OK

DEBUG: link: link wlxac9e17781e84 started (link_supplicant_started() in /home/longfei/miraclecast/src/wifi/wifid-link.c:287)
TRACE: wpa: raw message: FAIL

**Comment by albfan** [comment]
Yes, sadly at this time you need to run as root (to access dbus system messages)

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid.c#L56

I want to isolate that using polkit, but it is not done yet

**Comment by kred-jon** [comment]
are this fixed? or any workaround maybe

**Comment by albfan** [comment]
@kred-jon it is fixed. run as sudo. You can see this problem too if you do not install dbus policy (more I do on README.md) install step for whichever buildsystem should do for you

**Comment by adriweb** [comment]
Same here, as root:

```
% sudo miracle-wifid --log-level trace

INFO: miracle-wifid - revision 1.0 Mar  7 2019 04:22:12
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:941)
DEBUG: exiting.. (main() in wifid.c:618)
```
