### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect()

### ISSUE THREAD

**Issue by Brzotto** [albfan/miraclecast#207]
I know this is a common issue, but I cannot seem to figure out what is causing this error. I am running sudo miracle-wifid &, from the tutorial documentation and this error keeps arising. Any help is appreciated.

**Comment by albfan** [comment]
It is supposed that cmake and autotools copy dbus policy

>copy the dbus policy res/org.freedesktop.miracle.conf to /etc/dbus-1/system.d/

Check if that file is in right place

Provide logs collected as indicated in https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support and post here in a zip, to allow us to figure out the problem

**Comment by Brzotto** [comment]
[Journal logs.zip](https://github.com/albfan/miraclecast/files/1023742/Journal.logs.zip)
[miracle-sink logs.zip](https://github.com/albfan/miraclecast/files/1023743/miracle-sink.logs.zip)
[Wifid log.zip](https://github.com/albfan/miraclecast/files/1023744/Wifid.log.zip)

When I run sudo make install this is the following results. So i think the dbus policy is in the right place.
[ 15%] Built target miracle-shared
[ 22%] Built target miracled
[ 37%] Built target miracle-wifid
[ 53%] Built target miracle-dhcp
[ 64%] Built target miracle-wifictl
[ 80%] Built target miracle-sinkctl
[ 86%] Built target miracle-uibcctl
[ 91%] Built target test_rtsp
[ 95%] Built target test_wpas
[100%] Built target test_valgrind
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/bin/miracled
-- Up-to-date: /usr/local/bin/miracle-wifid
-- Up-to-date: /usr/local/bin/miracle-dhcp
-- Up-to-date: /usr/local/bin/miracle-wifictl
-- Up-to-date: /usr/local/bin/miracle-sinkctl
-- Up-to-date: /usr/local/bin/miracle-uibcctl
-- Up-to-date: /usr/local/bin/miracle-gst
-- Up-to-date: /usr/local/bin/gstplayer
-- Up-to-date: /usr/local/bin/uibc-viewer
-- Up-to-date: /etc/dbus-1/system.d/org.freedesktop.miracle.conf


I also think miracle sink is working correctly.

**Comment by albfan** [comment]
Brendan-VirtualBox? See #12

Virtualbox emulates network from any real device, and it do not expose wifi capabilites

**Comment by Brzotto** [comment]
Oh sorry about that, I thought the virtual machine would help me, because your documentation is in Linux OS, how would I start working at making a Windows host PC a source for miracle cast?

**Comment by albfan** [comment]
Windows 10 works out of the box as sink. See wip/windows-fix and #139 for a work in progress

If you want it as source you need a docker machine. That is not implemented yet. See #198.

**Comment by Brzotto** [comment]
Ok, I appreciate all the help! Just to clarify, Linux machines, including android phones with miracast capabilities, can source, correct? Also regardless if I get this working, I would love to donate to your project.

**Comment by albfan** [comment]
This is an incomplete list of devices tested

https://github.com/albfan/miraclecast/wiki/Known-working-devices

You can support the project on:

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=U92QJDVX574X6)

Bounty source and patreon are coming to well define funds target:

https://www.bountysource.com/teams/miraclecast

patreon is not ready yet

**Comment by Brzotto** [comment]
Ok, I am now running a dedicated linux machine, I am still having this error though...
here are the new logs. I also made the config using cmake, make, and sudo make install once again after remove the CMakeCache.txt


[journal.log.zip](https://github.com/albfan/miraclecast/files/1026420/journal.log.zip)
[sink.log.zip](https://github.com/albfan/miraclecast/files/1026421/sink.log.zip)
[wifid.log.zip](https://github.com/albfan/miraclecast/files/1026423/wifid.log.zip)

**Comment by albfan** [comment]
Great! Hope to integrate fixes to deploy miraclecast as a service and avoid all that fuss

**Comment by Brzotto** [comment]
Hey I don't mean to pester you, but would you be able to help me with other
issues I am having. I am having the same issues as the user in #210 and
#211. Thank you.

**Comment by albfan** [comment]
Sure. np

**Comment by vemonet** [comment]
Is there any update on this issue? Still having it on Ubuntu18.04. Thanks a lot!

**Comment by albfan** [comment]
@vemonet the issue is closed

> I figured it out, just make sure that you don't have multiple instances of miracle-wifid & running.

Your problem could be different anyway
