### ISSUE TITLE
no such file or directory #include <system/sd-event.h>

### ISSUE THREAD

**Issue by eelife** [albfan/miraclecast#209]
I am trying to run miracle cast as a sink on my raspberry pi 3, but I am running into this error when trying to make the project. I understand that there is a problem with my systemd being version 215, and does not have kdbus enabled, but I have read through your documentation and im still struggling figuring out how to enable kdbus on the pi. 

When i try to fetch --all following your documentation posted here (https://github.com/albfan/systemd-ubuntu-with-dbus), I cannot reach freedesktop or debain. Do you know what the error could be here?

I am using raspbian linux distro. I appreciate any help.

**Comment by albfan** [comment]
Check this issue. https://github.com/albfan/systemd-ubuntu-with-dbus/issues/9

This guy was in the same situation as you, and managed to compile systemd with kdbus.

If you are not particularly stick to a distro see there's an image ready to use on https://github.com/albfan/miraclecast/issues/100#issuecomment-237152709

**Comment by eelife** [comment]
That already image, can run miraclecast immediately, or does it need other configurations done?

**Comment by albfan** [comment]
it runs out of the box. Has mate desktop installed, and you can upgrade miraclecast doing:

    $ yaourt miraclecast

(yaourt is a package manager for AUR packages) https://aur.archlinux.org/packages/miraclecast/

**Comment by Brzotto** [comment]
I have your image of the archarm on my pi, but I cannot seem to connect to wifi. Any advice?

**Comment by Brzotto** [comment]
When i try to run miracle-sinkctl, i recieve the following error.

cannot retrieve objects: The name org.freedesktop.miracle.wifi was not provided by any .service files.

I think the error is the fact that i do not have the kdbus enabled, how would i go about this?

**Comment by eelife** [comment]
I am having the same issues as the other user.

**Comment by albfan** [comment]
Is good to add a comment when closing an issue to understand if you give up or finally solve the problem

**Comment by eelife** [comment]
The main error (the title of the error post), can be solved by using a linux distro with a default greater version of systemd (e.g. arch linux or ubuntu linux), where the default as of right now is 230 or 229. This allows you to use the dbus correctly. As for fixing it on the pi with systemd version 215, (By the way you can check systemd version with systemctl --version) I do not quite understand how to do that.

My solution was to switch my OS for raspbian which has a default systemd version of 215, to arch linux for the arm processor on the raspberry pi, with a default systemd of 230. 

To fix the other issue, you need to kill all daemons, or instances, of miracle-wifid. The dbus -17 error means that the file already exists, thus you need to kill that file, before running another instance of miracle wifid. This can be done by running sudo kill -9 $ ( where the $ represents the process ID number that you wish to kill). You can find the process ID number by using the following command.

`ps -ef | grep miraclewifid`

If you have processes running, you should see a few columns of root, and the number next to that is the process ID. Kill those processes, then the error should go away.

As for the P2P support issue, I am still battling that at this time, hopefully I can figure it out soon.
