### ISSUE TITLE
Missing sd-event.h on Debian testing

### ISSUE THREAD

**Issue by XDex** [albfan/miraclecast#21]
Hi!
I'm trying to compile on Debian testing, and I'm getting the following error:

[  3%] Building C object src/shared/CMakeFiles/miracle-shared.dir/rtsp.c.o
/home/andrei/tmp/miraclecast/src/shared/rtsp.c:31:30: fatal error: systemd/sd-event.h: No such file or directory
 #include <systemd/sd-event.h>
                              ^
compilation terminated.

Debian Testing already has systemd and libdbus, though I can't find this specific header in any packages..
Should I follow the same instructions as for Ubuntu and replace systemd with the one compiled from here (https://github.com/albfan/systemd-ubuntu-with-dbus), or is there a less-painful workaround?

I have systemd v. 215-17 and dbus/libdbus v1.8.16-1

Thanks!

**Comment by albfan** [comment]
You are right. You need to get a systemd with kdbus enabled.

I guess instructions on https://github.com/albfan/systemd-ubuntu-with-dbus are mostly valid for debian. 

This must be your valid source https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tag/?id=debian/215-17

I didn't know another easy way to get this dependency

**Comment by rektide** [comment]
sd-event is public in v221. Debian systemd devs just got it packaged today, not pushed yet- coming soon to an experimental/unstable near you.

**Comment by XDex** [comment]
Thanks for the update!

**Comment by Susurrus** [comment]
Maybe the README should be updated to reflect this new development then?

**Comment by albfan** [comment]
If anyone can provide feedback we can change prerrequisites for debian:

http://news.softpedia.com/news/systemd-221-Adds-an-Alternative-Very-Efficient-D-Bus-Client-Library-484819.shtml

**Comment by krustymars** [comment]
The easy way that worked for me on jessie : add the backports repository to your apt-sources and you can find systemd v930 and all dependencies without having to build from sources
