### ISSUE TITLE
Failed to create a P2P device interface p2p-dev-wlan0

### ISSUE THREAD

**Issue by eelife** [albfan/miraclecast#210]
I keep getting this error, but when I run res/test-hardware-capabilities it says that wlan0 supports P2P, so I don't understand why this is failing. the error says miracle cast failed to enable P2P device interface. Any suggestions? 

In #61 you said you need to compile systemd with kdbus from PKGBUILD. can you describe how to do this further? Thanks.

**Comment by derekdai** [comment]
@eelife make sure both NetworkManager and wpa_supplication are stopped, then run miraclecast. If the problem still, post your commands and log.

**Comment by eelife** [comment]
Ok, so when I run netctl stop wlan0-nameOfNetwork... and then run ./kill-wpa.sh. Im pretty sure im offline, because when i ping 8.8.8.8, i get network unreachable.

When I run sudo miracle-wifid &, after first booting, it says just a process number

[1] 801

Then i try to run sudo miracle-sinkctl, It says:

[1]+ Stopped               sudo miracle-wifid

But after the first run, everything is different. Now when i run sudo miracle-wifid, i get the wap_supplicant or driver does not support P2P (but its a pi3, running arch, and running ./hardware-capabilities says that wlan0 supports P2P).

Then when I run sudo miracle-sinkctl, it works like the documentation says, and I type list I receive the following...

LINK INTERFACE                                       FRIENDLY NAME
     3 wlan0                                                alarmpi
LINK PEER-ID                                            FRIENDLY NAME
   
0 peers and 1 links listed.

 This makes me think, that the pi cannot create a P2P network for some reason, or the phone cannot connect. But my phone is android and says it can cast.            

Sorry for the informality of the logs, the pi is too slow to post them there. and no internet during this whole process I believe.

**Comment by derekdai** [comment]
The `[1]+ Stopped sudo miracle-wifid` issue is caused by `sudo` **asking for password** + `&`, in short ([detailed explanation](http://curiousthing.org/sigttin-sigttou-deep-dive-linux)). This way, the command stopped at `sudo`, no `miracle-wifid` was executed.

Please try to run `miracle-wifid` with command below to get more log messages
```
$ sudo miracle-wifid --use-dev --log-level trace
```

Then run `miracle-sinkctl`
```
$ sudo miracle-sinkctl --log-level trace --uibc
[ADD] Link: 3
[miraclectl] # run 3
```

**Comment by eelife** [comment]
Sorry my pi is extremely slow, but here are the logs. When I try to run --use-dev with miracle-wifid It makes my miracle-sinkctl not work properly. What i mean is that when I run --use-dev, instead of &, it tells me that wpa_supplicant device or driver does not support P2P.

Here are the logs. And thanks again. 

[sink.zip](https://github.com/albfan/miraclecast/files/1032399/sink.zip)
[wifid.zip](https://github.com/albfan/miraclecast/files/1032400/wifid.zip)

**Comment by albfan** [comment]
@eelife & just sends a command to background. When you want to "debug" or monitorize an execution is better to use several terminals. You need to use two terminals (or two tabs). One for

    $ sudo miracle-wifid --use-dev --log-level trace

and another for

    $ miracle-sinkctl --log-level trace

so you don't mix output from both commands

Even more you can use more tabs for journals or dbus-monitor

If you need to provide logs, use commands showed on https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support

**Comment by eelife** [comment]
Ok, I took your advice, here are the new logs.
[sink.zip](https://github.com/albfan/miraclecast/files/1032692/sink.zip)
[wifid.zip](https://github.com/albfan/miraclecast/files/1032693/wifid.zip)

**Comment by albfan** [comment]
Add journal.log please, as problems with hardware will be shown only there

**Comment by eelife** [comment]
So i posted the new logs, i think the error is involved with the P2P network config, although I don't know too much.

**Comment by albfan** [comment]
You're right. A reboot normally helps, but you need to find everything that is running against your network hardware and stop it. This is normally hard because nowadays this essential services are monitorized to restart automatically to bring a smooth user experience, and that is totally the opposite you want know (you need to stop what restart your normal wifi config).

**Comment by eelife** [comment]
If my network is being used by multiple users, is there a good way to approach this problem?

**Comment by albfan** [comment]
After try this myself on a raspberry pi. Only solution by now is reboot, reopen if you find a way to fix without rebooting please
