### ISSUE TITLE
ERROR: cannot retrieve objects: The name org.freedesktop.miracle.wifi was not provided by any .service files (ctl_wifi_fetch() in ctl-wifi.c:1103)

### ISSUE THREAD

**Issue by eelife** [albfan/miraclecast#212]
I can run the wpa_supplicant daemon on the pi 3 using arch linux, but when I try to run 
`sudo miracle-sinkctl`
I am getting the above error.
[journal.zip](https://github.com/albfan/miraclecast/files/1038709/journal.zip)
[sink.zip](https://github.com/albfan/miraclecast/files/1038711/sink.zip)
[wifid.zip](https://github.com/albfan/miraclecast/files/1038710/wifid.zip)

Here are the following logs. I still dont quite understand what the error even means. If someone could help me out I would greatly appreciate it. Thanks.

Don't know if this is noteworthy, but when i run the following command:
`lsmod | grep kdbus`
nothing appears. Does this mean that I do not have kdbus on my pi 3? I am using the arch linux OS provided by albfan.

**Comment by albfan** [comment]
kdbus means kernel dbus. https://en.wikipedia.org/wiki/D-Bus. So it's something provided by kernel

Your problem is same as previous issue

https://github.com/albfan/miraclecast/issues/211#issuecomment-304434091

Try to comment there for same issue
