### ISSUE TITLE
Cannot connect to sink

### ISSUE THREAD

**Issue by eelife** [albfan/miraclecast#213]
Hello I am trying to use my android phone to connect to miracasting raspberry pi 3 running arch. The pi sees the phone, and the phone sees the pi. However when I try to connect to the pi from my phone, all that results is a timeout. I have a log for reference. 
[p2p.zip](https://github.com/albfan/miraclecast/files/1042391/p2p.zip)
[wifid5_31.zip](https://github.com/albfan/miraclecast/files/1042503/wifid5_31.zip)

Sometimes I get group owner negotiation failed errors.

**Comment by albfan** [comment]
Which are your android phones and android version?

if you add --log-level trace to miracle-sinkctl you can see more info about negotiation
 
Remember to execute miracle-sinkctl from a xsession or it will not show screen mirroring

**Comment by eelife** [comment]
Ill check with another android device in a bit, but the device im currently using is android N 7.1.1,

**Comment by albfan** [comment]
When you see this kind of messages on miracle-wifid

    no ifname in AP-STA-CONNECTED

means that wpa_suppplicant sends various messages AP-STA-CONNECTED and last one do not have ifname so miraclecast stores null on that var. To avoid that use

    $ miracle-wifid --use-dev

which keeps last valid ifname

remember to use sudo if you're not root and add --log-level if you need to see more detail

**Comment by eelife** [comment]
Okay, one step closer, I am getting an HUP/ERR on socket error and:
ERROR: cannot connect to remote host (111): Connection refused (sink_connected() in ctl-sink.c398)
Here is my log of wifid. I used --use-dev which allowed the device to CONNECT but this error prevents any actual connection to occur. 
[wifid6_1.zip](https://github.com/albfan/miraclecast/files/1044978/wifid6_1.zip)
Any ideas on how to fix this error? Thanks for all the help.

**Comment by albfan** [comment]
Provide the miracle-sinkctl.log and journal.log. There's the relevant info about hup

**Comment by eelife** [comment]
Okay all the logs, in this run. My first attempt resulted in failure, then it connected and I had the HUP error again. 
[journal6_1.zip](https://github.com/albfan/miraclecast/files/1045168/journal6_1.zip)
[sink6_1.zip](https://github.com/albfan/miraclecast/files/1045169/sink6_1.zip)

**Comment by albfan** [comment]
Basically it is saying it cannot listen from source on supposed communication port 7236 (where miracast listen from video and audio configuration)

https://github.com/albfan/miraclecast/blob/e5795edd0459ea13a409c93f8e7b0ea1e263819d/src/ctl/ctl-sink.c#L561

You need to check what port android 7 is opening:

Post here output from (during a succesful connect, see ip may change, this are taken from your miracle-wifid log, look for dhcp):

    $ sudo nmap -sT -O localhost
    $ sudo nmap -sT -O 192.168.50.1
    $ sudo nmap -sT -O 192.168.50.100

even more, output from:

    $ sudo dbus-monitor --system |&tee dbus.log is interesting too (capture during a session)

is interesting too.

Try to provide everytime all the logs because different sessions can behave different so see a log from miracle-wifid has no value without its miracle-sinkctl and journal pair. You can add all them in a single zip

**Comment by eelife** [comment]
Ok I'll post all the logs, also how would I check what port my android phone is opening?

**Comment by eelife** [comment]
Okay, interesting from the nmap outputs, was that for 192.168.50.100, was that it failed during a successful connection, and gave me the error of:
[192.168.50.100 6_1.zip](https://github.com/albfan/miraclecast/files/1045392/192.168.50.100.6_1.zip)
The others did not change.

The rest of the logs are here. 
[Newlogs.zip](https://github.com/albfan/miraclecast/files/1045419/Newlogs.zip)

**Comment by eelife** [comment]
Actually I noticed from 192.168.50.100 log it says that all 1000 ports are closed....

**Comment by eelife** [comment]
Any ideas? I'm still lost on this HUP/socket error.

**Comment by albfan** [comment]
In the middle of negotiation there's an IP renew that puzzles me. Can you describe your source devices to find its miracast support or any related problem?

**Comment by eelife** [comment]
My source device is an android phone running android N 7.1.1, its actually a product that is in still in development (I work for an android developer company), so it could possibly be an issue with the software of the device.

**Comment by albfan** [comment]
See miracast can detect your phone by wifi direct but if it do not support miracast is normal that it do not open a port for rstp negotiation.

Do you have access to android sources? Can you co firm you're enabling miracast?

Googling a bit seems that there are problems with android 7 and miracast

**Comment by eelife** [comment]
Okay, if I want to use another android device, do I need to download an app, or must the device have a casting option from its settings?

**Comment by eelife** [comment]
Okay, Im now using a windows phone with continuum casting. And it connects with no errors !! 

I am in xsession, using the sudo startx command, and i initiated miracle-sinkctl with --uibc, but I do not see anything.

**Comment by eelife** [comment]
Holy shit, I finally got my hands on another android phone, and it fucking works. Thanks for all the help with this project over the course of these 2 weeks. Ill probably still be asking followup questions!

**Comment by albfan** [comment]
Congrats, Let me tweet about it! Feel free to update wiki about supported devices

Open as many issues as you want about android 7 or windows phone or whatever that would help others to understand what you can achieve with those devices

**Comment by albfan** [comment]
https://twitter.com/albfanjul/status/870921619480432640

Please close this and open specific issues when needed
