### ISSUE TITLE
so close RiPi3

### ISSUE THREAD

**Issue by dotps1** [albfan/miraclecast#215]
i wanted this to work so bad, and go so close following: https://github.com/albfan/miraclecast/wiki/raspberry-pi-3 a as soon as i get to the miracle commands it just hangs......please help!

```
[alarm@alarmpi ~]$ sudo miracle-wifid
WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in wifid-supplicant.c:1698)
```

then just hangs

**Comment by albfan** [comment]
I normally find that situation after a firts succesful connection.

See [notes](https://github.com/albfan/miraclecast/wiki/raspberry-pi-3#notes)

After a first connection, you need to reboot raspberry pi 3 as something leaves p2p-wlan-0 busy and you  cannot activate again it (is the interface that allows wifi to scan p2p connections)

I'm trying to find a solution, given that on regular distros, that interface is released every disconnection and reconnect is not a problem

you can check seeing output from journalctl

Please reboot and provide logs as [log for support](https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support) describes

**Comment by dotps1** [comment]
i aplogize in advance, but im a windows guy and and im not very linux savy.  but all the commands from gather logs just hang.  I re flashed the card, logged in via ssh, installed miracast, then rebooted, same error.  here is the output from the commands:

```
[alarm@alarmpi ~]$ sudo miracle-wifid
WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in wifid-supplicant.c:1698)
^CNOTICE: caught signal 2, exiting..
ERROR: dbus: syscall failed (-107): Transport endpoint is not connected (link_dbus_removed() in wifid-dbus.c:767)
[alarm@alarmpi ~]$ ^C
[alarm@alarmpi ~]$ sudo journalctl -f |& tee journal.log
-- Logs begin at Sat 2016-06-25 18:58:12 UTC. --
Jun 17 13:16:09 alarmpi miracle-wifid-wlan0-3[1008]: nl80211: Failed to create a P2P Device interface p2p-dev-wlan0
Jun 17 13:16:09 alarmpi miracle-wifid-wlan0-3[1008]: P2P: Failed to enable P2P Device interface
Jun 17 13:16:19 alarmpi sudo[1006]: pam_unix(sudo:session): session closed for user root
Jun 17 13:16:19 alarmpi miracle-wifid-wlan0-3[1008]: nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Jun 17 13:16:20 alarmpi miracle-wifid-wlan0-3[1008]: wlan0: CTRL-EVENT-TERMINATING
Jun 17 13:16:20 alarmpi miracle-wifid-wlan0-3[1008]: CTRL_IFACE: Detach monitor /tmp/.miracle-wpas-1007-1\x00 that cannot receive messages
Jun 17 13:16:20 alarmpi systemd-timesyncd[262]: Network configuration changed, trying to establish connection.
Jun 17 13:16:20 alarmpi systemd-timesyncd[262]: Synchronized to time server [2600:3c03::f03c:91ff:fe67:49e9]:123 (2.arch.pool.ntp.org).
Jun 17 13:16:41 alarmpi sudo[1133]:    alarm : TTY=pts/0 ; PWD=/home/alarm ; USER=root ; COMMAND=/usr/bin/journalctl -f
Jun 17 13:16:41 alarmpi sudo[1133]: pam_unix(sudo:session): session opened for user root by alarm(uid=0)


^C
[alarm@alarmpi ~]$ sudo miracle-wifid --log-level trace |& tee wifid.log
INFO: miracle-wifid - revision 1.0 Jun 17 2017 13:08:13
DEBUG: friendly-name from local hostname: alarmpi (manager_read_name() in wifid.c:370)
DEBUG: link: new link: wlan0 (3) (link_new() in wifid-link.c:71)
DEBUG: supplicant: new supplicant for wlan0 (supplicant_new() in wifid-supplicant.c:2103)
INFO: link: add link: wlan0
INFO: link: manage link wlan0
DEBUG: supplicant: start supplicant of wlan0 (supplicant_start() in wifid-supplicant.c:2629)
DEBUG: supplicant: spawn supplicant of wlan0 (supplicant_spawn() in wifid-supplicant.c:2478)
INFO: supplicant: wpa_supplicant found: /usr/bin/wpa_supplicant
INFO: supplicant: wpas spawned as pid:1262
DEBUG: supplicant: open supplicant of wlan0 (supplicant_open() in wifid-supplicant.c:2269)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: wifi_display=1
ifname=wlan0
address=b8:27:eb:b4:bf:30

WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in wifid-supplicant.c:1698)
DEBUG: link: link wlan0 started (link_supplicant_started() in wifid-link.c:287)

^C
[alarm@alarmpi ~]$ sudo miracle-sinkctl --log-level trace --log-journal-level trace |& tee sink.log
ERROR: cannot retrieve objects: The name org.freedesktop.miracle.wifi was not provided by any .service files (ctl_wifi_fetch() in ctl-wifi.c:1103)
[miraclectl] #
```

as you can see i have to hit CTRL+C to terminate every command.

thanks

**Comment by albfan** [comment]
Don't worry. for miracle-wifid 'Ctrl+C 'is the normal way to stop it

If daemon (wifid) cannot listen to p2p rest of commands (controllers like sinkctl) cannot work either.

So most interesting log is on journalctl. Launch it before miracle-wifid, so all the system operations made by miracle-wifid get logged on it. Best way to do that is using different terminals (or tabs) but you can do too sending command to background (&)

See you don't need to install miraclecast by yourself. There's a manager for AUR (arch user repository) installed so to keep uptodate with miraclecast you only need to do:

    $ yaourt -S miraclecast

and it will recompile from master if needed and install

Did you stop network manager as said in wiki instructions? See you rpi tries to keep wlan0 up everytime, so you need to stop it from doing that

**Comment by dotps1** [comment]
thanks for the info.  I know this isn't exactly what you've asked for, but i think it will help at least.

so, everytime i stop the `wifid`, i have to re compile.  Its only when restarting that, that i get the `WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in wifid-supplicant.c:1698)` error.

Next, if i do things in this order, then it seems to work everytime:
1. `$ yaourt -S miraclecast`
2. `$ sudo miracle-wifid &`
3. `$ sudo ifconfig wlan0 down`
4. `$ sudo miracle-sinkctl`
5. `[miracledctrl] # run 3`

but as i said, as soon as the dameon stops, system reboot, what ever, i have to recompile.  Here is the entire ssh output for you to follow along on how i figured this out, minus the mircalecast re installation:

```
[alarm@alarmpi ~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.134  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 2601:404:cc00:12aa:f47b:7f31:f123:38a3  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::13ea:bc9a:c8d:8d00  prefixlen 64  scopeid 0x20<link>
        inet6 2601:404:cc00:12aa:ba27:ebff:fee1:ea65  prefixlen 64  scopeid 0x0<global>
        inet6 2601:404:cc00:12aa::4a6e  prefixlen 128  scopeid 0x0<global>
        ether b8:27:eb:e1:ea:65  txqueuelen 1000  (Ethernet)
        RX packets 1700  bytes 1091790 (1.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1502  bytes 193284 (188.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 166  bytes 13402 (13.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 166  bytes 13402 (13.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[alarm@alarmpi ~]$ sudo miracle-wifid &
[1] 6362
[alarm@alarmpi ~]$ jobs
[1]   Running                 sudo miracle-wifid &
[alarm@alarmpi ~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.134  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 2601:404:cc00:12aa:f47b:7f31:f123:38a3  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::13ea:bc9a:c8d:8d00  prefixlen 64  scopeid 0x20<link>
        inet6 2601:404:cc00:12aa:ba27:ebff:fee1:ea65  prefixlen 64  scopeid 0x0<global>
        inet6 2601:404:cc00:12aa::4a6e  prefixlen 128  scopeid 0x0<global>
        ether b8:27:eb:e1:ea:65  txqueuelen 1000  (Ethernet)
        RX packets 1778  bytes 1097420 (1.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1556  bytes 200216 (195.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 166  bytes 13402 (13.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 166  bytes 13402 (13.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b8:27:eb:b4:bf:30  txqueuelen 1000  (Ethernet)
        RX packets 4  bytes 250 (250.0 B)
        RX errors 0  dropped 4  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[alarm@alarmpi ~]$ sudo ifconfig wlan0 down
[alarm@alarmpi ~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.134  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 2601:404:cc00:12aa:f47b:7f31:f123:38a3  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::13ea:bc9a:c8d:8d00  prefixlen 64  scopeid 0x20<link>
        inet6 2601:404:cc00:12aa:ba27:ebff:fee1:ea65  prefixlen 64  scopeid 0x0<global>
        inet6 2601:404:cc00:12aa::4a6e  prefixlen 128  scopeid 0x0<global>
        ether b8:27:eb:e1:ea:65  txqueuelen 1000  (Ethernet)
        RX packets 1908  bytes 1106166 (1.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1641  bytes 210854 (205.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 166  bytes 13402 (13.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 166  bytes 13402 (13.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[alarm@alarmpi ~]$ sudo miracle-sinkctl
[ADD] Link: 3
[miraclectl] # run 3
now running on link 3
[miraclectl] #
```

so, as you can see, the `wlan0` only comes up after starting the `wifid`.  You do have this info across varies wiki docs, but it took me more then a few hours to get it all working.

this is rather cumbersome to do every time, and the reinstall takes a bit of time.  is there a way to just reinstall what is already downloaded?

thanks.

**Comment by albfan** [comment]
The part about reinstall is a one shot operation. Same as when you install a package.

`pacman` is the default package manager for arch linux (arch arm in this case) But miraclecast is not an official package so it is not avaliable on pacman. AUR is a collection of packages not officially supported by arch linux where many projects maintain a bleeding edge package. `yaourt` is a manager (one of the many ones that exists) for AUR. My AUR package for miraclecast 

https://aur.archlinux.org/packages/miraclecast/ 

is sticked to git master branch so everytime I updated something on my repo you can use that command and it will checkout, configure, make, make install, package, install on your distro and manage replace of old version of miraclecast (it just ease to be up to date, a time saver)

How to know when to relaunch yaourt again? Well like every other update. You can follow me on twitter (where I regularly make announcements), or follow my github repo, or try it from time to time

In my tries, rpi just works after reboot (no need to down wlan0 first time) but after source device or sink (rpi) stops screen mirroring you need to do that (and not always works) so here you're facing the real issue about rpi. In normal distros this do not fail (you can reconnect as many times as you want). I didn't find a solution yet.

The plan is fix that and turn miracle-wifid into a systemd service, so you can manage it as bluetooth or a net connection, but first I need to triage what's the problem (is something related with wpa_supplicant. 

See #216 for specific info

**Comment by dotps1** [comment]
ok, i will continue to play around with this.  I think the systemd service will make things better.

you can close this if you'd like, I'll leave that up to you.

**Comment by albfan** [comment]
ok, stay tuned!
