### ISSUE TITLE
No space left on device.

### ISSUE THREAD

**Issue by TBocuma** [albfan/miraclecast#218]
Hi there,

I'm trying to install miraclecast on my Rpi3 but I get an error stating "dd: error writing '/dev/mmcblk/: no space left on device. Thing is, I have lots of free space. What to do?

Can you help?

Ta.

Emmanuel.

**Comment by albfan** [comment]
It takes like 6Gb. Are you sure you have that space on it?

**Comment by TBocuma** [comment]
Yep! Pretty sure. Even tried with other SD cards... Perhaps this is more of a Ubuntu question and not a Miraclecast one, per se. I apologize if very basic.

I'm running Ubuntu Mate on a Rasp 3 (tried Raspbian too). I'm trying to stream my android's screen onto the Rasp's Display. This seems like the way to do it. Am I mistaken?

**Comment by albfan** [comment]
Did you follow instructions on https://github.com/albfan/miraclecast/wiki/raspberry-pi-3

See your sd card path depends on where you plug it (usb, sd card slot)

recheck it with:

    $ df -h

Post output here if you want to receive feedback

**Comment by TBocuma** [comment]
Yeah, I'm a bit of a linux NOOB, thanks for your help. I switched my Ubuntu system to a 64GB SD card, downloaded the archarm.230716.gz file to a windows desktop (as I had no good connection on my rasp at that moment) and copied it over to the rasp's dekstop on a usb drive. 

I ran df -h and this is the output:

dagaa@dagaa:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        57G  6.1G   51G  11% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           463M  196K  463M   1% /dev/shm
tmpfs           463M   13M  451M   3% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           463M     0  463M   0% /sys/fs/cgroup
/dev/mmcblk0p1   63M   21M   43M  34% /boot
tmpfs            93M   28K   93M   1% /run/user/1000

I see there is not enough space on /dev/mmcblk0p1 as you indeed mentioned. Can I extract the .gz onto another directory? /dev/root/ for example?

thanks again for your help.

**Comment by albfan** [comment]
It says you have a sd card with 63M (Megabytes) you need 6Gb(Gigabytes) here.

I think /dev/mmcblk extracts to all sd card, without worrying about partitions, can you upload a photo of sd card?

**Comment by TBocuma** [comment]
![sdcard](https://user-images.githubusercontent.com/26743285/27711953-7d3fcac0-5cea-11e7-92e4-59108ce52bcd.jpg)

Do you speak Spanish?

**Comment by albfan** [comment]
Yes, spanish is my native language, but here is better to talk in english so issues became useful for maximum audience.

Seems you need to format your sd card

https://raspberrypi.stackexchange.com/questions/9656/i-have-a-16-gb-sd-card-that-is-now-only-55-mb-how-do-i-get-15-945-gb-back

On linux you can use fdisk or parted. on windows there's a included format tool

**Comment by TBocuma** [comment]
Yep! Fair enough, english it is. 

I'm gonna study and check my SD partition. I'll let you know how it goes!

:D

**Comment by hardiksingh-rathore** [comment]
Hi TBocuma,
 Is that image worked ?

**Comment by albfan** [comment]
@TBocuma reopen if there's any further problem. Unpack an image into an SD card should just work

**Comment by albfan** [comment]
I was revisiting this. Reading similar questions, seems the problem is the dear path. Right path for SD card should be /dev/mmcblk0, so doing it to /dev/mmcblk is just creating that file in your disk were you have only 459Mb avaliable (so the error message).

You can check correct name with `fdisk -l`
