### ISSUE TITLE
streaming video without transcoding

### ISSUE THREAD

**Issue by lJoublanc** [albfan/miraclecast#219]
I understand from the **miracast** wiki that the portocol uses h.264 to transcode video.
And glancing at **miraclecast** readme it appears you use gstreamer to do the transcoding.
I'd like to know whether, when acting as a source, it's possible to stream pre-existing content (think a video file h.264 and AAC, like bluray), rather than transcoding your existing display? Or alternatively piping the output of a video encoder (e.g. mplayer) into miracast?
This would maintain the best visual fidelity of video content, instead of decode and then encode. Also save some cpu/memory resources. Is this possible? Sorry if the answer is obvious.

**Comment by albfan** [comment]
it is perfectly possible. miracast defines a protocol for two devices to communicate through wifi direct and share information about the streaming they will interchange.

on https://github.com/albfan/miraclecast/blob/wip/source-impl/res/gstencoder.vala#L174 you have an example of gst config that streams your screen, but you can perfectly replace imagesrc with a video (filesrc location=video.avi)

https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-ximagesrc.html

https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-plugins/html/gstreamer-plugins-filesrc.html

Any param to config such behaviour is wellcomed, so feel free to hack on it and ask if you get blocked

**Comment by derekdai** [comment]
This is possible that you can stream the existing content from source to sink, but with some limitations.

Since a miracast sink is not a generic decoder (usually, with constrained resources), in miracast spec, it only accept small set of h.264 profiles and levels. If you ignore the exchanged capability information, you break the protocol, the sink may or may not play the content you stream to.

**Comment by albfan** [comment]
In the end you're pairing two devices to stream content. as @derekdai said, If you stick to miracast spec there's a constraint you should respect.
