### ISSUE TITLE
Facing trouble in starting the application

### ISSUE THREAD

**Issue by anu1097** [albfan/miraclecast#223]
>Remember to save your config to use with `res/normal-wifi.sh` 

How to do this ? Every time I enter the command number 1, I can't reconnect to my Internet wifi router again because Network manager is crashed. I don't how to effectively use step 1.

**Comment by albfan** [comment]
Nowdays you can stop and start network with

    $ systemctl stop Network manager
    $ systemctl start Network manager

That old command is for the init.d days or custom systems

**Comment by anu1097** [comment]
I found these commands and ran them still I wasn't able to connect back to internet. My network manager runs but it doesn't allow me to connect me with my home-connection. Everytime I run step number one, I loose my connection because of the kill command and I unable to reconnect even with the CLI commands. I am still lost on DOC to use miracle-cast to connect with my FireTv device. I couldn't get to the option to type p2p-scan command on terminal.

**Comment by albfan** [comment]
You need to stop it when you run miraclecast (so it do not interfere with miraclecast) and start to use your WiFi normally again

See in wiki faq steps to upload logs to get support

**Comment by anu1097** [comment]
Ok thanks will upload the logs.

**Comment by albfan** [comment]
Keep pushing. You're close to get it working
