### ISSUE TITLE
unable to run in ubuntu 17.04

### ISSUE THREAD

**Issue by amit-handa** [albfan/miraclecast#224]
* compiled, installed successfully
on running, gives following error:
```
/ sudo miracle-wifid --log-level trace --use-dev
sudo: unable to resolve host amit-Latitude-3450: Resource temporarily unavailable
INFO: miracle-wifid - revision 1.0 Jul 31 2017 10:52:46
**ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:899)**
DEBUG: exiting.. (main() in wifid.c:591)
```
```
sudo dbus-monitor --system
error time=1501480556.297103 sender=org.freedesktop.DBus -> destination=:1.20802 **error_name=org.freedesktop.DBus.Error.AccessDenied reply_serial=2
   string "Connection ":1.20802" is not allowed to own the service "org.freedesktop.miracle.wifi" due to security policies in the configuration file"**
```

**Comment by albfan** [comment]
Can you check this file https://github.com/albfan/miraclecast/blob/master/res/org.freedesktop.miracle.conf is installed correctly on /etc/dbus-1/system.d/?

**Comment by amit-handa** [comment]
Thanks @albfan 
the file was missing. added it and error no more occurrs.
I followed the remaining steps to start miracasting.
```
sudo miracle-sinkctl
# run 3
```
I launched casting from android phone. phone is able to see the laptop as a sink.
Once I click connect, it starts to connect but doesnt complete. I am attaching the logs for your kind reference. would appreciate your help.


[cast.zip](https://github.com/albfan/miraclecast/files/1187149/cast.zip)

**Comment by amit-handa** [comment]
never mind. I am able to complete connection now.
was following issue-148. --use-dev does that job.
Thanks tons.

**Comment by amit-handa** [comment]
Hi, I have added following config to miraclecastrc
```
[wifid]
log-level=trace

[sinkctl]
log-level=trace
autocmd=run 3
external-player=gstplayer
rstp-port=7236

[wifictl]
log-level=trace
```
I am running kubuntu. and gstplayer is not launching on kubuntu. How could I launch view the casting on kubuntu.
Thanks,

**Comment by albfan** [comment]
Well done. It's supposed that cmake, autotools or meson installs the policy file. Can you post here what build tool are you using and the output for it?

About `--use-dev` it causes no harm to activate by default so I will make it default to avoid this problems for future users

About gstplayer, these are your options:
- a) You can start it manually (it is a python app with gtk bindings) to see if it works at all. There's problems with recent versions of gtk avoid running gtk from sudo (See #183) Maybe kde lack some deps. If:

        sudo gstplayer -p 7236

    works that is not the problem

- b) Choose another player. For example to use vlc you just need to use this wrapper. Installed by default https://github.com/albfan/miraclecast/blob/2aeec41290d5009261c4bddbaf7bf380ab9f16c0/res/miracle-vlc

    So using:
        ...
        [sinkctl]
        external-player=miracle-vlc
        ...

    should work

If it only works for you with another stream player, I'm still curious about what is the problem on kde (to benefit others on same distro) Please check both if you can (In that case we should open a different issue to ease to others to find the issue, ok?)

**Comment by amit-handa** [comment]
I used autototols in kubuntu to compile, install it.
miracle-vlc is working. I am able to use laptop as a sink when casting via my phone.
[screenshot attached]

few initial impressions:
- it seems slow.
- the colors are not hi def. guess its due to the resolution being set (7xx * 4xx) 

I ll check with gstplayer and report.

![wifidirect](https://user-images.githubusercontent.com/7656227/28775479-dde1bd50-760f-11e7-8371-5b54250edc32.png)

Thanks again for your help. I am excited :)

**Comment by amit-handa** [comment]
upon restarting the miracle-wifid & sinkctl. I couldnt connect for casting from phone. Its stuck in connecting stage. I get following logs.
```
TRACE: wpa: raw message: <3>P2P-GO-NEG-SUCCESS role=GO freq=2412 ht40=0 peer_dev=c2:ee:fb:30:24:10 peer_iface=c2:ee:fb:30:a4:10 wps_method=PBC
TRACE: wpa: raw message: <3>P2P-GO-NEG-SUCCESS role=GO freq=2412 ht40=0 peer_dev=c2:ee:fb:30:24:10 peer_iface=c2:ee:fb:30:a4:10 wps_method=PBC
TRACE: wpa: raw message: IFNAME=p2p-wlan0-2 <5>Failed to initialize driver interface
TRACE: wpa: raw message: <3>P2P-GROUP-FORMATION-FAILURE 
```

**Comment by amit-handa** [comment]
never mind, sir. I forgot the --use-dev option :)

**Comment by albfan** [comment]
Nice! Let's tweet about it

https://twitter.com/albfanjul/status/892125582246522881

you can collect relevant info following steps on https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support. Surely `journalctl` will show where's the problem

**Comment by amit-handa** [comment]
Hi, I am now trying to do the same on raspberry pi 3. I have followed the instructions on this project's wiki page for raspberry pi.
* downloaded/installed the archarm image
* configure wlan0 to connect to home router
* update miraclecast via yaourt

I am now starting miracle-wifid. I am facing an issue that wlan0 interface doesnt support p2p.
```
$  sudo miracle-wifid --use-dev --log-level trace
INFO: miracle-wifid - revision 1.0 Aug  2 2017 04:42:28
DEBUG: friendly-name from local hostname: alarmpi (manager_read_name() in wifid.c:370)
DEBUG: link: new link: wlan0 (3) (link_new() in wifid-link.c:71)
DEBUG: supplicant: new supplicant for wlan0 (supplicant_new() in wifid-supplicant.c:2103)
INFO: link: add link: wlan0
INFO: link: manage link wlan0
DEBUG: supplicant: start supplicant of wlan0 (supplicant_start() in wifid-supplicant.c:2629)
DEBUG: supplicant: spawn supplicant of wlan0 (supplicant_spawn() in wifid-supplicant.c:2478)
INFO: supplicant: wpa_supplicant found: /usr/bin/wpa_supplicant
INFO: supplicant: wpas spawned as pid:5839
DEBUG: supplicant: open supplicant of wlan0 (supplicant_open() in wifid-supplicant.c:2269)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: wifi_display=1
ifname=wlan0
address=b8:27:eb:2b:b1:df

**WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in wifid-supplicant.c:1698)**
DEBUG: link: link wlan0 started (link_supplicant_started() in wifid-link.c:287)
```
please help

**Comment by amit-handa** [comment]
- followed your wiki link for installing archarm on raspberry pi
- configured lan,wifi for connecting to internet and updating miraclecast via yaourt
- stopped networkd.service, network.target (via systemctl), killed wpa*
- started miracle-wifid,miracle-sinkctl 
- casted phone to rpi3 :) 

few observations:
- tried to launch firefox, it was seg faulting

**Comment by albfan** [comment]
@amit-handa Great, can you provide that as a different issue?. Backtrace or headdump will be great

I will delete as is non related with this issue. Btw Is this issue solved? Then please close it.
