### ISSUE TITLE
reliability, resolution, latency of miraclecast

### ISSUE THREAD

**Issue by amit-handa** [albfan/miraclecast#225]
frequently, connecting process doesnt complete.
```
TRACE: wpa: raw message: <3>P2P-INVITATION-RECEIVED sa=c2:ee:fb:30:24:10 go_dev_addr=16:bb:6e:d6:de:27 bssid=16:bb:6e:d6:de:27 unknown-network
TRACE: wpa: raw message: <3>P2P-INVITATION-RECEIVED sa=c2:ee:fb:30:24:10 go_dev_addr=16:bb:6e:d6:de:27 bssid=16:bb:6e:d6:de:27 unknown-network
DEBUG: supplicant: unhandled wpas-event: <3>P2P-INVITATION-RECEIVED sa=c2:ee:fb:30:24:10 go_dev_addr=16:bb:6e:d6:de:27 bssid=16:bb:6e:d6:de:27 unknown-network (supplicant_event() in wifid-supplicant.c:1499)
```

2. sinkctl sets low resolution for the stream. need to increase it. how do i do it ?
3. the speed of casting is slow, several frames are being skipped. how could I rectify it /
Thanks for your help,

**Comment by albfan** [comment]
About resolution you have the `--res` parameter. it depends a lot on source, and there's no option to setup on the fly. The idea is to read the supported formats in RSTP communication on sink (you need to read the miracast specs for that) and choose one of the supported ones.

About casting, it depends on source. For real interaction is bad to use buffering, but for video stream, you can tweak the buffering on player (gstplayer or external player you use)

**Comment by albfan** [comment]
Let me know if any of those tips work for you

**Comment by amit-handa** [comment]
couldnt progress much on it. unfortunately, I spent much time but there was a lot to do to achieve same level of performance which could be met easily by picking off-the-shelf sticks such as amazon fire stick.
thanks for your help.
