### ISSUE TITLE
windows 10 version 1703 stop to work with WIP for windows

### ISSUE THREAD

**Issue by trietend** [albfan/miraclecast#226]
Please find the logs from wip/windows-fix attached as discussed on gitter.
The streaming works nice from Windows 10 :)
There was no black screen at the start!
I had to initiate conection two times from windows.
The termination was initiate from the Windows 10 device
Thanks for your great work.

[logs.zip](https://github.com/albfan/miraclecast/files/1211715/logs.zip)

**Comment by trietend** [comment]
The resolution was first set to 1280x720 and then to 1600x900 (the max of my screen)

i understod that you said it would be necessarry to change the wff_display_edid for the right display resolution. i don't think that is necessarry. On a other device it changed to 1920x1080 (the max of the used screen)

**Comment by trietend** [comment]
This fix doesn't work for me anymore. Maybe the reason is a windows update (gui and behaviour of removing devices changed). Connection could be established, but gstreamer shows no window a transparent window.
Sometimes it looks like the stream starts after minutes, but the first displayed picture stays.

The following warnings occur. 
`Sep 25 03:22:05 ubuntu miracle-sinkctl-gst[2628]: 0:00:01.066775598  2628 0x5571fdbd0d40 WARN         rtpjitterbuffer rtpjitterbuffer.c:570:calculate_skew: delta - skew: 0:06:43.999872196 too big, reset skew`

`Sep 25 03:22:05 ubuntu miracle-sinkctl-gst[2628]: 0:00:01.066872809  2628 0x5571fdbd0ed0 WARN               h264parse gsth264parse.c:1225:gst_h264_parse_handle_frame:<h264parse0> broken/invalid nal Type: 1 Slice, Size: 7148 will be dropped`
[logs.zip](https://github.com/albfan/miraclecast/files/1329183/logs.zip)

**Comment by albfan** [comment]
Maybe you're now in same version that I test with.

https://www.howtogeek.com/236195/how-to-find-out-which-build-and-version-of-windows-10-you-have/

Mine is (windows 10 64bits):
 - version 1607
 - OS Build 14393.1593

**Comment by trietend** [comment]
My Windows 10 Home (64 Bit) is
- Version 1703
- Build 15063.608
You can now remove devices faster from "bluetooth and other devices" and you have an own miracast window if you hit the + in "Bluetooth and other devices". Thats what changed from user view.

**Comment by albfan** [comment]
Hmm. Seems microsoft added and option to share screen through local network, not only through wifi-direct

https://msdn.microsoft.com/library/mt796768.aspx

Time to read and update old issues related to that

**Comment by albfan** [comment]
This is available on master.

Documented on:

https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#extend-request-protocol
