### ISSUE TITLE
WARNING: supplicant: P2P_FIND failed

### ISSUE THREAD

**Issue by reaganch** [albfan/miraclecast#228]
Firstly, thanks so much for your efforts putting this together. I recently got an Epson Home Cinema 2045 projector and was exploring ways to cast the screen of my laptop running Linux Mint 18.2 to the projector when I found your project.

I built miraclecast but ran into the warning "supplicant: P2P_FIND failed (supplicant_p2p_find_fn() in /usr/local/miraclecast/src/wifi/wifid-supplicant.c:1913)" when I tried to connect to the projector. The list of commands I executed are as follows. Any help figuring out what I may be doing wrong here would be much appreciated.

$ sudo res/kill-wpa.sh
$ sudo miracle-wifid &
$ sudo miracle-wifictl --log-level trace
[ADD] Link: 3
[miraclectl] # list
  LINK INTERFACE                FRIENDLY-NAME                 
     3 wlp3s0                   laptop                 

  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 

 0 peers and 1 links listed.
[miraclectl] # select 3
link 3 selected
[miraclectl] # p2p-scan
[miraclectl] # **WARNING: supplicant: P2P_FIND failed (supplicant_p2p_find_fn() in /usr/local/miraclecast/src/wifi/wifid-supplicant.c:1913)**

**Comment by trietend** [comment]
Have you testet your hardware supports p2p with res/test-hardware-capabilities.sh?

**Comment by albfan** [comment]
@reaganc, using miraclecast as source is still a WIP. See https://github.com/albfan/miraclecast/wiki/Internals#source-implementation for more info

Any feedback is welcomed. Ask here if you get blocked

**Comment by reaganch** [comment]
@trietend - Just did. Ran res/test-hardware-capabilities.sh to get:
wlp3s0 supports P2P

@albfan - Thanks for the note. Will check back later to see if I can use miraclecast to solve my problem.

**Comment by dimag0g** [comment]
I ran into the same error using Raspberry Pi 4 running Raspbian Buster. No other error messages appeared until the `p2p-scan` step, and `./test-hardware-capabilities.sh` reports

> wlan0 supports P2P
