### ISSUE TITLE
HUP wpas crash

### ISSUE THREAD

**Issue by trietend** [albfan/miraclecast#230]
For a while wpas crashes after some time. After a trys it restarts successfully 
[logs.zip](https://github.com/albfan/miraclecast/files/1281213/logs.zip)

```
ERROR: supplicant: HUP on supplicant socket of wlan0 (supplicant_global_fn() in /opt/miraclecast/src/wifi/wifid-supplicant.c:2161)
ERROR: supplicant: wpas (pid:5365) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in /opt/miraclecast/src/wifi/wifid-supplicant.c:2331)
ERROR: supplicant: HUP on supplicant dev-socket of wlan0 (supplicant_dev_fn() in /opt/miraclecast/src/wifi/wifid-supplicant.c:2142)
ERROR: supplicant: wpas (pid:0) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in /opt/miraclecast/src/wifi/wifid-supplicant.c:2331)
ERROR: supplicant: wpas (pid:5369) failed again.. entering grace period, waiting 30s before relaunching (supplicant_failed() in /opt/miraclecast/src/wifi/wifid-supplicant.c:2335)
```

**Comment by albfan** [comment]
Attending to dbus messages about network would be the right way to do it, but know there's only a simple incresing timeout to try again

https://github.com/albfan/miraclecast/blob/a6f672311edaddb18d5c294d9328b77df77b15db/src/wifi/wifid-supplicant.c#L2555

Not much we can do with this implementation

I guess this can be related with the #75 where the solution is too to migrate to dbus
