### ISSUE TITLE
I've got error while installing from AUR

### ISSUE THREAD

**Issue by BondarenkoArtur** [albfan/miraclecast#234]
`./autogen.sh: /bin/sh^M: bad interpreter: No such file or directory`

I changed crlf to lf with vim `:set ff=unix` and `:wq`

After that I've got error from autogen.sh
```
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: linking file 'build-aux/ltmain.sh'
.ibtoolize:   error: AC_CONFIG_MACRO_DIRS([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4
autoreconf: libtoolize failed with exit status: 1
```

Then I changed file `build-aux/ltmain.sh` to unix by same way

But that doesn't help me. 
I was not able to build miraclecast

**Comment by albfan** [comment]
See now package is called miraclecast-git

I just test it and everything works correctly

    $ makepkg -si

Are you using linux? What is your distro and version

**Comment by albfan** [comment]
@BondarenkoArtur If you try again, reopen. I suppose you're using some custom system
