### ISSUE TITLE
Wrong instructions for autools build system

### ISSUE THREAD

**Issue by thisisnottaken** [albfan/miraclecast#235]
I want to mirror mobile screen on raspberry pi connected hdmi monitor.

I am using raspberry-pi b+ with tenda wifi adapter.

I am using raspbian stretch 9.1.
 
I have installed miraclecast from https://github.com/albfan/miraclecast/wiki/Building

I have a redmi 4 mobile that supports wireless display.

I can connect raspberry and mobile on same wireless network hosted by a netgear router.

I guess for my requirement I should use miraclecast as sink.

So, I read documentation of https://github.com/albfan/miraclecast.

I got following error

    $ ps -9 374

> I got 374 process ID from second field of 'ps -ef |  grep wpa'

    $ sudo miracle-wifid &
    [1] 29307
    pi@raspberrypi:~/Downloads/miracle_master/miraclecast-master $ ERROR:
    dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13
    (manager_dbus_connect() in wifid-dbus.c:899)
    [1]+  Exit 13                 sudo miracle-wifid

    systemctl --version
    systemd 232
    +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP
    +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS
    +KMOD +IDN

Please note that wireless network to which my mobile and raspberry pi are connected does not have internet access. 

    root@raspberrypi:~# miracle-wifid --log-level trace
    INFO: miracle-wifid - revision 1.0 Oct 19 2017 02:54:02
    ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13
    (manager_dbus_connect() in wifid-dbus.c:899)
    DEBUG: exiting.. (main() in wifid.c:591)

Can you suggest a way to resolve this?

If more details are required, please let me know.

**Comment by albfan** [comment]
> Please note the edits on your issue. The easy to read, the easy to solve

if you install miraclecast you should have a dbus policy `org.freedesktop.miracle.conf` in `/etc/dbus-1/system.d/` without that you get the `-13` error (look for older issues related with that) I you don't have that, let me know the steps you take to install miraclecast

See kill wpa_supplicant could be not enough. Is better to switch off networkmanager

    sudo systemctl stop NetworkManager

YMMV, so search for switch of your network manager on wiki

I'm working on run miraclecast with existing network manager, but still it is not avaliable.

I didn't know that raspbian is on 232 of systemd know. Have to give it a try!

**Comment by thisisnottaken** [comment]
Sorry , I will keep formatting in mind next time.

This is what I did to build miraclecast after extracting miraclecast-master.zip (obtained by clicking green clone or download button on https://github.com/albfan/miraclecast in web browser)
  $ ./autogen.sh
  $ mkdir build
  $ ./configure
  $ make
  $ sudo make install

I will post contents of /etc/dbus-1/system.d/ as soon as possible.
Also instead of killing wpa... , I wil try 'sudo systemctl stop NetworkManager' and report back.
By the way , i got latest debian distro 2017-09-07-raspbian-stretch from https://www.raspberrypi.org/downloads/raspbian/ .

thanks.

**Comment by albfan** [comment]
Then it is supposed that that file is installed

https://github.com/albfan/miraclecast/blob/master/res/CMakeLists.txt#L10

Please attach logs as decribed in https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support to take a look at what could be happening.

Maybe that path is not correct for dbus policy on raspbian

**Comment by thisisnottaken** [comment]
if you can suggest me a distro that worked for you . I can try that one too.

**Comment by albfan** [comment]
I have no access to raspberry pi 1.

Here are instructions for raspberry pi 2/3:

https://github.com/albfan/miraclecast/wiki/FAQ#raspberry-pi-instructions
https://github.com/albfan/miraclecast/wiki/raspberry-pi-3

Don't know if you can translate that somehow to rpi1

**Comment by thisisnottaken** [comment]
there is a 2.5GB which i can directly write to a memory card and put that card in rpi3 . i will need time to download 2.5GB .

meanwhile , i got an rpi3 from my friend and inserted the memory card from my rpi1 in it . ran 'sudo make uninstall' . then did

$ ./autogen.sh
$ mkdir build
$ ./configure
$ make
$ sudo make install

ran into same problem .
i will post the logs soon .
'sudo systemctl stop NetworkManager' was not suitable for raspbian .
So I tried 'service networking stop' .
one thing i noticed is that there is no file named *miracle* in /etc/dbus-1/system.d folder .

**Comment by albfan** [comment]
My fault. I read quickly your comments and didn't see the problem

`autogen.sh` already invokes `configure` and adds some options needed to install dbus policy file

https://github.com/albfan/miraclecast/blob/master/autogen.sh#L17

You can read about what is the autogen.sh script [here](http://inti.sourceforge.net/tutorial/libinti/autotoolsproject.html#AP07)

so the problem here is the wiki instructions for autogen.sh was wrong (I already fixed)

https://github.com/albfan/miraclecast/wiki/Building#autotools

Let me know if that works for you.

Thanks for reaching out I bet many people will benefit from your catch!

**Comment by thisisnottaken** [comment]
that helped in compilation on rpi3 (of my friend).
so far , i have been able to see raspberrypi in list of wireless displays on my mobile .

**Comment by albfan** [comment]
I suggest to close this issue and open another one with next problems, this seems to be solved

**Comment by thisisnottaken** [comment]
Now , the issue is my mobile gets stuck at connecting.

pi@raspberrypi:~ $ sudo kill -9 421
pi@raspberrypi:~ $ sudo miracle-wifid &
[1] 823
pi@raspberrypi:~ $ sudo miracle-sinkctl 
[ADD] Link: 3
[miraclectl] # run 3
now running on link 3
[ADD] Peer: fe:f1:36:b5:e4:37@3
[ADD] Peer: f6:f5:db:91:31:2f@3
[PROV] Peer: f6:f5:db:91:31:2f@3 Type: pbc PIN: 
[GO NEG] Peer: f6:f5:db:91:31:2f@3 Type: pbc PIN: 
[FAIL] Peer: f6:f5:db:91:31:2f@3 Reason: group owner negotiation failed
[PROV] Peer: f6:f5:db:91:31:2f@3 Type: pbc PIN: 
[GO NEG] Peer: f6:f5:db:91:31:2f@3 Type: pbc PIN: 
[FAIL] Peer: f6:f5:db:91:31:2f@3 Reason: group owner negotiation failed
no longer waiting for peer Android_6df1 (f6:f5:db:91:31:2f@3)
[REMOVE] Peer: f6:f5:db:91:31:2f@3

Should I post journalctl etc logs too OR is there some basic setting I am missing ?
I am sure f6:f5:db:91:31:2f is my mobile MAC.
Thanks.

**Comment by thisisnottaken** [comment]
Sorry , I will open this as another issue.
Thanks.
