### ISSUE TITLE
problem in connecting to wireless display hosted by rpi3

### ISSUE THREAD

**Issue by thisisnottaken** [albfan/miraclecast#236]
Here are details:
 
```
pi@raspberrypi:~ $ sudo miracle-wifid &
[1] 823
pi@raspberrypi:~ $ sudo miracle-sinkctl
[ADD] Link: 3
[miraclectl] # run 3
now running on link 3
[ADD] Peer: fe:f1:36:b5:e4:37@3
[ADD] Peer: f6:f5:db:91:31:2f@3
[PROV] Peer: f6:f5:db:91:31:2f@3 Type: pbc PIN:
[GO NEG] Peer: f6:f5:db:91:31:2f@3 Type: pbc PIN:
[FAIL] Peer: f6:f5:db:91:31:2f@3 Reason: group owner negotiation failed
[PROV] Peer: f6:f5:db:91:31:2f@3 Type: pbc PIN:
[GO NEG] Peer: f6:f5:db:91:31:2f@3 Type: pbc PIN:
[FAIL] Peer: f6:f5:db:91:31:2f@3 Reason: group owner negotiation failed
no longer waiting for peer Android_6df1 (f6:f5:db:91:31:2f@3)
[REMOVE] Peer: f6:f5:db:91:31:2f@3
```

Should I post journalctl etc logs too OR is there some basic setting I am missing ?
I am sure f6:f5:db:91:31:2f is my mobile MAC.
Thanks.

**Comment by albfan** [comment]
Yes. Read https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support for detailed instructions about collect relevant logs. Is based on activate `--log-level trace` on wifid, sinkctl, journalctl. 

That way you can see the device handshaking to create a peer to peer network (wifi direct on wifid) and rstp negotiation between devices to start streaming (on sinkctl). From journalctl you can see how your system manage its interfaces

**Comment by thisisnottaken** [comment]
[zippedlogs.zip](https://github.com/albfan/miraclecast/files/1437560/zippedlogs.zip)

Sorry for the delay , my friend took away his rpi3 on which I did all of the above .

Thanks.

**Comment by albfan** [comment]
I will review as soon as possible

**Comment by albfan** [comment]
Everything seems ok till P2P-GROUP-FORMATION-FAILURE. I just can say try again several times, it should work.

The only part unknown here is the Xioami phone, with a rooted phone you can see info if your phone and see what's happening.

Reopen if you try again or get any progress
