### ISSUE TITLE
Miracle-wifid tells that wpa_supplicant or my driver doesn't support p2p with the ready image

### ISSUE THREAD

**Issue by MrNHQ** [albfan/miraclecast#237]
I am using a rasberry pi 3 with the ready image from
https://github.com/albfan/miraclecast/wiki/raspberry-pi-3

I wrote the image to my sd card. it boots, then I try the two command
`$ sudo miracle-wifid
$ sudo miracle-sinkctl`

the first give the error
wpa_supplicant or my driver doesn't support p2p 

the second [ADD] Link: 3

Note the command
`$ yaourt -S miraclecast`
gives "target not found: miraclecast" 
https://aur.archlinux.org/packages/miraclecast/ returns error 404

I am pretty new and i don't know if there is some implicit steps i missed (connect to wifi? adapt config.txt?)

**Comment by albfan** [comment]
wiki fixed. I was told to follow the convention to add -git suffix for a package tied to master of a repo, so it is miraclecast-git

**Comment by albfan** [comment]
About first error

    wpa_supplicant or my driver doesn't support p2p

I think is related with the need to stop existing network services (as they are configured without Wifi Direct) miraclecast reuses the existing wpa_supplicant if any. See #75 for more information

Let me know if all this works for you

**Comment by albfan** [comment]
I have updated wiki with steps to stop existing network service

**Comment by MrNHQ** [comment]
Thank YOU! Now I can detect it from my phone using mirrorshare. Last question I hope, how do I accept pairing? When I try to connect with my phone I see, 
Peer: Mac address type: pbc Pin. On the terminal. 
Should I do something at that moment?
Then I have a timeout

**Comment by albfan** [comment]
Is supposed that it connects through PBC (miraclecast accepts any incomming connection. If not you need to run miracle-wifid and miracle-sinkctl with --log-level trace to see the pin you need to enter and complete the handshaking

Check 
https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support

to upload here logs if you get blocked

**Comment by albfan** [comment]
I suppose you get it to work. Reopen if not
