### ISSUE TITLE
negotiation failure error not verbose enough

### ISSUE THREAD

**Issue by Silur** [albfan/miraclecast#238]
Upon connecting to my device I get `[FAIL] Peer: xx:xx:xx:xx:xx:xx@5 Reason: group owner negotiation failed`. trace log level shows nothing useful either just the same message, and the corresponding "error handler" https://github.com/albfan/miraclecast/blob/a6f672311edaddb18d5c294d9328b77df77b15db/src/wifi/wifid-supplicant.c#L1295 is too generic, no way to get what the actual issue was with the handshake. Introducing some error codes for this function and more verbose messages would be wise.

**Comment by albfan** [comment]
Did you try `--log-level trace` You can see full handshage negotiation

For miraclecast side, you can take a look at journalctl.

See https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support for all the relevant info you can collect to see what's happen. Feel free to upload here to get support

**Comment by Silur** [comment]
Of course I tried trace loglevel, that's why I'm saying there's nothing about the negotiation there, only a -1 error and this message.

**Comment by albfan** [comment]
Then I only see three options:

- Upload logs to get support and triage the problem as I already mentioned.
- suggest a patch to fix it. A WIP is ok
- close this issue as this is only ranting

> I'm ok with rants but your message leave us in the same position about the issue. See I don't have your device to reproduce the problem

**Comment by hardiksingh-rathore** [comment]
Silur,
 Try WPS keypad method from your source side.
I think pbc method getting failed here as I was facing the same issue.

Hi albfan,
Request you to guide  how to do setup for wps pbc method?

**Comment by albfan** [comment]
At this moment, miraclecast uses its own configuration to support Wifi-Direct

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L2602

See the comment to accept other types of handshaking

Be aware that the config from other device is not controlled be miraclecast

A PR with custom configuration is welcome

https://github.com/albfan/miraclecast/wiki/Configuration

Something like
```
[supplicant]
wps=pin
```

would work

You can suggest a `--wps-method` too if you want

**Comment by hardiksingh-rathore** [comment]
Hi Albfan,

As given in [wpa.conf](https://github.com/albfan/miraclecast/blob/master/res/wpa.conf) file, 
do we have  "miraclectl" command ? (./miraclectl add-link wifi:wlan0)

**Comment by albfan** [comment]
No 

https://github.com/albfan/miraclecast/blob/master/src/miracled.c#L39

miraclectl do not exists. miracled is a barebone command not implemented. Was left that way from former maintainer

**Comment by albfan** [comment]
negotiation is done by wpa_supplicant, any patch about negotiation failure is welcomed. @Silur Reopen if you came out with something to be more verbose
