### ISSUE TITLE
Connect to Microsoft Display Adapter FAILED

### ISSUE THREAD

**Issue by hverjus** [albfan/miraclecast#239]
Hello,

after several attempts from three different Archlinux PCs, I always failed to connect to Microsoft Display Adapter. Using miracle-wifictl, the link is then selected and connection to peer ith connect <peerid>. On the display on the MS Display Adapter is connected to, the spinwheel appears attesting that a connection is initilized, then...it always failed. After that, the MS Display Adapter disappears from the scanning peer list. p2p-scan allows to add it again, and connect and failed etc.
I follow comment #103 on Microsoft fix and understood that the fix is now integrated to the current master branch: I both installed the Archlinux package using yaourt and a also compile miracle from myself in any case...but no way.

Any idea ? Thanks in advance.

Herve

**Comment by albfan** [comment]
#103 is really dense. Windows-fix 

https://github.com/albfan/miraclecast/pull/136

is not merged yet. Some people report it works correctly, others (me) sees a initial lag on streaming

code needs a cleanup to be compatible with master. windows-fix is just a WIP from reverse engineering sessions from Microsoft implementation

Please try and provide feedback on PR

**Comment by albfan** [comment]
I have added this to FAQ https://github.com/albfan/miraclecast/wiki/FAQ#microsoft-os-support

I will close this. Provide feedback on PR. Thaks!
