### ISSUE TITLE
config wpa_supplicant

### ISSUE THREAD

**Issue by keyser84** [albfan/miraclecast#24]
Which changes need to be made in the *wpa.conf*?
Should the network entry be a new network? Or could it be an existing network, e.g. from another AP. Both my phone and my computer are already connected to this existing network. I want the miraclecast sink (running on the computer) on the same network. In this case, I do not even need any pbc/display/keypad configuration, do it? What would I put into *wpa.conf*?

**Comment by albfan** [comment]
Wi-fi Direct means there's no AP between devices.

you can run [miracle-wifi.sh](https://github.com/albfan/miraclecast/blob/master/res/miracle-wifi.sh)k to kill actual connection and start wpa_supplicant in Wi-fi Direct mode. I should work on debian, arch linux and ubuntu. Please provide feedback if something goes wrong.

it uses a fixed config from [wpa.conf](https://github.com/albfan/miraclecast/blob/master/res/wpa.conf). You shouldn't need anymore to config your device.
