### ISSUE TITLE
 wpa_cli -iwlan0: "Could not connect to wpa_supplicant: wlan0 - re-trying" error

### ISSUE THREAD

**Issue by hardiksingh-rathore** [albfan/miraclecast#240]
I'm trying to run a command as given below  
$**wpa_cli -iwlan0**
but it's giving error. 

Will miraclecast work with this wpa_supplicant issue?

Logs are  as given below
`hardik@mate:~$ ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:492 errors:0 dropped:0 overruns:0 frame:0
          TX packets:492 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:36312 (36.3 KB)  TX bytes:36312 (36.3 KB)

hardik@mate:~$

hardik@mate:~$ **sudo miracle-wifid --log-level trace**
INFO: miracle-wifid - revision 1.0 Nov  4 2017 18:04:05
DEBUG: friendly-name from local hostname: mate (manager_read_name() in /home/harr
dik/miraclecast/src/wifi/wifid.c:370)
DEBUG: link: new link: wlan0 (3) (link_new() in /home/hardik/miraclecast/src/wiff
i/wifid-link.c:71)
DEBUG: supplicant: new supplicant for wlan0 (supplicant_new() in /home/hardik/mii
raclecast/src/wifi/wifid-supplicant.c:2103)
INFO: link: add link: wlan0
INFO: link: manage link wlan0
DEBUG: supplicant: start supplicant of wlan0 (supplicant_start() in /home/hardikk
/miraclecast/src/wifi/wifid-supplicant.c:2629)
DEBUG: supplicant: spawn supplicant of wlan0 (supplicant_spawn() in /home/hardikk
/miraclecast/src/wifi/wifid-supplicant.c:2478)
INFO: supplicant: wpa_supplicant found: /sbin/wpa_supplicant
INFO: supplicant: wpas spawned as pid:1601
DEBUG: supplicant: open supplicant of wlan0 (supplicant_open() in /home/hardik/mm
iraclecast/src/wifi/wifid-supplicant.c:2269)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: OK
TRACE: wpa: raw message: p2p_device_address=ba:27:eb:10:78:9b
p2p_state=IDLE
wifi_display=1
ifname=p2p-dev-wlan0
address=ba:27:eb:10:78:9b
ifname=wlan0
address=b8:27:eb:10:78:9b

DEBUG: supplicant: local p2p-address is: ba:27:eb:10:78:9b (supplicant_status_fnn
() in /home/hardik/miraclecast/src/wifi/wifid-supplicant.c:1823)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: OK

TRACE: wpa: raw message: FAIL

TRACE: wpa: raw message: OK

DEBUG: link: link wlan0 started (link_supplicant_started() in /home/hardik/miracc
lecast/src/wifi/wifid-link.c:287)
TRACE: wpa: raw message: FAIL

hardik@mate:~$ **ifconfig**
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3052 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3052 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:225752 (225.7 KB)  TX bytes:225752 (225.7 KB)

wlan0     Link encap:Ethernet  HWaddr b8:27:eb:10:78:9b
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:17 errors:0 dropped:17 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000

hardik@mate:~$ **sudo wpa_cli -iwlan0**
wpa_cli v2.6
Copyright (c) 2004-2016, Jouni Malinen <j@w1.fi> and contributors

This software may be distributed under the terms of the BSD license.
See README for more details.

Interactive mode

Could not connect to wpa_supplicant: wlan0 - re-trying`

**Comment by albfan** [comment]
wlan0 is a normal wifi connection. You need a Wifi direct connection. miraclecast starts wpa_supplicant correctly if there's no wpa_supplicant active.

A correct interface will be seen on ifconfig as `p2p-wlp3s0-0`
