### ISSUE TITLE
Connecting to Wireless Projector

### ISSUE THREAD

**Issue by AkshatMadan** [albfan/miraclecast#244]
Dear Alberto, 

Firstly, i'd like to congratulate you for your efforts towards this project. It is because of architects like you that the internet is thriving. 
Coming to the query, i've successfully installed MiracleCast and going forward would like to connect my system (running on lubuntu 17.10) to a projector which has a wireless display function that supports MIRACAST protocol. 

My knowledge of Linux and Ubuntu is very basic, but i consider myself to be quick learner. Can someone please guide me through the steps ahead 
What is function of Raspberry and is its download necessary?

If everything goes well, i would like to make a video of the entire process to aide future users.

thanks

**Comment by albfan** [comment]
Sadly using miraclecast as source is still a WIP (Work In Progress) .See #4 for details

It's a long wanted feature so it has its own wiki entry https://github.com/albfan/miraclecast/wiki/Internals#source-implementation

You should build the branch 

https://github.com/albfan/miraclecast/tree/wip/source-impl

Or better in the contributor repo

https://github.com/derekdai/miraclecast

to test it. 

Please provide feedback on PR #172

> Warning. There will be dragons there

**Comment by AkshatMadan** [comment]
Wow! It all reads greek to me, i bow down to the Dragon, leave it up to experienced warriors like you. 

> May the Force be with you

**Comment by albfan** [comment]
I always say that skilled people in technology don't have the right but the duty to release accessible software  for the community

Looking for time to finish this feature request
