### ISSUE TITLE
Raspberry pi instructions for Windows

### ISSUE THREAD

**Issue by georgeslegros** [albfan/miraclecast#245]
Hello,

I'm trying to follow the Wiki instructions for Rasapberry pi 3 but I only have a windows machine rather that a linux machine... 

Is there a way you could add a section in the [guide](https://github.com/albfan/miraclecast/wiki/raspberry-pi-3) for windows users?

Thanks.

**Comment by albfan** [comment]
I think you just need to save image to sdcard, 

https://www.raspberrypi.org/documentation/installation/installing-images/windows.md

The rest should be the same. Ask again if you get blocked

**Comment by georgeslegros** [comment]
All right, I could get it to work. Thanks. 
I'm opening a different issue for next problem.
Thanks!

**Comment by albfan** [comment]
I will update wiki with that
