### ISSUE TITLE
Running old version of miraclecast on U untu 17.10

### ISSUE THREAD

**Issue by YoranJansen** [albfan/miraclecast#251]
The output of `systemctl --version` is 
systemd 234
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
I am using ubuntu 17.10 and the output of `/res/test-hardware-capabilities` is `wlp1s0 supports P2P` and I know this computer can use miracast on windows, and miracast compiled and installed without errors and I already tried to reboot (I also followed the steps on https://github.com/albfan/miraclecast for how to use)

**Comment by albfan** [comment]
Seems you do not install dbus miraclecast policy. Read FAQ https://github.com/albfan/miraclecast/wiki/FAQ#install-dbus-policy

Remember to close if that works

**Comment by YoranJansen** [comment]
Now I am getting ```
ERROR: supplicant: execution of wpas (/usr/bin/wpa_supplicant) not possible: No such file or directory (supplicant_spawn() in wifid-supplicant.c:2418)
ERROR: link: cannot start supplicant on wlp1s0 (link_set_managed() in wifid-link.c:149)
```
I do not want to open more issues for little things so that is why I am asking it here.

**Comment by albfan** [comment]
That line do not match

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L2481

Did you modify the code? That line says that miraclecast find /usr/bin/wpa_supplicant and then that file do not exists (has no sense)

`supplicant_find` search for wpa_supplicant in your PATH. There was as `--wpa-bindir` option to set the path for wpa_supplicant. These days if you don't have wpa_supplicant in your PATH, just launch the wifi daemon with

    $ PATH=$PATH:/path/for/your/wpa_supplicant miracle-wifid --any-option-you-want

See `/path/for/your/wpa_supplicant` is the path to the parent dir of wpa_supplicant (like `/usr/local/bin` for `/usr/local/bin/wpa_supplicant`)

**Comment by YoranJansen** [comment]
I did not modify the code. and when i execute supplicant_find it tells me invalid command.

**Comment by albfan** [comment]
supplicant_find is a C function, not a command

If you didn't modify the code, then you're using an old version of miraclecast where it looks for wpa_supplicant in `/usr/bin/wpa_supplicant`, and you have the `--wpa-bindir` option to set a different path for it.

First locate wpa_supplicant

    $ which wpa_supplicant

If that command don't show you any match you need to install it before (or compile yourself, is a similar process than compile and install miraclecast)

Then you can:

- Update your miraclecast code
- use the config option

**Comment by YoranJansen** [comment]
Ok so i found my wpa_supplicant in /sbin/wpa_supplicant, how can i use it as config option, on which file (./configure, ./autogen, miracle-wifid or miracle-sinkctl and is it just filename --bindir /sbin/wpa_supplicant or something else?)

**Comment by albfan** [comment]
$ sudo miracle-wifid --wpa-bindir /sbin

Should be enough

I recommend to upgrade your repo anyway

**Comment by YoranJansen** [comment]
I downloaded it directly from https://github.com/albfan/miraclecast/

**Comment by albfan** [comment]
There's no /use/bin search since August 2016

https://github.com/albfan/miraclecast/commit/4601514799e4b1e017d5c723e69a4fbbefd693e7#diff-744bdd52c5f3b71aac2263033f8c9261L43

Use miraclecast as source is a WIP. You can try it with #172

miracle-wifid is a daemon, so surely it steals terminal input and output, if you want to know what's happening add `--log-level (info|debug|trace)` to command. That message tells you that miraclecast stop by brute force and something fails.

You can append & to send to background but is better to use various terminals. Run miraclecast as a service is an open issue too, See #98. That way miraclecast could stop gracefully

**Comment by YoranJansen** [comment]
I am using the newest version of miraclecast

**Comment by albfan** [comment]
Try to get progress in every comment, your last one left us in same position:

- You 're using the newest version of miraclecast now and everything works so you can close this issue? 
- You *think* you're using the newest version of miraclecast from the very beginning of this issue? Is easy to detect, copy/paste here the line src/wifi/wifid-supplicant.c:2418  and compare with https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L2418. if they are not the same you're not in the lastest version. See lastest version should not accept `--wpa-bindir` option too

As said, you need a different branch to use miraclecast as source, and some skills to adjust it as it is a WIP. I'm working on it these days, I think is better for you to wait till that is finished (subscribe to #4 issue)

I'm ok with teach you every detail you need to know to get this working, but: are you taking this project as user or as developer?

**Comment by YoranJansen** [comment]
It still does not work because: sudo miracle-wifid --wpa-bindir /sbin it hangs anc CTRL + C tells me: ^CNOTICE: caught signal 2, exiting..
ERROR: dbus: syscall failed (-107): Transport endpoint is not connected (link_dbus_removed() in wifid-dbus.c:766)

I am using it as a user and would like it if it works.

**Comment by albfan** [comment]
Read the previous message. It do not hangs, it is a daemon. It is communicating with other miraclecast programs through wpa_supplicant and dbus.

All is explained on README.md

Anyway what you're looking for (use miraclecast as source) is not available yet.

Maybe you want to try other miracast implementations, like https://github.com/intel/wds. I think this project is not mature for your needs (as user). If so please close this issue

**Comment by YoranJansen** [comment]
So do i need 2 terminal windows, one for the daemon and the other for sinkctl?

**Comment by albfan** [comment]
Yes. you can run daemon in background (appending & in the end of miracle-wifid command)

**Comment by YoranJansen** [comment]
so `miracle-wifid & miracle-sinkctl` as one command? or in different terminals?

**Comment by albfan** [comment]
Please reread messages. If I change the subject is because that fit better. This is not a forum but an issue about running miraclecast.

This is the third time I answer that use miraclecast as source (the device here it runs is the stream origin) is a WIP, and you need to try #172 

I will close this. Refer to that PR if you want to try it

**Comment by shamim2018** [comment]
Please tell me an easy way to install and use Miraclecast on Linux Mint 19. I am just an ordinary user, trying to cast my PC on a Sony Smart TV

**Comment by albfan** [comment]
@shamim2018 open your own issue please
