### ISSUE TITLE
Command Not Found (run 3)

### ISSUE THREAD

**Issue by TiboQc** [albfan/miraclecast#253]
Hi,

When I try to run miraclecast as the destination on my ubuntu machine, I get "command not found" when trying to run on the available link.

I managed to compile and install correctly. I even managed to make it almost work (phone detected it, but couldn't connect), but now it won't let me select the link.

Steps:

```
res> ./kill-wpa.sh
res> sudo miracle-wifid &
res> sudo miracle-wifictl
[ADD] Link: 2
[miraclectl] run 2
command not found
```

Could you please help me?

Thanks,

**Comment by albfan** [comment]
miracle-wifictl is not fully implemented. See #4

**Comment by TiboQc** [comment]
Thanks, I then tried running with vlc as followw:
`> sudo miracle-sinkctl -e miracle-vlc`
I can see the link, run it, then see the laptop from my phone, but it won't connect.

```
res$ sudo miracle-sinkctl --log-level trace
[sudo] password for tibo: 
[ADD] Link: 2
[miraclectl] # run 2
now running on link 2
[miraclectl] # list
  LINK INTERFACE                FRIENDLY-NAME                 
     2 wlp1s0                   tibo-dell                     

  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 

 0 peers and 1 links listed.
[ADD] Peer: b6:f1:da:e8:e8:af@2
[PROV] Peer: b6:f1:da:e8:e8:af@2 Type: pbc PIN: 
[GO NEG] Peer: b6:f1:da:e8:e8:af@2 Type: pbc PIN: 
[TIMEOUT] waiting for V30
```
And then my phone times out.
Any idea? I've been playing around with a few tests here and there based on the tickets and wiki, but can't seem to make it work.

From my understanding, once I get them connected, I can start a stream in VLC on my laptop and see the phone, but even then, I can't find what the address of the stream would be.

Thanks for any tip, I'm keeping on trying and looking around.
