### ISSUE TITLE
Can't get wifi back after running miraclecast on ubuntu

### ISSUE THREAD

**Issue by TiboQc** [albfan/miraclecast#254]
Hi,

When I (try to) run miraclecast, upon exiting, I can't get my wifi back. The network manager restarts, wifi connections are found, but I can't reconnect anymore, I need to restart the whole laptop.

Steps:

```
res> ./kill-wpa.sh
res> sudo miracle-wifid &
res> sudo miracle-wifictl
[ADD] Link: 2
[miraclectl] quit
res> ./normal-wifi.sh
Linux version 4.13.0-21-generic (buildd@lgw01-amd64-037) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017
stopping NetworkManager
killing existing wpa_supplicant connection
starting wpa_supplicant for normal connection
Linux version 4.13.0-21-generic (buildd@lgw01-amd64-037) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017
Linux version 4.13.0-21-generic (buildd@lgw01-amd64-037) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017
starting NetworkManager
ERROR: supplicant: wpas (pid:4263) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in /home/<user>/programs/miraclecast-master/src/wifi/wifid-supplicant.c:2331)
```
From then, the wifi is back on, and tries to connect to my hotspot that it finds, but it won't, indicator just spins, without connecting. I need to restart the laptop.

I tried running `sudo service network-manager restart`, but I get the same result.

And as I can't manage to get miraclecast working, I constantly try something, start miraclecast, reboot laptop to try the next thing... Thanks for SSDs for a fast restart!

Thank you!

**Comment by albfan** [comment]
you need to kill miracle-wifid too, which keeps relaunching wpa_supplicant with special conf for WiFi Direct

>ERROR: supplicant: wpas (pid:4263) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in /home/<user>/programs/miraclecast-master/src/wifi/wifid-supplicant.c:2331)

for that is better to launch different programs in different terminals, but in your case

    $ fg
    Ctrl+C

before ./normal-wifi.sh, should work. anyway these days

    $ sudo systemctl stop NetworkManager
    $ sudo systemctl stop wpa_supplicant
    $ sudo systemctl disable NetworkManager

    $ sudo systemctl enable NetworkManager
    $ sudo systemctl start NetworkManager

is a preferred way to stop/start normal WiFi. See #98

**Comment by TiboQc** [comment]
Thanks, it worked! I can't believe I didn't think about stopping the WiFi Direct daemon...

Thanks also for the advice on how to start/stop the network-manager, I didn't know that.
