### ISSUE TITLE
Wrong resolution when connecting OLED screen to RPI3 

### ISSUE THREAD

**Issue by eelife** [albfan/miraclecast#256]
Hi albert, 

I currently have a RPi3 setup configured with a breakout board that uses both RGB and SPI to communicate to a AMOLED display over MIPI DSI. However, when using miracast the session defaults to 800x600 pixels. How can I change the default to 1920x1080p, or 1280x720p?

thanks!

**Comment by albfan** [comment]
you need to use `--res` on miracle-sinkctl. See there's a `--help-res` to see all the avaliable configurations, but it depends on the source capabilities, you need to choose a resolution source supports. If you use `--log-level trace` you can see the communication between source and miraclecast and there's a param which communicates what resolutions source supports (can remember exactly what now)

Try to dig into pdf spec and codebase, I can tell you the exact param later

**Comment by eelife** [comment]
Sorry this took so long. In the middle of 1000 things. But could you help me understand this. I connected the RPI3 to my samsung s8. This was the output.
[sink.log](https://github.com/albfan/miraclecast/files/1690608/sink.log)

**Comment by eelife** [comment]
Any ideas?

**Comment by albfan** [comment]
From your log:

This is your input: The formats miraclecast tell sink it supports by default. You can see them on `miracle-sinkctl --help` [near to `--res` option](https://github.com/albfan/miraclecast/wiki/miracle-sinkctl)

    wfd_video_formats: 00 00 03 10 0000001f 00000003 00000000 00 0000 0000 10 none none

And this is the formats source answers it supports:

    wfd_video_formats: 00 00 02 04 00000000 00000001 00000000 00 0000 0000 00 none none

If you look into [spec](https://github.com/albfan/miraclecast/wiki/files/Wi-Fi_Display_Technical_Specification_v2.1_0.pdf), you can see that formats are on those series of 8 numbers See (table 5-10, 5-11 and 5-12). 

I added more info on wiki so this is better explained [detail of resolutions avaliable](https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#detail-of-resolutions-avaliable) and how to use it.

Miraclecast tells it supports all CEA resolutions and only 2 VESA resolutions (and none HH resolutions) This is just the defaults, you can modify them

Based on that info (cause I suppose samsung 8 supports more resolutions) source answers it can share the screen on 1 VESA resolution (which is "800x600 p60")

I guess samsung 8 only supports resolutions VESA, so you need to tell miraclecast that you want to use more VESA resolutions

Playing with `--res` you should find the resolution your device supports. This is to tell source miraclecast supports all the VESA resolutions:

    miracle-sinkctl --res 00,1FFFFFFF,00

**Comment by eelife** [comment]
You are a legend. I got it working! Thanks

**Comment by albfan** [comment]
Maybe is time to change the defaults to support everything, want to provide a PR?

**hint**: Is a change in these 3 lines (just need to read doc avoid those 8 hex numbers)
https://github.com/albfan/miraclecast/blob/04a1ec8aa3f791dc276dab827df8968cf87e0c47/src/ctl/sinkctl.c#L70-L73 😉

**Comment by albfan** [comment]
Done! 1d01ae2
