### ISSUE TITLE
Using MiracleCast as source in RPI 3

### ISSUE THREAD

**Issue by Chaitanyachavali** [albfan/miraclecast#257]
I have a [AnyCast](https://www.amazon.in/Anycast-AC1350-2-Wireless-Display-Android/dp/B01ERHGH6C) device which is connect to the monitor via HDMI. I want to cast my raspberry pi 3 screen to the monitor via AnyCast device connected to it. I haven't found any instructions or steps to do the same. 
Is it possible to achieve it ?. If not what would be the best way to cast raspberry pi 3 screen to monitor ?

**Comment by albfan** [comment]
To use miraclecast as source take a look at #4 and #172, but is still a WIP, feedback wellcome
