### ISSUE TITLE
unknown-network Error while Connecting

### ISSUE THREAD

**Issue by Caliban2017** [albfan/miraclecast#261]
Hallo,

first, sorry for my bad english. I bought myself a Raspberry Pi 3 Model B yesterday and want to use Miraclecast to Screencast my Tablet to the Raspberry. 

I downloaded Miracast with a git clone command, and then i downloaded systemd via apt-get command  and all other missing things like glib and gstreamer on the same way. i downloaded autotools and used the make command and make install like in the Documentary/Readme. 

Everything seems fine so far, i can use sudo miracle-wifid & command to start the demon and miracle-sinkctl works too. On My Tablet (Levono Tab A1070F with Android 7) i can find the Raspberry in the Miracast Devicelist. But when i try to connec,t, it takes some time but nothing happens.

Sinkctl shows up [Add] Peer and Numbers. But after a Minute oder two it does not connect and say [Remove] Peer.

i starten miracle-wifid with --log-level trace and this is the result:

> pi@raspberrypi:~
> 
>  $ sudo miracle-wifid --log-level trace
> INFO: miracle-wifid - revision 1.0 Feb 16 2018 21:29:06
> DEBUG: friendly-name from local hostname: raspberrypi (manager_read_name() in ../../../src/wifi/wifid.c:370)
> DEBUG: link: new link: wlan0 (3) (link_new() in ../../../src/wifi/wifid-link.c:71)
> DEBUG: supplicant: new supplicant for wlan0 (supplicant_new() in ../../../src/wifi/wifid-supplicant.c:2103)
> INFO: link: add link: wlan0
> INFO: link: manage link wlan0
> DEBUG: supplicant: start supplicant of wlan0 (supplicant_start() in ../../../src/wifi/wifid-supplicant.c:2629)
> DEBUG: supplicant: spawn supplicant of wlan0 (supplicant_spawn() in ../../../src/wifi/wifid-supplicant.c:2478)
> INFO: supplicant: wpa_supplicant found: /sbin/wpa_supplicant
> INFO: supplicant: wpas spawned as pid:1202
> DEBUG: supplicant: open supplicant of wlan0 (supplicant_open() in ../../../src/wifi/wifid-supplicant.c:2269)
> TRACE: wpa: raw message: OK
> 
> TRACE: wpa: raw message: OK
> 
> TRACE: wpa: raw message: p2p_device_address=ba:27:eb:26:5f:22
> p2p_state=IDLE
> wifi_display=1
> ifname=p2p-dev-wlan0
> address=ba:27:eb:26:5f:22
> ifname=wlan0
> address=b8:27:eb:26:5f:22
> 
> DEBUG: supplicant: local p2p-address is: ba:27:eb:26:5f:22 (supplicant_status_fn() in ../../../src/wifi/wifid-supplicant.c:1823)
> TRACE: wpa: raw message: OK
> 
> TRACE: wpa: raw message: OK
> 
> TRACE: wpa: raw message: FAIL
> 
> TRACE: wpa: raw message: OK
> 
> DEBUG: link: link wlan0 started (link_supplicant_started() in ../../../src/wifi/wifid-link.c:287)
> TRACE: wpa: raw message: FAIL
> 
> DEBUG: supplicant: send 'WFD_SUBELEM_SET 0 000600111c4400c8' to wpas on wlan0 (supplicant_set_wfd_subelements() in ../../../src/wifi/wifid-supplicant.c:1991)
> TRACE: wpa: raw message: OK
> 
> DEBUG: supplicant: sent P2P_FIND to wpas on wlan0 (supplicant_p2p_start_scan() in ../../../src/wifi/wifid-supplicant.c:2036)
> TRACE: wpa: raw message: OK
> 
> DEBUG: supplicant: p2p-scanning now active on wlan0 (supplicant_p2p_find_fn() in ../../../src/wifi/wifid-supplicant.c:1917)
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>P2P-DEVICE-FOUND 76:04:2b:e8:f0:82 p2p_dev_addr=76:04:2b:e8:f0:82 pri_dev_type=8-0050F204-2 name='Lenovo TAB 2 A10-70F_96ec' config_methods=0x188 dev_capab=0x5 group_capab=0x0 wfd_dev_info=0x00101c440032 new=1
> TRACE: wpa: raw message: <3>P2P-DEVICE-FOUND 76:04:2b:e8:f0:82 p2p_dev_addr=76:04:2b:e8:f0:82 pri_dev_type=8-0050F204-2 name='Lenovo TAB 2 A10-70F_96ec' config_methods=0x188 dev_capab=0x5 group_capab=0x0 wfd_dev_info=0x00101c440032 new=1
> DEBUG: peer: new peer: 76:04:2b:e8:f0:82 @ wlan0 (peer_new() in ../../../src/wifi/wifid-peer.c:52)
> INFO: peer: add peer: 76:04:2b:e8:f0:82
> DEBUG: peer: peer 76:04:2b:e8:f0:82 @ wlan0 started (peer_supplicant_started() in ../../../src/wifi/wifid-peer.c:162)
> DEBUG: supplicant: requesting data for new peer 76:04:2b:e8:f0:82 (supplicant_event_p2p_device_found() in ../../../src/wifi/wifid-supplicant.c:962)
> TRACE: wpa: raw message: 76:04:2b:e8:f0:82
> pri_dev_type=8-0050F204-2
> device_name=Lenovo TAB 2 A10-70F_96ec
> manufacturer=MediaTek Inc.
> model_name=MTK Wireless Model
> model_number=1.0
> serial_number=2.0
> config_methods=0x188
> dev_capab=0x5
> group_capab=0x0
> level=-62
> age=0
> listen_freq=2462
> wps_method=not-ready
> interface_addr=00:00:00:00:00:00
> member_in_go_dev=00:00:00:00:00:00
> member_in_go_iface=00:00:00:00:00:00
> go_neg_req_sent=0
> go_state=unknown
> dialog_token=0
> intended_addr=00:00:00:00:00:00
> country=__
> oper_freq=0
> req_config_methods=0x0
> flags=[REPORTED]
> status=0
> invitation_reqs=0
> wfd_subelems=00000600101c4400320700020001
> 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: IFNAME=p2p-dev-wlan0 <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED 
> TRACE: wpa: raw message: <3>P2P-INVITATION-RECEIVED sa=76:04:2b:e8:f0:82 go_dev_addr=76:04:2b:e8:f0:82 bssid=76:04:2b:e8:f0:82 unknown-network
> TRACE: wpa: raw message: <3>P2P-INVITATION-RECEIVED sa=76:04:2b:e8:f0:82 go_dev_addr=76:04:2b:e8:f0:82 bssid=76:04:2b:e8:f0:82 unknown-network
> DEBUG: supplicant: unhandled wpas-event: <3>P2P-INVITATION-RECEIVED sa=76:04:2b:e8:f0:82 go_dev_addr=76:04:2b:e8:f0:82 bssid=76:04:2b:e8:f0:82 unknown-network (supplicant_event() in ../../../src/wifi/wifid-supplicant.c:1499)
> TRACE: wpa: raw message: <3>P2P-DEVICE-LOST p2p_dev_addr=76:04:2b:e8:f0:82
> TRACE: wpa: raw message: <3>P2P-DEVICE-LOST p2p_dev_addr=76:04:2b:e8:f0:82
> DEBUG: supplicant: lost peer 76:04:2b:e8:f0:82 (supplicant_event_p2p_device_lost() in ../../../src/wifi/wifid-supplicant.c:986)
> DEBUG: peer: peer 76:04:2b:e8:f0:82 @ wlan0 stopped (peer_supplicant_stopped() in ../../../src/wifi/wifid-peer.c:172)
> DEBUG: peer: free peer: 76:04:2b:e8:f0:82 @ wlan0 (peer_free() in ../../../src/wifi/wifid-peer.c:90)
> INFO: peer: remove peer: 76:04:2b:e8:f0:82

i hope you can tell me, what i am doing wrong. i am a total noob of linux and raspberry and that stuff... i learned all that by myself so far, so if you help me, please do it so i can understand it.. :)

thank you for your help

**Comment by albfan** [comment]
From your log, seems both devices see each other but handshaking is not started. Maybe your tablet is asking for a pin instead of work by PBC.
 
Try to collect all the logs related to see the problem. See [log for support](https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support)

**Comment by Caliban2017** [comment]
so it means it will not work with that Tablet? A very strange thing is, it worked so far for ONE TIME.... after a fresh installation of Raspbian and MiracleCast i started miracle-wifid and sinkctl as normal and on the tablet it sayed connectet and i had a green [Connected] in the sinkctl Terminal. But i didn't have installed gstreamer at this time, so there was so Screen output. I stopped it and after that i installed gstreamer and started everything again, and there was the Error. So it worked only once so far and after that only Errors. 

i will try now everything again from the beginning and then i create all the logs and post them here later.

**Comment by Caliban2017** [comment]
Okay, i tried now with another Device, used a Galaxy S8 Smartphone and it worked! So there is defenitly the Problem on the Tablet, but what i can do to connect it to MiracleCast..? Can i change that PIN thing to PBC somehow?

**Comment by albfan** [comment]
No is just we need to see in detail what is happening. Miracast is a spec, and many manufacturers implement it in a loose way. What is exactly your tablet? Please upload the logs

**Comment by albfan** [comment]
Reopen if you still have this problem and collect that information
