### ISSUE TITLE
miraclecast build for ARM

### ISSUE THREAD

**Issue by NKAVY** [albfan/miraclecast#262]
Hi,

I am trying to build miraclecast source for ARM, following the below steps:

git clone
mkdir build
cd build
../autogen.sh g
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var  --host=arm-cortexa9-linux-gnueabi --build=i686-host-linux-gnu 

I have got "systemd" version 37 and UDEV 181 installed on the system. While running "./configure", there is a build error as follows:

********************************************************************************
configure: error: Package requirements (libudev libsystemd > 219) were not met:

No package 'libudev' found
No package 'libsystemd' found
********************************************************************************
As it is not advisable to change the systemd, UDEV versions for the platform I am working on, I am stuck up here. Is there any work around to make the build work for the above mentioned systemd,UDEV versions? Any help here is much appreciated.

Thanks.

**Comment by albfan** [comment]
This software strongly depends on systemd to work. It starts at systemd 205 and now (due to an interface change on systemd) depends on systemd > 219.

There's a branch for miraclecast prior 219, but don't know the changes from systemd 37 to systemd 219, maybe you can try it

Stability is not great on that <219 version (don't know the details it just works randomly) 

I'm curious, what's the device? There's an arch arm where you can use arch linux and the AUR package for miraclecast or a recipe for yocto https://github.com/OSSystems/meta-miracast/tree/master/recipes-miracast/miraclecast, which I guess is a really tiny system

**Comment by NKAVY** [comment]
Hi,

Thank you for a quick reply! I will surely check with an earlier branch with systemd<219. I see various branches on the source. May I know the branch information of the source prior 219?

Ours is an ARM Cortex-A9 type running Linux system with a kernel version 3.0.35. We are trying to install miraclecast on this system.

**Comment by albfan** [comment]
The branch is: https://github.com/albfan/miraclecast/tree/systemd-219

Don't know if it is an option but arch arm https://archlinuxarm.org/platforms/armv7 support your core and you should be able to install on it https://aur.archlinux.org/packages/miraclecast-git/ and get any update easily

**Comment by NKAVY** [comment]
Thank you for your inputs! Unfortunately, it is not an option for me to switch to arch arm.  I am going to try on systemd-219 branch and see how it goes.

**Comment by albfan** [comment]
Sure. For quick replies remember there's a gitter chat avaliable https://gitter.im/albfan/miraclecast

**Comment by NKAVY** [comment]
Hey, just to share,

systemd-219 branch expects systemd>213 and I have a basic version of systemd -- 37. I observe that miraclecast uses files such as "sd-event.h" to perform few functionalities, but my version of systemd doesn't have this header file at all.  Since my intention is to build and install, any "miracast" based media servers on this configuration, I couldn't do much at this stage. So, I am giving up here.

Would appreciate if could refer any other open source miracast based media servers, if any.

**Comment by albfan** [comment]
Yes it do need that version. I think miraclecast starts with systemd 205

- https://github.com/intel/wds (based on connman)
- This is a library implementation of miracast (https://www.freedesktop.org/wiki/Software/miracle/libwfd/) that do not uses systemd

**Comment by NKAVY** [comment]
Hi,

I would look into these options. Thanks a lot for your help here. Appreciate it!

**Comment by albfan** [comment]
Please close this if miraclecast does not fit for your needs
