### ISSUE TITLE
Understanding internal protocols of miraclecast

### ISSUE THREAD

**Issue by Zibri** [albfan/miraclecast#264]
I wish to test just the connectivity part.
Is there a way using wpa_cli or miracle-wifictl to only do this?
I mean connecting from a linux box to a miracast device exactly as and android phone does.
I know how to start a normal p2p connection but android uses a different way somehow.

**Comment by albfan** [comment]
See this question is unrelated with miraclecast. You can learn about wpa_cli looking into its docs or reading specific tutorials, (I recommend you this one) https://thangamaniarun.wordpress.com/2013/03/03/how-to-use-wi-fi-direct-on-androidubuntu-part1/ (there are three parts)

If there's nothing related to miraclecast please close this isssue

**Comment by Zibri** [comment]
It's not unrelated. I know how to make a wifi-direct connection between 2 devices. What I don't know is why screen mirroring is different. Screen mirroring causes the screen device to connect to the casting device in wifi-direct and that's what I wish to learn to do. But I don't know where to search or who to ask.

**Comment by albfan** [comment]
Miraclecast is an implementation of miracast protocol. You can read it in detail here https://github.com/albfan/miraclecast/wiki/Miracast. It is based on several other specs (WiFi direct to create a local network, RTSP to stream it and RTP to transport it: https://stackoverflow.com/a/4303565/848072

You. can do all that with wpa_cli, netcat and VLC (is pretty easy) but is unrelated with miraclecast.

**Comment by albfan** [comment]
Resume: Having two devices miracast compatible:

- One device search for others
- Choose one avaliable and start a handshaking
- After successful pairing start a setup by RTSP to stream media content (its own screen)
- Device acting as sink plays that stream

Links provided describe all that process in detail

Hope it helps
