### ISSUE TITLE
issue in following wiki

### ISSUE THREAD

**Issue by thisisnottaken** [albfan/miraclecast#266]
sir ,
i am following instructions from https://github.com/albfan/miraclecast/wiki/raspberry-pi-3 .
i got the gz file and flashed it to sd card . 
then i booted my raspberry pi 3 model b v 1.2
opened a terminal & ran 
 sudo miracle-wifid
opened another terminal & ran
sudo miracle-sinkctl
Note that my raspberry's ethernet port is idle .
i hope that above command will create a wifi hotspot so that which will appear in list of wireless displays on my mobile redmi note 3 .
so my question is that i don't see any SSID in my wireless display options on android  6.0.1 ?

thanks .

**Comment by albfan** [comment]
Miracle-wifid is the daemon to manage in network interfaces, but to work as sink you need to run miracle-sinkctl (sink controller)

**Comment by thisisnottaken** [comment]
Now, I will try to be more concise 
 I ran following commands in separate terminal
sudo journalctl -f |& tee journaltxt.log
sudo miracle-wifid --log-level trace |& tee wifidtxt.log
sudo miracle-sinkctl --log-level trace --log-journal-level trace |& tee sinktxt.log
[journaltxt.log](https://github.com/albfan/miraclecast/files/1781743/journaltxt.log)
[wifidtxt.log](https://github.com/albfan/miraclecast/files/1781745/wifidtxt.log)
[sinktxt.log](https://github.com/albfan/miraclecast/files/1781747/sinktxt.log)

This time I had turned off mobile data on my mobile.
When I ran 'run 3' in sinkctl terminal then alarmpi appeared in list of wireless displays on my mobile .
this time my mobile also got connected to it .
But in gstplayer , there was just a black window.
I hoped that my mobile screen will be visible in it.

what am I doing wrong here ?

Thanks.

**Comment by albfan** [comment]
I think your problem is https://github.com/albfan/miraclecast/issues/183#issuecomment-291012571

Can you try. I guess I need to update the image to add that if that's the problem

**Comment by thisisnottaken** [comment]
sir ,
that comment is about broken gstplayer .
in my case , gstplayer did not report anything in terminal .
anyway , i am not able to figure out - what should i try .
also, i hope that the way i did things above was correct .
i am expecting mobile screen to mirror on raspberry pi 3 .

thanks .

**Comment by albfan** [comment]
the player is irrelevant, if you get a black window is because running as sudo (whichver play is spawn from miracle-sinkctl) you don't have permissions to see stream

Try that workaround and close this issue if that works, by now is the only solution

**Comment by thisisnottaken** [comment]
should i run 
sudo gstplayer 

?

**Comment by albfan** [comment]
That comment suggests to add that those lines on .bashrc to have all the terminal sessions configured

For a quick try, run this on same terminal you will run miracle-sinkctl

    xhost +si:localuser:root

and try again miraclecast. (miracle-sinkctl will run the configured player automatically)

**Comment by thisisnottaken** [comment]
xhost command not found .
by the way , when i ran sudo gstplayer i saw my mobile on raspberry attached display once after which my mobile got disconnected from alarmpi , don't know why .

**Comment by thisisnottaken** [comment]
also note that

$ sudo systemctl stop networkd.service 
$ sudo systemctl stop network.target 
don't work in the OS image you have provided .

Thanks for your patience .

**Comment by albfan** [comment]
Are you following https://github.com/albfan/miraclecast/wiki/FAQ#raspberry-pi-instructions?

I did a little fix. Commands are:

    $ sudo systemctl stop NetworkManager
    $ sudo systemctl stop wpa_supplicant

**Comment by thisisnottaken** [comment]
ok .
those commands work .
I found that mi max 2 got displayed in gstplayer while my mi note never did .
It is nice to see mobile screen on big HDMI monitor.

 Have you been able to play something on mxplayer in mobile and see it on raspberry connected display .
In my case, connection gets disconnected when I do that .

**Comment by albfan** [comment]
I see a bunch of different issues here:

# You can always upload logs to check the problem for note (galaxy note I suppose)
# Mxplayer is an android video player. can't see how it is related, but as it says it uses hardware graphic acceleration you should ask first on an mxplayer bugtracker. All I can find is a google form in a facebook page, damn it, just that is a reason to uninstall it a use vlc for android.
# gstplayer or whatever player you configure to run with miraclecast should rise automatically, doesnt' it do that for you? that's another issue

**Comment by thisisnottaken** [comment]
okay sir .
I will post logs .

**Comment by thisisnottaken** [comment]
I am closing this issue and will post new issue with full log and observation.
Thanks.
