### ISSUE TITLE
Fedora problems with libudev

### ISSUE THREAD

**Issue by walzert** [albfan/miraclecast#269]
I tried to install miraclecast on Fedora 27 , my systemd-devel  version is 234, installed it with dnf

```
systemctl --version
systemd 234
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
```

with autogen.sh  i got following problem

```
checking for DEPS... no
configure: error: Package requirements (libudev libsystemd > 219) were not met:

Package 'libudev', required by 'virtual:world', not found
Package 'libsystemd', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEPS_CFLAGS
and DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
 
what can I do?
Thank you.

**Comment by albfan** [comment]
On fedora the package seems to be "systemd-devel"

https://rpmfind.net/linux/RPM/fedora/updates/27/x86_64/Packages/s/systemd-devel-234-10.git5f8984e.fc27.i686.html

On fedorea you can find which package provides a file with:

    dnf provides systemd.pc
    dnf provides udev.pc

**Comment by albfan** [comment]
solved? can you close this?

**Comment by walzert** [comment]
yes thank you it worked.
