### ISSUE TITLE
Could not read interface -Dnl80211 flags: No such device

### ISSUE THREAD

**Issue by sollidsnake** [albfan/miraclecast#27]
I'm trying to run the `miracle-wifi.sh` script, but I'm getting this error:
```
➜  res git:(master) sudo ./miracle-wifi.sh 
cannot find wpa_supplicant connection to kill
starting wpa_supplicant for miraclecast on
wpa_supplicant v2.3
dbus: Register D-Bus object '/fi/w1/wpa_supplicant1'
Providing DBus service 'fi.w1.wpa_supplicant1'.
Providing DBus service 'fi.epitest.hostap.WPASupplicant'.
Successfully initialized wpa_supplicant
Initializing interface '-Dnl80211' conf './wpa.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file './wpa.conf' -> '/tmp/miraclecast/res/./wpa.conf'
Reading configuration file '/tmp/miraclecast/res/./wpa.conf'
ctrl_interface='/run/wpa_supplicant'
ap_scan=1
device_name='my-device'
config_methods='pbc'
rfkill: initial event: idx=0 type=1 op=0 soft=0 hard=0
rfkill: initial event: idx=1 type=2 op=0 soft=0 hard=0
Could not read interface -Dnl80211 flags: No such device
nl80211: Driver does not support authentication/association or connect commands
nl80211: Remove monitor interface: refcount=0
netlink: Operstate: ifindex=0 linkmode=0 (kernel-control), operstate=6 (IF_OPER_UP)
Could not read interface -Dnl80211 flags: No such device
nl80211: Set mode ifindex 0 iftype 2 (STATION)
nl80211: Failed to set interface 0 to mode 2: -19 (No such device)
-Dnl80211: Failed to initialize driver interface
Failed to add interface -Dnl80211
-Dnl80211: Cancelling scan request
-Dnl80211: Cancelling authentication timeout
dbus: Unregister D-Bus object '/fi/w1/wpa_supplicant1'
```

The test says my hardware is compatible:
```
➜  res git:(master) ./test-wifi-capabilities.sh 
wlp2s0 supports P2P
```

**Comment by albfan** [comment]
See it is not needed to launch script with `sudo`. You will be prompt when neccesary.

Anyway script is not detecting your device.

Line:

     starting wpa_supplicant for miraclecast on

Should say something like

    starting wpa_supplicant for miraclecast on <your_device>

It is suppose to detect it automatically. I have added a debug config mechanism. Basically do define this variable:

    $ export miracle_wifi_sh_DEBUG=1

And add output here.

**Comment by albfan** [comment]
24c7c37572eb74ede2acf212795c8393a6176bd7 is after b0f985069c1225c2df59b717855e44a8e0634e35 (which depends on systemd 219 or higher) anyway, could you test that changes? I think now script has to refuse to work (as it doesn't find devices)

**Comment by sollidsnake** [comment]
Sorry taking so long, I've been a little busy these last few days. Right now I'm at work, I'll try that in a few hours when I'm free. Thanks :)

**Comment by sollidsnake** [comment]
Yes, with the last commits this seems fixed. I don't get the error anymore
