### ISSUE TITLE
After Installing, how to proceed?

### ISSUE THREAD

**Issue by guettli** [albfan/miraclecast#272]
I installed miraclecast from this source: https://launchpad.net/~thopiekar/+archive/ubuntu/miraclecast

What is the next step to connect my laptop to my samsung smartTV?

**Comment by albfan** [comment]
Using miraclecast as source is still not implemented, see #4

Feedback welcomed there (but master source will not work for that)

**Comment by guettli** [comment]
@albfan I am unsure what you mean with "Using miraclecast as source". Here is my goal: I want my ubuntu laptop to be the source and the SmartTV the target. I want to see the screen of my laptop on the SmartTV.

**Comment by albfan** [comment]
Yes, exactly that. The device which runs miraclecast acting as source.

You need to be able to build a miraclecast branch to try it and provide feedback. For me it fails on group formation (code is not mine) it is supposed to work for its creator @derekdai at least

I think k you can close this and continue on that issue

**Comment by guettli** [comment]
I heard that the spec is broken by design.

I heard that it is broken because the spec relies on wifi. I am confused. Wouldn't it be nice if this could be used via ethernet, too? I don't understand this.

What do you think about the topic "spec is broken"?

**Comment by albfan** [comment]
Don't think is fair.

The spec is so simple that every company adds it's extensions.

1. Create an internal network where both devices can see each other
2. Share a video stream between them using a known protocol RTSP

You can do the step 2 through ethernet, but that's not miracast, here the key is quick connectivity, you and an mate has two devices miracast compatible? You can share video without share of passwords, connect cables, transfer files...

That hacmve a cost, miracast is a battery drainer

**Comment by guettli** [comment]
What does "hacmve" mean?

I have no clue. I am a stupid user. I just know that I can't use the Samsung SmartTV as display (without cable) using ubuntu.

**Comment by albfan** [comment]
Then you're looking for this to happen:

1. Integrate Wifi Direct on GNOME Desktop through NetworkManager https://wiki.gnome.org/NetworkManager/WifiDirect
2. Create a networkmanager plugin to expose the screen sharing feature (miraclecast) #98

I'd love to implement that, but, sadly, this is not my job, so cannot promise anything

**Comment by guettli** [comment]
Roughly two years ago albfan wrote this

> These days I'm working on #98, which should hide all that boilerplate commands to run miraclecast

See https://github.com/albfan/miraclecast/issues/97#issuecomment-234955699

Today you said "I'd love to implement that, but, sadly, this is not my job, so cannot promise anything".

**Comment by albfan** [comment]
That confirms exactly what I'm saying, thanks for pointing out

This is not a forum, so I will delete your comment, ok?

**Comment by Ryu945** [comment]
Does using MiracleCast as source from Ubuntu/Mint repository work now?

**Comment by albfan** [comment]
No. You can try https://github.com/benzea/gnome-network-displays. At so e point we will integrate that in GNOME
