### ISSUE TITLE
On attempting to connect: ERROR: supplicant: HUP on supplicant socket of wlan0 ...

### ISSUE THREAD

**Issue by apenni** [albfan/miraclecast#275]
Followed the instructions to install/use miracle cast on Pi (not the arch img)
I downloaded the git master repo, compiled and installed.
I boot up, and end network services using "sudo systemctrl stop network*"
(the network service names in the FAQ don't match those running on Raspbian so I just stop them all)
Then I use res/kill-wpa.sh to kill any remaining wpa_supplicants

I start "sudo miracle-wifid &"
and then "sudo miracle-sinkctl"
It detects the link (*ADD LINK"), and I enter "run 3".

Things seem fine and it starts scanning and I can see the device in my miracast targets from Windows 10. But as soon as I go to connect the display, wifid spits out the generic error message in the title. I can't tell what went wrong other than the wpa_supplicant child process it launched failed and was terminated.

logs attached
[miraclecastlogs.zip](https://github.com/albfan/miraclecast/files/1845674/miraclecastlogs.zip)

Background:
I am running Raspbian Stretch Lite. I have RetroPi (emulation station) installed and Kodi installed on top of that.

**Comment by albfan** [comment]
windows 10 do not follow exactly the miracast spec.

See #136

I think you should close this issue and provide feedback there
