### ISSUE TITLE
lipcap dependency

### ISSUE THREAD

**Issue by 275288698** [albfan/miraclecast#28]
I download the file on my ubuntu , and when i try

    # ./configure 

it happened a error like this:

    configure: error: *** POSIX caps headers not found

**Comment by 275288698** [comment]
hi albfan
    i have found the solution , i need install the libcap2.22 ,here is the link http://archive.ubuntu.com/ubuntu/pool/main/libc/libcap2/libcap2_2.22.orig.tar.gz

**Comment by albfan** [comment]
I guess you are trying to compile systemd, Am I right?

http://packages.ubuntu.com/utopic/systemd

Please follow instructions (and open issues if needed) on 

https://github.com/albfan/systemd-ubuntu-with-dbus
