### ISSUE TITLE
How to Enable Visibility for other devices

### ISSUE THREAD

**Issue by KaapstadMK** [albfan/miraclecast#280]
Linux newbie here.
I'm trying to run Miraclecast to establish my computer as the source, mirroring to Roku. (I assume that means running as peer).
I was able to run steps 1 and 2, before getting to the miraclectl command prompts. I have no idea how to enable device visibility in Linux (not sure I knew how to in windows) and > p2p-scan didn't yield any results

What exactly am I supposed to do? I noticed a roku on my network connections as an available connection, but it required a password, which I don't recall the roku having/me setting up on the roku (I may have, but It's been a while and I keep petty busy)

**Comment by albfan** [comment]
No, that means run as a source (the other option is as a sink) You need to see #4 but it is still a WIP

**Comment by albfan** [comment]
The branch for miraclecast as source is on PR #172. Provide feedback there
