### ISSUE TITLE
Unable to find and connect to Miracast

### ISSUE THREAD

**Issue by bnkose** [albfan/miraclecast#283]
sudo miracle-wifid --log-level trace gives the following result.

```
INFO: miracle-wifid - revision 1.0 Jun 10 2018 06:56:48
DEBUG: friendly-name from local hostname: issac (manager_read_name() in wifid.c:370)
DEBUG: link: new link: wlx20e916017060 (3) (link_new() in wifid-link.c:71)
DEBUG: supplicant: new supplicant for wlx20e916017060 (supplicant_new() in wifid-supplicant.c:2103)
INFO: link: add link: wlx20e916017060
INFO: link: manage link wlx20e916017060
DEBUG: supplicant: start supplicant of wlx20e916017060 (supplicant_start() in wifid-supplicant.c:2629)
DEBUG: supplicant: spawn supplicant of wlx20e916017060 (supplicant_spawn() in wifid-supplicant.c:2478)
INFO: supplicant: wpa_supplicant found: /sbin/wpa_supplicant
INFO: supplicant: wpas spawned as pid:24411
DEBUG: supplicant: open supplicant of wlx20e916017060 (supplicant_open() in wifid-supplicant.c:2269)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: wifi_display=1
ifname=wlx20e916017060
address=20:e9:16:01:70:60

WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in wifid-supplicant.c:1698)
DEBUG: link: link wlx20e916017060 started (link_supplicant_started() in wifid-link.c:287)
```

sudo miracle-wifictl --log-level trace gives the result

```
[ADD] Link: 3


[miraclectl] # list
  LINK INTERFACE                FRIENDLY-NAME                 
     3 wlx20e916017060          issac                         

  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 

[miraclectl] # select 3
link 3 selected
```

What should I do to find my device. I dont know its MAC address. Its SSID : Mirascreen 5D1CED2A PSK: 60648437 PIN : 12345670

**Comment by albfan** [comment]
At this time, you should discover miracast from your source device (as Miracast only act by now as sink)

**Comment by bernd-wechner** [comment]
Aargh, I need use my Linux server as a source to send images to a miracast device. What to do? Wasted my time here it seems? Is there not solution out there?

**Comment by albfan** [comment]
@bernd-wechner Thanks for sharing your rantings in this issue totally unrelated with your problem

There're solutions out there for sure (even here) but you should rethink on how to ask for help

I will delete your comment as is only noise

**Comment by bernd-wechner** [comment]
Aargh, I need use my Linux server as a source to send images to a miracast device. What to do? Wasted my time here it seems? Is there not solution out there?

**Comment by albfan** [comment]
@bnkose see #4 for this
