### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in /home/pi/miraclecast/src/wifi/wifid-dbus.c:899)

### ISSUE THREAD

**Issue by keny5551** [albfan/miraclecast#284]
When I start 'sudo miracle-wifid' I get this error

```
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in /home/pi/miraclecast/src/wifi/wifid-dbus.c:899)
```

Is there something missing in my system?

**Comment by albfan** [comment]
It's supposed you install miraclecast so there's a policy to allow you to access those resources. Look for that error on other issues for more info (or in README)

**Comment by albfan** [comment]
Error 17 (EEXISTS) occurs if you run several time `miracle-wifid`. You can check if you run it several times with

    ps -ef | grep miracle-wifid

and killing all that process

**Comment by devbharat** [comment]
After you make install, it could be that the dbus policy conf is installed in `/usr/local/etc/dbus-1/system.d/org.freedesktop.miracle.conf ` but your system needs it in `/etc/dbus-1/system.d` directory. You can manually move it there, then it works.

**Comment by albfan** [comment]
@devbharatis better idea to define prefix and relates to use correct path, all that leads to more unknown errors
