### ISSUE TITLE
Android unable to connect to miraclecast sink

### ISSUE THREAD

**Issue by cool00geek** [albfan/miraclecast#286]
I am using Ubuntu 16.04 as a miraclecast sink, but my Android phone is unable to connect to my computer.

My computer has an intel 7260AC wifi card.

My Android phone is a Samsung Galaxy s5 running Lineage OS 14.1, Android 7.1.2

I know my phone supports miracast because I have mirrored it to various TVs that support miracast. I have attached the required logs. Plea
se let me know how I can use miraclecast on my computer.
[logs.tar.gz](https://github.com/albfan/miraclecast/files/2173215/logs.tar.gz)

**Comment by albfan** [comment]
Seems your phone is asking for a PIN to do the connection:

```
Type: pbc PIN:
```

normally 0000 or 1234 works but you need to figure out that

**Comment by cool00geek** [comment]
My phone is not prompting for anything though. I'm assuming I am supposed to enter the pin on my phone?

**Comment by albfan** [comment]
Your phone seems to be requesting that to miraclecast. You can type on the `miracle-sinkctl` when it prompts

**Comment by cool00geek** [comment]
Sorry if this has been addressed previously.

Do I just type the pin on `miracle-sinkctl`?

So when it prompts for the pin, do I just type `1234` or `0000` in the `miracle-sinkctl` prompt?

**Comment by albfan** [comment]
Yes, definitely not so clear.

You may want to change your config to avoid your phone to ask for password

**Comment by cool00geek** [comment]
How do I go about changing the configuration to use something other than pbc? I see the `wpa.conf` file [here](https://github.com/albfan/miraclecast/blob/master/res/wpa.conf) has settings to change the authentication mechanism, but how do I actually make miraclecast start wpa_supplicant with these modified settings?

**Comment by albfan** [comment]
You can change here:

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L2602

See pbc, means no pin, so the source (your mobile) is the ruler of the negotiation, it is the one that is claiming for a password, there's nothing you can do on the sink to change that. You need to setup your mobile to don't ask for password

**Comment by dreirund** [comment]
> Your phone seems to be requesting that to miraclecast. You can type on the `miracle-sinkctl` when it prompts

I have this issue, too, that Android is not making the connection and `miracle-sinkctl --log-lvl 9 --log-time` shows  
```
[0010.790545] [ADD] Peer: 7a:[...]@3
[0015.038244] [PROV] Peer: 7a:[...]@3 Type: pbc PIN: 
[0015.540567] [GO NEG] Peer: 7a:[...]@3 Type: pbc PIN: 
```  
when I try to connect from android (MAC adresses I have censored here).

But how can I type it into `miracle-sinkctl`?

It just complains that it cannot understand the command.

I tried typing `pbc 0000`, `0000`, and `Type: pbc 0000`, in all cases `miracle-sinkctl` did respond with  
```
Command not found
```

Can you please enlighten me how to type the pin into `miracle-sinkctl`?

Regards!

**Comment by albfan** [comment]
@dreirund is better to open your own issue, if you device ask for a PIN it should be shown somewhere in your device or in logs

**Comment by dreirund** [comment]
I don't really understand your comment.

You wrote earlier in this thread

> *You can type on the `miracle-sinkctl` when it prompts*

but when I tried it did not recognise it.

**Comment by albfan** [comment]
> but when I tried it did not recognise it.

it do now recognize what?

**Comment by albfan** [comment]
there's a prompt asking for that if you select display or keyboard

check help on miracle-sinkctl prompt:

	{ "connect",		"<peer> [provision] [pin]",		CLI_M,	CLI_LESS,	3,	cmd_connect,		"Connect to peer", {peers_generator, NULL} },

Default provider is auto but you can set:

pbc
display
pin

or just a number to start your connection with a defined pin
