### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in ../src/wifi/wifid-dbus.c:899)

### ISSUE THREAD

**Issue by yabb85** [albfan/miraclecast#289]
Hi,

I try to use miraclecast on fedora 28 with sytemd 238 and kernel 4.17.17.
I follow the build instruction and launch documentation.

After 
``
systemctl stop NetworkManager.service
``
``
systemctl stop wpa_supplicant.service 
``
and

``
sudo miracle-wifid &
``
The error is : ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in ../src/wifi/wifid-dbus.c:899)

with command
``
sudo miracle-wifid --log-level trace
``
the display is:
INFO: miracle-wifid - revision 1.0 Aug 25 2018 10:33:50
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in ../src/wifi/wifid-dbus.c:899)
DEBUG: exiting.. (main() in ../src/wifi/wifid.c:591)

**Comment by albfan** [comment]
Error 13 means permission denied

Install phase deploy a policy for dbus to allow miraclecast to access WiFi.

Did you install miraclecast? Maybe the path on fedora is different from the one miraclecast use

**Comment by yabb85** [comment]
Yes i have installed miraclecast in /usr/local/ (default path)
The syscondir=/etc
I find path /etc/dbus-1. Is it this repository?

**Comment by albfan** [comment]
Yes. Checking a random package that uses dbus (bolt) https://fedora.pkgs.org/28/fedora-x86_64/bolt-0.3-1.fc28.x86_64.rpm.html seems that path is correct, as it installs "/etc/dbus-1/system.d/org.freedesktop.bolt.conf" there.

You should find there this file https://github.com/albfan/miraclecast/blob/master/res/org.freedesktop.miracle.conf

Another option is that you already has another old I stance of miraclecast running so second one cannot claim that dbus name (check with `ps -ef | grep miracle` and kill it if so)

**Comment by yabb85** [comment]
Thanks you after reboot and check all file it works.
in tutorial the steps 3 is: Enable visibility for other devices
how to enable visiblity please?

**Comment by yabb85** [comment]
after use another miracast device i can connect to with "connect" command.
But it display an error:

[miraclectl] # ERROR: supplicant: HUP on dhcp-comm socket on p2p-wlp2s0-2 (supplicant_group_comm_fn() in ../src/wifi/wifid-supplicant.c:247)
[FAIL] Peer: 24:da:9b:d8:b4:51@2 Reason: unknow

**Comment by albfan** [comment]
miracle-wifictl is not still usable, see #172.

About miracle-sinkctl, provide logs as in https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support as seems something is ending your conection

The main problem is fixed. Please open new issues for new problems to help others to find responses to their problems.
