### ISSUE TITLE
Q: How to setup Miraclecast on the second WiFi NIC?

### ISSUE THREAD

**Issue by lucky62** [albfan/miraclecast#293]
Hello,
I was not able to run miraclecast on the Intel NIC.
So I have connected second WiFi NIC to the laptop (USB dongle, Realtek chip).
Network Manager is configured to ignore this second NIC (wlx801f0 unmanaged).

How can I run the Miraclecast with this second NIC?
It is possible to run Miraclecast and Network Manager + wpa_supplicant simultaneously?
```

$ nmcli dev status
DEVICE             TYPE      STATE         CONNECTION 
wlp4s0             wifi      connected     Auto dtx99 
enp0s31f6          ethernet  unavailable   --         
lo                 loopback  unmanaged     --         
wlx801f0           wifi      unmanaged     --  

```

**Comment by lucky62** [comment]
I can answer by myself:
Yes, it is possible to run simultaneously Miraclecast with Network Manager + wpa_supplicant when using second wifi NIC.

My Network Manager configuration (/etc/NetworkManager/NetworkManager.conf):
```
[main]
plugins=ifupdown,keyfile,ofono
dns=dnsmasq

[ifupdown]
managed=false

[keyfile]
unmanaged-devices=mac:80:1f:02:XX:XX:XX.
```
Then you need to run miracle-wifid with -i patrameter:

**miracle-wifid -i wlx801f0**

You don't need to stop Network Manager and wpa_supplicant so other network traffic is not affected (e.g. internet connection).

**Comment by albfan** [comment]
Great you find the answer. That works because they are different network cards. See #75 to support at same time with same network card

**Comment by albfan** [comment]
See there's a #75 ongoing. Thanks to recent merge of `--lazy-managed` option it is closer to be implemented

I will close this issue by now, open new ones for new problems
