### ISSUE TITLE
I think the problem is my wifi usb device.

### ISSUE THREAD

**Issue by hechengjie** [albfan/miraclecast#294]
So i try to connect the ubuntu to my android phone by p2p_connect, and get go neg fail.
My wifi usb device is rtl8192eu, so i use the rtl-wpa_supplicant which is modify by rtl.
Then the go neg is success, but i get CTRL-EVENT-EAP-FAILURE......
Maybe it is not a problem. This is my p2p-connect log.
[wpa_supplicant.log](https://github.com/albfan/miraclecast/files/2417787/wpa_supplicant.log)

_Originally posted by @hechengjie in https://github.com/albfan/miraclecast/issues/290#issuecomment-424562871_

**Comment by albfan** [comment]
You can reopen that issue
