### ISSUE TITLE
Raspberry Pi 3+ not booting with image

### ISSUE THREAD

**Issue by hex-m** [albfan/miraclecast#299]
The image you link on the [rpi3 wiki page](https://github.com/albfan/miraclecast/wiki/raspberry-pi-3) does not boot on the Raspberry Pi 3+. According to [this](https://raspberrypi.stackexchange.com/a/19356/27994) the image would have to be updated to support 3+.

Thank you for your effort!

**Comment by albfan** [comment]
Last time I tried it works, but other people have reported problems booting that image, 

See if their feedback help you on that:

https://github.com/albfan/miraclecast/issues?utf8=✓&q=is%3Aissue+boot

These days  raspbian is updated enough to run miraclecast, so you can try building it directly. See https://github.com/albfan/miraclecast/wiki/Building

If you still want to try provided image, send any feedback you can collect to see the problem. We can reopen this issue in that case

**Comment by CSEEEE** [comment]
I recently came across the same issue. 

Has there been a solution to this?
