### ISSUE TITLE
Isolate from systemd

### ISSUE THREAD

**Issue by albfan** [albfan/miraclecast#3]
In theory, there is no need for systemd on miraclecast. Just some compile (but not runtime) dependencies

That will allow to install in non systemd OS

**Comment by Susurrus** [comment]
This also prevents compilation on many distros unless you've rebuilt the kernel with kdbus and then rebuilt systemd with that support enabled. If this is possible it'd be great for no other reason than this.

**Comment by Likeyn** [comment]
:+1:, I'm a Gentoo + OpenRC user and the systemd requirement prevents me from using Miraclecast.

**Comment by thopiekar** [comment]
According to http://lists.freedesktop.org/archives/systemd-devel/2015-February/027742.html it looks like it is just needed as no network-managing service got a Wifi-Direct API.
Currently Connman seems to start supporting WifiDirect: http://git.kernel.org/cgit/network/connman/connman.git/tree/doc/wifi-p2p-overview.txt

**Comment by albfan** [comment]
I will give it a try 

http://git.kernel.org/cgit/network/connman/connman.git/tree/test/p2p-on-supplicant

Isolate this is a long wanted feature.

**Comment by thopiekar** [comment]
Great! Well rebuilding systemd for every Ubuntu release doesn't seem to be a good solution at the moment. Noticed that the source import and rebuild with kdbus enabled got broken, as they are working on Ubuntu wily (15.10) now.
However, I just wonder why Network-Manager still misses this feature while Wifi-Direct is a known technology (and working with wpa_supplicant) for many years.
Just think about that: Here a mailing list entry from 2010 and after 5 years still no progress http://osdir.com/ml/networkmanager-list/2010-08/msg00204.html :disappointed:

**Comment by albfan** [comment]
Sometimes you can see the forest for the trees

https://www.freedesktop.org/wiki/Software/miracle/libwfd/

Let's see what can be reused

**Comment by mosajjal** [comment]
if isolation from Systemd gets done, I can start working on creating a Docker container for Miraclecast.

**Comment by MichaelMackus** [comment]
:+1: 

Cool app, but systemd means 1 less user

**Comment by albfan** [comment]
I have systemd in my raspberry pi. Just curious, what linux flavour and version are you using?

**Comment by MichaelMackus** [comment]
Use Ubuntu at work, Arch at home. Planning on going full Gentoo soon since I've had enough of systemd on all my devices.

**Comment by perrin4869** [comment]
can't use on Slackware :(

**Comment by archenroot** [comment]
Is there anyone working on this openrc version? the referenced commit actually still put systemd as dependency in derekdai fork... I am also Gentoo OpenRC user :-)

**Comment by albfan** [comment]
I don't think so

**Comment by albfan** [comment]
I do have gentoo account. I add some useful info there

**Comment by albfan** [comment]
Option to build without systemd is merged

**Comment by nxdefiant** [comment]
Looks like systemd is still required: https://github.com/albfan/miraclecast/blob/master/CMakeLists.txt#L43

**Comment by albfan** [comment]
Can you provide a PR it was moved to https://github.com/albfan/miraclecast/blob/master/CMakeLists.txt#L19 so that line is unneeded

**Comment by TriMoon** [comment]
Although i can understand the apathy vs systemd like 5 years ago, but uhmmm...
Are there any serious distro's left that do NOT use systemd nowadays? :thinking:

**Comment by nxdefiant** [comment]
Slightly offtopic, but sure, eg. https://www.devuan.org/

**Comment by albfan** [comment]
@TriMoon, the purpose here is to allow embedded systems to run miraclecast if possible. Main goal was CentOS

**Comment by smartguy1196** [comment]
@TriMoon ChromeOS, ChromeOS Flex, Android

**Comment by smartguy1196** [comment]
Speaking of Chrome OS. I shouldn't have any issues trying to compile this for a system that uses Upstart, right? I'm considering adding utility to the Chromebrew project.

**Comment by smartguy1196** [comment]
FWIW, if anyone finds this later, I've started [porting miraclecast into Chrome OS via Chromebrew](https://github.com/chromebrew/chromebrew/issues/7892)

**Comment by smartguy1196** [comment]
Seem to have hit a hard stop on the port. miracle-wifid requires write access to /etc/dbus-1/system.d/org.freedesktop.miracle.conf in order to work. This directory is mounted as read only on Chrome OS, so without removing write protection, this isn't fully possible.

**Comment by albfan** [comment]
@smartguy1196 probably your comments are unrelated with this issue. Removing for clarity
