### ISSUE TITLE
Setting up miraclecast errors

### ISSUE THREAD

**Issue by tokerato** [albfan/miraclecast#300]
I've managed to set up miraclecast on Ubuntu 16.04 and im trying to get it to work on my LG.

So far - my LG is showing 'Miracle' on Wi-fi direct.

If I click on Miracle on my TV it asks that I accept the request on my laptop. I see output on the miracle daemon but no way of accepting.

If I initiate a connection request from miracle-wifictl - it pops up on my TV however on accepting I see a group formation failure:

> DEBUG: supplicant: no ifname in AP-STA-CONNECTED: <3>AP-STA-CONNECTED b2:e6:2a:73:a2:fc p2p_dev_addr=b4:e6:2a:73:a2:fc (supplicant_event_ap_sta_connected() in wifid-supplicant.c:1377)
> DEBUG: supplicant: dhcp-comm-p2p-wlp58s0-0: R:b2:e6:2a:73:a2:fc 192.168.50.100 (supplicant_group_comm_fn() in wifid-supplicant.c:254)
> DEBUG: supplicant: connect to b4:e6:2a:73:a2:fc via pbc/(null) (supplicant_peer_connect() in wifid-supplicant.c:739)
> TRACE: wpa: raw message: OK
> 
> TRACE: wpa: raw message: IFNAME=p2p-wlp58s0-0 <3>AP-STA-DISCONNECTED b2:e6:2a:73:a2:fc p2p_dev_addr=b4:e6:2a:73:a2:fc
> TRACE: wpa: raw message: <3>AP-STA-DISCONNECTED b2:e6:2a:73:a2:fc p2p_dev_addr=b4:e6:2a:73:a2:fc
> DEBUG: supplicant: unbind peer b4:e6:2a:73:a2:fc from its group (supplicant_event_ap_sta_disconnected() in wifid-supplicant.c:1421)
> TRACE: wpa: raw message: <3>P2P-GO-NEG-FAILURE status=-1
> TRACE: wpa: raw message: <3>P2P-GO-NEG-FAILURE status=-1
> DEBUG: supplicant: connect to b4:e6:2a:73:a2:fc via pbc/(null) (supplicant_peer_connect() in wifid-supplicant.c:739)
> TRACE: wpa: raw message: OK
> 
> TRACE: wpa: raw message: <3>P2P-GO-NEG-SUCCESS role=GO freq=2437 ht40=0 peer_dev=b4:e6:2a:73:a2:fc peer_iface=b2:e6:2a:73:a2:fc wps_method=PBC
> TRACE: wpa: raw message: <3>P2P-GO-NEG-SUCCESS role=GO freq=2437 ht40=0 peer_dev=b4:e6:2a:73:a2:fc peer_iface=b2:e6:2a:73:a2:fc wps_method=PBC
> TRACE: wpa: raw message: IFNAME=p2p-wlp58s0-2 <5>Failed to initialize driver interface
> TRACE: wpa: raw message: <3>P2P-GROUP-FORMATION-FAILURE

**Comment by albfan** [comment]
miracle-wifictl is not usable. See #4 to use miraclecast as source
