### ISSUE TITLE
Sink RTSP and UIBC files

### ISSUE THREAD

**Issue by peter102096** [albfan/miraclecast#302]
Hello,

I'm developing a Miracast Sink app.

now, wifi p2p is connection,next step I should build RTSP protocol(M1~M4)

I open the socket, and capture source send me 

OPTIONS * RTSP/1.0
CSeq: 1
Require: org.wfa.wfd1.0

What can I response, use which one file,and I should what I input, socket or port or address.

Thank you for being patient with me !

**Comment by albfan** [comment]
Read the spec in wiki or follow the code from this repo
