### ISSUE TITLE
Raspi 3 "archarm230716.gz" image restore on sd card failing

### ISSUE THREAD

**Issue by sibav** [albfan/miraclecast#308]
@albfan Thank you for your effort building this.

However, I am having bit of a trouble flashing the sd card with the raspi 3 image.

Steps I followed:

Start fdisk to partition the SD card:
fdisk /dev/sdb
At the fdisk prompt, delete old partitions and create a new one:
Type o. This will clear out any partitions on the drive.
Type p to list partitions. There should be no partitions left.
Type n, then p for primary, 1 for the first partition on the drive, press ENTER to accept the default first sector, then type +100M for the last sector.
Type t, then c to set the first partition to type W95 FAT32 (LBA).
Type n, then p for primary, 2 for the second partition on the drive, and then press ENTER twice to accept the default first and last sector.
Write the partition table and exit by typing w.
Create and mount the FAT filesystem:
mkfs.vfat /dev/sdb1
mkdir boot
mount /dev/sdb1 boot
Create and mount the ext4 filesystem:
mkfs.ext4 /dev/sdb2
mkdir root
mount /dev/sdb2 root
Downloaded image from here: https://drive.google.com/file/d/0B6La7AoEnzRBQy04S0ZBMXF2R28/view?usp=sharing&resourcekey=0-zkxna3WLVzrgJTaI_HHSOA

Run as root: gzip -dc ~/archarm230716.gz | dd bs=4M of=/dev/sdb2

After I run the dd, this is what I get:
0+122765 records in
0+122765 records out
794820680 bytes (7.9 GB, 7.4 GB) copied, 1527.36 s, 5.2 MB/s

And then I run: mv root/boot/* boot/

This is what I get and this is where I am stuck:
**mv: cannot stat 'root/boot/*': Structure needs cleaning**

I have tried doing this twice already with the same image and then a re-downloaded image, but get to the exact same point. What am I doing wrong??

**Comment by sibav** [comment]
@albfan, any thoughts?

**Comment by albfan** [comment]
Please follow wiki instructions https://github.com/albfan/miraclecast/wiki/raspberry-pi-3
