### ISSUE TITLE
Can not do mirroring

### ISSUE THREAD

**Issue by fmoyaarnao** [albfan/miraclecast#31]
Hi Alberto, 

I have all installed and running in a CentOS 7 machine.

I view my machine in my android device, but when I try to send my display, my device says "Connecting" but after a few seconds it disconnect and then show again my machine with miraclecast.

Miraclecast have logs? where is the log? What can I do to find what is wrong?
My wifi device has no IP when I run miraclecast, is that normal?
When I run "sudo ./miracle-sinkctl" and then "run 3" the binary ends, is that normal?

Thanks again.

**Comment by albfan** [comment]
systemd is changing constantly. Most errors comes from that. See 

b0f985069c1225c2df59b717855e44a8e0634e35

Check your systemd version. It's supposed to be >=219 on master (My fault not to change it, I have to look when systemd change that interface exactly)

you have `--log-level` (from 1 to 7) avaliable on all commands.

    $ miracle-sinkctl --log-level=7

https://github.com/albfan/miraclecast/blob/master/src/shared/shl_log.h#L25

Even more you can compile with

make CFLAGS=-g -O0

and depending on system, install systemd debug and linker symbols. It helps to see interaction between systemd and miraclecast. 

Don't know exactly procedure for CentOS, here is instructions for Arch Linux

https://aur.archlinux.org/packages/systemd-kdbus/
https://aur.archlinux.org/packages/sy/systemd-kdbus/PKGBUILD

Sometimes a simple 

    $ strace miracle-sinkctl

could be enough

**Comment by albfan** [comment]
Any progress here?
