### ISSUE TITLE
cannot connect to sink. No PIN displayed

### ISSUE THREAD

**Issue by Subburaj47** [albfan/miraclecast#310]
[miracle-wifid.log](https://github.com/albfan/miraclecast/files/2615518/miracle-wifid.log)
[miracle-sinkctl.log](https://github.com/albfan/miraclecast/files/2615519/miracle-sinkctl.log)

I'm using raspberry pi3 and have the installed the required dependency packages to run miraclecast. 
Here is the step I followed to get the casting (I didn't succeed though).
1) run miracle-wifid --log-level=7
2) run miracle-sinkctl
3) connect to **miracle** from the android mobile (casting source)
4) I don't see the PIN getting displayed, instead it gets timed out.

Prior to this, I ensured to disable **network.target**, there is no **wpa_supplicant**  running and brought down the wlan0 interface too. Also, I don't see the few CLI commands like connect, disconnect (although I see them in the code with the necessary call backs) in the **miraclectl** CLI interface.
Please help me to get the casting on raspb screen. 
Thanks in advance for your support 👍

**Comment by Subburaj47** [comment]
@albfan, Did you find a chance to look into this? Sorry If I'm being a bother here. I was spending so much time and quite curious to know what I'm missing.

**Comment by albfan** [comment]
Both devices seems to see each other. Sometimes you just need to run it a second time.

Anyway, I suppose that journal.log will tell us what's the problem, can you upload it?

**Comment by Subburaj47** [comment]
Thanks for the swift response. Please find the logs attached. I have zipped the **/var/log/messages** and **/var/log/syslog** along with the miracle-wifid/sinkctl logs.
[miraclecast_logs.zip](https://github.com/albfan/miraclecast/files/2619545/miraclecast_logs.zip)

**Comment by albfan** [comment]
Please follow instructions in https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support. `journalctl -f` should be enough

**Comment by Subburaj47** [comment]
@albfan Did you find a chance to look into this?

**Comment by albfan** [comment]
Everything seems ok

> Nov 24 08:45:39 raspberrypi miracle-wifid-wlan0-3[885]: P2P-GO-NEG-SUCCESS role=GO freq=2412 ht40=0 peer_dev=3a:e6:0a:b0:76:87 peer_iface=3a:e6:0a:b0:76:87 wps_method=PBC

But then a problem came up:

> Nov 24 08:45:39 raspberrypi miracle-wifid-wlan0-3[885]: Failed to create interface mon-wlan0-0: -95 (Operation not supported)

Anyway group is created

> Nov 24 08:45:46 raspberrypi miracle-wifid-wlan0-3[885]: P2P-GROUP-FORMATION-SUCCESS
> Nov 24 08:45:46 raspberrypi miracle-wifid-wlan0-3[885]: P2P-GROUP-STARTED p2p-wlan0-0 GO ssid="DIRECT-g3" freq=2412 go_dev_addr=72:c6:29:cf:52:3b

Try to use the option `--use-dev` for daemon

    $ sudo miracle-wifid --use-dev
 
There're some devices that stop to send interface name in some messages where miraclecast expect to get it. This command keeps the interface name from the first message with it.

**Comment by Subburaj47** [comment]
[miracle_cast_use_dev.tar.gz](https://github.com/albfan/miraclecast/files/2648376/miracle_cast_use_dev.tar.gz)
@albfan Please find the logs with **--use-dev** option. Unfortunately, I see the same behaviour and unable to succeed the connection to the app. Here is what I notice after the --use-dev option included.

> kernel: brcmfmac: brcmf_p2p_send_action_frame: Failed to send Action Frame(retry 1)
> miracle-wifid-wlan0-3[1154]: Failed to initialize wpa_supplicant
> p2p-wlan0-1: Failed to initialize driver interface
> miracle-wifid-wlan0-3[1176]: Failed to initialize wpa_supplicant

I happened to go through [this](https://github.com/albfan/miraclecast/issues/153) issue where you have suggested to use the same flag (mentioned above). But it is not helping me though. 
Please help me to resolve this issue.

**Comment by Subburaj47** [comment]
@albfan Thanks a lot. I could cast my mobile to the screen. After a couple of attempts, **--use-dev** worked.

**Comment by albfan** [comment]
Nice. There some cases when WiFi direct handshaking goes in a different way than miraclecast expect, that's why it is not 100% reliable. We have some unhandled messages (you can see them on log for miracle-wifid).

Turn `--use-dev` as default is becoming mandatory, thanks for the feedback.

Please close this issue. You can open different ones for further questions

**Comment by Subburaj47** [comment]
Sure. Thanks for the support.
