### ISSUE TITLE
timeout for sinkctl

### ISSUE THREAD

**Issue by amakropoulos** [albfan/miraclecast#313]
Hi there,
I'm trying to use miraclecast to connect and cast the screen of my mobile to the screen of my laptop (sink).

I'm doing the following:
```
systemctl stop wpa_supplicant.service
systemctl stop NetworkManager.service
sudo miracle-wifid --log-level 7
```
and on another shell 
```
sudo miracle-sinkctl --log-level 7
[miraclectl] # run 2
```
Finally I try to connect my mobile to the created 'screen' but the connection gives a timeout after a while.

<details>
<summary>The miracle-sinkctl output is:</summary>
[ADD] Link: 2<br>
[miraclectl] # run 2<br>
now running on link 2<br>
[ADD] Peer: 36:8b:75:07:00:71@2<br>
[PROV] Peer: 36:8b:75:07:00:71@2 Type: pbc PIN: <br>
[PROV] Peer: 36:8b:75:07:00:71@2 Type: pbc PIN: <br>
[GO NEG] Peer: 36:8b:75:07:00:71@2 Type: pbc PIN: <br>
[GO NEG] Peer: 36:8b:75:07:00:71@2 Type: pbc PIN: <br>
[TIMEOUT] waiting for Pixel V2+
</details>
<br>
<details>
<summary>and the miracle-wifid is:</summary>
INFO: miracle-wifid - revision 1.0 Dec 11 2018 12:33:31<br>
DEBUG: friendly-name from local hostname: thinksono (manager_read_name() in /home/benuix/codes/miraclecast/src/wifi/wifid.c:388)<br>
DEBUG: link: new link: wlp2s0 (2) (link_new() in /home/benuix/codes/miraclecast/src/wifi/wifid-link.c:71)<br>
DEBUG: supplicant: new supplicant for wlp2s0 (supplicant_new() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:2103)<br>
INFO: link: add link: wlp2s0<br>
INFO: link: manage link wlp2s0<br>
DEBUG: supplicant: start supplicant of wlp2s0 (supplicant_start() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:2628)<br>
DEBUG: supplicant: spawn supplicant of wlp2s0 (supplicant_spawn() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:2478)<br>
INFO: supplicant: wpa_supplicant found: /sbin/wpa_supplicant<br>
INFO: supplicant: wpas spawned as pid:4977<br>
DEBUG: supplicant: open supplicant of wlp2s0 (supplicant_open() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:2269)<br>
DEBUG: supplicant: local p2p-address is: 9c:b6:d0:f1:35:af (supplicant_status_fn() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:1823)<br>
DEBUG: supplicant: send 'WFD_SUBELEM_SET 0 000600111c4400c8' to wpas on wlp2s0 (supplicant_set_wfd_subelements() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:1991)<br>
DEBUG: supplicant: sent P2P_FIND to wpas on wlp2s0 (supplicant_p2p_start_scan() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:2036)<br>
DEBUG: supplicant: p2p-scanning now active on wlp2s0 (supplicant_p2p_find_fn() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:1917)<br>
DEBUG: peer: new peer: 36:8b:75:07:00:71 @ wlp2s0 (peer_new() in /home/benuix/codes/miraclecast/src/wifi/wifid-peer.c:52)<br>
INFO: peer: add peer: 36:8b:75:07:00:71<br>
DEBUG: peer: peer 36:8b:75:07:00:71 @ wlp2s0 started (peer_supplicant_started() in /home/benuix/codes/miraclecast/src/wifi/wifid-peer.c:162)<br>
DEBUG: supplicant: requesting data for new peer 36:8b:75:07:00:71 (supplicant_event_p2p_device_found() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:962)<br>
DEBUG: supplicant: GO Negotiation Request from 36:8b:75:07:00:71 (supplicant_event_p2p_go_neg_request() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:1065)<br>
DEBUG: supplicant: GO Negotiation Request from 36:8b:75:07:00:71 (supplicant_event_p2p_go_neg_request() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:1065)<br>
DEBUG: supplicant: connect to 36:8b:75:07:00:71 via pbc/(null) (supplicant_peer_connect() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:739)<br>
DEBUG: supplicant: connect to 36:8b:75:07:00:71 via pbc/(null) (supplicant_peer_connect() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:739)<br>
DEBUG: supplicant: p2p-scanning stopped on wlp2s0 (supplicant_event_p2p_find_stopped() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:904)<br>
DEBUG: supplicant: sent P2P_FIND to wpas on wlp2s0 (supplicant_p2p_start_scan() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:2036)<br>
DEBUG: supplicant: p2p-scanning now active on wlp2s0 (supplicant_p2p_find_fn() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:1917)<br>
DEBUG: supplicant: requesting data for new peer 36:8b:75:07:00:71 (supplicant_event_p2p_device_found() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:962)</details>

<br>
What I am doing wrong?
<br>
Thank you!

**Comment by amakropoulos** [comment]
Also I tried with:
````
sudo miracle-wifid --log-level 8 --config-methods display
````
and 
```
sudo miracle-sinkctl --log-level 7
[ADD] Link: 2
[miraclectl] # set-managed 2 yes
[miraclectl] # run 2
```
<details>
<summary>The miracle-sinkctl output is:</summary>
now running on link 2<br>
[ADD] Peer: 36:8b:75:07:00:71@2<br>
[PROV] Peer: 36:8b:75:07:00:71@2 Type: display PIN: 50701933<br>
[PROV] Peer: 36:8b:75:07:00:71@2 Type: display PIN: 31703727<br>
[GO NEG] Peer: 36:8b:75:07:00:71@2 Type: display PIN: 31703727<br>
[GO NEG] Peer: 36:8b:75:07:00:71@2 Type: display PIN: 31703727<br>
[TIMEOUT] waiting for Pixel V2+
</details>
<br>
<details>
<summary>and the relevant part of miracle-wifid is:</summary>
TRACE: wpa: raw message: IFNAME=p2p-dev-wlp2s0 <3>CTRL-EVENT-SCAN-STARTED <br>
TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED <br>
TRACE: wpa: raw message: <3>P2P-GO-NEG-REQUEST 36:8b:75:07:00:71 dev_passwd_id=1 go_intent=0<br>
TRACE: wpa: raw message: <3>P2P-GO-NEG-REQUEST 36:8b:75:07:00:71 dev_passwd_id=1 go_intent=0<br>
DEBUG: supplicant: GO Negotiation Request from 36:8b:75:07:00:71 (supplicant_event_p2p_go_neg_request() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:1065)<br>
TRACE: wpa: raw message: <3>P2P-GO-NEG-REQUEST 36:8b:75:07:00:71 dev_passwd_id=1 go_intent=0<br>
TRACE: wpa: raw message: <3>P2P-GO-NEG-REQUEST 36:8b:75:07:00:71 dev_passwd_id=1 go_intent=0<br>
DEBUG: supplicant: GO Negotiation Request from 36:8b:75:07:00:71 (supplicant_event_p2p_go_neg_request() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:1065)<br>
DEBUG: supplicant: connect to 36:8b:75:07:00:71 via display/31703727 (supplicant_peer_connect() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:739)<br>
DEBUG: supplicant: connect to 36:8b:75:07:00:71 via display/31703727 (supplicant_peer_connect() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:739)<br>
TRACE: wpa: raw message: <3>P2P-FIND-STOPPED <br>
TRACE: wpa: raw message: OK<br>
<br>
TRACE: wpa: raw message: <3>P2P-FIND-STOPPED <br>
DEBUG: supplicant: p2p-scanning stopped on wlp2s0 (supplicant_event_p2p_find_stopped() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:904)<br>
TRACE: wpa: raw message: OK<br>
<br>
DEBUG: supplicant: sent P2P_FIND to wpas on wlp2s0 (supplicant_p2p_start_scan() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:2036)<br>
TRACE: wpa: raw message: OK<br>
<br>
DEBUG: supplicant: p2p-scanning now active on wlp2s0 (supplicant_p2p_find_fn() in /home/benuix/codes/miraclecast/src/wifi/wifid-supplicant.c:1917)<br>
TRACE: wpa: raw message: IFNAME=p2p-dev-wlp2s0 <3>CTRL-EVENT-SCAN-STARTED <br>
TRACE: wpa: raw message: <3>CTRL-EVENT-SCAN-STARTED <br>
</details>
<br>
any ideas :)?

**Comment by albfan** [comment]
try adding `--use-dev` to miracle-wifid there're some wpa messages that fools the daemon

**Comment by amakropoulos** [comment]
That's awesome thanks a lot!
It is connecting now and can view the mobile screen with VLC.
However there is a delay of about 4 secs.
Is there any way to display the stream real-time?
Thanks again for your time :)!

**Comment by albfan** [comment]
that's just a matter for the underneath streaming protocol. Not much we can do. There will be always a lag.

I take your feedback to make --use-dev default (will do no harm on devices that do work without it)

Please close this if your issue is solved

**Comment by amakropoulos** [comment]
thanks, yes --use-dev solves the issue!
