### ISSUE TITLE
about UIBC for windows

### ISSUE THREAD

**Issue by peter102096** [albfan/miraclecast#316]
hello,

I watch issues and I know windows need HIDC.

But it seem to not implement HIDC now?

or I miss some issues?

Now I need implement HIDC, Is there any direction?

Thanks a lot.

**Comment by runtucha** [comment]
> hello,
> 
> I watch issues and I know windows need HIDC.
> 
> But it seem to not implement HIDC now?
> 
> or I miss some issues?
> 
> Now I need implement HIDC, Is there any direction?
> 
> Thanks a lot.

Hi peter

Have you implemented UIBC(HIDC) for windows OS?
There're some issue when I send mouse event. Could you please help provide more guidance to me?
Looking forward to your reply.

Thanks a lot.

**Comment by albfan** [comment]
Microsoft extends miracast protocol, so you need more info at some points. There's a PR with that here: #136. About HIDC there's another PR here #154 

All need review to be merge but you can start there

**Comment by peter102096** [comment]
> > hello,
> > I watch issues and I know windows need HIDC.
> > But it seem to not implement HIDC now?
> > or I miss some issues?
> > Now I need implement HIDC, Is there any direction?
> > Thanks a lot.
> 
> Hi peter
> 
> Have you implemented UIBC(HIDC) for windows OS?
> There're some issue when I send mouse event. Could you please help provide more guidance to me?
> Looking forward to your reply.
> 
> Thanks a lot.

Hi Runtucha,

I use UIBC to develop Android App for Smart TV,

And it has Control port (use UIBC comment control).
 
So we need to find UIBC spec.(All event what need value), 

And connect the control port.

And send event need value.

It will be fun when you look it success work.

Hope this experience helps you.

Peter,
Best regards.

**Comment by runtucha** [comment]
@peter102096 
I‘m a developer of Android App for Smart TV, too.
And we have implemented the uibc between Android TV and Android phone，also the keyboard event between Android TV and windows 10. But the mouse event doesn’t work.
Are you Chinese？Maybe we could do in-depth communication.
My E-mail : 532179548@qq.com

Thanks a lot.

**Comment by albfan** [comment]
You're misusing this issue tracker as a forum
