### ISSUE TITLE
Unable to connect a Samsung phone to miracle-cast sink

### ISSUE THREAD

**Issue by Subburaj47** [albfan/miraclecast#318]
[logs.zip](https://github.com/albfan/miraclecast/files/2793335/logs.zip)

I'm using raspberry pi3 and have the installed the required dependency packages to run miraclecast.
Here is the step I followed to get the casting (I didn't succeed though).

```
run miracle-wifid --log-level trace --use-dev
run miracle-sinkctl
```

connect to miracle from the Samsung note 9/ Samsung galaxy (casting source)
I don't see the PIN getting displayed, instead it gets timed out. 
But I'm able to connect to miraclecast-sink with XIAOMI MI android phone. It was perfectly casting. 

Please let me know if you need any more logs than this.
Thanks in advance for your support 👍

**Comment by albfan** [comment]
> miracle-wifid-wlan0-3[31553]: P2P-GO-NEG-REQUEST 6e:c7:ec:12:65:d5 dev_passwd_id=4

It tries 3 times to create a p2p group. Sometimes it takes several times to connect. I think is related with devices storing mac address and doing the connection by some different method or similar.

Can tell you what's the problem. If you have a rooted phone you can dump the connection on the phone side and see what is happening.

**Comment by Subburaj47** [comment]
Several times due to persisting the MAC? you mean in the mobile side or the miraclecast stack persists the MAC? During the device capability exchange, I happen to notice that the config methods(pin, pbc etc.,) supported by the Samsung phone are the same as that of the working case ( XIAOMI MI phone). Please let me know if there is a way to identify the method you are pointing here and would that be possible to enforce only a single method to create a connectivity?
Unfortunately the phone isn't rooted and I don't have logs of the phone side.

**Comment by Subburaj47** [comment]
@albfan Did you find a chance to check this? 
I have another query. Is it mandatory for a peer to have wfd_subelements to get connected?

**Comment by albfan** [comment]
I have no more clues about this.

You can read about the spec in wiki https://github.com/albfan/miraclecast/wiki/Miracast#specifications

> 5.1.2 WFD Device Information Subelement
The WFD Device Information subelement is used to signal information required by a peer WFD Device during discovery to
facilitate a decision as to whether to attempt pairing with the peer WFD Device and creating a WFD Session

**Comment by albfan** [comment]
I suggest to try again from master, there's a fix about wfd_video_formats on master. Closing by now
