### ISSUE TITLE
W10 to Raspbian stretch fails - ERROR: supplicant: HUP

### ISSUE THREAD

**Issue by Vegz78** [albfan/miraclecast#325]
Hi @albfan,

Have trouble getting Miracast working on a Raspberry Pi 3 with Raspbian stretch and connecting from W10.

I get the sink running on the RPi ok and it's discoverable on W10. But when I try to connect, it crashes on the RPi with error message "ERROR: supplicant: HUP on supplicant socket of wlan0" after it has added my W10 peer, and then removes the peer.

I've compiled, installed and tried both the main branch and the wip/windows-fix, as you referred to in #136 and #275. With 2 different recently updated W10 PC and on 2 RPi's, both on Raspbian stretch, one recently updated, one older distro.

Hope for some help and explaination, since this project is really of great utility for me! I'll be happy to donate a small sum if/when I get it working.

Br,

Vegard

**Comment by albfan** [comment]
Can you collect logs as wiki FAQ indicates?

Review that should be first step

**Comment by Vegz78** [comment]
Hi albfan,

Thanks for your reply and sorry for my late reply. I found another app that solved my initial need and didn't and haven't got any time to dig deeper into this, I'm afraid.

Keep up the good work!

Vegard
