### ISSUE TITLE
Problem with build using cmake

### ISSUE THREAD

**Issue by jbrepogmailcom** [albfan/miraclecast#329]
When using command as instructed:

cmake -DCMAKE_INSTALL_PREFIX=/usr ..

I get error

CMake Error: The source directory "/home/janbenes" does not appear to contain CMakeLists.txt.

Please provide more detailed instructions.

**Comment by albfan** [comment]
Thanks for trying miraclecast, I guess your problems come from basic knowledge of git and cmake, am I right?

I doubt you cloned miraclecast on your home directory

This steps should work:

```
git clone https://github.com/albfan/miraclecast
cd miraclecast
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make
sudo make install
```

You should read git tutorials or cmake tutorials, but that's unrelated with miraclecast

**Comment by jbrepogmailcom** [comment]
Thank you very much. When running cmake I got:

-- Checking for module 'glib-2.0'
--   No package 'glib-2.0' found
CMake Error at /usr/share/cmake-3.12/Modules/FindPkgConfig.cmake:436 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.12/Modules/FindPkgConfig.cmake:602 (_pkg_check_modules_internal)
  CMakeLists.txt:27 (pkg_check_modules)

I installed 
sudo apt-get install pkg-config
sudo apt-get install glib-2.0

But still getting the error (Ubuntu 18.10)

**Comment by albfan** [comment]
Now you just need to read about development in ubuntu :wink:. They split their packages into bin, debug and develop:

See FAQ: https://github.com/albfan/miraclecast/wiki/FAQ#ubuntu-requirements

**Comment by jbrepogmailcom** [comment]
Hello, I started to install recommended packages but I get following error in Ubuntu 18.10:

sudo apt-get install ubuntu-restricted-extras gstreamer1.0 libglib2.0-dev libreadline-dev libudev-dev libsystemd-dev libusb-dev build-essential

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gstreamer1.0-python3-dbg-plugin-loader : Conflicts: gstreamer1.0-python3-plugin-loader but 1.14.4-1 is to be installed
 gstreamer1.0-python3-plugin-loader : Conflicts: gstreamer1.0-python3-dbg-plugin-loader but 1.14.4-1 is to be installed

I believe Ubuntu 18.10 is stable so it should work, right?

**Comment by Ryu945** [comment]
I tried 

git clone https://github.com/albfan/miraclecast
```
cd miraclecast
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make
sudo make install
```


The line:
`cmake -DCMAKE_INSTALL_PREFIX=/usr ..`

puts the following in my error log

```
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags:  

The output was:
No such file or directory
```

**Comment by albfan** [comment]
I guess you need gcc. Maybe package build-essential on ubuntu
