### ISSUE TITLE
different number for interface on miracle-sinkctl

### ISSUE THREAD

**Issue by 275288698** [albfan/miraclecast#33]
I get to the step 4 of the usage guide:

4. launch sink control (your network card will be detected. here 3)

         $ sudo miracle-sinkctl
         [ADD]  Link: 3

however, my result is 

    $ sudo miracle-sinkctl
    [ADD]  Link: 7

is there something wrong ? what this num meaning?

**Comment by albfan** [comment]
label for interface depends on systemd.

Here is the code trace about it:

https://github.com/albfan/miraclecast/blob/b0f985069c1225c2df59b717855e44a8e0634e35/src/ctl/ctl-wifi.c#L827
https://github.com/albfan/miraclecast/blob/b0f985069c1225c2df59b717855e44a8e0634e35/src/ctl/ctl-wifi.c#L700
https://github.com/albfan/miraclecast/blob/b0f985069c1225c2df59b717855e44a8e0634e35/src/ctl/ctl-wifi.c#L383

**Comment by albfan** [comment]
Is this issue fixed? Can I close it. I would prefer you to close it
