### ISSUE TITLE
Cannot connect to Epson EH-TW5650

### ISSUE THREAD

**Issue by maciejmrozinski** [albfan/miraclecast#330]
Hi,

I'm trying to connect to projector as a peer. I installed Miraclecast using this PPA: https://launchpad.net/~thopiekar/+archive/ubuntu/miraclecast

Projector is easily connectable from other Windows 10 machine (default Windows connect remote display feature, no installations needed). When I'm trying to connect to projector from my Ubuntu 18.04 machine it's connecting and then it disconnects before connecting process finishes.

**Comment by maciejmrozinski** [comment]
Also tried branch `derekdai-master-squashed` with `miracle-dispctl -i wlp3s0 -p 9e:ae:d3:43:28:d2@3` command and only getting error: `miracle-dispctl: failed to cast to wireless display: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Invalid argument`

**Comment by albfan** [comment]
master here do not work as miracast source. That branch derekdai-master-squashed is for work as source, but didn't work for me too.

Take a look to https://github.com/benzea/gnome-screencast, maybe fet your needs

**Comment by maciejmrozinski** [comment]
Thanks for tip, will try to check that today.
