### ISSUE TITLE
p2p advertisement issue in rtl8812au driver

### ISSUE THREAD

**Issue by visbs** [albfan/miraclecast#333]
Hi, I am using realtek rtl8812au chip-set and i am not able to use miracle-cast as it is not advertising. When i use the same in Intel wireless chip-set drivers its working fine. Have u ever tested miracle-cast on realtek drivers !
Any other way to advertise my device using wpa_supplicant.

**Comment by albfan** [comment]
See our faq: https://github.com/albfan/miraclecast/wiki/FAQ#Does-my-hardware-supports-miraclecast-requirements

This are the (non up to date) list of supported devices:
https://github.com/albfan/miraclecast/wiki/Known-working-devices

You can always upload the logs to get support:
https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support
