### ISSUE TITLE
Windows  Cmake  No package 'glib-2.0' found

### ISSUE THREAD

**Issue by farmercz** [albfan/miraclecast#334]
D:\AndroidStudioProjects\miraclecast\build>cmake -DCMAKE_INSTALL_PREFIX=/usr ..
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.16299.
-- Checking for module 'glib-2.0'
--   No package 'glib-2.0' found
CMake Error at E:/cmake-3.14.2-win64-x64/share/cmake-3.14/Modules/FindPkgConfig.cmake:457 (message):
  A required package was not found
Call Stack (most recent call first):
  E:/cmake-3.14.2-win64-x64/share/cmake-3.14/Modules/FindPkgConfig.cmake:642 (_pkg_check_modules_internal)
  CMakeLists.txt:27 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "D:/AndroidStudioProjects/miraclecast/build/CMakeFiles/CMakeOutput.log".

**Comment by albfan** [comment]
https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md#bugs
