### ISSUE TITLE
Build Errors Raspberry Pi B+

### ISSUE THREAD

**Issue by oytunistrator** [albfan/miraclecast#338]
master build:
```
....
ctl-cli.c:(.text+0xaf0): undefined reference to `rl_on_new_line'
ctl-cli.c:(.text+0xaf4): undefined reference to `rl_redisplay'
ctl-cli.c:(.text+0xafc): undefined reference to `rl_message'
ctl-cli.c:(.text+0xb00): undefined reference to `rl_callback_handler_remove'
CMakeFiles/miracle-wifictl.dir/ctl-cli.c.o: In function `cli_init':
ctl-cli.c:(.text+0xedc): undefined reference to `rl_callback_handler_install'
ctl-cli.c:(.text+0xee4): undefined reference to `rl_set_prompt'
ctl-cli.c:(.text+0xef0): undefined reference to `rl_on_new_line'
ctl-cli.c:(.text+0xef4): undefined reference to `rl_redisplay'
ctl-cli.c:(.text+0xf78): undefined reference to `rl_erase_empty_line'
collect2: error: ld returned 1 exit status
src/ctl/CMakeFiles/miracle-wifictl.dir/build.make:147: recipe for target 'src/ctl/miracle-wifictl' failed
make[2]: *** [src/ctl/miracle-wifictl] Error 1
CMakeFiles/Makefile2:321: recipe for target 'src/ctl/CMakeFiles/miracle-wifictl.dir/all' failed
make[1]: *** [src/ctl/CMakeFiles/miracle-wifictl.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
...

```

v1.0 build:

```
...
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcheck_pic.a(check_pack.o): undefined reference to symbol '__pthread_register_cancel@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_rtsp.dir/build.make:95: recipe for target 'test/test_rtsp'
failed
make[2]: *** [test/test_rtsp] Error 1
CMakeFiles/Makefile2:468: recipe for target 'test/CMakeFiles/test_rtsp.dir/all'
failed
make[1]: *** [test/CMakeFiles/test_rtsp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
...
```

Raspbian version;

```
pi@raspberrypi:~/miraclecast/build$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
```

Device: Raspberry Pi B+

And also depends doesnt exist in documentation. Maybe i write blog post about this for new users.

Debian install;

```
cd miraclecast/
sudo apt install pkg-config build-essentials ninja cmake automake autoconf libreadline-dev libsystemd-dev glib2.0 libudev-dev -y
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr .. 
make
make install
```

I cant make install. Help please.

**Comment by albfan** [comment]
There's a FAQ with info for ubuntu like distros, but in general there's no simple answer for "install dependencies". First error is for readline dep, which on ubuntu is libreadline-dev, but on fedora is readline-devel and on arch linux is readline. So those details depends on your distro and you have to figure out them. Maybe readline on raspbian is too old or new, you need to check those undefined symbols to understand why they are not there.

Not sure about v1.0 build, ¿why you tried to build it? it is from 2016, since then systemd has changed a lot, so you're not supposed to be able to build on up-to-date distros.

Remember to remove CMakeCache.txt after install new deps (that is related with using cmake, see you can use autotools or meson too as buildsystems)

**Comment by oytunistrator** [comment]
Thanks for help. I tested master from git. And also downloaded 1.0 release. I cant compile with make. Giving same errors.

**Comment by albfan** [comment]
Provide your version for readline, to check if that version has those symbols, and how to solve the problem. There's FAQ to build on cmake, meson and autotools.

**Comment by oytunistrator** [comment]
I rebuild again new SD card. Problem fixed. I think problem is SD card. Because not write success.

**Comment by albfan** [comment]
Glad to hear!
