### ISSUE TITLE
WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in /home/user/workdir/miraclecast/src/wifi/wifid-supplicant.c:1708)

### ISSUE THREAD

**Issue by AVCHD** [albfan/miraclecast#339]
I have read the issue https://github.com/albfan/miraclecast/issues/285
and follow the steps:

1、sudo systemctl start NetworkManager
2、sudo systemctl start wpa_supplicant
3、sudo kill -9 $(ps -ef | grep wpa_supplican[t] | awk '{print $2}')
4、./res/kill-wpa.sh
5、./test-hardware-capabilities.sh
wlan0 supports P2P

make sure that wpa_supplicant and NetworkManager has been killed

```
user@user:/usr/local/bin$ sudo miracle-wifid --log-level trace --wpa-loglevel 8 |& tee wifid.log
INFO: miracle-wifid - revision 1.0 Jun 29 2019 16:36:48
DEBUG: friendly-name from local hostname: user (manager_read_name() in /home/user/workdir/miraclecast/src/wifi/wifid.c:376)
DEBUG: link: new link: wlp0s20f3 (2) (link_new() in /home/user/workdir/miraclecast/src/wifi/wifid-link.c:72)
DEBUG: supplicant: new supplicant for wlp0s20f3 (supplicant_new() in /home/user/workdir/miraclecast/src/wifi/wifid-supplicant.c:2122)
INFO: link: add link: wlp0s20f3
DEBUG: supplicant: start supplicant of wlp0s20f3 (supplicant_start() in /home/user/workdir/miraclecast/src/wifi/wifid-supplicant.c:2648)
DEBUG: supplicant: spawn supplicant of wlp0s20f3 (supplicant_spawn() in /home/user/workdir/miraclecast/src/wifi/wifid-supplicant.c:2497)
INFO: supplicant: wpa_supplicant found: /sbin/wpa_supplicant
INFO: supplicant: wpas spawned as pid:3157
INFO: link: acquiring link ownership wlp0s20f3
DEBUG: supplicant: open supplicant of wlp0s20f3 (supplicant_open() in /home/user/workdir/miraclecast/src/wifi/wifid-supplicant.c:2288)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: wifi_display=1
ifname=wlp0s20f3
address=38:de:ad:89:03:5a

WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in /home/user/workdir/miraclecast/src/wifi/wifid-supplicant.c:1708)
```

**Comment by visbs** [comment]
Check the output of  cmd : iw list .
If it contains something like,
```
* P2P-client: 0x40 0xd0
* P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
 * P2P-device: 0x40 0xd0
````

**Comment by albfan** [comment]
The important thing is what is in the wpa messages:

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L1698

All wpa_supplicant messages will output on systemd journal so:

    sudo journalctl -f |& tee journal.log

is the needed log to see what's the problem. In general all the logs pointed out in https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support are interesting

**Comment by afirth** [comment]
fix from #285 fixes this for me
```
sudo iw dev wlp0s20f3 del
sudo iw phy0 interface add wifi type managed
```

**Comment by ohkeenan** [comment]
I had this same issue with the wifi radio being turned off. Make sure it is enabled to avoid my mistake in case you're running on a desktop with eth and wifi like me.

miracle-wifid output the following when starting sink:

    ➜ sudo miracle-wifid -i wlp5s0
    WARNING: supplicant: P2P_FIND failed (supplicant_p2p_find_fn() in wifid-supplicant.c:1912)

`journalctl -f` showed the following:

    Jan 17 22:43:18 mylinuxpc miracle-wifid-wifi-24[892211]: p2p-dev-wifi: Reject P2P_FIND since interface is disabled

Which was verified by:

    ➜ nmcli radio     
    WIFI-HW  WIFI      WWAN-HW  WWAN    
    enabled  disabled  enabled  enabled

solved by running `nmcli radio wifi on`

**Comment by albfan** [comment]
Closing as no log for support is provided
