### ISSUE TITLE
[Question]  Setup problems on Ubuntu

### ISSUE THREAD

**Issue by Ryu945** [albfan/miraclecast#341]
I added to this closed down issue as it sums up the conversation well.

https://github.com/albfan/miraclecast/issues/329

My post is on the bottom.

edit: I saw another post about using the ubuntu/mint repository and it said does not work as source.  Does it work as source now?

https://github.com/albfan/miraclecast/issues/272

**Comment by albfan** [comment]
No. You can use gnome-screencast for that
