### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by viniciusov** [albfan/miraclecast#342]
How can I uninstall it? Is it possible to add some uninstall/remove notes on Readme?

I want to test it but I also want to be able to fully uninstall it if necessary, but I don't know how.

**Comment by albfan** [comment]
meson provide an uninstall step

https://mesonbuild.com/Release-notes-for-0-38-0.html

other buildsystem do not provide that step, so your only option is to use a package manager.

https://aur.archlinux.org/packages/miraclecast-git/

yaourt -S miraclecast-git
pacman -R miraclecast-git

will work, but only for arch Linux. for other distros you need other packages.

you can package using DESTDIR to see all the files generated and remove manually.

**Comment by viniciusov** [comment]
I'm using Linux Mint here (apt).

Is there a way to remove these files with a command like this?
`sudo find / -name "miracle" -type d,f -delete`

**Comment by albfan** [comment]
Of course you can do an script to uninstall, but that's just reinvent the wheel ( why you want to do that?).

Document how a buildsystem provides an uninstall step is neither a miraclecast duty.

**Comment by viniciusov** [comment]
Thanks @albfan , I didn't know it is possible to uninstall directly from the buildsystem.

In my case, I succesfully unistalled (except some files inside */proc/*) with the command:
`sudo make uninstall`
