### ISSUE TITLE
p2p-dev-wlan0 interface went down afer P2P-GROUP-STARTED

### ISSUE THREAD

**Issue by Subburaj47** [albfan/miraclecast#343]
I executed the miraclecast stack in my device and happened to notice that the p2p-dev-wlan0 interface goes down after the group formation is successful (in fact, the group also started). I tried to capture the packets in that interface. Very rarely (only twice until now), I was able to have the RTSP packets in the packet capture. 
There is a **NL80211_CMD_DEL_STATION** received at the driver level, which takes down the interface (p2p-dev-wlan0). Based on the logs, it seems to be an event originated from GO (peer device). Could you please let me know your view on this? Should there be any configuration tweak in the wpa_supplicant for such devices?

> 2019 Jul 23 16:08:28.686203: nl80211: Drv Event 20 (NL80211_CMD_DEL_STATION) received for p2p-wlan0-3
> 2019 Jul 23 16:08:28.686282: nl80211: Delete station 6e:c7:ec:12:e5:d5
> 2019 Jul 23 16:08:28.692127: nl80211: Drv Event 39 (NL80211_CMD_DEAUTHENTICATE) received for p2p-wlan0-3
> 2019 Jul 23 16:08:28.692179: nl80211: Deauthenticate event
> 2019 Jul 23 16:08:28.692196: p2p-wlan0-3: Event DEAUTH (11) received
> 2019 Jul 23 16:08:28.692217: p2p-wlan0-3: Deauthentication notification
> 2019 Jul 23 16:08:28.692231: p2p-wlan0-3:  * reason 3
> 2019 Jul 23 16:08:28.692248: p2p-wlan0-3:  * address 6e:c7:ec:12:e5:d5
> 2019 Jul 23 16:08:28.692259: Deauthentication frame IE(s) - hexdump(len=0): [NULL]
> 2019 Jul 23 16:08:28.692276: p2p-wlan0-3: CTRL-EVENT-DISCONNECTED bssid=6e:c7:ec:12:e5:d5 reason=3
> 2019 Jul 23 16:08:28.692308: P2P: GO indicated that the P2P Group session is ending

**Comment by albfan** [comment]
Try running the daemon `miracle-wifid` with `--use-dev` wpa_supplicant omit the device after some messages and miraclecast relay on it to continue the process. That option store the device name if some message omit it.

**Comment by Subburaj47** [comment]
I tried to use the --use-dev option. But I still see the same behaviour. Here's the log for that execution. Could you please let me know if there is anything weird going on?
A quick sequence of what's happening.

> P2P-DEVICE-FOUND 6e:c7:ec:12:65:d5 p2p_dev_addr=6e:c7:ec:12:65:d5 pri_dev_type=10-0050F204-5 name='[Phone] Raja's' config_methods=0x188 dev_capab=0x25 group_capab=0x0 wfd_dev_info=0x01101c440032 vendor_elems=1 new=1
>P2P-PROV-DISC-PBC-REQ 6e:c7:ec:12:65:d5 p2p_dev_addr=6e:c7:ec:12:65:d5 pri_dev_type=10-0050F204-5 name='[Phone] Raja's' config_methods=0x188 dev_capab=0x25 group_capab=0x0
>P2P-GO-NEG-REQUEST 6e:c7:ec:12:65:d5 dev_passwd_id=4 go_intent=13
>P2P-FIND-STOPPED 
>P2P-GO-NEG-SUCCESS role=client freq=2437 ht40=0 peer_dev=6e:c7:ec:12:65:d5 peer_iface=6e:c7:ec:12:e5:d5 wps_method=PBC
>P2P-GROUP-FORMATION-SUCCESS 
>P2P-GROUP-STARTED p2p-wlan0-0 client ssid="DIRECT-Dd-SM-N960F" freq=2437 go_dev_addr=6e:c7:ec:12:65:d5 [PERSISTENT] ip_addr=192.168.49.200 ip_mask=255.255.255.0 go_ip_addr=192.168.49.1
>p2p-dev-wlan0: Control interface command 'P2P_GROUP_REMOVE p2p-wlan0-0'

**Comment by Subburaj47** [comment]
[wifid.log](https://github.com/albfan/miraclecast/files/3476895/wifid.log)
[wpa_supplicant.log](https://github.com/albfan/miraclecast/files/3476897/wpa_supplicant.log)
And an interesting part is, I don't see the following logs before the terminationg, which left me no choices to search for.
>2019 Jul 23 16:08:28.692308: P2P: GO indicated that the P2P Group session is ending

**Comment by Subburaj47** [comment]
The issue was due to the input filter I had in my device. This abruptly blocked the incoming and outgoing packets. I was a bit deviated due to the log which says the GO is ending the session.
@albfan Thanks for the support. This ticket can be closed.

**Comment by albfan** [comment]
Great. Any info on how do you detect the problem would help others.

You can close the issue yourself.

**Comment by Subburaj47** [comment]
Within matter of seconds the interface went down. Just had a hunch on the ipfilters.
Check for *iptables -L* and see if any rule is available.
