### ISSUE TITLE
Build methods not working

### ISSUE THREAD

**Issue by geekiehiway** [albfan/miraclecast#344]
None of the build methods identified work (Fedora 30):

localacct@fedora30 miraclecast-master]$ mkdir build
localacct@fedora30 miraclecast-master]$ cd build
localacct@fedora30 build]$ pwd
/home/localacct/Downloads/miraclecast/miraclecast-master/build
localacct@fedora30 build]$ ../autogen.sh g --prefix=/usr
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

==========================================================
localacct@fedora30 build]$ cmake -DCMAKE_INSTALL_PREFIX=/usr .. 
-- The C compiler identification is GNU 9.1.1
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/localacct/Downloads/miraclecast/miraclecast-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/localacct/Downloads/miraclecast/miraclecast-master/build/CMakeFiles/CMakeError.log".

===========================================================
localacct@fedora30 build]$ cd -
localacct@fedora30 miraclecast-master]$ meson build --prefix=/usr --sysconfdir=/etc
The Meson build system
Version: 0.50.1
Source dir: /home/localacct/Downloads/miraclecast/miraclecast-master
Build dir: /home/localacct/Downloads/miraclecast/miraclecast-master/build
Build type: native build
Project name: Miraclecast
Project version: 1
Native C compiler: cc (gcc 9.1.1 "cc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring config.h using configuration
Library readline found: 31mNO
Found pkg-config: /usr/bin/pkg-config (1.6.1)
Found CMake: /usr/bin/cmake (3.14.5)
Dependency glib-2.0 found: NO (tried pkgconfig and cmake)

meson.build:35:0: ERROR: Dependency "glib-2.0" not found, tried pkgconfig and cmake

A full log can be found at /home/localacct/Downloads/miraclecast/miraclecast-master/build/meson-logs/meson-log.txt

localacct@fedora30 build]$ rpm -qa |grep glib
glib2-2.60.6-1.fc30.x86_64

=================================================================

**Comment by albfan** [comment]
You need to install aclocal tool and glib dependency. Check exact instructions for your distro

**Comment by geekiehiway** [comment]
you need to add these as dependencies for autoconf in Fedora 30:
dnf install check 
dnf install gstreamer 
dnf install glib2 
dnf install readline 
dnf install autoconf 
dnf install automake 
dnf install libtool 
dnf install libudev libsystemd 
dnf install systemd-libs 
dnf install systemd-devel 
dnf install glib-devel 
dnf install glib2-devel 
dnf install readline-devel
