### ISSUE TITLE
syslog wpa ERROR HUP 

### ISSUE THREAD

**Issue by warrenc5** [albfan/miraclecast#345]
I get the error - after this I have to restart wifid as ctl no longer responds.

> sudo src/wifi/miracle-wifid  --log-level 8 --wpa-loglevel 8 &

` TRACE: wpa: raw message: <3>P2P-DEVICE-FOUND 56:e4:bd:06:38:95 p2p_dev_addr=56:e4:bd:06:38:95 pri_dev_type=7-0050F204-1 name='Wecast-12b5e1' config_methods=0x88 dev_capab=0x21 group_capab=0x0 wfd_dev_info=0x01111c440032 new=1`

`ERROR: supplicant: HUP on supplicant socket of wlp3s0 (supplicant_global_fn() in wifid-supplicant.c:2161)`

>   -s = log output to syslog instead of stdout
> gvim src/wifi/wifid-supplicant.c

```
	argv[i++] = s->global_ctrl;
++	argv[i++] = "-s";
	argv[i] = NULL;
```

> tail -f /var/log/syslog

```
nl80211: Failed to open /proc/sys/net/ipv4/conf/p2p-dev-wlp3s0/drop_unicast_in_l2_multicast: No such file or directory
Aug 18 00:07:21 localhost wpa_supplicant[16192]: 
nl80211: Failed to set IPv4 unicast in multicast filter
```

**Comment by warrenc5** [comment]
Some sysctl patch that did happen,  will investigate further

https://patchwork.kernel.org/patch/7559041/

**Comment by warrenc5** [comment]
```
nl80211: Driver-advertised extended capabilities mask (default) - hexdump(len=8): 04 00 00 00 00 00 00 40
nl80211: Use separate P2P group interface (driver advertised support)
nl80211: Enable multi-channel concurrent (driver advertised support)
nl80211: use P2P_DEVICE support
nl80211: interface p2p-dev-wlp3s0 in phy phy0
nl80211: Set mode ifindex 0 iftype 10 (P2P_DEVICE)
nl80211: Failed to set interface 0 to mode 10: -22 (Invalid argument)
nl80211: Subscribe to mgmt frames with non-AP handle 0x563513d781a0
```

**Comment by warrenc5** [comment]
https://askubuntu.com/questions/845211/ap-mode-with-wpa-supplicant/846665

**Comment by warrenc5** [comment]
Damn! I really want to watch this movie on my big TV ;)

**Comment by albfan** [comment]
you can start collecting logs for support. See wiki FAQ for instructions.

You can open a MR about output to syslog if you find it interesting

**Comment by warrenc5** [comment]
PR for syslog as promised https://github.com/albfan/miraclecast/pull/348

**Comment by albfan** [comment]
PR was merged, but 

> Damn! I really want to watch this movie on my big TV ;)

Are you using miraclecast in a raspberry pi? Use miraclecast as source is not available yet, so daemon should be run in target device.

You should be able to do it with https://github.com/benzea/gnome-network-displays which integrates with network manager too.

**Comment by albfan** [comment]
We can reopen if this is still valid
