### ISSUE TITLE
Error : supplicant:HUP on supplicant socket of wlan0(supplicant_global_fn() in ../wifid-supplicant.c :2161

### ISSUE THREAD

**Issue by rahuls4** [albfan/miraclecast#347]
**Objective** 
Mirror Android phone screen to Raspberry pi 3B+ device

**Steps Followed**
```
$ sudo systemctl stop NetworkManager.service
$ sudo systemctl stop wpa_supplicant.service
kill any running instances of wpa_supplicant
$ sudo miracle-wifid &
$ sudo miracle-sinkctl
[miraclectl] # run 3
```

Connect android phone with raspberry. It is done successfully
Start casting from android device. It results in following error

**Observation**
```
Error : supplicant:HUP on supplicant socket of wlan0(supplicant_global_fn() in ../wifid-supplicant.c :2161
```

PFA detailed error screenshot

![IMG-3287](https://user-images.githubusercontent.com/54251889/63321887-adef2e00-c33f-11e9-9532-909baca51dd4.JPG)

**Comment by albfan** [comment]
See the wiki FAQ for collect logs for support

**Comment by joelihn** [comment]
I have the same problem, here is log files.
[log.gz](https://github.com/albfan/miraclecast/files/3545058/log.gz)

command line is:
**$ sudo journalctl -f |& tee journal.log
$ sudo miracle-wifid --log-level trace |& tee wifid.log
$ sudo miracle-sinkctl --external-player vlc  --log-level trace --log-journal-level trace |& tee sink.log**

**Comment by rahuls4** [comment]
@Albfan were you able to look in the above logs to understand the problem

**Comment by albfan** [comment]
@rahuls4 you should provide the logs, @joelihn should open a different issue in my opinion

**Comment by joelihn** [comment]
> @rahuls4 you should provide the logs, @joelihn should open a different issue in my opinion

@albfan thanks for your reply. I have open another issue [https://github.com/albfan/miraclecast/issues/350](url)

**Comment by rahuls4** [comment]
[log.zip](https://github.com/albfan/miraclecast/files/3562919/log.zip)
PFA log file...Request for an urgent support

**Comment by albfan** [comment]
I would say you shutdown in some strange way:

```
Sep·01·03:57:13·intelisa·miracle-wifid-wlan0-3[1949]:·ctrl_iface·exists·and·seems·to·be·in·use·-·cannot·override·it¶
  2 Sep·01·03:57:13·intelisa·miracle-wifid-wlan0-3[1949]:·Delete·'/run/miracle/wifi/wlan0-3.global'·manually·if·it·is·not·used·anymore¶
  3 Sep·01·03:57:13·intelisa·miracle-wifid-wlan0-3[1949]:·Failed·to·initialize·wpa_supplicant¶
```

that's why `miracle-wifid` cannot start correctly.

Delete those files and try again.

**Comment by rahuls4** [comment]
Thanks Albfan..I reset the directory permissions using chmod to resolve the above problem. It works but behaviour is not consitent. Sometimes I have to retry 4-5 times to connect. PFA failure logs. Request your feedback on the same
[log.zip](https://github.com/albfan/miraclecast/files/3584336/log.zip)

**Comment by rahuls4** [comment]
@albfan were you able to have a look on the updated log file...

**Comment by rahuls4** [comment]
@albfan PFA updated log after manuaaly deleting the files. As per journal log Failed to open /proc/sys/net/ipv4/conf/p2p-dev-wlan0/drop_unicast_in_l2_multicast: No such file or directory

I don't see a directory with p2p-dev-wlan0 in my raspberry. Is it possible to change the directory name from p2p-dev-wlan0 to wlan0 in source code

**Comment by albfan** [comment]
That's the network interface created for peer to peer using wlan0. You cannot modify it.

**Comment by rahuls4** [comment]
@albfan is there a way to resolve this issue..i have updated the logs in my previous post

**Comment by albfan** [comment]
Latest logs do not look like a valid record of a unsucessful try. Attach correctly to continue with issue
