### ISSUE TITLE
ERROR: invalid arguments (ctl_wifi_parse_peer() in ctl-wifi.c:826)

### ISSUE THREAD

**Issue by l0ophole** [albfan/miraclecast#351]
miracle-wifid is running, but when I run miracle-wifictl I get an error and it quits?

$ sudo miracle-wifictl
ERROR: invalid arguments (ctl_wifi_parse_peer() in ctl-wifi.c:826)
[miraclectl] # 
$

**Comment by albfan** [comment]
miracle-wifictl is not operational right now.
