### ISSUE TITLE
can I use the Wifi-Direct and Ethernet at the same time?

### ISSUE THREAD

**Issue by myxiaojun** [albfan/miraclecast#353]
when i use the commands below to shutdown NetworkManager, my wifi and Ethernet both not work.
$ systemctl stop NetworkManager.service
$ systemctl stop wpa_supplicant.service 

So , can i use ethernet when i am using miracast ? if yes, how?

**Comment by albfan** [comment]
See #75. Basically we should migrate to network manager which is already integrated with  Wifi-Direct. 
https://github.com/benzea/gnome-network-displays should work out of the box.
