### ISSUE TITLE
how to access the gst-launch screen in qml

### ISSUE THREAD

**Issue by ParulRani** [albfan/miraclecast#354]
Hi,
I am creating a qml application through qt creator . do we have any way to not play the screen in gst launch and play it on qml application.

I appreciate you help
Thanks

**Comment by albfan** [comment]
Sure. check the `--external-player` option

This s riot will run screen AST in VLC

https://github.com/albfan/miraclecast/blob/master/res/miracle-vlc

**Comment by Adesh-code** [comment]
Thanks for the reply.I really appreciate that u took some time for me from ur busy schedule

I Follow the below steps
1. sudo miracle-wifid
2. sudo miracle-sinkctl
3. run 3

after 3 when i connect my phone to miraclecast its automatically open the gst-launch with phone screen

so for which i command i need to give --external-player  arguments


Please reply

Thanks

**Comment by albfan** [comment]
`miracle-sinkctl`

Check `miracle-vlc`
https://github.com/albfan/miraclecast/blob/master/res/miracle-vlc#L66

    sudo miracle-sinkctl --external-player miracle-vlc

Should work as the script is installed.

You can use that as a wrapper. You will get the parameters parsed and you can use as you want

**Comment by Adesh-code** [comment]
Thankssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss Thank u very much
:-)

**Comment by Adesh-code** [comment]
Hi,
I run the QProcess for "sudo miracle-wifid &"
But it give me the below error
unparsed remaining arguments starting with : &

do we have some other option for this..

**Comment by albfan** [comment]
That symbol launch the process to background in terminal so you can use same terminal for next command.

You can open two terminals and avoid the `&`.

If you're running in a QProcess you don't need the symbol. Just run each command in a new QProcess.

I guess you can avoid `sudo` too, using PolicyKit

**Comment by albfan** [comment]
The main issue should be fixed using `--external-player` the other questions looks offtopic, you can add new issues if you want to address that
