### ISSUE TITLE
glib.h 

### ISSUE THREAD

**Issue by felipesaldias** [albfan/miraclecast#355]
Hi, i'm having some troubles trying to install your progrman by autotools method in ubuntu 18.04, i got the following error: 

In file included from ../../../src/wifi/wifid.c:39:0:
../../../src/shared/util.h:34:10: fatal error: glib.h: No existe el archivo o el directorio
 #include <glib.h>

when i use `locate glib.h` i've got this: 

/snap/core/7270/usr/include/reglib/reglib.h
/snap/core/7917/usr/include/reglib/reglib.h
/usr/include/reglib/reglib.h
/usr/src/linux-headers-5.0.0-31-generic/include/config/blk/dev/bsglib.h
/usr/src/linux-headers-5.0.0-32-generic/include/config/blk/dev/bsglib.h

any suggestion to try to solve this? thanks in advance for your help :)

**Comment by albfan** [comment]
You need to install devel packages.

See https://github.com/albfan/miraclecast/wiki/FAQ#ubuntu-requirements

glib.h is provided by `libglib2.0-dev`

**Comment by rossliscut** [comment]
I'm facing this issue too.
I've already installed the libglib2.0-dev, and there is a glib.h in the directory /usr/include/glib-2.0/

**Comment by rossliscut** [comment]
> I'm facing this issue too.
> I've already installed the libglib2.0-dev, and there is a glib.h in the directory /usr/include/glib-2.0/

It solved after rm the build dir and rerun the atuogen.sh script. I think I should first install the dependencies then run the script.
