### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by ParulRani** [albfan/miraclecast#356]
Hi can we change the name of miraclecast to something else

**Comment by Adesh-code** [comment]
I need to change the name that appears on phone screen

**Comment by albfan** [comment]
The name comes from the hostname on device:

```
$ hostname
myhost-name
$ cat /etc/hostname 
myhost-name
```
Remember change that can affect your hosts. So review this file
```
$ cat /etc/hosts
# Static table lookup for hostnames.
# See hosts(5) for details.
....
```

There're options on android devices to change de name seen there.

**Comment by Adesh-code** [comment]
thats not the hostname its always "miracle" on android device

**Comment by albfan** [comment]
If for some reason there's no way to resolve the hostname, I think it fallback to "Miracle"

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L1714

We can add an option `--friendly-name` to use as fallback there. Are you able to code it? I can guide you.

**Comment by Adesh-code** [comment]
yeah ofcourse i can code please tell me what i need to do

**Comment by albfan** [comment]
You just need to add a parameter similar to interface:

https://github.com/albfan/miraclecast/blob/58dd6c411e182265a69dd81ff6fb994a5ada02ed/src/wifi/wifid.c#L516

And use in this line (when miraclecast cannot retrieve the name on his own

https://github.com/albfan/miraclecast/blob/58dd6c411e182265a69dd81ff6fb994a5ada02ed/src/wifi/wifid.c#L378

**Comment by albfan** [comment]
Now you can use set-friendly-name from miracle-sink to change name (it comes with autocompletion, you can use link or mac adress)

    set-friendly-name <link|peer> <new-name>
