### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by ParulRani** [albfan/miraclecast#357]
Hi albfan I am very thankfull to you that you always replied my problems about miraclecast .

Thanks a lot  , but now i have a another problem  :-)

I need the miraclecast password protected can we do that .

Waiting for your reply.

Thanks in advance

**Comment by albfan** [comment]
Not sure what you mean. You want to type `****` as you type the password or what?

**Comment by Adesh-code** [comment]
i want to send a password to android device and f password is correct then they can connect to each other

**Comment by Adesh-code** [comment]
can you please tell me which IDE you are using for miraclecast

**Comment by Adesh-code** [comment]
can we use p2p-Prove-Disc-Enter-Pin

**Comment by albfan** [comment]
Take a look at `--config-methods`. `display` or `keypad` is what you're looking for

**Comment by Adesh-code** [comment]
I need the connection between android and linux system will be password protected. whenever we click on miracle in android to connect , so it will ask to put a password which should be as same we are showing on linux system.can it be possible in miracle, I know we can do this in p2p connection .but i don't know about miracle.

**Comment by albfan** [comment]
Please read the spec. A password to start communication is available in miracast protocol using mentioned `--config-methods`
