### ISSUE TITLE
Autotools Dependancy Missing

### ISSUE THREAD

**Issue by jeffmbelt** [albfan/miraclecast#360]
Add steps to install the following dependant packages to ensure autogen.sh runs correctly on Raspbian Buster.

sudo apt-get install libglib2.0-dev
sudo apt-get install libsystemd-dev
sudo apt-get install libudev-dev
sudo apt-get install libreadline-dev

**Comment by albfan** [comment]
There're even more to run correctly.

For Debian like OS you can follow the FAQ for ubuntu:
 https://github.com/albfan/miraclecast/wiki/FAQ#ubuntu-requirements
