### ISSUE TITLE
Miracle-wifid Error

### ISSUE THREAD

**Issue by yasirabs** [albfan/miraclecast#362]
I m getting this error on using :

```
miraclecast$ sudo miracle-wifid 
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:941)
```

**Comment by albfan** [comment]
You need to install so dbus policy is installed.

See https://github.com/albfan/miraclecast/wiki/FAQ

https://github.com/albfan/miraclecast/wiki/FAQ#install-dbus-policy

**Comment by dragonxtek** [comment]
I have the same error.

> sudo miracle-wifid --log-level trace |& tee wifid.log
INFO: miracle-wifid - revision 1.0 May  9 2020 20:40:50
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:941)
DEBUG: exiting.. (main() in wifid.c:624)

I check if my interface supports miracle
> ./test-hardware-capabilities.sh                      
wlp2s0 supports P2P

Also, I checked that both policies are the same

> /res/org.freedesktop.miracle.conf
/usr/local/etc/dbus-1/system.d/org.freedesktop.miracle.conf

But the error continues...

**Comment by albfan** [comment]
@dragonxtek systemd do not attend `/usr/local` you need to set the prefix to `/usr` in your buildsystem.

**Comment by dragonxtek** [comment]
I configured it with --prefix=/usr and now configuration file is in /usr/etc

![Selection_957](https://user-images.githubusercontent.com/10552658/81781636-73798280-94c6-11ea-8640-50482af9129f.png)

but...I still have the same error

**Comment by albfan** [comment]
There're some obscure steps in `autogen.sh`

https://github.com/albfan/miraclecast/wiki/Building#autotools

https://github.com/albfan/miraclecast/blob/master/autogen.sh#L17-L19

So you need

> --sysconfdir=/etc 

for that to be put in proper place.

**Comment by dragonxtek** [comment]
Now this error doesn't appear, but now I have other issue:

![Selection_958](https://user-images.githubusercontent.com/10552658/81831298-2f5ca100-950b-11ea-8710-561b76565767.png)

This chipset doesn't support P2P?

**Comment by albfan** [comment]
@dragonxtek this is not a forum, your problem has relation with the issue, but this is unrelated. There're other issues related with intel having bad support for wifi direct on linux.

Removing as it is unrelated
