### ISSUE TITLE
Selecting a certain wi-fi card

### ISSUE THREAD

**Issue by hvv19890828** [albfan/miraclecast#368]
Hello. I'm gonna use it as a sink. I've got 3 wi-fi cards on my server. And i've got 3 questions:

1. Can i choose a a certain wi-fi interface?
2. Is that obligatory to disable network manager? I assume by disabling it i will loose connection via my two other cards
3. And also i would like to put it inside docker but i'm not sure if it's feasible, because i do not know which port is supposed to be exposed for vlc in case i want to use it in sink mode.

thx a lot for any help

**Comment by albfan** [comment]
Check https://github.com/benzea/gnome-network-displays, it should do what you need out of the box
 
For work at same time see #75
