### ISSUE TITLE
Virtual NIC

### ISSUE THREAD

**Issue by AtesComp** [albfan/miraclecast#369]
MiracleCast should create a virtual NIC from a selected NIC--probably during install--controlled by a MiracleCast user (also created during install).  This follows best practices used by other software systems, such as VirtualBox, specifically used for casting.  It eliminates the need to hijack an existing NIC for the process.

Can a virtual NIC be created "as needed" by MiracleCast?

**Comment by albfan** [comment]
Yes. Ser #75

**Comment by AtesComp** [comment]
A virtual NIC is much simpler than the described #75 and is surprising it wasn't mentioned earlier.  While an older article, see this example:  https://linuxconfig.org/configuring-virtual-network-interfaces-in-linux

**Comment by albfan** [comment]
miraclecast is not screencast using anything I want, is screencast over wifi direct. is an implementation of miracast.

**Comment by AtesComp** [comment]
I didn't suggest using anything you want.  Of course a user "should" use a wireless NIC.  However, WiFi Direct can be bridged over ethernet.  In any event, it still uses a NIC as well as TCP/IP,  RTSP, and RTP.  So my statement stands--a virtual NIC (even if limited to a wireless NIC) is much simpler than the described #75.
