### ISSUE TITLE
Timeout as I try to share Windows 10 screen to Raspberry PI 3

### ISSUE THREAD

**Issue by Trillien** [albfan/miraclecast#371]
Hi,

I'm using a Raspberry PI3 with Arch Linux 64 to sink. On the other side, I try to mirror my Windows 10 screen. Windows connects to Raspberry, but stays at "Establishing connection" step. It disconnects after approximatly one minute.

Log files:
[miracle-sinkctl.log](https://github.com/albfan/miraclecast/files/4351863/miracle-sinkctl.log)
[miracle-wifid.log](https://github.com/albfan/miraclecast/files/4351865/miracle-wifid.log)
[journalctl.log](https://github.com/albfan/miraclecast/files/4351866/journalctl.log)

Can you please provide some help on how to solve this timeout issue?

Trillien

**Comment by albfan** [comment]
Microsoft has his own extension for miracast. See #136
