### ISSUE TITLE
Sink/Peer won't start on Ubuntu 18.04

### ISSUE THREAD

**Issue by 4g0tt3nSou1** [albfan/miraclecast#372]
Hi, I saw this as a suggestion for getting a linux machine to screencast media to my roku device (A TCL Roku TV)

I am running Ubuntu (kubuntu) 18.04 LTS. 
I have installed miraclecast per instructions and ran the commands to stop the services needed and start the daemon.  Upon trying to p2p-scan or run the sink, I get the following output:

`dovahkin@Wolfpack-Alpha:~$ sudo miracle-sinkctl
[ADD] Link: 3
[miraclectl] # run 3
ERROR: supplicant: invalid arguments (supplicant_p2p_start_scan() in ../../../src/wifi/wifid-supplicant.c:2002)
ERROR: cannot change p2p-scanning state on link 3 to 1: Invalid argument (ctl_link_set_p2p_scanning() in ../../../src/ctl/ctl-wifi.c:740)
now running on link 3`

It doesn't seem to want to change the state of the link to scan. 

I do not see it on my roku, I have Screen Mirroring set to Always Allow, and no devices are listed.

Am I missing something/being a noob? Please help

**Comment by 4g0tt3nSou1** [comment]
Also, any future plans to package this into a deb, and maybe use a GUI for management over manual build and CLI. I'll take the heat for it, but I'd prefer such options.

**Comment by albfan** [comment]
Work as source is not implemented. See #4 

There're several packages out there. 

- AUR (arch linux): https://aur.archlinux.org/packages/miraclecast-git/
- PPA (ubuntu): https://launchpad.net/~thopiekar/+archive/ubuntu/miraclecast

If you miss one, that's an issue to open on the distro you look for.

You should be able to do what you want with https://github.com/benzea/gnome-network-displays
