### ISSUE TITLE
[forhelp] cmake build error,then installed libsystemd error

### ISSUE THREAD

**Issue by ShiverZm** [albfan/miraclecast#373]
as title said,
firstly,i use cmake to build this project and it tips that
![image](https://user-images.githubusercontent.com/26861023/77506959-21db5100-6ea2-11ea-8202-df698c9c5750.png)
then i install apt-get install libsystemd error

![image](https://user-images.githubusercontent.com/26861023/77507458-716e4c80-6ea3-11ea-9033-3b541f8aa5ea.png)

so i need guys ' help,give me some advices.

**Comment by albfan** [comment]
- Upload command line photos in an issue is a terrible idea.
- Learn how your distro works (binary/devel packages)
- Try to look around for existing documentation:
https://github.com/albfan/miraclecast/wiki/FAQ#ubuntu-requirements

**Comment by AtesComp** [comment]
Try installing libsystemd0.  Modules various programs use/need/require are
often part of a larger deb install package.
