### ISSUE TITLE
ERROR Compile in Ubuntu 18.04

### ISSUE THREAD

**Issue by PulsarArena** [albfan/miraclecast#374]
CMake Error at /snap/cmake/301/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY)
Call Stack (most recent call first):
  /snap/cmake/301/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindReadline.cmake:26 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/ctl/CMakeLists.txt:5 (find_package)

**Comment by albfan** [comment]
https://github.com/albfan/miraclecast/wiki/FAQ#ubuntu-requirements
