### ISSUE TITLE
mirroring: connection to peer fails

### ISSUE THREAD

**Issue by odorono2** [albfan/miraclecast#375]
Hello -- trying to cast my laptop screen (using Ubuntu 18.04) to my projector (Acer H6535i). 
 p2p-scan finds it, but when I try to connect the projector screen changes and shows a black screen for a couple of seconds, then it fails.  
  
 I attach a zip with the logs of journal , wifid, and wifictl

[miracle-logs.zip](https://github.com/albfan/miraclecast/files/4471357/miracle-logs.zip)

 Hope you can point out what the issue is! Really keen to get this working. 
 Thanks in advance

**Comment by albfan** [comment]
miracle-wifictl is not implemented see #4
