### ISSUE TITLE
Provide Binaries

### ISSUE THREAD

**Issue by 13hannes11** [albfan/miraclecast#378]
Are there any plans to provide binaries, maybe even as snap or flatpak?

If so I'd be wiling to help.

**Comment by albfan** [comment]
I'm totally open to add flatpak, but until it doesn't communicate with network manager by d-bus I don't think it is possible. So #75 is a blocker for this.

If you want to start it I can review and merge

**Comment by 13hannes11** [comment]
Sadly I won't have the capacity to help. If I actually have time in the future I'll reopen the issue.
