### ISSUE TITLE
Can this miraclecast project support my board?

### ISSUE THREAD

**Issue by zhaozhenhong5** [albfan/miraclecast#379]
**hello,albfan. I think your project is good. My question is that can this miraclecast project support my board and how can I do that?
My cpu infomation is :**
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 11.93
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5
processor       : 1

**Comment by albfan** [comment]
There's a section on wiki for raspberry pi (armv7)
