### ISSUE TITLE
gstreamer-plugin missed, miracle-utils.sh: No such file or directory

### ISSUE THREAD

**Issue by ShiverZm** [albfan/miraclecast#380]
ubuntu 20.4

1.RUN test-viewer.sh and ERROR

shiverzhao@shiverzhao:~/Desktop/project/miraclecast$ res/test-viewer.sh
testing plugins required:

test udpsrc... (passed)
test rtpjitterbuffer... (passed)
test rtpmp2tdepay... (passed)
test tsdemux...
	gst plugin "tsdemux" not available
test h264parse...
	gst plugin "h264parse" not available
test avdec_h264...
	gst plugin "avdec_h264" not available
test autovideosink... (passed)

Some plugins required for visualization are missed

Try installing packages "gst-plugins-bad, gst-plugins-base, gst-plugins-base-libs, gst-plugins-good, gst-plugins-ugly, gst-libav, gstreamer".

If that fails too, try:

$ vlc rtp://@:1991

2.AND THEN RUN  test-hardware-capabilities.sh

shiverzhao@shiverzhao:~/Desktop/project/miraclecast$ ./res/test-hardware-capabilities.sh
./res/test-hardware-capabilities.sh: line 15: miracle-utils.sh: No such file or directory
./res/test-hardware-capabilities.sh: line 18: find_wireless_network_interfaces: command not found
There is no wireless devices available

FOR HELP
and i don know how solve the plugin problem in Ubuntu 20.4 ,i always can not find the plugins in apt,
so please help me ,i am newbird.

**Comment by albfan** [comment]
Probaby you need to be on `res/` directory to find the other scripts

Missing plugins should be on packages gst-plugins-bad, gst-plugins-base, gst-plugins-base-libs, gst-plugins-good, gst-plugins-ugly, gst-libav, gstreamer
