### ISSUE TITLE
RPI4 Raspbian nl80211: Failed to open /proc/sys/net/ipv4/conf/p2p-dev-wlan0/drop_unicast_in_l2_multicast

### ISSUE THREAD

**Issue by edefranco** [albfan/miraclecast#381]
Hi to all.

I am working on an RPI4 with a recent version of rasbian (kernel 4.19.118-v7l+)

I have installed miraclecast (download from https://github.com/albfan/miraclecast) on recent Raspbian version on an RPI 4.

My obiective is show android device to an TV connected to RPI.

Some days ago, (I have not changed nothing) after some attempts, on android was displayed an popup that ask me if I would like to connect do miracle and, after that I accept, android and RPI make connection but not showing nothing.

After that, the situation was this:

1) stopping network manager;
2) stopping all wpa_supplicant;
3) starting miracle-wifid &;
4) starting miracle-sinkctl

The system tell me [ADD] Link: 3, I digit run 3 and after some time on the android I view:

Miracle 

I click on and I view "connecting" and list command on RPI tell me:

```
[ADD] Peer: fa:32:e4:eb:8c:c8@3
[PROV] Peer: fa:32:e4:eb:8c:c8@3 Type: pbc PIN:
[GO NEG] Peer: fa:32:e4:eb:8c:c8@3 Type: pbc PIN:
[miraclectl] # list
  LINK INTERFACE                FRIENDLY-NAME                  MANAGED  
     3 wlan0                    <unknown>                      yes      

  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED
     3 fa:32:e4:eb:8c:c8@3      Android_70a7                   no       

 1 peers and 1 links listed.
 
but not connecting and nothing popup is displayed on android phone.

Now, I view the android very rarely but usualy I don't see and syslog I found:

Jul  9 18:54:07 emilio-3 miracle-wifid-wlan0-3[11277]: nl80211: Failed to open /proc/sys/net/ipv4/conf/p2p-dev-wlan0/drop_unicast_in_l2_multicast: No such file or directory
Jul  9 18:54:07 emilio-3 miracle-wifid-wlan0-3[11277]: nl80211: Failed to set IPv4 unicast in multicast filter
Jul  9 18:54:07 emilio-3 miracle-wifid-wlan0-3[11277]: nl80211: Failed to open /proc/sys/net/ipv4/conf/p2p-dev-wlan0/drop_unicast_in_l2_multicast: No such file or directory
Jul  9 18:54:07 emilio-3 miracle-wifid-wlan0-3[11277]: nl80211: Failed to set IPv4 unicast in multicast filter
Jul  9 18:54:07 emilio-3 miracle-wifid-wlan0-3[11277]: P2P-FIND-STOPPED
Jul  9 18:54:07 emilio-3 miracle-wifid-wlan0-3[11277]: CTRL_IFACE: Detach monitor that cannot receive messages: /tmp/.miracle-wpas-11271-2\x00
Jul  9 18:54:07 emilio-3 miracle-wifid-wlan0-3[11277]: nl80211: deinit ifname=p2p-dev-wlan0 disabled_11b_rates=0
Jul  9 18:54:07 emilio-3 miracle-wifid-wlan0-3[11277]: p2p-dev-wlan0: CTRL-EVENT-TERMINATING
Jul  9 18:54:07 emilio-3 miracle-wifid-wlan0-3[11277]: nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Jul  9 18:54:08 emilio-3 miracle-wifid-wlan0-3[11277]: wlan0: CTRL-EVENT-TERMINATING
Jul  9 18:55:27 emilio-3 kernel: [ 8527.481749] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
Jul  9 18:55:27 emilio-3 kernel: [ 8527.481785] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Jul  9 18:56:06 emilio-3 dbus-daemon[383]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.90' (uid=0 pid=18994 comm="miracle-wifid ")
Jul  9 18:56:06 emilio-3 systemd[1]: Starting Hostname Service...
Jul  9 18:56:07 emilio-3 dbus-daemon[383]: [system] Successfully activated service 'org.freedesktop.hostname1'
Jul  9 18:56:07 emilio-3 systemd[1]: Started Hostname Service.
Jul  9 18:56:07 emilio-3 miracle-wifid-wlan0-3[19000]: Successfully initialized wpa_supplicant
```

Suggestions ?

Thank in advance, 

Emilio

**Comment by albfan** [comment]
Be sure that you install all the required gstreamer plugins. More details in https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#external-player (rest/test-viewer.sh)

You can use a different player like vlc following https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#external-player

**Comment by albfan** [comment]
You can try https://gitlab.gnome.org/GNOME/gnome-network-displays for a better implementation that should work out of the box and be compatible with your normal wifi

**Comment by edefranco** [comment]
Ok, here today is a good day for miracle.

Without any change (this is very strange, maybe is related to reboot of RPI ...I will investigate), start miracle-wifid & and miracle-sinkctl -> run 3, click on phone connect on miracle and the ip connession go up.

This is the log:

Jul 11 18:02:39 emilio-3 dbus-daemon[360]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.57' (uid=0 pid=20513 comm="miracle-wifid ")
Jul 11 18:02:39 emilio-3 systemd[1]: Starting Hostname Service...
Jul 11 18:02:39 emilio-3 dbus-daemon[360]: [system] Successfully activated service 'org.freedesktop.hostname1'
Jul 11 18:02:39 emilio-3 systemd[1]: Started Hostname Service.
Jul 11 18:02:39 emilio-3 miracle-wifid-wlan0-3[20527]: Successfully initialized wpa_supplicant
Jul 11 18:02:39 emilio-3 kernel: [ 5516.483032] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Jul 11 18:03:09 emilio-3 systemd[1]: systemd-hostnamed.service: Succeeded.
Jul 11 18:04:20 emilio-3 miracle-wifid-wlan0-3[20527]: P2P-DEVICE-FOUND fa:32:e4:eb:8c:c8 p2p_dev_addr=fa:32:e4:eb:8c:c8 pri_dev_type=10-0050F204-5 name='Android_70a7' config_methods=0x188 dev_capab=0x25 group_capab=0x0 wfd_dev_info=0x00101c440032 new=1
Jul 11 18:04:20 emilio-3 miracle-wifid-wlan0-3[20527]: P2P-PROV-DISC-PBC-REQ fa:32:e4:eb:8c:c8 p2p_dev_addr=fa:32:e4:eb:8c:c8 pri_dev_type=10-0050F204-5 name='Android_70a7' config_methods=0x188 dev_capab=0x25 group_capab=0x0
Jul 11 18:04:21 emilio-3 miracle-wifid-wlan0-3[20527]: P2P-GO-NEG-REQUEST fa:32:e4:eb:8c:c8 dev_passwd_id=4 go_intent=14
Jul 11 18:04:21 emilio-3 kernel: [ 5618.114887] brcmfmac: brcmf_p2p_discover_listen: Previous LISTEN is not completed yet
Jul 11 18:04:21 emilio-3 miracle-wifid-wlan0-3[20527]: P2P-FIND-STOPPED
Jul 11 18:04:21 emilio-3 systemd-udevd[23647]: Using default interface naming scheme 'v240'.
Jul 11 18:04:22 emilio-3 kernel: [ 5618.558598] brcmfmac: brcmf_p2p_send_action_frame: Failed to send Action Frame(retry 1)
Jul 11 18:04:22 emilio-3 kernel: [ 5618.817783] brcmfmac: brcmf_p2p_send_action_frame: Failed to send Action Frame(retry 1)
Jul 11 18:04:22 emilio-3 dhcpcd-run-hooks[23667]: p2p-wlan0-0: starting wpa_supplicant
Jul 11 18:04:22 emilio-3 kernel: [ 5619.056320] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save disabled
Jul 11 18:04:23 emilio-3 kernel: [ 5619.603226] brcmfmac: brcmf_p2p_send_action_frame: Failed to send Action Frame(retry 1)
Jul 11 18:04:23 emilio-3 kernel: [ 5619.604534] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save disabled
Jul 11 18:04:23 emilio-3 dhcpcd[433]: p2p-wlan0-0: connected to Access Point 
Jul 11 18:04:23 emilio-3 dhcpcd[433]: p2p-wlan0-0: waiting for carrier
Jul 11 18:04:23 emilio-3 dhcpcd[433]: p2p-wlan0-0: carrier acquired
Jul 11 18:04:23 emilio-3 dhcpcd[433]: p2p-wlan0-0: carrier lost
Jul 11 18:04:23 emilio-3 miracle-wifid-wlan0-3[20527]: P2P-GO-NEG-SUCCESS role=client freq=2437 ht40=0 peer_dev=fa:32:e4:eb:8c:c8 peer_iface=fa:32:e4:eb:8c:c8 wps_method=PBC
Jul 11 18:04:23 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: WPS-PBC-ACTIVE
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: Trying to associate with fa:32:e4:eb:8c:c8 (SSID='DIRECT-c5-Android_70a7' freq=2437 MHz)
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: Associated with fa:32:e4:eb:8c:c8
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: CTRL-EVENT-EAP-STARTED EAP authentication started
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=14122 method=1
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: CTRL-EVENT-EAP-METHOD EAP vendor 14122 method 1 (WSC) selected
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: WPS-CRED-RECEIVED
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: WPS-SUCCESS
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: P2P-GROUP-FORMATION-SUCCESS
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: CTRL-EVENT-EAP-FAILURE EAP authentication failed
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: CTRL-EVENT-DISCONNECTED bssid=fa:32:e4:eb:8c:c8 reason=3 locally_generated=1
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: Trying to associate with SSID 'DIRECT-c5-Android_70a7'
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: Associated with fa:32:e4:eb:8c:c8
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: CTRL-EVENT-CONNECTED - Connection to fa:32:e4:eb:8c:c8 completed [id=0 id_str=]
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: P2P-GROUP-STARTED p2p-wlan0-0 client ssid="DIRECT-c5-Android_70a7" freq=2437 go_dev_addr=fa:32:e4:eb:8c:c8 [PERSISTENT]
Jul 11 18:04:24 emilio-3 miracle-wifid-wlan0-3[20527]: p2p-wlan0-0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
Jul 11 18:04:24 emilio-3 dhcpcd[433]: p2p-wlan0-0: carrier acquired
Jul 11 18:04:24 emilio-3 dhcpcd[433]: p2p-wlan0-0: connected to Access Point `DIRECT-c5-Android_70a7'
Jul 11 18:04:25 emilio-3 dhcpcd[433]: p2p-wlan0-0: soliciting a DHCP lease
Jul 11 18:04:28 emilio-3 dhcpcd[433]: p2p-wlan0-0: offered 192.168.49.162 from 192.168.49.1
Jul 11 18:04:30 emilio-3 dhcpcd[433]: p2p-wlan0-0: probing address 192.168.49.162/24
Jul 11 18:04:30 emilio-3 avahi-daemon[382]: Joining mDNS multicast group on interface p2p-wlan0-0.IPv4 with address 192.168.49.162.
Jul 11 18:04:30 emilio-3 avahi-daemon[382]: New relevant interface p2p-wlan0-0.IPv4 for mDNS.
Jul 11 18:04:30 emilio-3 avahi-daemon[382]: Registering new address record for 192.168.49.162 on p2p-wlan0-0.IPv4.
Jul 11 18:04:35 emilio-3 dhcpcd[433]: p2p-wlan0-0: leased 192.168.49.162 for 3600 seconds
Jul 11 18:04:35 emilio-3 avahi-daemon[382]: Withdrawing address record for 192.168.49.162 on p2p-wlan0-0.
Jul 11 18:04:35 emilio-3 avahi-daemon[382]: Leaving mDNS multicast group on interface p2p-wlan0-0.IPv4 with address 192.168.49.162.
Jul 11 18:04:35 emilio-3 avahi-daemon[382]: Interface p2p-wlan0-0.IPv4 no longer relevant for mDNS.
Jul 11 18:04:35 emilio-3 avahi-daemon[382]: Joining mDNS multicast group on interface p2p-wlan0-0.IPv4 with address 192.168.49.162.
Jul 11 18:04:35 emilio-3 avahi-daemon[382]: New relevant interface p2p-wlan0-0.IPv4 for mDNS.
Jul 11 18:04:35 emilio-3 avahi-daemon[382]: Registering new address record for 192.168.49.162 on p2p-wlan0-0.IPv4.
Jul 11 18:04:35 emilio-3 dhcpcd[433]: p2p-wlan0-0: adding route to 192.168.49.0/24
Jul 11 18:04:35 emilio-3 dhcpcd[433]: p2p-wlan0-0: adding default route via 192.168.49.1
Jul 11 18:04:35 emilio-3 dhcpcd[433]: p2p-wlan0-0: pid 0 deleted route to 192.168.49.0/24

But I cannot view nothing: netstat -anu and netstat -ant don't show any rtp service that listen on RPI.

ifconfig show a p2p-wlan0-0 interface with IP 192.168.49.162, and in /proc/sys/net/ipv4/conf/ the p2p-dev-wlan0 directory not exist but is present a p2p-wlan0-0 and into it there is the file drop_unicast_in_l2_multicast.

There are some error in miracle-wifid or in miracle-sinkctl about the p2p-wlan0-0 directory (it search p2p-dev-wlan0) ???

In any case, also starting the palyer with your script, there are no streming because nothing listen on RPI !!

Have any idea about ?

On gnome-network-display: is no simple to try because it would like network-manager version 1.15.2 and on the rasbian is is not installed (rasbian use LXDE) and in any case it is available in 1.14.6-2.
Also installing on RPI4 an xubuntu, the network manager available is 1.10.6-2.

The execution of test-viewer in /res tell me all PASSED and that is everything installed.

I think that is no started by the miracle some pieces relative as RTP ... 

What do you think about ?

Emilio

**Comment by albfan** [comment]
In wifi there's a FAQ about log to get support. See the important part here is miracle-sinkctl output

**Comment by edefranco** [comment]
Where ? Can you give me the link, because I cannot found it !
Emilio

**Comment by albfan** [comment]
https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support

**Comment by edefranco** [comment]
Ok, thank !
Now try to generate all log and after submit it
Emilio

**Comment by albfan** [comment]
closing until logs are provided
