### ISSUE TITLE
Proposal for README: make info on external players more accessible

### ISSUE THREAD

**Issue by bitfasching** [albfan/miraclecast#390]
Hi @albfan,

thank you for maintaining miraclecast! I recently started using it and invested some time to find out how to customize the stream playback. I added a section with my findings to the [wiki page on miraclecast-sinkctl](https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#using-ffplay-as-external-player-for-miracle-sinkctl). Perhaps we can make miraclecast easier for others to use if we link to this info in README.md?

After [Steps to use it as sink](https://github.com/albfan/miraclecast#steps-to-use-it-as-sink), we could add a comment like:
> More information on how to customize the player can be found in the [wiki](https://github.com/albfan/miraclecast/wiki/miracle-sinkctl).

**Comment by albfan** [comment]
Using external player is covered on https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#external-player

document a exact tool if out of our wiki scope.

Using a nop like `true` to not run anything miss all the configuration pair step does between devices.

You can add here that info until we see how that can help others and find a place for it.

Closing by now
