### ISSUE TITLE
Variant without systemd

### ISSUE THREAD

**Issue by tomekdev** [albfan/miraclecast#394]
Is it possible to compile this project without systemd support ? I don't like systemd and I avoid it in my systems. I'd like to try miracle cast but I can't as for now. Doing some steps manually where systemd does them automatically is not a problem for me. Will it be possible to compile and run this project without systemd ?

**Comment by albfan** [comment]
Indeed it do not use systemd.

Those steps are to switch off network manager and wpa_supplicant as right now miraclecast uses his own wpa_supplicant implementation.

We can reopen this if you have any further questions
