### ISSUE TITLE
Connected To mobile device successfully but casting issues

### ISSUE THREAD

**Issue by shreysway** [albfan/miraclecast#395]
Hi, its connected to my device successfully and casting working but there is noticeable lag while watching videos

**Comment by albfan** [comment]
Yes that's expected. Buffering they call it.

On what spec do you base your expectations? We can reope. If you show any alternative without lag

**Comment by shreysway** [comment]
Hey Albfan could you guide what best i can do to reduce this jitters?! without modifying the code
