### ISSUE TITLE
arch package missing.

### ISSUE THREAD

**Issue by steverweber** [albfan/miraclecast#40]
arch package missing.
https://aur.archlinux.org/packages/miraclecast-github/

**Comment by steverweber** [comment]
Also... 
name miraclecast vs miracast  I feel this project should take over the miracast name because this project is most active.  perhaps a different issue :)

**Comment by albfan** [comment]
AUR was on a git workflow migration. 

https://wiki.archlinux.org/index.php/Arch_User_Repository#AUR_4

I suppose old way packages were deleted. I had tried to migrate the package but steps seems little confusing.

Now migration os done everything looks easier.

Meanwhile I upload the package you could get it with:

    $ sudo abs
    $ cp -r /var/abs/core/systemd .
    $ cd systemd
    $ #enable kdbus on PKGBUILD
    $ #optionally remove strip options(!strip debug) too (a sane move to debug)
    $ makepkg -s
    $ sudo pacman -U systemd.... libsystemd...

... If I remember correctly. Correct any little mistake otherway.

If you achieve this push it to AUR. That's the archlinux way to to things. I will glad to see that package from you.

**Comment by albfan** [comment]
That would be for systemd. I'm annoyed I did not push PKGBUILD on res/ directory for miraclecast.

About name, that was a joke from project creator (about how hard was too get this to work) and I think it's cool to keep it. 

Another story is add and advanced search on AUR so people looking for miracast projects can find this one.

**Comment by steverweber** [comment]
thanks for the quick help. I'll give it a try tonight!.

**Comment by steverweber** [comment]
# arch

compile systemd with --enable-kdbus
```
sudo abs
mkdir ~/scm
cd ~/scm
cp -r /var/abs/core/systemd .
cd systemd
vi PKGBUILD
# replace ./configure .. --disable-kdbus with --enable-kdebus
sudo pacman -Syu python-lxml docbook-xsl
makepkg -s -i
reboot
```

install miraclecast
```
mkdir ~/scm
cd ~/scm
git clone https://github.com/albfan/miraclecast.git
cd miraclecast
mkdir build
cd build
cmake ..
sudo make install
```

```
./test-wifi-capabilities.sh 
Sorry, wls3 do not support P2P
```

darn, well I'll give it a try on a good system some day. I look forward to the future when wireless displays are simple.

**Comment by albfan** [comment]
That test is for your hardware. Your card or usb dongle do not support wifi
direct. Read its specs.

Have you ever try to see a beta cassete inside a vhs player? hahaha!

**Comment by Psykar** [comment]
For the record, old AUR PKGBUILD's are located here:
https://github.com/aur-archive/miraclecast-github/

**Comment by albfan** [comment]
Thanks for that. Little bit easier now

**Comment by Hans-Maulwurf** [comment]
Is there a howto to get miracastle working on a fresh installed arch linux (antergos with gnome3) without systemd? would be awesome to get it working

**Comment by albfan** [comment]
Systemd is used as helper to interact with dbus. There is an issue to isolate from systemd but no progress since open.

**Comment by zglx2008** [comment]
Many embedded system can not install systemd, which miraclecast can not be transplanted , the portability is not very well .

**Comment by albfan** [comment]
Solved. https://aur.archlinux.org/packages/miraclecast/

Thanks @Psykar
