### ISSUE TITLE
Support With Log file

### ISSUE THREAD

**Issue by Quaqmre** [albfan/miraclecast#402]
Pls help me , I have anyCast device but I cant Use it and I get error your device not sup. p2p device , 
can u check my logs I dont understand what ı have to do , I check all issues but it doesnt help me,
[miracastErrorLog.zip](https://github.com/albfan/miraclecast/files/5788715/miracastErrorLog.zip)

**Comment by albfan** [comment]
miraclecast still do not work as source. See #4
