### ISSUE TITLE
My device can't connect to miracle-sink

### ISSUE THREAD

**Issue by zebrinpav** [albfan/miraclecast#403]
I ran 
miracle-wifid --use-dev
miracle-sinkctl
But my device can't connect to miracle
Log files:
[l.zip](https://github.com/albfan/miraclecast/files/5847854/l.zip)

**Comment by zebrinpav** [comment]
Laptop OS Ubuntu 20.04.1 
Device OS Android 9

**Comment by albfan** [comment]
Log show your android device didn't start a connection with miracle-sinkctl. That step is needed
