### ISSUE TITLE
Any Uninstall Instructions?

### ISSUE THREAD

**Issue by Alimint16** [albfan/miraclecast#404]
Hi, just wanted to ask if there are uninstall instructions, I just want to reinstall because there are some errors, i am using linux mint 20.1 and i build it using cmake or the make command, can someone help me?

**Comment by albfan** [comment]
Uninstall step should be provided by buildsystem. And cmake do notprovide it.

You can install to a different prefix and see the list of files to remove from real prefix.

So:

    make install DESTDIR=PKG

Will install all files in pkg/... On your current for.

Then remove those files in real prefix, `/usr` or `/usr/local`.

Closing as that is not a project problem is a buildsystem problem or a package manager problem that should be fixed at that level
