### ISSUE TITLE
Doesnt it work via ETHERNET? 

### ISSUE THREAD

**Issue by aco1731** [albfan/miraclecast#405]
I got my Chromecast via WIFI but my PC is linked in my router via CABLE. Miraclecast doesnt work in that case?

Is it need wifi to work?? It makes no sense to  me.

**Comment by albfan** [comment]
Sure, how can it be that a protocol based on WiFi only works on WiFi?

This is an implementation of miracast a protocol based on WiFi Direct (two devices linked directly without routers in the middle), that uses Real-Time Streaming Protocol (RTSP).

So even if this would work by ethernet, using routers (it doesn't), your PC is linked to your router but? If your PC is the source what is the sink? If your PC is the sink what is the source?

Feel free to explain yourself better, but I would close by now this pure ranting
