### ISSUE TITLE
kdbus not mainlined yet

### ISSUE THREAD

**Issue by steverweber** [albfan/miraclecast#41]
could dbus be used instead of kdbus?

thanks/

**Comment by steverweber** [comment]
never mind...

**Comment by vindicatorr** [comment]
@steverweber I think your question is still valid. I don't think kdbus will build for kernel 4.6+.
I personally attempted to build for 4.7RC# and it fails because code had moved in 4.6.
https://github.com/gregkh/kdbus/issues/38

**Comment by albfan** [comment]
correct me if I'm wrong, I'm not an expert here. 

https://www.reddit.com/r/linux/comments/3auufg/eli12_dbus_vs_kdbus_vs_sdbus/

kdbus is dbus on kernel, so there's no "instead of", simply kdbus is not avaliable by default. There's no way to listen to wifi interface messages without enabling kdbus on systemd.

It's relative easy to enable kdbus on systemd, don't know the reasons to release it without it by default.

**Comment by vindicatorr** [comment]
Neither am I, but recall seeing pcap in Linux and even Windows I think.
http://linux.die.net/man/3/pcap

While searching for info, I came across a "miracle-cast" implementation at freedesktop: https://www.freedesktop.org/wiki/Software/miracle/libwfd/
It doesn't look like it has to use kdbus (or any "heavy dependencies"). Am I missing something?

**Comment by albfan** [comment]
I should give a try again to libwfd. Ireference it for #3, thanks.

**Comment by vindicatorr** [comment]
For a headsup, I did build and run intel's wds.
I only went as far as run test-sink and the connection process was sketchy but eventually worked.
There is a notable lag from what's on my device and what appears on my computer.

Another downside which is probably DRM-related regarding FandangoNOW is no video is transmitted (not on computer nor device), only audio. I'm really not liking Fandango in general, and that is just another reason.

**Comment by midi1996** [comment]
Are you using a 7000 series Intel chip? Just curious, as I tried wds on my 6000 series card and didn't work, for some reason p2p device (which should be from the driver) doesn't appear on my computer!

**Comment by vindicatorr** [comment]
Ummm, I'm thinking the cpu isn't going to play much of a role (none) regarding p2p capability, but rather the wifi chip, in my case RTL8821AE, will.

Specifically, what step did not work? I had 4 terminal windows open (wpa_supplicant, connmand, connmanctl, sink-test) so I could watch/interact with each command.

**Comment by midi1996** [comment]
Lol, sorry you misunderstood me, i wasnt talking about the cpu but the wifi chip series, as in wds they wrote either intel 7000 series wifi chip or ath9k. Good thing that it worked for you.

**Comment by albfan** [comment]
@midi1996 @vindicatorr open different issues for different problems if possible.

**Comment by albfan** [comment]
Since version 220 systemd has kdbus enabled by default:

https://github.com/systemd/systemd/commit/1b09f54#diff-67e997bcfdac55191033d57a16d1408aR1206

**Comment by vindicatorr** [comment]
I was going to give a heads-up regarding systemd having kdbus enabled vs having it in the kernel, but now I'm now wondering if I should even bother if comments are just going to be deleted.

**Comment by albfan** [comment]
That's not the question of issue, which indeed has been resolved.

You can open another issue if that improves in some way miraclecast.

Try to focus on precise issues and detailed solutions that's the purpose of an issue tracker
