### ISSUE TITLE
The test-hardware-capabilities script says p2p support, but sink cannot be discovered by peer devices

### ISSUE THREAD

**Issue by wanted002** [albfan/miraclecast#410]
Hi, alb

As title described, my sink device with ubuntu20.04 can not be discovered while scan is running and device-found message is shown. The wireless card has  realtek chips, with driver module 8821ce. And I can see the "Supported interface modes" info by "iw list". It shows like below:

```
*IBSS
*managed
*AP
*P2P-client
*P2P-GO
```

By debugging wpa_supplicant, I found there's no MGMT frame received , which means the PROBE_REQUEST frame cannot be handled , I think.  So, after comparing with other cards running miraclecast sink perfectly, I suppose that the issue is caused by lack of the "monitor" capability in "Supported interface modes". Am I on the right way ? 

If true, maybe we should change the test-xxx.sh script,  or If not , please give me some advices

Thanks

**Comment by albfan** [comment]
Only `P2P-client` and `P2P-GO` is needed. `monitor` is a wider sniffer capability.

https://git.kernel.org/pub/scm/linux/kernel/git/linville/wireless.git/tree/include/uapi/linux/nl80211.h?id=HEAD#n2116.

Feel free to open a different issue about your working and non working devices
