### ISSUE TITLE
Why this implementation needs closing NetworkManager/wpa_supplicant to work

### ISSUE THREAD

**Issue by szlee118** [albfan/miraclecast#415]
As the title, many other miracast applications such as Windows screen sharing / Android / GNOME Network Display can support p2p without closing it's own Wi-Fi.  May I ask why it is designed this way. Thanks.

**Comment by albfan** [comment]
At the time this app was created, there was no API to deal with P2P in network manager.

Based on this work, gnome-network-displays @benzea, was able to contribute to NM and provide that API (a huge task worth to review)

Use wi-fi in that way is planned through #75

**Comment by szlee118** [comment]
Is there any method now to **start the miracle-wifid & miracle-sinkctl** without closing Networkmanager. Does that need a lot of changes to be done to source code? Thanks.

**Comment by albfan** [comment]
No it needs a reimplementation based on dbus to interact with NM.

gnome-network-displays does it out of the box, you can find the code in that project
