### ISSUE TITLE
Is there any method now to **start the miracle-wifid & miracle-sinkctl** without closing Networkmanager or wpa_supplicant?

### ISSUE THREAD

**Issue by szlee118** [albfan/miraclecast#416]
Is there any method now to **start the miracle-wifid & miracle-sinkctl** without closing Networkmanager or wpa_supplicant. Does that need a lot of changes to be done to source code? Thanks.

_Originally posted by @szlee118 in https://github.com/albfan/miraclecast/issues/415#issuecomment-932059301_

**Comment by albfan** [comment]
Answered there
