### ISSUE TITLE
my phone can‘t find device when i run in VMware Ubuntu 16.04

### ISSUE THREAD

**Issue by zrzhuang** [albfan/miraclecast#419]
I have done with the reference of readme，but i can't find out the miracle device by my phone,After  i run the command `sudo miracle-sinkctl` in the Ubuntu16.04 in the VMware

Kernel Version：
 
System Version:
 
res/test-viewer.sh:
 

test-hardware-capabilities.sh
 

I have copy the file org.freedesktop.miracle.conf
 

```
make install
../configure --enable-rely-udev
sudo miracle-wifid &
sudo miracle-sinkctl -> set-managed x yes
```

still can’t find the device on my phone.

**Comment by zrzhuang** [comment]
here is the log when i do below cmds in three different tabs
[log_20211101.tar.gz](https://github.com/albfan/miraclecast/files/7452222/log_20211101.tar.gz)
:
from this lpg ,i find the sink can find my phone,but can not receive the P2P-PROV-DISC-PBC-REQ of my phone.

**Comment by albfan** [comment]
You have to start the screen sharing from your phone, miraclecast is waiting for your phone to start that.

**Comment by zrzhuang** [comment]
my phone has start the screen sharing,keep on searching the sink device always，but can't find the sink device on my phone.in the sink code ,the sink can't receive the probe req event of my phone likely  ,and i don't know the reason,hope you answer,and i don't know how to solve this

**Comment by albfan** [comment]
That implies debug your android device. I strongly suggest to try in a recent ubuntu version.

**Comment by zrzhuang** [comment]
hi.i have run this code in  Raspberry Pi 4B，the system is the Raspbian，my phone can connect the sink,but can't see the mirror screen on the sink device,below is the log
[Log.tar.gz](https://github.com/albfan/miraclecast/files/7509579/Log.tar.gz)
;
