### ISSUE TITLE
No links listed when using computer as sink

### ISSUE THREAD

**Issue by mcp292** [albfan/miraclecast#421]
Nothing shows up after entering `sudo miracle-sinkctl`.

```bash
> list
----
 0 peers and 0 links listed.
```

**Comment by albfan** [comment]
See you need to run miracle-wifid to have a daemon able to configure your wifi device to check for sources to stream their screens.

**Comment by mcp292** [comment]
Yes, I should have noted my steps.

Following [the instructions](https://github.com/albfan/miraclecast#documentation):

1. `sudo systemctl stop iwd` (I don't use `wpa_supplicant` nor `NetworkManager`)
2. `sudo miracle-wifid &`
3. `sudo miracle-sinkctl`

That's what I do to get to my first comment.

**Comment by albfan** [comment]
I see.

Please attach logs for support: https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support

see the step to stop network manager is to ensure you don't have a wpa_supplicant running. miraclecast spawn it with a custom config. If you don't have wpa_supplicant miraclecast will not work, it is not agnostic about network manager

**Comment by mcp292** [comment]
That may simply be the issue. `wpa_supplicant` is not listed as a dependency in the [requirments](https://github.com/albfan/miraclecast#requirements) nor in the [AUR](https://aur.archlinux.org/packages/miraclecast-git/).

**Comment by albfan** [comment]
yes, the idea is to get rid of that at some point talking with network manager through d-bus

**Comment by mcp292** [comment]
Okay. In my case I have neither. I use only `iwd` and `dhcpcd`. Whatever you decide please add as a dependency. I think `wpa_supplicant` is the smaller dependency though. 

Maybe there is some agnostic way, but I don't have time at the moment to familiarize with the code base. Looks like nice, clean C code though ;).

**Comment by albfan** [comment]
Remember this is the project, how it is packaged is an issue to open downstream.

**Comment by mcp292** [comment]
Not fully. Your requirements section should contain `wpa_supplicant`.

**Comment by albfan** [comment]
I got you know. When you say dependency you mean document requirements. PR welcome!

**Comment by akvadrako** [comment]
A way to work with iwd would be nice. It seems like the future instead of wpa_supplicant.
