### ISSUE TITLE
ERROR: cannot change p2p-scanning state on link 3 to 1: Invalid argument (ctl_link_set_p2p_scanning() in ctl-wifi.c:739)

### ISSUE THREAD

**Issue by Creativious** [albfan/miraclecast#424]
Below is the screenshot of the result and show how I've done it and the errors I receive
![image](https://user-images.githubusercontent.com/28994028/143820029-7eb08856-0e5b-47d2-8744-df1930aa3b1d.png)
I'm currently running the latest version of Arch Linux
Here's the neofetch
![image](https://user-images.githubusercontent.com/28994028/143820309-e7ade821-a9a7-4662-94a8-277e5d8008e8.png)
and here's my wireless card
![image](https://user-images.githubusercontent.com/28994028/143820478-f8b7b5b9-d304-4f6f-9ae0-3cbe659da35d.png)
I'll try to reply to anything as soon as I can

**Comment by albfan** [comment]
See steps to configure your environment (you need to stop wpa_supplicant to allow miraclecast to spawn a version with a special config)

**Comment by Creativious** [comment]
I did stop it, the first screenshot shows me stopping it with `sudo systemctl stop wpa_supplicant.service`

**Comment by albfan** [comment]
I see now. Can you run miracle-wifid with --log-level trace and attach output (a file is preferred) See https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support

**Comment by gcb** [comment]
got the same issue.


here's the trace.
```
INFO: miracle-wifid - revision 1.0 Feb 17 2023 23:48:30
DEBUG: friendly-name from local hostname: elite (manager_read_name() in wifid.c:395)
DEBUG: link: new link: wlp1s0 (2) (link_new() in wifid-link.c:71)
DEBUG: supplicant: new supplicant for wlp1s0 (supplicant_new() in wifid-supplicant.c:2123)
INFO: link: add link: wlp1s0
INFO: link: manage link wlp1s0
DEBUG: supplicant: start supplicant of wlp1s0 (supplicant_start() in wifid-supplicant.c:2661)
DEBUG: supplicant: spawn supplicant of wlp1s0 (supplicant_spawn() in wifid-supplicant.c:2507)
INFO: supplicant: wpa_supplicant found: /bin/wpa_supplicant
INFO: supplicant: wpas spawned as pid:58702
DEBUG: supplicant: open supplicant of wlp1s0 (supplicant_open() in wifid-supplicant.c:2289)
TRACE: wpa: raw message: OK

TRACE: wpa: raw message: wifi_display=1
ifname=wlp1s0
address=30:03:c8:fe:ee:31

WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in wifid-supplicant.c:1718)
ERROR: supplicant: invalid arguments (supplicant_p2p_start_scan() in wifid-supplicant.c:2022)
```

my driver/device seems to support p2p just fine
```
$ iw phy | grep -i p2p
                 * start_p2p_device
                 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-client: 0x40 0xd0
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * P2P-device: 0x40 0xd0
```

**Comment by albfan** [comment]
@gcb please open your own issue and provide all logs needed mentioned in wiki FAQ

**Comment by masoud-msk** [comment]
@Creativious How did you fix the problem?
I encountered the same issue

**Comment by ElHyperion** [comment]
How was this fixed? I am using Miraclecast for the first time and cannot get over this issue.

**Comment by albfan** [comment]
As this issue do not provide any logs for support, is better to open a new issue and provide your details there
