### ISSUE TITLE
it's work on windows os?

### ISSUE THREAD

**Issue by qianxifu** [albfan/miraclecast#425]

**Comment by albfan** [comment]
No, this implement miracast using Linux technology stack. Like dbus. Although, you can connect with Windows using #136

**Comment by albfan** [comment]
See https://github.com/albfan/miraclecast/pull/136#issue-184400260

Now you can provide extra parameters with miraclecast ini file (see this should be on your root home directory)

**Comment by albfan** [comment]
I tested locally and is working, feedback welcome
