### ISSUE TITLE
Difficulty connecting to Roku Ultra

### ISSUE THREAD

**Issue by AFunProgrammer** [albfan/miraclecast#427]
I'm grateful someone is supporting this for Linux and trying to make it run really well!
As for myself, I downloaded and compiled/installed miraclecast. After using both the Sink / Peer instructions to connect to Roku Ultra, I couldn't initiate a connection.  The best I could do was get the Roku Ultra device to be listed as a Link with it's MAC address but connect never worked.  What information can I gather to find out what was going on, or if you want to point me to an easy to use visual debugger and a line of code to debug-break on; I'd be glad to look deeper in to what is going on.

Thanks!

**Comment by albfan** [comment]
https://www.roku.com/products/roku-ultra

Looks like you want to use miraclecast as source.

See #4 for that. Gnome-network-displays should world out of the box.

I planned to works on It this holidays, but other project releases get in the way.

Hope to find time soon
