### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by jze2** [albfan/miraclecast#428]
Compiled (hey, the "configure" file is completely missing!!!), installed in /usr/local, stopped wpa_supplicant.service and NetworkManager.service and started miracle-wifid:

ERROR: supplicant: wpas (pid:13253) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in /home/jze/src/miraclecast/src/wifi/wifid-supplicant.c:2338)
ERROR: supplicant: wpas (pid:13254) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in /home/jze/src/miraclecast/src/wifi/wifid-supplicant.c:2338)
ERROR: supplicant: wpas (pid:13255) failed again.. entering grace period, waiting 30s before relaunching (supplicant_failed() in /home/jze/src/miraclecast/src/wifi/wifid-supplicant.c:2342)

**Comment by albfan** [comment]
configure is a file dependant on your system, you need to run ./autogen.sh script to get it.

/usr/local is fine, but you need to be sure that dbus are deployed in correct path . local prefix will not work for dbus.

There're instructions on wiki faq to report info if you need help.

Does not work at all looks like unpolite way to ask for help, just in case you want to continue with this, read docs and try to provide info needed, and we can reopen this

**Comment by jze2** [comment]
1.) "....you need to run ./autogen.sh script to get it."
The described cmake way of compiling does not mention it.

2.) "..... dbus are deployed...."
dbus is a communication system, dbus daemon is up and running. If you app needs some configuration for connecting to dbus, then it should be stated in the documentation. If it should be autodetected, then it obviously does not work.

3.) I am not asking for help, I just wanted to report the bug, if you still care:

Does my hardware supports miraclecast requirements: Check it running res/test-hardware-capabilities.sh:

command failed: No such device (-19)
cannot find physical device for wlx18a6f71c3993

and

led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5154]: Successfully initialized wpa_supplicant
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5154]: nl80211: Driver does not support authentication/association or connect commands
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5154]: nl80211: deinit ifname=wlx18a6f71c3993 disabled_11b_rates=0
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5154]: wlx18a6f71c3993: Failed to initialize driver interface
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5155]: Successfully initialized wpa_supplicant
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5155]: nl80211: Driver does not support authentication/association or connect commands
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5155]: nl80211: deinit ifname=wlx18a6f71c3993 disabled_11b_rates=0
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5155]: wlx18a6f71c3993: Failed to initialize driver interface
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5156]: Successfully initialized wpa_supplicant
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5156]: nl80211: Driver does not support authentication/association or connect commands
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5156]: nl80211: deinit ifname=wlx18a6f71c3993 disabled_11b_rates=0
led 30 23:54:53 n1 miracle-wifid-wlx18a6f71c3993-5[5156]: wlx18a6f71c3993: Failed to initialize driver interface


while I am writing this connected through the device, so just your code does not work.

**Comment by albfan** [comment]
Cmake do not use configure. Why you mention then that? Autoreconf generate that file for autoconf

**Comment by albfan** [comment]
res/CMakeLists.txt

You can see there dbus policy is installed

If you don't know how to use a buildsystem (install step) try to no act so entitled, only show arrogancy.

**Comment by jze2** [comment]
1.) In the documentation the use of configure is mentioned outside building wiki for each tool which of course suggests it is generic and not just for non-cmake ways. So I suggest you put it in the building wiki to the autotools section. Unless you made the documentation just as a hint for yourself to remember and not for general public. Not everybody uses cmake on daily basis.

2.) "res/CMakeLists.txt
      You can see there dbus policy is installed"
OK, now I understand: "....but you need to be sure that dbus are deployed in correct path...." You meant "....but you need to be sure that dbus POLICY IS deployed in correct path...". Sorry, my telepathic abilities faded a bit recently :-)

Yes, it is installed in the correct path (among other policies):

$ cat /etc/dbus-1/system.d/org.freedesktop.miracle.conf
<?xml version="1.0"?> 
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
        "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">



<busconfig>

...
...


3.) I don't know why are you mentioning building and the d-bus policy at all as the build obviously passed without error and the
application doesn't say something like "Cannot connect to d-bus..." or anything related to d-bus, it just says something about supplicant failing for unknown reason with "wlx18a6f71c3993: Failed to initialize driver interface" in the log without stating why.
That looks like just "Error, bitch!" with the same usefulness....

**Comment by albfan** [comment]
configure is not mentioned at all for cmake: https://github.com/albfan/miraclecast/wiki/Building#cmake

if you talk about configure, I talk about autotools, where sysconfdir defaults to /usr/local if not forced:

https://github.com/albfan/miraclecast/blob/master/autogen.sh#L17

I'm unsure why you keep insisting in this subject, I just want to denote, that your way to expose your problem was incorrect, unpolite and kind of rude.

Simply asking for help, instead of "not working at all", asking for scripts you're not using (misleading), I'm resilent to this kind of issues, because you took the time to report something here, so probably we can turn all that energy into something useful, but don't expect this kindness from other open source projects, usually people do not tolerate that.

There's a FAQ about how to provide info if you have problems: https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support

I will be glad to help to troubleshoot that, but probably there're matching feedback in existing issues.
