### ISSUE TITLE
MiracleCast  fail on Windows 11 1st) As Sink do not Accepts peer connection, 2nd) as Peer do not connect

### ISSUE THREAD

**Issue by OliveiraICTS** [albfan/miraclecast#431]
I detected it feils when I tryed to stablish sessin with Windows 11.
When I use as Sink, pressed Windows-K and tryed to  pair with MiracleCast I got bellow fail:
DEBUG: supplicant: unhandled wpas-event: <3>P2P-INVITATION-RECEIVED sa=02:05:16:61:ce:07 go_dev_addr=02:05:16:61:ce:07 bssid=12:05:16:61:ce:07 unknown-network (supplicant_event() in src/wifi/wifid-supplicant.c:1505)
When I use as Peer, MiracleCast detects Sink, but when I tryed to stablish session it also fail.
Important:- When I used as Sink and paired with Android Device it works propperly. I Didnt tested as Peer because I do not have SmartTV with Miracast over WIFI.

Question:- What is required to do when received message: P2P-INVITATION-RECEIVED??? wifid-supplicant.c do not proccess it event.

**Comment by albfan** [comment]
Microsoft extends the miracast protocol.

See #136

**Comment by OliveiraICTS** [comment]
Thank you!
Looking logging Microsoft has omplemented WPA2 and it implements WPA1. By the way, my Android Device works propperly.

**Comment by jinhui123789** [comment]
DEBUG: supplicant: unhandled wpas-event: <3>P2P-INVITATION-RECEIVED sa=02:05:16:61:ce:07 go_dev_addr=02:05:16:61:ce:07 bssid=12:05:16:61:ce:07 unknown-network (supplicant_event() in src/wifi/wifid-supplicant.c:1505)
Is there any solution to this problem

**Comment by jinhui123789** [comment]
DEBUG: supplicant: unhandled wpas-event: <3>P2P-INVITATION-RECEIVED sa=02:05:16:61:ce:07 go_dev_addr=02:05:16:61:ce:07 bssid=12:05:16:61:ce:07 unknown-network (supplicant_event() in src/wifi/wifid-supplicant.c:1505)

Is there any solution to this problem

**Comment by OliveiraICTS** [comment]
Hello!!
Windows uses Miracast Microsoft Extensions.  The M3 GET_PARAMETERS from windows sends a list of windows required parameter response it needs. So, Miraclecast has a feature with allow add mocked defalut responses for each one of them. If you fill the correct value Miraclecst works on Windows 11.  The care you must have is to answare feature you really sopport, because is you sends a feature that you do not support and the source support it will try to use and you will not be able to work.  Other important thing is UIBC. Miraclecast only support limited UIBC events and when I tested them it didnt works propperly because I didnt see UIBC events being send back on it channel.
