### ISSUE TITLE
Token in custom CMake command interpreted as invalid $-escape

### ISSUE THREAD

**Issue by JosiahWI** [albfan/miraclecast#432]
## Summary
```
ninja: error: build.ninja:1176: bad $-escape (literal $ must be written as $$)

  COMMAND = cd /home/mezhir/code/prgm/miraclecast/test && for i in $(MEM...
                                                                   ^ near here
```

This is likely caused by a command intended for a Makefile feature that Ninja doesn't support, as was the case in this issue here: https://gitlab.kitware.com/cmake/cmake/-/issues/20130

The build log in #346 suggests that Ninja can be used with the Meson build, so it would be nice to have Ninja support for the CMake build as well.

## OS Version
- Debian Bullseye

## Package Versions
- CMake 3.18.4
- Ninja 1.10.1

## Steps to Reproduce
```
git clone git@github.com:albfan/miraclecast.git
cd miraclecast
cmake -S . -G Ninja
```

**Comment by albfan** [comment]
Fixed on 0b72e0b
