### ISSUE TITLE
cant get int to work on debian bullseye

### ISSUE THREAD

**Issue by nanderer** [albfan/miraclecast#433]
Hi,

thanks a lot for providing me the tools to stream to my beamer-laptop live using mirracast, unfortunately i wasnt able to get it to work on debian bullseye (11).

i was fortunately able to build it and install it using checkinstall using your guide, ill attach the debian package here, but i cant get it to work as a sink  using 

```
t@tp:~/git/miraclecast/build$ bg
[1]+ sudo miracle-wifid &
t@tp:~/git/miraclecast/build$ sudo miracle-sinkctl
[ADD] Link: 3
[miraclectl] # run 3
ERROR: supplicant: invalid arguments (supplicant_p2p_start_scan() in /home/t/git/miraclecast/src/wifi/wifid-supplicant.c:2009)
ERROR: cannot change p2p-scanning state on link 3 to 1: Invalid argument (ctl_link_set_p2p_scanning() in /home/t/git/miraclecast/src/ctl/ctl-wifi.c:739)
now running on link 3
(failed reverse-i-search)`': 
(failed reverse-i-search)`': 
quitaclectl] # search)`': 
[miraclectl] # 


```

**Comment by nanderer** [comment]
seams like github dosnt allow .deb but .gz file (for some obscure reason) so you have to download
[miraclecast_0b72e0b4358b4908daf_build_at_20220331-for_debian_bullseye_amd64_by_mrt.deb.gz](https://github.com/albfan/miraclecast/files/8392951/miraclecast_0b72e0b4358b4908daf_build_at_20220331-for_debian_bullseye_amd64_by_mrt.deb.gz)
and than to ``gunzip``  bfore you can use ``dpkg -i`` to install (or just compile it your self)

**Comment by albfan** [comment]
@nanderer you're supposing others cannot build and run miraclecast? I will remove the irrelevant comments about deb package or dependencies you might now. that has nothing to do with your issue

**Comment by albfan** [comment]
You need to stop existing wpa_supplicant (which is not configured to create wifi direct interfaces. that should be stop network manager or similar.

In wiki there's a faq to provide logs for support. Probably on journalctl it will show that your wpa_supplicant is not correct. Closing this as that is probably the reason. We can reopen if you provide needed logs
