### ISSUE TITLE
Device connected but display not coming

### ISSUE THREAD

**Issue by shreysway** [albfan/miraclecast#438]
Hi my device gets successfully connected now but display not coming on tv
[journal.log](https://github.com/albfan/miraclecast/files/8644832/journal.log)
[sink.log](https://github.com/albfan/miraclecast/files/8644833/sink.log)
[wifiid.log](https://github.com/albfan/miraclecast/files/8644834/wifiid.log)

**Comment by shreysway** [comment]
working

**Comment by weishusheng** [comment]
I have encountered the same problem. Is there any solution?

**Comment by albfan** [comment]
@weishusheng share your logs an analyze
