### ISSUE TITLE
Miraclecast Lag issue

### ISSUE THREAD

**Issue by monabharti** [albfan/miraclecast#440]
I am using ubuntu 18 as sink and tring to connect my android phone. it display my device but it takes 40-45 seconds to connect and display player also sometimes player get stuck and stop.

please suggest what should i do to reduce lag and how to save stream in h264 file. I m new to C++.

**Comment by albfan** [comment]
You should provide los for support as describes in wiki faq.

Store video is out of scope of this project, but you can extend player as describes on wiki to record the video stream.

This project uses C, no C++

**Comment by monabharti** [comment]
The data that we are streaming and playing it in vlc, we want to send /stream data to custom application. My current custom application is accepting data in .h264 format and playing it. Any suggestion on that will be helpful

**Comment by monabharti** [comment]
@albfan please help

**Comment by albfan** [comment]
In wiki you have examples on how to run a custom player:

https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#external-player

there're examples on `res` directory like https://github.com/albfan/miraclecast/blob/master/res/miracle-vlc

if you want to turn the video into h264 you need to adapt https://github.com/albfan/miraclecast/blob/master/res/miracle-gst to turn video to h264 and pipe to your app

**Comment by raghwendra2022** [comment]
Getting below error. Please support.

ERROR: supplicant: wpas (pid:10250)
failed unexpectedly, relaunching after short grace period..
(supplicant_failed() in
/home/ajit/miraclecast/src/wifi/wifid-supplicant.c:2338)

**Comment by albfan** [comment]
@raghwendra2022 comment on other issue is misleading. Please open your own issue. I'm deleting your comment

**Comment by albfan** [comment]
As far as I can tell, answer provided
