### ISSUE TITLE
SIGCHLD starting miracle-wifid

### ISSUE THREAD

**Issue by aditcoding** [albfan/miraclecast#45]
sudo miracle-wifid --wpa-bindir /sbin --log-level 8 &
    [1] 25868
    adi@adi:~/miraclecast/res$ 
    INFO: miracle-wifid - revision some-rev-TODO-xyz Apr 29 2015 23:35:15
    DEBUG: friendly-name from local hostname: adi (manager_read_name() in wifid.c:355)
    DEBUG: link: new link: wlan0 (3) (link_new() in wifid-link.c:71)
    DEBUG: supplicant: new supplicant for wlan0 (supplicant_new() in wifid-supplicant.c:2062)
    INFO: link: add link: wlan0
    INFO: link: manage link wlan0
    DEBUG: supplicant: start supplicant of wlan0 (supplicant_start() in wifid-supplicant.c:2543)
    DEBUG: supplicant: spawn supplicant of wlan0 (supplicant_spawn() in wifid-supplicant.c:2391)
    INFO: supplicant: wpas spawned as pid:25871
    ERROR: supplicant: wpas (pid:25871) failed unexpectedly, relaunching after short grace period.. (supplicant_failed() in wifid-supplicant.c:2287)
    DEBUG: supplicant: terminating wpas (pid:25871) (supplicant_failed() in wifid-supplicant.c:2302)
    DEBUG: supplicant: close supplicant of wlan0 (supplicant_close() in wifid-supplicant.c:2266)
    DEBUG: caught SIGCHLD for 25871, reaping child (manager_signal_fn() in wifid.c:163)

**Comment by aditcoding** [comment]
So the supplicant wpa keeps failing and when I do "sudo miracle-sinkctl" the output is just a prompt like this "[miraclectl] #". I am on ubuntu 15.04

**Comment by albfan** [comment]
did you kill previous wpa connections?

**Comment by albfan** [comment]
These error can also happen if you have more than one avaliable interface

See there's a recent option added to solve these

https://github.com/albfan/miraclecast/blame/master/README.md#L64

**Comment by aditcoding** [comment]
I got this working. I have a question though. I have a Samsung smart tv which is miracast enabled. Now how can I cast my ubuntu screen to the tv? In other words, how can I use my laptop as source and the tv as sink?

**Comment by albfan** [comment]
Great!

There is a `miracle-wifictl` to expose your laptop as a source.

    $ sudo miracle-wifictl
    [miracle-wifictl] select <your peerr number>
    [miracle-wifictl] connect <destination mac> prov pin
    
But after pairing, there's no implementation of any stream protocol

I will close these issue, please for different issue open a new one.

**Comment by aditcoding** [comment]
So after pairing, I can't mirror my laptop screen on tv since there is no implementation?

**Comment by albfan** [comment]
I'm looking on github api to translate this to a new issue. See this is not a forum, people will come to this issue for SIGCHLD error.

It would be easy if you delete the new questionand open a new issue

**Comment by aditcoding** [comment]
Ok. I raised a new issue. Thank you for all the help on this issue.

**Comment by suiye223** [comment]
After pairing ,I find that my phone act as GO,
DEBUG: supplicant: start local group on new group p2p0 as Client/0
but now I want the phone act as GC, can you give any suggestion?
tanks.

**Comment by albfan** [comment]
Please @suiye223 create a new issue for your question. Something like "Config the go_intent"

First try to setup that on config

https://wireless.wiki.kernel.org/en/developers/p2p/howto

> \# If you need to modify the group owner intent, 0-15, the higher
> \# number indicates preference to become the GO. You can also set
> \# this on p2p_connect commands.
> \#p2p_go_intent=15

so p2p_go_intent=0 is probably what you're looking for

I will remove these last comments, if problem persists open a new issue
