### ISSUE TITLE
Build error in ubuntu 22.04

### ISSUE THREAD

**Issue by xliang-lifesize** [albfan/miraclecast#464]
There is build error in ubuntu 22.04 which caused by the newer gcc
This is the patch can fix it.

```
diff --git a/src/dhcp/CMakeLists.txt b/src/dhcp/CMakeLists.txt
index 7ae3e30..d7f8b7b 100644
--- a/src/dhcp/CMakeLists.txt
+++ b/src/dhcp/CMakeLists.txt
@@ -13,6 +13,7 @@ add_executable(miracle-dhcp ${miracle-dhcp_SRCS})
 find_package(PkgConfig)
 pkg_check_modules (GLIB2 REQUIRED glib-2.0)
 pkg_check_modules (UDEV REQUIRED libudev)
+target_link_libraries(miracle-dhcp miracle-shared)
 link_directories( ${UDEV_LIBRARY_DIRS})
 include_directories( ${UDEV_INCLUDE_DIRS})
 target_link_libraries(miracle-dhcp ${UDEV_LIBRARIES})
@@ -21,7 +22,6 @@ link_directories( ${GLIB2_LIBRARY_DIRS})
 include_directories( ${GLIB2_INCLUDE_DIRS})
 target_link_libraries(miracle-dhcp ${GLIB2_LIBRARIES})

-target_link_libraries(miracle-dhcp miracle-shared)

 install(TARGETS miracle-dhcp DESTINATION bin)
 INCLUDE_DIRECTORIES(${CMAKE_BINARY_DIR} ${CMAKE_SOURCE_DIR}/src ${CMAKE_SOURCE_DIR}/src/shared)
```

**Comment by albfan** [comment]
Build for cmake on latest commit from master:

https://albfan.semaphoreci.com/jobs/0a20a300-db7f-4777-942c-6265823d8d88

how is it possible that a change in order makes a difference?

I use this image for CI

https://hub.docker.com/layers/albfan/miraclecast-ci/latest/images/sha256-1054c0555ac2344f1322ff0a522523797c21783ebf234259ff8dda43af43e939?context=explore

probably move to github actions is a good idea, but still I need more info to make that change, seems irrelevant

**Comment by xliang-lifesize** [comment]
I am not sure why this happen. But looks like the link lib order need be correct

**Comment by albfan** [comment]
From this comment, looks as you mention, order is relevant for this

https://stackoverflow.com/a/34513053/848072

Let me know if you can provide a PR (to be properly credited)

**Comment by SvenDowideit** [comment]
this also hit me on 22.04 , and the diff above was enough to resolve it for me - @albfan or @xliang-lifesize

**Comment by xliang-lifesize** [comment]
> 

Hi @albfan,

I am really sorry I missed this comment. 

I tried to create a PR, but I failed with push the PR by user error. Looks like I don't have the correct user for this project. Or I didn't push it correct.
Could you help to create the PR? I found the issue and have the fix. But I learned from the stackoverflow too. So, the credit should go to everyone. 

Happy new year!

**Comment by albfan** [comment]
@xliang-lifesize we only need a name and email like the one you provide on:

git config user.name
git config user.email

https://github.com/albfan/miraclecast/pull/472 should be enough, but let me know those details to properly credit you

**Comment by xliang-lifesize** [comment]
> @xliang-lifesize we only need a name and email like the one you provide on:
> 
> git config user.name git config user.email
> 
> #472 should be enough, but let me know those details to properly credit you

Hi @albfan 
Here is my config
user.name: Xiao Qiang Liang
user.email: xliang@lifesize.com

Thank you.
