### ISSUE TITLE
Connect fail

### ISSUE THREAD

**Issue by fromhell333** [albfan/miraclecast#469]
I install miraclecast on a device with Debian 10.
I can found the miraclecast device on my Android phone and Windows 10 PC
but can't successfully connect to it.

Here is the log,
please help to check it
Thank you

[dbus.log](https://github.com/albfan/miraclecast/files/10153257/dbus.log)
[journal.log](https://github.com/albfan/miraclecast/files/10153258/journal.log)
[sink.log](https://github.com/albfan/miraclecast/files/10153259/sink.log)
[wifid.log](https://github.com/albfan/miraclecast/files/10153260/wifid.log)

**Comment by albfan** [comment]
You have a typo on miracle-sink (log-level trace, no --log-level tarce)

You run twice miracle-wifid:

> INFO: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: it is already being acquired

So this wifid.log do not show what's going on with your connection. There we should see what happen with connection.

there's no evidence that conection happens, that should be shown on miracle-sinkctl.

**Comment by fromhell333** [comment]
Thanks for your reply
I re-upload the log
Thanks

[journal_1209.log](https://github.com/albfan/miraclecast/files/10193133/journal_1209.log)
[wifid_1209.log](https://github.com/albfan/miraclecast/files/10193135/wifid_1209.log)
[sink_1209.log](https://github.com/albfan/miraclecast/files/10193137/sink_1209.log)

**Comment by albfan** [comment]
From this logs, it starts to connect at 08:28:11, group was formed correctly and dhcp shared. So the disconnect was done by the other side.

I cannot tell what was wrong for the other device, we can reopen if you can collect info for it.

Sometimes it works after try few times
