### ISSUE TITLE
cannot claim org.freedesktop.miracle.wifi bus-name: it is already being acquired

### ISSUE THREAD

**Issue by zlz3132** [albfan/miraclecast#474]
Hi~  ,
when  I  execute Cmd  /miracle-wifid --log-level trace,  connect fail and show that : 
INFO: miracle-wifid - revision 1.0 Jan 31 2023 14:38:29
INFO: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: it is already being acquired
DEBUG: exiting.. (main() in ../../../src/wifi/wifid.c:644)

my miraclecast githut commit id :commit f3debd5678e7699dfd8acfdcc77fda64e9509cae
systemd version : systemd 241 (241)
also cp res/org.freedesktop.miracle.conf /etc/dbus-1/system.d/

please help me check if sth  lack, thanks!

**Comment by zlz3132** [comment]
this issue is I run twice miracle-wifid

**Comment by albfan** [comment]
@zlz3132 great for you to find it!
