### ISSUE TITLE
wpa_supplicant or driver does not support P2P

### ISSUE THREAD

**Issue by zlz3132** [albfan/miraclecast#475]
From the log,I saw:

```
WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in ../../../src/wifi/wifid-supplicant.c:1718)
```

review the code :

```
wpas_message_dict_read(reply, "p2p_state", 's', &p2p_state);
```

p2p_state return value is false

but i input cmd 

```
./test-hardware-capabilities.sh 
wlan0 supports P2P
```

[miracast-wifid.log](https://github.com/albfan/miraclecast/files/10544294/miracast-wifid.log)

**Comment by Ergus** [comment]
Hi:
Any progress on this? I am having EXACTLY the same problem.

**Comment by albfan** [comment]
to me looks like you didn't stop the current networkmanager, so wpa_supplicant didn't start the interface with P2P support.

the log attached is not enough

Closing until logs for support are added as wiki describes in fact
