### ISSUE TITLE
RPI4 cannot peer with any device as sink

### ISSUE THREAD

**Issue by Wh1t3s0ul** [albfan/miraclecast#483]
I am running yocto linux. Like you will see from the logs the rpi4 cannot keep a peer.
test sequence:

```
rfkill unblock all
iw dev wlan0 set power_save off
killall wpa_supplicant
```

wpa_supplicant service is disable.
dont have NetworkManager

```
miracle-wifid --use-dev --log-level trace |& tee log

miracle-sinkctl --log-level trace |& tee log
>run 3
...
```

[journal.log](https://github.com/albfan/miraclecast/files/11069729/jour.log)
[wifid.log](https://github.com/albfan/miraclecast/files/11069728/newf_pc.log)
[sink.log](https://github.com/albfan/miraclecast/files/11069732/sink.log)

PS: the sink log is from another test try, but the content is the same only the mac is different

**Comment by albfan** [comment]
Please check latest update for `Log for support` in wiki. It adds parameters to add timestamps to logs, so understand what's going on is easier to correlate.

For sure you need to attach all captures for same session, if no that would be missleading and impossible to figure out

we can reopen if you attach correct info

**Comment by Wh1t3s0ul** [comment]
Hi,
sorry for the cheep logs and description.
I saw the problem with peering(the ip was in /sbin not in /bin) , now I can connect, but another pops up

It seems I have problem, starting the player correctly 
[logs.zip](https://github.com/albfan/miraclecast/files/11071399/logs.zip)

**Comment by albfan** [comment]
Yes, default route for ip can be configured or set at runtime.

I'm unsure if this issue is then still valid for that question you ask. Probably keep this as closed and open a new one with proper subject and description
