### ISSUE TITLE
Wiki documents tools that do not exist.

### ISSUE THREAD

**Issue by dreirund** [albfan/miraclecast#486]
[The Wiki](https://github.com/albfan/miraclecast/wiki) documents some tools which do not exist (at least in the standard installation after `make` and `make install`, and also not in the `res/` folder of the source tree):

* [`miracle-dispctl`](https://github.com/albfan/miraclecast/wiki/miracle-dispctl),
* [`miracle-dispd`](https://github.com/albfan/miraclecast/wiki/miracle-dispd), also mentioned in the article for [miracle dispctl](https://github.com/albfan/miraclecast/wiki/miracle-dispctl).

On the other hand, I have the following executables where I cannot find documentation for:

* `miracled`,
* `miracle-dhcp`,
* `miracle-gst`,
* `miracle-omxplayer`
* `miracle-uibcctl`.

**Comment by albfan** [comment]
Those are for the WIP of running as source. See #4 

miracled: is a general daemon, not implementes yet
miracle-dhcp: controls the IP assigment on wifi direct
miracle-gst: the basic stream player provided based on gstreamer
miracle-omxplayer: an example to use omxplayer as player
miracle-uibcctl: is the daemon that listen to UIBC commands (user input back channel). On gstplayer you see an implementation that listen to mouse events and outputs to standard output. That is read by miracle-uibc and sent to source device

**Comment by dreirund** [comment]
And what about the wiki pages about the non-existing executables? Should they be deleted?

**Comment by albfan** [comment]
Just added this note:

> NOTE: This is from WIP source PR

but is mentioned here: https://github.com/albfan/miraclecast/wiki/Internals#wip

I added the other commands in that wiki page too
