### ISSUE TITLE
Audio supported?

### ISSUE THREAD

**Issue by peterdk** [albfan/miraclecast#487]
Hi, I am trying to get a mirror of my Android device (Samsung Note) to Ubuntu 23.04. It works great with displaying the phone's screen. However, the audio is not mirrored. I was wondering, is that indeed not possible? On windows with AirServer it works without issue, but I want to stay on Linux for this. 

I don't see anything mentioned in the docs about audio, so I am wondering if it's indeed not possible.

**Comment by peterdk** [comment]
So, just to update my findings. I did see a audio option in the sink ctl. It is on by default. It turns out that when I connect VLC to the proper port, I do get audio. So I think the default gst stream handler just doesn't support my audio type. It working now, great!

**Comment by albfan** [comment]
There're gstreamer plugins you need to install. Probably that's your problem See FAQ to test if you install all needed plugins
