### ISSUE TITLE
ubuntu22.04 sink cannot connect

### ISSUE THREAD

**Issue by chengpings** [albfan/miraclecast#496]
Hello, please analyze the log.[log.zip](https://github.com/albfan/miraclecast/files/12681046/log.zip)

asus@asus-UX303LB:~/work/miraclecast-master/res$ ./test-hardware-capabilities.sh
wlp2s0 supports P2P

 asus@asus-UX303LB:~/work/miraclecast-master/res$ ./test-viewer.sh
testing plugins required:

test udpsrc... (passed)
test rtpjitterbuffer... (passed)
test rtpmp2tdepay... (passed)
test tsdemux... (passed)
test h264parse... (passed)
test avdec_h264... (passed)
test autovideosink... (passed)

everything installed

All dependent libraries should be installed，Please.

**Comment by chengpings** [comment]
After adding 'use dev' to Wifid, most Android devices are now able to screen, but Win11 cannot link to Sink. I don't know how to use the extensions. file. Could you please tell me how to use the miraclecast ini file method?

**Comment by albfan** [comment]
Is documented on https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#extend-request-protocol and there's an example for extensions microsoft needs (the only one detected to need changes)
