### ISSUE TITLE
Compilation with `--enable-disable-systemd` fails with `/usr/bin/ld: cannot find -lsystemd: No such file or directory`: `src/shared/Makefile.am` unconditionally adds `-lsystemd`.

### ISSUE THREAD

**Issue by dreirund** [albfan/miraclecast#500]
When I build with `./configure --enable-disable-systemd`, compilation fails with  
```
/usr/bin/ld: cannot find -lsystemd: No such file or directory
```

It turns out that the file [`src/shared/Makefile.am`](https://github.com/albfan/miraclecast/blob/master/src/shared/Makefile.am#L20) has  
```
libmiracle_shared_la_LIBADD = -lsystemd \
[...]
```

which unconditionally adds a `-lsystemd`.

Removing that `-lsystemd` makes build without systemd working for me, but I don't know enough about the configuration system to give a fix that works conditionally weather `--enable-disable-systemd` is specified or not.

Regards!

**Comment by albfan** [comment]
Fixed on af6ab25

systemd dependency or elogind should come in DEP_LIBS

good catch!
