### ISSUE TITLE
Gstplayer image not fully shown.

### ISSUE THREAD

**Issue by oceanmar** [albfan/miraclecast#502]
Hi i tried miracast with “motorola ready for “ but the image shown is cut off even in fullscreen . Do i need to change settings of gstplayer? 

System:
Debian 12, xfce

**Comment by albfan** [comment]
You assume I know what "motorola ready for" is. I don't. 

Whatever that is, from point of view of miraclecast, it probably is just another miracast source. For any problem there's a FAQ in miraclecast wiki where collecting "logs for support" is described.

We can reopen if you provide logs. Probably some screenshots will help to understand the problem
