### ISSUE TITLE
Can't copy the dbus policy res/org.freedesktop.miracle.conf to /etc/dbus-1/system.d/

### ISSUE THREAD

**Issue by TheGitGubGuy** [albfan/miraclecast#503]
How do you do this on Ubuntu l. I have tried so many ways but all of them failed for some reason. Whenever I try to copy it using Thunar file manager It keeps on saying access tonight and I don't know how to open this with super user privileges.

**Comment by InsertX2k** [comment]
Open a new terminal window in the directory where you've cloned this repository in, then run the following command:
```sh
sudo cp -fv ./res/org.freedesktop.miracle.conf /etc/dbus-1/system.d/
```
then authenticate with your root password, and that's it.

**Comment by albfan** [comment]
install steps from different buildsystem do that for you. Not always these files goes to /etc

Look for sysconfdir in the buildsystem you choose (autotools, cmake or meson)
