### ISSUE TITLE
[Question] Flutter FFI Binding for micralecast

### ISSUE THREAD

**Issue by dinbtechit** [albfan/miraclecast#505]
Hi, I would like to write Flutter FFI wrapper for miraclecast. Can you give me any pointers on how can I achieve this?

I am planning on using dart-c-interop -> https://dart.dev/interop/c-interop. 

[![image](https://github.com/albfan/miraclecast/assets/17984781/fd53ce56-5ff2-4aa8-bede-b369c71d3f4d)](https://www.youtube.com/watch?v=2MMK7YoFgaA)

Any advice on how to interact with your c code. It would be very helpful! thank you.

**Comment by albfan** [comment]
this is not just a library. Is a daemon miracle-wifid interacting with wpa_supplicant to create a wifi direct interface ( a connection between wireless devices without a router)

After that there're two commands. miracle-sinkctl (if you want to act as sink (show other screen) or miracle-wifictl (if you want to act as source screen) but miracle-wifictl is not fully implemented.

both uses miracle-dhcp to assign ip in the created p2p interface. It fails to act as GO (Group owner)

So I'm unsure if you can just use ffi trampoline to make this work.

**Comment by dinbtechit** [comment]
Appreciate your response!  

This seems like bit more effort than I thought.  I would most likely have to execute the shell commands via the flutter app and use FFI for querying the device info etc (if there is an option within the app).  Thanks again.
