### ISSUE TITLE
Does it support TDLS ? Or infrastructure? Or Wi-Fi Direct?

### ISSUE THREAD

**Issue by simondss** [albfan/miraclecast#507]
I would like to know if this project supports TDLS, Wi-Fi Direct, and infrastructure. I saw in the miracast protocol specification that there are three mechanisms for device discovery. If this project supports them, how do I configure it to select which discovery mechanism to use? thanks!

**Comment by albfan** [comment]
Only Wifi Direct is implementes in this project
