### ISSUE TITLE
Unable to scan sink after startup(ubuntn:20.04  wifi driver:rtl8188)

### ISSUE THREAD

**Issue by jk1666** [albfan/miraclecast#518]
Here is the log:
$ sudo systemctl stop NetworkManager.service
$ sudo systemctl stop wpa_supplicant.service
$ sudo miracle-wifid &
 [1] 3022013

 $ sudo miracle-sinkctl 
    [ADD] Link: 35
>run 35
now running on link 35
>list
  LINK INTERFACE                FRIENDLY-NAME                  MANAGED   
  35 wlx347de441e4ef          <unknown>                      yes       
  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 
 0 peers and 1 links listed.

question:Always displaying 0 peers

**Comment by albfan** [comment]
Your source devices should show up. This info is not enough to check that. If your sources do not see your sink is there where you should check.

You can add logs as wiki FAQ says if you need more details.

closing by now as no option to investigate your problem
