### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in /home/rafa/miraclecast/src/wifi/wifid-dbus.c:943)

### ISSUE THREAD

**Issue by gitra123** [albfan/miraclecast#520]
compiled with CMAKE
test-hardware-capabilities: wlp1s0 supports P2P

**Comment by albfan** [comment]
Did you install?

Miraclecast needs a dbus policy

If you did most probably you need to restart

Check wiki FAQ for instructions on how to collect logs for support

**Comment by gitra123** [comment]
Thanks, worked, closing now
