### ISSUE TITLE
Disconnect sinkctl without quit/exit

### ISSUE THREAD

**Issue by nir-ontar** [albfan/miraclecast#523]
I am working with this repo for some time and everything is working perfectly. 

So first of all great work!

Now, I am working with my android phone, mirroring it to my Ubuntu.

If I want to disconnect an active link I can do one of two options:
- disconnect on the android side. This way the Ubuntu side detects the disconnection and waits for the next new connection.
- quit/exit on the Ubuntu side (miracle-sinkctl). The program **exits** and the android detects the disconnection.

I want to disconnect the active link from the Ubuntu side but keep miracle-sinkctl **running** and waiting for the next connection.

Is it possible? (I don't want to re-run every time)

**Comment by albfan** [comment]
There's no such "stop"/"disconnect" command on miracle-sinkctl.

But with autocmd, kill miracle-sinkctl and rerun with "run X" where X is your desired interface, should do exactly what you need ( restart a cli ready to be used as sink).

Why is It a problem to rerun but no to retype some parameters?

A simple use case might help to understand what this will solve
