### ISSUE TITLE
Is this software still being maintained?

### ISSUE THREAD

**Issue by InsertX2k** [albfan/miraclecast#525]
Is Miraclecast still maintained?, Taking into consideration the fact that the latest change done on the code was like 9 years ago

**Comment by albfan** [comment]
Last change is from 13 Jul 2024.

Anyway some big features are long delayed like #4 or #75. PR welcome!

**Comment by InsertX2k** [comment]
> Last change is from 13 Jul 2024.
> 
> Anyway some big features are long delayed like #4 or #75. PR welcome!

Thank you for the clarification, I closed this as I just noticed that.
