### ISSUE TITLE
SIGSEGV in miracle-sinkctl on peer connect

### ISSUE THREAD

**Issue by nethack42** [albfan/miraclecast#53]
Hi,
after a lot of trail and error I finally got miracle-cast working (at least my phone is able to discover the sink). The problem occurs as soon as I try to start mirroring my phone screen. miracle-sinkctl crashes with a segmentation fault instantly. 

My current setup:
Ubuntu 15.04 (amd64)
wpa_supplicant (2.4; build from [source](https://launchpad.net/ubuntu/+source/wpa/2.4-0ubuntu1) since 2.1 results in 'wifi-direct not supported')
miracle-cast (build from source; master branch)

I have been able to track down the problem at least a bit:

The SIGSEGV is raised by [sd_bus_message_is_signal()](https://github.com/albfan/miraclecast/blob/master/src/ctl/ctl-wifi.c#L885) in ctl-wifi.c

The first two lines of gdb's backtrace look like:

```bash
0 0x0007ffff7946c7 in sd_bus_message_is_signal() from /lib/x86_64-.../libsystemd.so.0
1 0x00000000406bfa in ctl_wifi_properties_fn(m=0x617010, data=0x63b530, err=<optimized out>)
```

I also looked up the source of sd_bus_message_is_signal which (at least according to [this](http://www.freedesktop.org/software/systemd/coverage/libsystemd/sd-bus/bus-message.c.gcov.html#1078)) already checks if the message struct pointers (interface and member) are valid. Only m->header is not checked. So I assume this one is to blame.

Cheers,
Patrick

**Comment by albfan** [comment]
Let me know your systemd version

    $ systemctl --version

And your commit hash for miraclecast version

    $ miracle-wifid --version

Those sigsev sounds like incompatible systemd version (configure is not tied to a recent systemd version to give some flexibility, but maybe is time to define it correctly)

**Comment by nethack42** [comment]
```bash
$ systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN

$ miracle-wifid --version
miracle 1
```

Maybe it is also interesting to know that as soon as sinkctl crashes it is not possible to relauch it or miracle-wifictl unless the peer canceled the connection or miracle-wifid is restarted.

**Comment by albfan** [comment]
Systemd is a project with a quickly codebase change, moreover when it's expected to be the replace to sysvinit.

If you see this commits, related issues and systemd linked commits:
https://github.com/albfan/miraclecast/commit/b0f985069c1225c2df59b717855e44a8e0634e35
https://github.com/albfan/miraclecast/commit/756535a61d4ddcaab13639af09e22e5cf33502b6
https://github.com/albfan/miraclecast/issues/30
https://github.com/albfan/miraclecast/issues/35

on systemd version 219 happens some critical interface changes. A sigsev is always a good clue of public interfaces changed. You need to find what changes affect to you and what don't. checkout those commits detached and test wheter it works for you.

As I say I will fix autools config to avoid OS based on old systemd version to compile miraclecast version not compatible

Here is the blame:

https://github.com/albfan/miraclecast/blob/master/configure.ac#L47

I bet if you do a rebase removing those interface changes, you could get a compatible version 1 of miraclecast with systemd 219.

If you get that to work I will be glad to open a "219 branch" for those OS and I promise to start to tag miraclecast to avoid confusion on dependencies.

**Comment by albfan** [comment]
Expect updates on #54 about your problem. I would close this issue. I left that decision to you. Refer this or that issue on a PR

**Comment by nethack42** [comment]
Ok, I'll try to get it working with systemd 219 when I have some free time left. I'll send a PR afterwards.

**Comment by albfan** [comment]
I have created https://github.com/albfan/miraclecast/tree/systemd-219. It is master branch rebased to remove callback interface changes on systemd on +219 versions. Chances that this works out of the box for you are high. If it continues giving sigsev, check your exact version of systemd and see if you need to cherry-pick one of those interface change commits.

Feel free to ask anything. Many people can benefit from this.

**Comment by nethack42** [comment]
The new systemd-219 branch now works for me! Thanks a lot!

**Comment by albfan** [comment]
Glad to hear it. Thanks to you, Ubuntu community is again on the go.
