### ISSUE TITLE
Add information, how to build/use miraclecast with Ubuntu 15.10 to the README.md 

### ISSUE THREAD

**Issue by supertobi** [albfan/miraclecast#55]
At the moment there is only information about Ubuntu 15.04.

**Comment by albfan** [comment]
Uhmm, seen this:

https://launchpad.net/ubuntu/wily/+package/systemd

ubuntu 15.10 uses systemd 225, so you can use master branch to get it working.

To get systemd (not my business, but gived the nightmare to build a package on ubuntu I will give you a few tips) 

There is a repo with freedesktop pristine copies and tweaks for debian an ubuntu.

https://anonscm.debian.org/cgit/pkg-systemd/systemd.git

basically, ubuntu takes a vanilla release from freedesktop 

http://www.freedesktop.org/software/systemd/

and tweak it in a series of patches, waiting for them to be included in next release of freedesktop or maintain till is accepted. Find your exact version and checkout, I guess it would be:

get the upstream:

    $ git clone git://anonscm.debian.org/pkg-systemd/systemd.git

add the tweaks to get systemd with kdbus

    $ git remote add miraclecast https://github.com/albfan/systemd-ubuntu-with-dbus.git
    $ git fet
rebase that on your desire version

    $ git checkout rebase 219-7ubuntu3..miraclecast/master --onto ubuntu/225-1ubuntu9

fix what is wrong if something

generate package

    $ git-buildpackage -S -us -uc -nc

If that does not work follow more handmade instructions on https://github.com/albfan/systemd-ubuntu-with-dbus

install new systemd package
install miraclecast

test it

send a PR with your work to https://github.com/albfan/systemd-ubuntu-with-dbus.
      

at this moment

**Comment by albfan** [comment]
Uhmm, seen this:

https://launchpad.net/ubuntu/wily/+package/systemd

ubuntu 15.10 uses systemd 225, so you can use master branch to get it working.

To get systemd (not my business, but gived the nightmare to build a package on ubuntu I will give you a few tips) 

There is a repo with freedesktop pristine copies and tweaks for debian an ubuntu.

https://anonscm.debian.org/cgit/pkg-systemd/systemd.git

basically, ubuntu takes a vanilla release from freedesktop 

http://www.freedesktop.org/software/systemd/

and tweak it in a series of patches, waiting for them to be included in next release of freedesktop or maintain till is accepted. Find your exact version and checkout, I guess it would be:

1. get the upstream:

    $ git clone git://anonscm.debian.org/pkg-systemd/systemd.git

2. add the tweaks to get systemd with kdbus

    $ git remote add miraclecast https://github.com/albfan/systemd-ubuntu-with-dbus.git
    $ git fetch --all

3. rebase last tweaks to your desire version:

    $ git checkout rebase 219-7ubuntu3..miraclecast/master --onto ubuntu/225-1ubuntu9

4. fix what is wrong if something is (hack,hack,hack)

5. generate package

    $ git-buildpackage -S -us -uc -nc

If that does not work follow more handmade instructions on https://github.com/albfan/systemd-ubuntu-with-dbus

6. install new systemd package
7. install miraclecast
8. test it
9. If everything works send a PR with your work to https://github.com/albfan/systemd-ubuntu-with-dbus.
      
Feel free to ask anything, I can guide you through this pain if you don't miss the faith at some point.

**Comment by albfan** [comment]
See update README.md on https://github.com/albfan/systemd-ubuntu-with-dbus to build your own package for ubuntu 15.10
