### ISSUE TITLE
Support for UIBC

### ISSUE THREAD

**Issue by alexhumphreys** [albfan/miraclecast#57]
Hey there,

Just wondering, does Miraclecast support UIBC, and if not are there plans to add support for it?

Cheers,
Alex

**Comment by albfan** [comment]
Definitely UIBC rocks!. You're not the first to ask about this.

Once paired, that's just another stream behind miracast protocol.

Can you do some research about this?

I will contact a couple of experts and see what is needed to implement but I can't promise anything

**Comment by albfan** [comment]
http://es.scribd.com/doc/250439511/Wi-Fi-Display-Technical-Specification-v1-0-0#scribd

Read page 50 for more info

See table 4.6 for message structure on input events

**Comment by alexhumphreys** [comment]
Hey hey,

Thanks for getting back to me and for sending on the specs. I may end up looking into this over the next 2 months, but the project details ain't confirmed yet unfortunately. If it does go ahead I'll keep you posted though. Cheers!

Alex

**Comment by albfan** [comment]
Follow https://github.com/01org/wds/issues/121 for another approach

**Comment by albfan** [comment]
I'm working on this. UIBC connection is working, and now only need to resolve the messages for different events.

Android open source project helps with this (but can find original source so use this)

https://github.com/jmyuan/JsonUtil/blob/master/frameworks/av/media/libstagefright/wifi-display/uibc/UibcMessage.cpp#L74

Documentation is here

https://www.wi-fi.org/downloads-registered/Wi-Fi_Display_Specification_v1.1.zip/Wi-Fi%2BDisplay%2BTechnical%2BSpecification%2Bv1.1/21848

after pair with uibc enable you can do nmap on source (the device) and check uibc port is open)

By now I'm composing messages with okteta and sending it through netcat.

Hope the get a working version soon

**Comment by albfan** [comment]
Implementation is finished. I'm refactoring code to upload an emulator and enable config for a mouse/keyboard/hidc report event window.

**Comment by heri16** [comment]
Looking forward to this! Miracast with UIBC is great for in-car PC.

**Comment by albfan** [comment]
@heri16 Is this an in-car PC? http://www.in-carpc.co.uk/

Seems like a windows OS. UIBC implementation will be agnostic about OS, but stream video is not at this point See #3 (Isolate from systemd).

**Comment by heri16** [comment]
In car PC that I intend to use is Linux and Android. I thought miracle cast
would help as the peer if it has UIBC support.

**Comment by heri16** [comment]
Thanks so much! Which platform has UIBC been tested on?

**Comment by albfan** [comment]
Great news!. I tested this from an arch linux distro to a an android 5.0.1 device, but core functionality (miracle-uibcctl) is not systemd dependant, so this must work in any platform (if rest of miraclecast would work in any platform, and that's not true by now)

I would love to confirm if it works from an windows 10 source (it should)

About multitouch support, from PyGtk perspective I do a little research and seems that using kivy

https://praveenlearner.wordpress.com/2013/12/17/kivy-open-source-python-library/

could be a right choice to do the job, but from miracle-uibcctl perspective it is implemented. You just need to add more points on mouse event message. Let me do a little explain from the mess this at this time:

Communication from viewer to uibc controller happens on bash pipe.

- [launch uibc-viewer](https://github.com/albfan/miraclecast/commit/1e69dd6dae5f2332face744b247dbeb72036e0cf#diff-847d97cb50c996b8fe585c689f550df6R393)
- [pipe messages](https://github.com/albfan/miraclecast/commit/1e69dd6dae5f2332face744b247dbeb72036e0cf#diff-0bf57a4215d3f974dadf7868fe73d671R8)
- [create event messages](https://github.com/albfan/miraclecast/commit/1e69dd6dae5f2332face744b247dbeb72036e0cf#diff-e50333667268649cfca37aded33133ddR155)
- [create key messages](https://github.com/albfan/miraclecast/commit/1e69dd6dae5f2332face744b247dbeb72036e0cf#diff-e50333667268649cfca37aded33133ddR159)

Well, for multitouch events you just need to send:

<mouse event type>,<number of events>,<event id>,<x>,<y>[,<event id>,<x>,<y>]*

See pag 55 from spec on https://github.com/albfan/miraclecast#additional-urls for more information (you can read [online](https://es.scribd.com/doc/250439511/Wi-Fi-Display-Technical-Specification-v1-0-0) too)

A simple test configuration that will work would be to modify uibc-viewer (removing pipe)

<pre>
echo 'run "miracle-uibcctl $IP $UIBC_PORT" to send UIBC events'
gstplayer $@
</pre>

and start `miracle-uibcctl` alone. That way you can send multitouch events right now. See miracle-uibcctl.c come with all avaliable events half implemented (just need some corrections here and there)

https://github.com/albfan/miraclecast/commit/1e69dd6dae5f2332face744b247dbeb72036e0cf#diff-9e5e57e9123126a025d73d8154ba4d26R146

as it comes from an existing android open source implementation.

**Comment by wzhy90** [comment]
I add "Keyboard" to generic_cap_list and all alphabets work fine. But other key like "Enter", shift, control an so on didn't work.
As I input shift + A, it will input "┌" & "A". How to fix this?

**Comment by albfan** [comment]
I need to came out with something to provide feedback on these. There's no clear spec about some keystrokes.

Let me see if I can prepare something so you can collect input, expected output and real output

**Comment by albfan** [comment]
@wzhy90 #288 will be the place to get progress on that. Provide there logs for support https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support. I think UIBC traces must be seen on `journal.log`
