### ISSUE TITLE
Connect from android (Xperia L, cyanogenmod 11)

### ISSUE THREAD

**Issue by aurabindo** [albfan/miraclecast#58]
Hi,

I am trying to get wireless display to work from my xperia. So far I am able to get miraclecast to detect my device. However, the device is unable to connect to the sink.

miracle-wifid log is at http://pastebin.com/sj7bFx5U . At around line 275, you can see the device is detected.

Please guide me with further instructions on how to troubleshoot the problem and get the sink display to show up.

**Comment by albfan** [comment]
Hey. I totally miss this issue, sorry. Did you achieve to make it work? Can I close this? Did you start the `miracle-sinkctl`?

**Comment by aurabindo** [comment]
Hi,

No I didnt  not get it to work. But now my phone is running CM 13, so need to check if it works. You may close this. I didnt not try the software since a long time. I'd be trying it out soon. I'll update you if I make some progress. Thanks for follow up.

**Comment by albfan** [comment]
I here something about CM 12 even don't have miracast support (you can hack phone to have som kind of support)
