### ISSUE TITLE
 miracle-sinkctl  Fail

### ISSUE THREAD

**Issue by fmoyaarnao** [albfan/miraclecast#62]
Hello Alberto,

I have all miraclecast running and when I try to connect my device I have an error in "miracle-sinkctl".

I'm trying in a CentOS7. I need to download the systemd 221 and compiled it, because CentOS has the version 219.
I also download and compiled wpa_supplicant version 2.5, because CentOS has the version 2.0.

When I execute 

    $ sudo ./miracle-wifid --wpa-bindir /home/fmoya/wpa_supplicant-2.5/wpa_supplicant --log-level 7

I have the next output:

    INFO: miracle-wifid - revision some-rev-TODO-xyz Jan 23 2016 16:12:37
    INFO: link: add link: wlp2s0
    INFO: link: manage link wlp2s0
    INFO: supplicant: wpas spawned as pid:15723
    INFO: peer: add peer: 4e:74:03:e6:a3:2c
    INFO: peer: remove peer: 4e:74:03:e6:a3:2c
    INFO: peer: add peer: 4e:74:03:e6:a3:2c

When I execute 

    $ sudo ./miracle-sinkctl

I have the next output:

    [ADD] Link: 2
    [miraclectl] # run 2
    now running on link 2
    [ADD] Peer: 4e:74:03:e6:a3:2c@2
    [PROV] Peer: 4e:74:03:e6:a3:2c@2 Type: pbc PIN: 
    [GO NEG] Peer: 4e:74:03:e6:a3:2c@2 Type: pbc PIN: 
    [FAIL] Peer: 4e:74:03:e6:a3:2c@2 Reason: unknown
    no longer waiting for peer Aquaris M10 FHD (4e:74:03:e6:a3:2c@2)
    [REMOVE] Peer: 4e:74:03:e6:a3:2c@2
    [ADD] Peer: 4e:74:03:e6:a3:2c@2
    [miraclectl] # 

Thanks.

**Comment by albfan** [comment]
At that point you can enable a more verbose log `--log-level 8` (or more human readable `--log-level trace`) to know what decisions your hardware is taking

https://github.com/albfan/miraclecast/blob/master/src/shared/shl_log.c#L261

Post it here (inside a `<pre>` section please) to see what problem is happening underneath

**Comment by albfan** [comment]
Please update miraclecast repo. Now you can trace hardware tester this way:

    $ cd res
    $ export test_hardware_capabilities_DEBUG=1 
        # use export test_hardware_capabilities_DEBUG=10 for more verbose output
    $ ./test-hardware-capabilities.sh
        # use ./test-hardware-capabilities.sh &> trace_info to capture all stdout and stderr info

Post script execution output here (or trace_info contents if you capture it) to detect the problem.

**Comment by fmoyaarnao** [comment]
Hi Alberto,

here you have the output from "test-hardware-capabilities.sh" with test_hardware_capabilities_DEBUG=10
[trace_info.txt](https://github.com/albfan/miraclecast/files/104076/trace_info.txt)

**Comment by albfan** [comment]
sorry that message was not for you

**Comment by fmoyaarnao** [comment]
Hi Alberto,

I see this in "/var/log/messages"
<pre>Feb  7 20:59:11 fmoyalaptop miracle-wifid-wlp2s0-2: Successfully initialized wpa_supplicant
Feb  7 20:59:12 fmoyalaptop NetworkManager[903]: <info>  wpa_supplicant die count reset
Feb  7 20:59:35 fmoyalaptop miracle-wifid-wlp2s0-2: P2P-DEVICE-FOUND 3f:3a:3e:27:06:43 p2p_dev_addr=3f:3a:3e:27:06:43 pri_dev_type=10-0050F204-5 name='Android_3b52' config_methods=0x188 dev_capab=0x25 group_capab=0x0 wfd_dev_info=0x00101c440032 vendor_elems=1 new=1
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: P2P-PROV-DISC-PBC-REQ 3f:3a:3e:27:06:43 p2p_dev_addr=3f:3a:3e:27:06:43 pri_dev_type=10-0050F204-5 name='Android_3b52' config_methods=0x188 dev_capab=0x25 group_capab=0x0
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: P2P-GO-NEG-REQUEST 3f:3a:3e:27:06:43 dev_passwd_id=4 go_intent=0
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): using nl80211 for WiFi device control
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): driver supports Access Point (AP) mode
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): new 802.11 WiFi device (carrier: UNKNOWN, driver: 'ath9k', ifindex: 14)
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: P2P-FIND-STOPPED
Feb  7 20:59:44 fmoyalaptop systemd-udevd: Error changing net interface name 'p2p-wlp2s0-0' to 'wlp2s0': File exists
Feb  7 20:59:44 fmoyalaptop systemd-udevd: could not rename interface '14' from 'p2p-wlp2s0-0' to 'wlp2s0': File exists
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): device state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
Feb  7 20:59:44 fmoyalaptop kernel: IPv6: ADDRCONF(NETDEV_UP): p2p-wlp2s0-0: link is not ready
Feb  7 20:59:44 fmoyalaptop kernel: IPv6: ADDRCONF(NETDEV_UP): p2p-wlp2s0-0: link is not ready
Feb  7 20:59:44 fmoyalaptop systemd: Device sys-subsystem-net-devices-wlp2s0.device appeared twice with different sysfs paths /sys/devices/pci0000:00/0000:00:1c.3/0000:02:00.0/net/wlp2s0 and /sys/devices/pci0000:00/0000:00:1c.3/0000:02:00.0/net/p2p-wlp2s0-0
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): reset MAC address to DC:85:DE:F9:46:17
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <error> [1454875184.292445] [platform/nm-linux-platform.c:2878] do_change_link(): platform-linux: do-change-link: failure changing link 14: Unspecific failure (1)
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <error> [1454875184.292641] [platform/nm-linux-platform.c:2878] do_change_link(): platform-linux: do-change-link: failure changing link 14: Unspecific failure (1)
Feb  7 20:59:44 fmoyalaptop dbus[791]: [system] Activating via systemd: service name='fi.w1.wpa_supplicant1' unit='wpa_supplicant.service'
Feb  7 20:59:44 fmoyalaptop dbus-daemon: dbus[791]: [system] Activating via systemd: service name='fi.w1.wpa_supplicant1' unit='wpa_supplicant.service'
Feb  7 20:59:44 fmoyalaptop systemd: Starting WPA Supplicant daemon...
Feb  7 20:59:44 fmoyalaptop dbus[791]: [system] Successfully activated service 'fi.w1.wpa_supplicant1'
Feb  7 20:59:44 fmoyalaptop systemd: Started WPA Supplicant daemon.
Feb  7 20:59:44 fmoyalaptop dbus-daemon: dbus[791]: [system] Successfully activated service 'fi.w1.wpa_supplicant1'
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  wpa_supplicant running
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (wlp2s0): supplicant interface state: init -> starting
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <error> [1454875184.305780] [supplicant-manager/nm-supplicant-interface.c:766] interface_add_cb(): (p2p-wlp2s0-0): error adding interface: GDBus.Error:fi.w1.wpa_supplicant1.UnknownError: wpa_supplicant couldn't grab this interface.
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): supplicant interface state: starting -> down
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <error> [1454875184.320820] [supplicant-manager/nm-supplicant-interface.c:766] interface_add_cb(): (p2p-wlp2s0-0): error adding interface: GDBus.Error:fi.w1.wpa_supplicant1.UnknownError: wpa_supplicant couldn't grab this interface.
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): supplicant interface state: starting -> down
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (wlp2s0) supports 4 scan SSIDs
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <error> [1454875184.322347] [supplicant-manager/nm-supplicant-interface.c:766] interface_add_cb(): (p2p-wlp2s0-0): error adding interface: GDBus.Error:fi.w1.wpa_supplicant1.UnknownError: wpa_supplicant couldn't grab this interface.
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): supplicant interface state: starting -> down
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (wlp2s0): supplicant interface state: starting -> ready
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (wlp2s0): device state change: unavailable -> disconnected (reason 'supplicant-available') [20 30 42]
Feb  7 20:59:44 fmoyalaptop kernel: IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <error> [1454875184.325279] [supplicant-manager/nm-supplicant-interface.c:766] interface_add_cb(): (p2p-wlp2s0-0): error adding interface: GDBus.Error:fi.w1.wpa_supplicant1.UnknownError: wpa_supplicant couldn't grab this interface.
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): supplicant interface state: starting -> down
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <error> [1454875184.338351] [supplicant-manager/nm-supplicant-interface.c:766] interface_add_cb(): (p2p-wlp2s0-0): error adding interface: GDBus.Error:fi.w1.wpa_supplicant1.UnknownError: wpa_supplicant couldn't grab this interface.
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): supplicant interface state: starting -> down
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: P2P-GO-NEG-SUCCESS role=GO freq=2462 ht40=0 peer_dev=3f:3a:3e:27:06:43 peer_iface=8e:3a:e3:72:b2:04 wps_method=PBC
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: Could not set interface p2p-wlp2s0-0 flags (UP): Name not unique on network
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: nl80211: Could not set interface 'p2p-wlp2s0-0' UP
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: nl80211: deinit ifname=p2p-wlp2s0-0 disabled_11b_rates=0
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: p2p-wlp2s0-0: Failed to initialize driver interface
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: P2P: Failed to create new wpa_supplicant interface
Feb  7 20:59:44 fmoyalaptop avahi-daemon[780]: Withdrawing workstation service for p2p-wlp2s0-0.
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <info>  (p2p-wlp2s0-0): device state change: unavailable -> unmanaged (reason 'removed') [20 10 36]
Feb  7 20:59:44 fmoyalaptop ModemManager[762]: <info>  (net/p2p-wlp2s0-0): released by modem /sys/devices/pci0000:00/0000:00:1c.3/0000:02:00.0
Feb  7 20:59:44 fmoyalaptop miracle-wifid-wlp2s0-2: P2P-GROUP-FORMATION-FAILURE
Feb  7 20:59:44 fmoyalaptop NetworkManager[903]: <warn>  (p2p-wlp2s0-0): failed to disable userspace IPv6LL address handling
Feb  7 20:59:46 fmoyalaptop ModemManager[762]: <warn>  Couldn't find support for device at '/sys/devices/pci0000:00/0000:00:1c.3/0000:02:00.0': not supported by any plugin
Feb  7 20:59:47 fmoyalaptop NetworkManager[903]: <info>  (wlp2s0): supplicant interface state: ready -> inactive</pre>

**Comment by albfan** [comment]
Sure, but add `--log-level trace` output too please.

**Comment by fmoyaarnao** [comment]
Hi Alberto.

<pre>[fmoya@fmoyalaptop wifi]$ sudo ./miracle-wifid --wpa-bindir /home/fmoya/devel/wpa_supplicant-2.5/wpa_supplicant/ --log-level trace
INFO: miracle-wifid - revision 1.0 Feb  1 2016 23:10:24
INFO: link: add link: wlp2s0
INFO: link: manage link wlp2s0
INFO: supplicant: wpas spawned as pid:5358
INFO: peer: add peer: f2:8f:fe:13:23:4f
INFO: peer: add peer: e6:f8:ef:12:ac:2f
INFO: peer: remove peer: f2:8f:fe:13:23:4f</pre>

<pre>[fmoya@fmoyalaptop ctl]$ sudo ./miracle-sinkctl --log-level trace
[ADD] Link: 2
[miraclectl] # run 2
now running on link 2
[ADD] Peer: f2:8f:fe:13:23:4f@2
[PROV] Peer: f2:8f:fe:13:23:4f@2 Type: pbc PIN: 
[GO NEG] Peer: f2:8f:fe:13:23:4f@2 Type: pbc PIN: 
[FAIL] Peer: f2:8f:fe:13:23:4f@2 Reason: unknown
[ADD] Peer: e6:f8:ef:12:ac:2f@2
no longer waiting for peer Samsung (SM-T535) (f2:8f:fe:13:23:4f@2)
[REMOVE] Peer: f2:8f:fe:13:23:4f@2
[miraclectl] # </pre>

**Comment by albfan** [comment]
This kind of messages 

> Feb  7 20:59:44 fmoyalaptop NetworkManager[903]:  [1454875184.338351] [supplicant-manager/nm-supplicant-interface.c:766] interface_add_cb(): (p2p-wlp2s0-0): error adding interface: GDBus.Error:fi.w1.wpa_supplicant1.UnknownError: wpa_supplicant couldn't grab this interface.

suggest me there're two problems at least

Did you kill any network manager controlling your card or usb dongle?. Miraclecast starts itself a wpa_supplicant process

Did you see network interfaces on system dbus session. An easy way to see it is using [dfeet](https://wiki.gnome.org/action/show/Apps/DFeet?action=show&redirect=DFeet). On its system tab, you can filter by "miraclecast" to see them.

Remember to add dbus policy using [d-bus policy](https://github.com/albfan/miraclecast/blob/master/res/org.freedesktop.miracle.conf)

**Comment by fmoyaarnao** [comment]
I need to kill NetworkManager before launch "miracle-wifid"

But now I have the next error
<pre>[fmoya@fmoyalaptop wifi]$ sudo ./miracle-wifid -i wlp2s0 --wpa-bindir /home/fmoya/devel/wpa_supplicant-2.5/wpa_supplicant/ --wpa-loglevel trace --log-level trace
INFO: miracle-wifid - revision 1.0 Feb 13 2016 12:10:24
INFO: link: add link: wlp2s0
INFO: link: manage link wlp2s0
INFO: supplicant: wpas spawned as pid:10059
INFO: peer: add peer: 4e:74:03:e6:a3:2c
ERROR: supplicant: HUP on dhcp-comm socket on p2p-wlp2s0-0 (supplicant_group_comm_fn() in /home/fmoya/devel/miraclecast/src/wifi/wifid-supplicant.c:246)</pre>

Here is the output of d-feet
![screenshot from 2016-02-14 19-10-32](https://cloud.githubusercontent.com/assets/12513995/13035407/ab5ad92a-d34f-11e5-8947-e874f1cef2c0.png)

**Comment by albfan** [comment]
Well we are closer. kill network managers is by now the way to go.

You're receiving a https://en.wikipedia.org/wiki/SIGHUP from our custom dhcp server.

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L246

so probably it's not starting correctly. See it is an independent program `miracle-dhcp` so debug is not an easy task. Anyway if you find a way comfortable to you to trace it's execution, see this is the line where magic happens

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L524

to start `miracle-dhcp` on

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L524

you can issue that command alone an see if it's broken for a CentOS in some way

communication happens on commfd, hope that is not a too much low level debug. Let me know if there's something I can explain in more detail

**Comment by albfan** [comment]
Let me know if there's any progress on this.
