### ISSUE TITLE
Running on raspberry pi

### ISSUE THREAD

**Issue by tepf** [albfan/miraclecast#63]
I would like to run miraclecast as a server on my Raspberry Pi over Ethernet. `miracle-sinkctl` didn't find any links. And `res/test-hardware-capabilities.sh` would just `Calling CRDA to update world regulatory domain` a couple times and then stop.

As you might figured out by now I don't know much about this. Is this even possible or do you need a wifi dongle supporting Wifi-Direct?

**Comment by albfan** [comment]
Sure. I'm working on better self detection on wifi capabilities from miraclecast. iw maintainer points to some code extraction on iw to detect Wifi-Display support, but by now you should not if your system supports it.

Be sure you have iw installed (is used on hardware tester)

http://www.rpiblog.com/2012/12/turn-raspberry-pi-into-wireless-access.html

And be sure you use systemd to start your machine

http://blog.higgsboson.tk/2012/09/19/systemd-on-raspbian/

I make the assumption that systemd on raspberry comes without dbus support so you should recompile it. Is that above your skills or you can hack raspberry pi?

Don't know if raspeberry uses debian or ubuntu packages and you can benefit from 

https://github.com/albfan/systemd-ubuntu-with-dbus

or this raw instructions

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=systemd-kdbus

If you want to try post a good guide to build a raspeberry package and I can help you with the hardest parts

**Comment by tepf** [comment]
Yes I have `iw` installed. And I am actually using Arch Linux for ARM instead of Raspbian. `systemd` in version 228-3 and `dbus` are running as well. Not kdbus though.

I just ran `test-hardware-capabilities.sh` again and it said `No such file or directory (-2)` (no display connected this time, just ssh). I assume, because the `$WIFI_NAME` variable is empty and it didn't detect the network card.

Does this have something to do with `dbus`?

**Comment by albfan** [comment]
This is really interesting.

For unknown environments I use to provide a trace option. Let me upload it and see what's happening on tester script execution.

Good to know arch linux works on raspberry. That will ease config. Yes, you need to recompile systemd package to enable kdbus. Use my AUR package for that

Wait until I upload changes (It will be done in a couple of hours)

**Comment by tepf** [comment]
I cannot compile your `systemd-kdbus` package because the raspberry pi doesn't have `gnu-efi-libs` in it's repositories. I also wasn't able to compile `gnu-efi-libs` from the AUR because it was missing a header file `efibind.h`.

Furthermore I can't boot the Pi anymore because `rcu_sched_kthread` starves everytime (I guess because all the new dependencies I had to install to compile `kdbus` and `systemd-kdbus`)

Maybe I'll try it again some time, but for now I am at the end of my abilities. I am not quite comfortable with the fact that I have to replace the init system (and compile it on an embedded device).

**Comment by albfan** [comment]
Please update miraclecast repo. Now you can trace hardware tester this way:

    $ cd res
    $ export test_hardware_capabilities_DEBUG=1 
        # use export test_hardware_capabilities_DEBUG=10 for more verbose output
    $ ./test-hardware-capabilities.sh
        # use ./test-hardware-capabilities.sh &> trace_info to capture all stdout and stderr info

Post script execution output here (or trace_info contents if you capture it) to detect the problem.

**Comment by albfan** [comment]
About systemd dependency I cannot decouple from miraclecast at this time, so is a prerrequisite for use it.

To get the package you should take the steps to create a standard systemd package for raspberry pi and change configure step to enable kdbus.

See systemd is a freedesktop upstreams and every linux flavour make its changes over it to adapt to its distro.

**Comment by albfan** [comment]
Did you notice this:

https://github.com/archlinuxarm/PKGBUILDs/tree/master/core/systemd

These are the sources and patches to compile systemd for arm. I'm pretty sure there you can find a way to compile systemd with kdbus for raspberry pi.

**Comment by tepf** [comment]
I don't know how to compile it with kdbus. I am not a OS developer. Also shouldn't it already be included in Linux 4.4?

**Comment by albfan** [comment]
I'm collaborating with someone to get this to work.

Just need to clone repo, add `--enable-kdbus` on PKGBUILD and compile and install package with 

    $ makepkg -si

**Comment by tepf** [comment]
Alright I compiled it (it took > 2h). I forgot to append `-si` so I just installed `systemd-229-2-armv7h.pkg.tar.xz`, `libsystemd-229-2-armv7h.pkg.tar.xz` and `systemd-sysvcompat-229-2-armv7h.pkg.tar.xz` manually afterwards. I can't verfiy that kdbus is enabled like [this site](https://www.freedesktop.org/wiki/Software/systemd/kdbus/) suggests. I also added it to the kernel parameters.

I proceeded anyway and ran `test-hardware-capabilities` which got me this output:

````bash
[alarm@alarmpi res]$ ./test-hardware-capabilities.sh              
+ '[' 1 -ge 10 ']'
+ . miracle-utils.sh
++ ARPHRD_LOOPBACK=772
++ find_wireless_network_interfaces
+++ find_choosable_networknames
++++ ls /sys/class/net
+++ for i in '$( ls /sys/class/net )'
++++ cat /sys/class/net/eth0/type
+++ '[' 1 '!=' 772 ']'
+++ echo eth0
+++ for i in '$( ls /sys/class/net )'
++++ cat /sys/class/net/lo/type
+++ '[' 772 '!=' 772 ']'
++ for i in '$( find_choosable_networknames )'
++ '[' -d /sys/class/net/eth0/wireless ']'
+ WIFI_NAMES=
++ echo ''
++ wc -l
+ WIFI_COUNT=1
+ '[' 0 = 1 ']'
+ '[' 1 = 1 ']'
+ WIFI_NAME=
+ search_p2p_capabilities
+ WI_DEVICE=
++ find_physical_for_network_interface
+++ iw dev info
+++ grep wiphy
+++ awk '{print $2}'
++ PHY_INDEX=
++ '[' -n ']'
++ echo phy
+ PHY_DEVICE=phy
+ iw phy phy info
+ grep -Pzo '(?s)Supported interface modes.*Supported commands'
+ grep P2P
command failed: No such file or directory (-2)
+ echo Sorry, do not support P2P
Sorry, do not support P2P
+ exit 1
````

**Comment by bass0324** [comment]
Just a quick overview of what Alberto has helped me do to attempt to get running on the raspberry Pi

git clone https://github.com/archlinuxarm/PKGBUILDs.git
cd ./PKGBUILDs/core/systemd
vim PKGBUILD
     - edit line 12 to be "ARCH=('armv6h')" [ONLY IF BUILDING FROM RASPBERRY PI]
     - add line below line 67 '--enable-kdbus' (dont forget '\' at end of line above)
makepkg -si

One of the things I did not have setup was 'pacman -S iw'.  Once I did that, I still go the same does not support P2P errors.  You can test if your wireless device/driver supports p2p by issuing "iwpriv wlan0 p2p_set enable=1"  If you get 'no private ioctls', then your driver or device does not support wifi direct.  This is where I am at.  Need to fix the driver to support p2p and will work on getting miraclecast working on the pi.

**Comment by bass0324** [comment]
Also, to get the iwpriv command, do 'pacman -S wireless_tools'.

**Comment by tepf** [comment]
I got there as well, however I don't want to run it wirelessly but via ethernet.

What output do you get when running `dmesg | grep kdbus`?

**Comment by albfan** [comment]
I have forked and added systemd changes on

https://github.com/albfan/PKGBUILDs/blob/master/core/systemd/PKGBUILD

just clone and `makepkg -si` should be enough

See test-hardware capabilities is totally independent from this step. card or usb dongle with Wifi Direct is a prerrequisite, not achieved by enabling kdbus on systemd. kdbus is used to listen wifi events on an already wifi direct capable device.

See these guide for a general view and a particular approach for realtek devices.

http://dishingtech.blogspot.com.es/2012/01/realtek-wi-fi-direct-programming-guide.html

I have detected a few bugs on tester script, so I upload a correction.

@tepf seems the only card detected on your raspberry is `eth0` (cable) You need a wifi card or usb wifi as prerrequisite, with wifi direct capabilities. updated script should warn you about no wireless devices avaliable

@bass0324 about your problems,: I do compile some realtek drivers in past and is really straightforward. Realtek still provides original source

http://www.realtek.com.tw/downloads/downloadsView.aspx?Langid=1&PNid=48&PFid=48&Level=5&Conn=4&DownTypeID=3&GetDown=false&Downloads=true#RTL8192CU

it is a bunch of software supposedly patched for your chipset, but compilation instructions are wrong in many ways, you need to fix here and there, as you did on

https://github.com/bass0324/rtl8192cu

I'm interested on this, so I have forked your repo and added original from realtek just to keep it as reference

https://github.com/albfan/rtl8192cu/tree/original

See there's even a test for p2p (old name for Wifi Direct)

https://github.com/bass0324/rtl8192cu/tree/master/WiFi_Direct_User_Interface

so focus on that `install.sh` script to test your device

I have added a few corrections on a PR

https://github.com/bass0324/rtl8192cu/pull/1

Did not tested throughly but seems to work. If some command is old or some config need to be fixed this is the point to change config

https://github.com/bass0324/rtl8192cu/blob/master/WiFi_Direct_User_Interface/p2p_ui_test_linux.c#L154

Let me know any problems to fix them and get this working

**Comment by albfan** [comment]
@tepf there's now way to run a process based on wifi via ethernet.

Maybe you're asking for streaming video between two devices. miraclecast just connected to devices with Wifi direct and stream audio/video from created network between paired devices, but if you don't want the wifi handshake pairing process you can do simply running two vlc or gstreamer from commandline, but is not the point for this project.

@bass0324 let me know any progress you make.

**Comment by tepf** [comment]
@albfan Why didn't you tell me in the beginning? The issue was even called running it via ethernet. I just want the pi to take video from lets say an android phone screen cast and display it on a monitor via hdmi.

**Comment by albfan** [comment]
Yes I realize rereading your first post. I confuse network card or usb dongle when you talk about ethernet or usb dongle. I was focused on raspberry support for miraclecast, sorry.

Well hdmi is not ethernet anyway. You seem little confused about your objetives.

So your question seems to be resolved.

I will create a new issue for raspberri support. 

@bass0324 change to #66 for raspberry support

@tepf Feel free to close this.

**Comment by ralfeus** [comment]
Hi,
I'm trying to do same thing - create a sink on Ethernet host (has no wifi at all). Is such configuration supported? 
`test-hardware-capabilities.sh` with trace=1 shows this:
```
+ '[' 1 -ge 10 ']'
+ . miracle-utils.sh
++ ARPHRD_LOOPBACK=772
+ WIFI_COUNT=0
++ find_wireless_network_interfaces
+++ find_choosable_networknames
++++ ls /sys/class/net
+++ for i in $( ls /sys/class/net )
++++ cat /sys/class/net/br-1e8142f85cf3/type
+++ '[' 1 '!=' 772 ']'
+++ echo br-1e8142f85cf3
+++ for i in $( ls /sys/class/net )
++++ cat /sys/class/net/br-293de4c82bc5/type
+++ '[' 1 '!=' 772 ']'
+++ echo br-293de4c82bc5
+++ for i in $( ls /sys/class/net )
++++ cat /sys/class/net/br-60453a0a9334/type
+++ '[' 1 '!=' 772 ']'
+++ echo br-60453a0a9334
+++ for i in $( ls /sys/class/net )
++++ cat /sys/class/net/br-694a438f97c0/type
+++ '[' 1 '!=' 772 ']'
+++ echo br-694a438f97c0
+++ for i in $( ls /sys/class/net )
++++ cat /sys/class/net/br-a0367e80b91f/type
+++ '[' 1 '!=' 772 ']'
+++ echo br-a0367e80b91f
+++ for i in $( ls /sys/class/net )
++++ cat /sys/class/net/br-c8198378793b/type
+++ '[' 1 '!=' 772 ']'
+++ echo br-c8198378793b
+++ for i in $( ls /sys/class/net )
++++ cat /sys/class/net/docker0/type
+++ '[' 1 '!=' 772 ']'
+++ echo docker0
+++ for i in $( ls /sys/class/net )
++++ cat /sys/class/net/eno1/type
+++ '[' 1 '!=' 772 ']'
+++ echo eno1
+++ for i in $( ls /sys/class/net )
++++ cat /sys/class/net/lo/type
+++ '[' 772 '!=' 772 ']'
++ for i in $( find_choosable_networknames )
++ '[' -d /sys/class/net/br-1e8142f85cf3/wireless ']'
++ for i in $( find_choosable_networknames )
++ '[' -d /sys/class/net/br-293de4c82bc5/wireless ']'
++ for i in $( find_choosable_networknames )
++ '[' -d /sys/class/net/br-60453a0a9334/wireless ']'
++ for i in $( find_choosable_networknames )
++ '[' -d /sys/class/net/br-694a438f97c0/wireless ']'
++ for i in $( find_choosable_networknames )
++ '[' -d /sys/class/net/br-a0367e80b91f/wireless ']'
++ for i in $( find_choosable_networknames )
++ '[' -d /sys/class/net/br-c8198378793b/wireless ']'
++ for i in $( find_choosable_networknames )
++ '[' -d /sys/class/net/docker0/wireless ']'
++ for i in $( find_choosable_networknames )
++ '[' -d /sys/class/net/eno1/wireless ']'
+ WIFI_NAMES=
+ '[' -n '' ']'
+ '[' 0 = 0 ']'
+ echo There is no wireless devices available
There is no wireless devices available
+ exit 1
```

**Comment by albfan** [comment]
No, miracast is a protocol based on Wifi Direct

**Comment by drewsed** [comment]
I wonder how the guys from Aiserver managed this.

I have Aiserver installed on my xbox one, which is connected to a wifi Repeater via ethernet. My PC has no WiFi at all and is connected to my router.

In google chrome the xbox shows up as a Chromecast Ultra and i can stream my entire desktop.

**Comment by albfan** [comment]
@drewsed there's nothing special in stream a video signal. Is just miracast is a protocol to do using wifi direct to connect two devices.

**Comment by drewsed** [comment]
@albfan you are right, but they offer Airplay, Miracast and Chromecast. All of them are working with my Android, Apple and Windows devices natively and it doesn't matter whether I am connected to my router via WiFi or ethernet.

**Comment by albfan** [comment]
That's means they use different things for different use cases. Scope of miraclecast is not to stream anything by any channel, is just offer an implementation of miracast protocol.

**Comment by drewsed** [comment]
I don't get what you mean with different use cases. All I wanted to say and inform about is that there is an working solution which seems it ignores the Miracast spec in this detail and is working fine with a wired connection somehow.

If you will stay conform with the protocol I'm perfectly fine with that. Thanks for your hard work!

**Comment by albfan** [comment]
stream over ethernet is a different use case than stream over wifi direct.

People might have wrong impression there's a solution under miracast protocol to work on ethernet. Just that

**Comment by davispuh** [comment]
I'm also looking for a way to cast Android phone's screen to desktop PC. Android supports Miracast out of box, it's connected over WiFi to a router where PC is connected so they're both in same network. It should be possible to stream to PC which would have service listening.

**Comment by albfan** [comment]
get vlc and start a stream from your android. Open your PC and attach to that stream with vlc. miracast is a protocol based on wifi direct, for different spec you need to find different implementation than miraclecast
