### ISSUE TITLE
miracle-sinkctl: phone refuses connection

### ISSUE THREAD

**Issue by amarin-it-uc3m-es** [albfan/miraclecast#65]
Hi, 
I have setup miraclecast and run it with a USB wifi dongle. 
My android phone lg e975 discovers the server and I see the P2P group formation

<pre>
TRACE: wpa: raw message: <3>P2P-GROUP-STARTED p2p-0 GO ssid="DIRECT-rb" freq=2437 passphrase="XXXXXXX" go_dev_addr=14:cc:20:1f:65:8f
DEBUG: supplicant: ssid: DIRECT-rb (supplicant_event_p2p_group_started() in ../../../src/wifi/wifid-supplicant.c:1215)
DEBUG: supplicant: new group: p2p-0 (supplicant_group_new() in ../../../src/wifi/wifid-supplicant.c:484)
DEBUG: supplicant: start local group on new group p2p-0 as GO/1 (supplicant_event_p2p_group_started() in ../../../src/wifi/wifid-supplicant.c:1250)`
</pre>

dhcp starts, and my phone gets an IP address

<pre>
TRACE: wpa: raw message: IFNAME=p2p-0 <3>AP-STA-CONNECTED 42:b0:fa:bc:7a:de p2p_dev_addr=42:b0:fa:bc:fa:de
DEBUG: supplicant: bind peer 42:b0:fa:bc:fa:de to existing local group p2p-0 (supplicant_event_ap_sta_connected() in ../../../src/wifi/wifid-supplicant.c:1369)
DEBUG: supplicant: dhcp-comm-p2p-0: R:42:b0:fa:bc:7a:de 192.168.50.100 (supplicant_group_comm_fn() in ../../../src/wifi/wifid-supplicant.c:253)
</pre>

miracle-sink displays the connection:

<pre>
[ADD] Peer: 42:b0:fa:bc:fa:de@13
[PROV] Peer: 42:b0:fa:bc:fa:de@13 Type: pbc PIN:
[GO NEG] Peer: 42:b0:fa:bc:fa:de@13 Type: pbc PIN:
[CONNECT] Peer: 42:b0:fa:bc:fa:de@13
now running on peer 42:b0:fa:bc:fa:de@13
</pre>

But then it goes into a continuous loop showing the following messages:

<pre>
ERROR: cannot connect to remote host (111): Conexión rehusada (sink_connected() in ../../../src/ctl/ctl-sink.c:381)
NOTICE: HUP/ERR on socket
</pre>

The phone shows the icon of wifi-direct connected and the miracast screen shows "Establishing connection" without any progress. 

I can ping the phone from the server. It looks like the phone is waiting for something to initiate the connection. Any ideas?

Thanks.

**Comment by albfan** [comment]
Did you run commands with sudo?

Post here output of `sudo miracle-wifid --log-level trace` and `sudo miracle-sinkctl --log-level trace` to take a look

**Comment by foamboarder** [comment]
Hi Alberto,

I'm seeing the same error:
ERROR: cannot connect to remote host (111): Connection refused (sink_connected() in ../../../src/ctl/ctl-sink.c:392)
NOTICE: HUP/ERR on socket

For reference, I'm using Ubuntu 16.04.1 LTS and a Nexus 7 running Android 6.0.1. I also ran the commands with sudo. Here are the logs you requested.

[miracle-sinkctl.txt](https://github.com/albfan/miraclecast/files/415944/miracle-sinkctl.txt)
[miracle-wifid.txt](https://github.com/albfan/miraclecast/files/415945/miracle-wifid.txt)

**Comment by albfan** [comment]
HUP means something nasty happens outside control of miraclecast. Try

    $ sudo miracle-sinkctl --log-level trace

As journalctl didn't implement  regexp filter app name collect and post too this command output:

    $ sudo journalctl -f | grep miracle

Let's see where we are

**Comment by foamboarder** [comment]
I ran miracle-sinkctl with log-level trace and the log is the same as before. I see there's log-journal-level, should I be using that instead? It looks closer to the code in wifid:

https://github.com/albfan/miraclecast/blob/master/src/ctl/sinkctl.c#L788
https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid.c#L505

I'm attaching the journalctl log.
[journalctl.txt](https://github.com/albfan/miraclecast/files/416169/journalctl.txt)

**Comment by foamboarder** [comment]
I was able to connect the Nexus 7 for casting. However, I don't see any display. Here's the log from miracle-sinkctl.

[miracle-sinkctl-2.txt](https://github.com/albfan/miraclecast/files/419207/miracle-sinkctl-2.txt)

**Comment by albfan** [comment]
@foamboarder your log says that the phone is sending screen mirroring normally.

Try to run `miracle-sinkct`l with `--uibc`. At this time is the only way to use the python viewer. Seems it works better than the default `gst-launch` in some distros.

@amarin-it-uc3m-es any progress?

**Comment by foamboarder** [comment]
I tried --uibc but still don't see any display. I ran journalctl and it shows permission denied on uibc-viewer.

Aug 16 09:44:17 foo-OptiPlex-9010 miracle-dhcp-p2p-0[20578]: DEBUG: gdhcp: Broadcasting packet to client (<unknown>() in <unknown>:0)
Aug 16 09:44:17 foo-OptiPlex-9010 miracle-dhcp-p2p-0[20578]: DEBUG: gdhcp: lease_mac 0x1159f90 lease_nip 0x1159f90 (<unknown>() in <unknown>:0)
Aug 16 09:44:18 foo-OptiPlex-9010 miracle-sinkctl-gst[20581]: 20581
Aug 16 09:44:18 foo-OptiPlex-9010 miracle-sinkctl-gst[20581]: /usr/local/bin/uibc-viewer: line 18: /usr/local/bin/gstplayer: Permission denied
Aug 16 09:44:18 foo-OptiPlex-9010 miracle-sinkctl-gst[20581]: INFO: server 192.168.50.100 port 0
Aug 16 09:44:18 foo-OptiPlex-9010 miracle-sinkctl-gst[20581]: ERROR connecting: Connection refused
Aug 16 09:45:36 foo-OptiPlex-9010 miracle-wifid-wlx00c0ca849dab-3[20558]: P2P-DEVICE-LOST p2p_dev_addr=02:15:99:cd:68:6c
Aug 16 09:45:36 foo-OptiPlex-9010 miracle-wifid-wlx00c0ca849dab-3[20558]: P2P-DEVICE-LOST p2p_dev_addr=02:15:99:cd:81:f4
Aug 16 09:47:52 foo-OptiPlex-9010 sudo[20875]:      foo : TTY=pts/1 ; PWD=/home/foo/dev/miraclecast/res ; USER=root ; COMMAND=/bin/journalctl -f

**Comment by foamboarder** [comment]
It looks like gstplayer was not being copied to /usr/local/bin. I manually copied it and can see the display now. Thanks!

**Comment by albfan** [comment]
Did you install it with cmake?

There's a easy fix needed on

https://github.com/albfan/miraclecast/blob/master/res/CMakeLists.txt#L4

Send a PR and be part of the project!

**Comment by foamboarder** [comment]
I'm not really sure why gstplayer was not copied. I cleaned and rebuilt with autogen and everything works fine.

I added the fix for cmake in this pull request:
https://github.com/albfan/miraclecast/pull/106

**Comment by albfan** [comment]
Merged.

gstplayer is a recent change

From autotools:

    $ make distclean

Or from cmake:

    $ rm CMakeCache.txt

is needed to regenerate Makefiles.

@amarin-it-uc3m-es please check if that works.

Anyway detect what's happening with gst-launch would be nice. After sucessful connect miracle-gst can be launched manually with:

    $ miracle-gst -p 1991

Any problem must be output to stdout

**Comment by albfan** [comment]
Can I close this? Close if it is resolved please
