### ISSUE TITLE
Running on raspberry pi

### ISSUE THREAD

**Issue by albfan** [albfan/miraclecast#66]
install `iw` for use hardware tester script

http://www.rpiblog.com/2012/12/turn-raspberry-pi-into-wireless-access.html

Enable systemd with kdbus

http://blog.higgsboson.tk/2012/09/19/systemd-on-raspbian/

for archarm use this PKGBUILD

https://github.com/albfan/PKGBUILDs/tree/master/core/systemd

and `makepkg -si` on it

**Comment by bass0324** [comment]
Few updates to systemd folder:

Adjust below line to be "arch=('armv6h' 'armv7h')" to cover both original pi and pi 2
https://github.com/albfan/PKGBUILDs/blob/master/core/systemd/PKGBUILD#L13 

Was this line a copy and paste error? Not sure it was needed to be added.
https://github.com/albfan/PKGBUILDs/blob/master/core/systemd/PKGBUILD#L14


Update from the front of driver builds.  I am getting errors when attempting to build from source.  See errors in this file: https://www.dropbox.com/s/hbqrd17yu4p7okt/rtl8192cu%20build%20errors.txt?dl=0
I had to make some changes to build with arm from raspberry pi but unsure why these errors are occuring.  I am attempting to cross compile from my main pc and see if that works.

**Comment by albfan** [comment]
I have fixed systemd for arm and (by now) open an issue about driver compilation

Before trying to compile driver, can you accept my pull request?

https://github.com/bass0324/rtl8192cu/pull/1

and try `p2p_ui`?

https://github.com/bass0324/rtl8192cu/tree/master/WiFi_Direct_User_Interface

See it's a complete standalone example (it compiles all commands it will use for p2p test)

https://github.com/bass0324/rtl8192cu/blob/master/WiFi_Direct_User_Interface/p2p_ui_test_linux.c#L154

There's too a complete pdf guide on that directory

That way we can confirm your actual driver don't work and you need this new one.

**Comment by bass0324** [comment]
I have tried to use this test, which I have previously used with success on debian.  It does not seem to be working as it previously did, and I am unable to make the raspberry pi discoverable by my android device as I used to be able to.  Seems like the driver is the problem and not the commands.

**Comment by albfan** [comment]
Then let's focus on compile it. I have openened an issue with your compile problems

https://github.com/albfan/rtl8192cu/issues/1

But open it on your repo if you prefer.

As I told you I have compile a realtek driver time ago and should be an easy task, except for replace obsolete code or tweaks like that

**Comment by bass0324** [comment]
So it seems as though the realtek drivers are not supported on kernels > 3.9.  Without updated code that also supports the nl80211 driver within the rtl8192cu, it does not looks like it will be possible to run on the latest arch linux without going back to an older kernel (<3.9).  The other option is, wifi direct works perfect under debian, if we could get systemd with kdbus compiled for debian, we can run miraclecast under that.

**Comment by albfan** [comment]
Then you can search for compiling a package for raspbian. Try to find info about that. The upstream for systemd with kdbus on ubuntu is debian. There you can find rules to compile systemd with kdbus for debian. I guess it must be tweaked in some way to work on raspbian (maybe not)

Or you can take the inverse approach. Get the source for your driver working. Find the related kernel version, look for an archarm or raspbian with similar kernel and install that. It should work

**Comment by bass0324** [comment]
I think I am going to take the raspbian approach, hopefully I can get
source code for the systemd under raspbian if it differs at all from the
Debian source, then make the changes which were done in your Ubuntu branch,
and hopefully be able to get something to work.

**Comment by bass0324** [comment]
Seems as though systemd version > 221 will enable kdbus by default as long as kdbus=1kernel configuration is set. https://www.freedesktop.org/wiki/Software/systemd/kdbus/

So as long as I have systemd > 221, and kdbus module is installed and I set it in the kernel configuration, it should work. Is there any way to test kdbus support in systemd?

**Comment by albfan** [comment]
using d-feet you can check if there's dbus messages on your systemd

**Comment by bass0324** [comment]
I will have to check this tool out, I have taken a break from looking into this at the moment as there has been alot of other things consuming my time recently. Maybe I'll jump back into this this week and see if I can utilize this tool and get this working

**Comment by bpipi** [comment]
Hi all,

I am trying the miraclecast with Rpi(Raspbian OS with 8.0 jessie). I have followed the given steps. I got passed results with the test scripts present in the res folder. I have successfully compiled and installed. But when I am trying to launch wifi-daemon I am getting following error...

     miracle-wifid: /lib/arm-linux-gnueabihf/libsystemd.so.0: version 'LIBSYSTEMD_FUTURE' not found      (required by miracle-wifid) 
Could you please help with this?

Thanks

**Comment by albfan** [comment]
@bpipi that was solved on https://github.com/albfan/miraclecast/issues/68. Reopen if you still have problems.

**Comment by robotmaker42** [comment]
Hi, I am having trouble getting kdbus to work here is my error:


pi@raspberrypi:~/display/miraclecast/build $ cmake ..
-- Found Readline: /usr/include
-- Compiling with Readline support
-- Compiling with Readline support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/display/miraclecast/build
pi@raspberrypi:~/display/miraclecast/build $ make
[  3%] Building C object src/shared/CMakeFiles/miracle-shared.dir/rtsp.c.o
/home/pi/display/miraclecast/src/shared/rtsp.c:31:30: fatal error: systemd/sd-event.h: No such file or directory
 #include <systemd/sd-event.h>
                              ^
compilation terminated.
src/shared/CMakeFiles/miracle-shared.dir/build.make:54: recipe for target 'src/shared/CMakeFiles/miracle-shared.dir/rtsp.c.o' failed
make[2]: *** [src/shared/CMakeFiles/miracle-shared.dir/rtsp.c.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'src/shared/CMakeFiles/miracle-shared.dir/all' failed
make[1]: *** [src/shared/CMakeFiles/miracle-shared.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi:~/display/miraclecast/build $


I followed these instructions for enableing systemd on the raspberry pi:
http://blog.higgsboson.tk/2012/09/19/systemd-on-raspbian/


I have a raspberry pi 2, running the latest version of raspbian jessie, I have a tp-link wn722n wireless adapter. please help!

**Comment by albfan** [comment]
systemd comes by default with kdbus disabled. That guide only change your system to use systemd.

Process on debian system is something like this:

    $ mkdir sandbox
    $ cd sandbox
    $ apt-get source systemd
    $ sudo apt-get build-dep systemd
    $ cd systemd-<version>
        
        # Add kdbus compilation

    $ vi debian/rules

        # replace 

 CONFFLAGS_deb = \ 

        # with 

 CONFFLAGS_deb = \ 
      --enable-kdbus \

        # Then execute

    $  debuild -us -uc
    $ cd ..
    $ dpkg -i *.deb

Hope it helps, normally there's a lot of troubles in that steps. On ubuntu "there's more that a million ways to cannot compile a package"

I try to help providing https://github.com/albfan/systemd-ubuntu-with-dbus, but don't know if it feets on a raspberry. I recommend to change to archarm and use https://github.com/albfan/PKGBUILDs/tree/master/core/systemd

**Comment by bpipi** [comment]
Now I am running with arch linux. when I give miracle-sinkctl, sink is connecting successfully. But the mirroring screen is not appearing on the screen. 
I am attaching the image here. Please check it. It says SINK connected, but no display on the screen.
![img_20160427_115151](https://cloud.githubusercontent.com/assets/17920983/14843703/1704e2fc-0c70-11e6-8774-9e0d78e9cfaf.jpg)

**Comment by albfan** [comment]
Did you check all gstreamer plugins are installed?

https://github.com/albfan/miraclecast/blob/1cbfa5b42a9dcdce04e8c7b5267367f82611b327/res/test-viewer.sh

There's a work in progress to polish the stream player, see #78

It that fails or if you cannot see the player, you can install a stream player, like [vlc](http://www.videolan.org/vlc/) and try suggested option if gstreamer fails

https://github.com/albfan/miraclecast/blob/1cbfa5b42a9dcdce04e8c7b5267367f82611b327/res/test-viewer.sh#L38

That is:

    $ vlc rtp://@1991

**Comment by bpipi** [comment]
No I have tested with the ./res/test-viewer.sh. All required packages are installed, and all results were passed and final output was everything installed.

**Comment by albfan** [comment]
try it from vlc GUI. Menu "Media/Open Stream Network" and enter there the rtp url

**Comment by bpipi** [comment]
I am trying to open vlc but its not opening in gui mode. Now I am running arch linux with rpi in lxde desktop mode. But still its just connecting successfully without any display on the screen.

**Comment by albfan** [comment]
Try to fix vlc or gst. That has nothing to do with miraclecast.

You have to check if gst is working on your system

try:

    $ gst-launch videotestsrc ! xvimagesink

if it didn't show this

http://e2e.ti.com/cfs-file/__key/communityserver-discussions-components-files/354/8688.ZEY92J4L8N_2900_AHDD_7B00_F_7E007D00_OPUI.jpg

it is now working

See examples section:

http://docs.gstreamer.com/display/GstSDK/gst-launch

Same for vlc or whatever player capable of reproduce rtp streams.

**Comment by bpipi** [comment]
I have installed following gstreamer packages. Please tell me if any package is missing 
pacman -S --needed --noconfirm gst-plugins-bad gst-plugins-base gstreamer gstreamer0.10 gstreamer0.10-bad gstreamer0.10-bad-plugins gstreamer0.10-base-plugins gstreamer0.10-ffmpeg gstreamer0.10-good gstreamer0.10-good-plugins gstreamer0.10-python gstreamer0.10-ugly gstreamer0.10-ugly-plugins phonon-qt4-gstreamer

**Comment by albfan** [comment]
This script tells you:

https://github.com/albfan/miraclecast/blob/master/res/test-viewer.sh

but I guess your problem is you cannot run gst. If this script don't work as expected

    $ gst-launch videotestsrc ! xvimagesink

You need to fix that. miraclecast relay on other programs that do well it's work to complete the task, but you must asure they are working.

I can't tell you why vlc or gst don't work on your system, you must ask on their respective issue tracker for clues about your problem.

**Comment by robotmaker42** [comment]
I tried compiling systemd and kdbus on debian but hit too many roadblocks so I installed arch linux and tried to compile PKGBUILD but I keep getting the following error:

/home/now/display/PKGBUILDs/core/systemd/PKGBUILD: line 70: --with-sysvinit-path=: command not found
==> ERROR: A failure occurred in build().
    Aborting...
[now@alarmpi systemd]$

**Comment by bpipi** [comment]
Here is the output of the ./res/viewer.sh. It says everything is installed. 

testing plugins required:

test udpsrc... (passed)
test rtpjitterbuffer... (passed)
test rtpmp2tdepay... (passed)
test tsdemux... (passed)
test h264parse... (passed)
test avdec_h264... (passed)
test autovideosink... (passed)

everything installed

**Comment by albfan** [comment]
@robotmaker42, you try it on debian or on raspbian? this is for install miraclecast on raspberri pi. For amd64/i386 OS (arch linux, debian, ubuntu) there's another source packages avaliable.

**Comment by albfan** [comment]
@bpipi After check that you need to check that those test commands behave as expected. If not, there's something wrong with gst.

Again. gst, is just the miraclecast selection. on #78 we will work to use other players (feature wanted since #57 needs an special player with mouse event captures) if you have any working stream player just  use it.

**Comment by albfan** [comment]
I will close this as there's other issues where you can find a image to use with raspberry pi ready to use #100
