### ISSUE TITLE
Add some explainations about Systemd recompiling

### ISSUE THREAD

**Issue by jonalbertini** [albfan/miraclecast#67]
hi, I'm really interested on implementing miraclecast on Raspberry pi and some Linux OS,
I can't find any tutorial on how to recompile my systemd with the enable-kdbus option.
have you some tips to achieve this ?

**Comment by albfan** [comment]
read #66. There you have all the progress about that

is based on archarm (arch linux on arm)

Basically:

    $ git clone https://github.com/albfan/PKGBUILDs
    $ cd core/systemd
    $ makepkg -si

Restart and if you have a recent usb dongle it should work out of the box. If not please close this issue and collaborate on #66

**Comment by jonalbertini** [comment]
great! thank you for being so fast.
