### ISSUE TITLE
Using miraclecast on arch antergos

### ISSUE THREAD

**Issue by andreabauce** [albfan/miraclecast#69]
I use [arch antergos](https://antergos.com/]). I am a beginner. What steps I have to do to install miraclecast?

**Comment by albfan** [comment]
Since it is an arch linux flavour, you should be enable to compile it from AUR packages. Search for that on issues and you will find extensive information about that (remove the open issue filter)

Ask anything that blocks you with confidence, should be an easy task, but could be lot of new concepts new to you.

**Comment by andreabauce** [comment]
I installed following the instructions


I wrote in the terminal

export _systemd_git_kdbus = - enable-kdb


I downloaded the package is given

Yaort dpkgbuild


All right. He did not give any error.



Then I downloaded miracle-master

I copied the file

res / org.freedesktop.miracle.conf to /etc/dbus-1/system.d/


I run in sequence

Cmake ..

make

Sudo make install


performed compile all dependencies resolved.


But when I try to start with


sudo kill -9 $ (ps -ef | grep wpa_supplican [t] | awk '{print $ 2}')

sudo miracle-wifid &

sudo miracle-sinkctl
[ADD] Link: 3

> Run 3


Does not work…

 What am I doing wrong?

**Comment by andreabauce** [comment]
not knowing English using google. I certainly many errors

**Comment by albfan** [comment]
run it with --log-level trace, to see exact problem

**Comment by andreabauce** [comment]
how do I do it?

**Comment by albfan** [comment]
$ sudo miracle-wifid --log-level trace &
    $ sudo miracle-sinkctl --log-level trace

It can be really verbose. Try to detect exact part where device handshake happens and post it here

**Comment by andreabauce** [comment]
[ab@pcfix ~]$ INFO: miracle-wifid - revision 1.0 Mar 22 2016 07:40:12
DEBUG: friendly-name from local hostname: pcfix (manager_read_name() in ../../../src/wifi/wifid.c:367)
DEBUG: link: new link: wlp0s18f2u1 (3) (link_new() in ../../../src/wifi/wifid-link.c:71)
DEBUG: supplicant: new supplicant for wlp0s18f2u1 (supplicant_new() in ../../../src/wifi/wifid-supplicant.c:2082)
INFO: link: add link: wlp0s18f2u1
INFO: link: manage link wlp0s18f2u1
DEBUG: supplicant: start supplicant of wlp0s18f2u1 (supplicant_start() in ../../../src/wifi/wifid-supplicant.c:2564)
DEBUG: supplicant: spawn supplicant of wlp0s18f2u1 (supplicant_spawn() in ../../../src/wifi/wifid-supplicant.c:2411)
INFO: supplicant: wpas spawned as pid:1542
DEBUG: supplicant: open supplicant of wlp0s18f2u1 (supplicant_open() in ../../../src/wifi/wifid-supplicant.c:2245)
TRACE: wpa: raw message: OK
.....
TRACE: wpa: raw message: IFNAME=wlp0s18f2u1 <3>No network configuration found for the current AP
DEBUG: supplicant: unhandled wpas-event: <3>No network configuration found for the current AP (supplicant_event() in ../../../src/wifi/wifid-supplicant.c:1478)
TRACE: wpa: raw message: IFNAME=wlp0s18f2u1 <3>CTRL-EVENT-DISCONNECTED bssid=6c:b0:ce:24:a8:17 reason=3 locally_generated=1
...........
TRACE: wpa: raw message: IFNAME=wlp0s18f2u1 <3>CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
DEBUG: supplicant: unhandled wpas-event: <3>CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN (supplicant_event() in ../../../src/wifi/wifid-supplicant.c:1478)
TRACE: wpa: raw message: IFNAME=wlp0s18f2u1 <3>CTRL-EVENT-BSS-ADDED 13 3c:df:bd:e0:24:94
TRACE: wpa: raw message: IFNAME=wlp0s18f2u1 <3>CTRL-EVENT-BSS-REMOVED 0 6c:b0:ce:24:a8:17
TRACE: wpa: raw message: IFNAME=wlp0s18f2u1 <3>CTRL-EVENT-BSS-REMOVED 11 90:35:6e:9b:27:88
TRACE: wpa: raw message: IFNAME=wlp0s18f2u1 <3>CTRL-EVENT-BSS-REMOVED 5 f8:e9:03:eb:26:e3
TRACE: wpa: raw message: IFNAME=wlp0s18f2u1 <3>CTRL-EVENT-SCAN-RESULTS

**Comment by andreabauce** [comment]
[ab@pcfix ~]$ sudo miracle-sinkctl --log-level trace
[sudo] password di ab: 
[ADD] Link: 3
[miraclectl] #

**Comment by andreabauce** [comment]
I think I should abandon plans to run miraclecast?

**Comment by albfan** [comment]
I will check this again and tell you some hints if I can detect your problem

**Comment by albfan** [comment]
From your logs can see where is the problem. See README.md. At this point you need to start screen mirroring from source device. miraclecast is waiting for that.

**Comment by andreabauce** [comment]
I performed the procedure. but it still does not work. I ask you to write a more detailed installation procedure miracle cast, I am a Linux beginner. I'm afraid you may have missed some steps, I did not understand what it means to fill systemed with kdbus enabled. Very thanks for your work.

**Comment by albfan** [comment]
systemd comes with dbus disabled. Is the bus miraclecast uses to communicate with hardware. For antergos you can do something like this:

    $ git clone https://github.com/albfan/PKGBUILDs
    $ cd PKGBUILDs
    $ cd core/systemd
    $ makepkg -si

After that reboot and you should have a systemd with kdbus enabled

Here is the simple change needed

https://github.com/albfan/PKGBUILDs/commit/7c103a99d40b7d6a3bf4db06224ee01a839b1439#diff-ab9782e8eb5e35c2ab71ea1166329015R70

compile again miraclecast and tell if it is working now.

**Comment by albfan** [comment]
Any progress? can I close this issue?
