### ISSUE TITLE
Error with miracle-wifid

### ISSUE THREAD

**Issue by bpipi** [albfan/miraclecast#70]
Hi,
   I have a arm board with ubuntu 14.04. I am successfully built Miraclecast. But I am getting following error with miracle-wifid --wpa-bindir /sbin &

ERROR: link: invalid arguments (link_set_friendly_name() in ../../../src/wifi/wifid-link.c:190)

I am attaching the error screenshot. Please help me with this.

Thanks
![2016-03-23-095509_1440x900_scrot](https://cloud.githubusercontent.com/assets/17920983/13982260/fa4ba26c-f10e-11e5-8504-430c09128dc1.png)

**Comment by albfan** [comment]
Your systemd has not kdbus enabled so it cannot config wifi daemon miracle-wifid.

Everything fails after that

**Comment by albfan** [comment]
Suggestion: Run `miracle-wifid` on different tab to avoid mix it's output with `miracle-sinkctl`

**Comment by bpipi** [comment]
I have enabled the kdbus while compiling systemd-220. But still following error comes

ERROR: link: invalid arguments (link_set_friendly_name() in ../../../src/wifi/wifid-link.c:190)

[configure-systemd-with-kdbus.txt](https://github.com/albfan/miraclecast/files/225622/configure-systemd-with-kdbus.txt)

**Comment by albfan** [comment]
Ubuntu is compatible with systemd from version 15.04. Forget to make it work on older versions. Once you have a compatible ubuntu version, it is unlikely that you get kdbus from `configure --enable-kdbus` See config for arch linux 

https://github.com/albfan/PKGBUILDs/blob/master/core/systemd/PKGBUILD#L58

or ubuntu

https://github.com/albfan/systemd-ubuntu-with-dbus/blob/master/debian/rules#L13

real distros are more complex that `./configure make make install` even more for an init system.

**Comment by bpipi** [comment]
Here I am using ubuntu 14.04. How to make it compatible with systemd.
Now I will use archlinux, but can you tell me the steps to compile the systemd for the archlinux.
And More importantly, tell me the archlinux version which is compatible with systemd.

Thanks

**Comment by albfan** [comment]
It's not possible to use systemd with ubuntu 14.04.

arch linux is a rolling release, so you are always on lastest version. arch linux is using systemd long time ago.


Chek if you have makepkg installed. To do so:

    $ sudo pacman -S makepkg

to use systemd with kdbus, quickest way is:

    $ git clone https://aur.archlinux.org/systemd-kdbus.git
    $ cd systemd-kdbus
    $ makepkg -si

reboot

Anyway check yaourt. Is a manager for AUR (arch linux user repos) more convenience than install packages manually.

All these stuff is in README.md
