### ISSUE TITLE
miracle-wifid fails

### ISSUE THREAD

**Issue by bpipi** [albfan/miraclecast#71]
Hi,
   I have netgear wlan usb adaptor. It supports P2P interface. I have tested this adaptor with the ./test-hardware-capabilities.sh and ./test-wifi-capabilities.sh and it gives me wlan1 supports P2P output.
   I am using following contents in the /etc/wpa_supplicant/wpa_supplicant.conf        `ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1`

   But when I use miracle-wifid --wpa-bindir /sbin & command I am getting following output.
   
   Successfully initialized wpa_supplicant
   WARNING: supplicant : wpa_supplicant does not support wifi-display (supplicant_status_fn () in ../../../src/wifi/wifid-supplicant.c:1768) 

   After this the hostapd service will stop. I have to manually restart hostapd service.

   Could you please help me with this?

  Thanks

**Comment by albfan** [comment]
Did you kill existing wpa_supplicant process? Miraclecast starts its own tweaked to work on Wifi direct

**Comment by bpipi** [comment]
Yes killed before starting using ./res/kill-wpa.sh. But again same problem
Successfully initialized wpa_supplicant
WARNING: supplicant : wpa_supplicant does not support wifi-display (supplicant_status_fn () in ../../../src/wifi/wifid-supplicant.c:1768)

Please help me with this...

Thanks

**Comment by albfan** [comment]
https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L1678

See miraclecast just parses the wpa communication and it is not finding your wifi_display

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-supplicant.c#L1673

Run miracle-wifid adding `--log-level trace` (to show wpa messages) and find the problem. Paste it here then

**Comment by bpipi** [comment]
Hi,
   I am now running the miracle-sinkctl. 
   > run 3
   After running this command I am getting continuous messages like wlan1 : CTRL -EVENT-SCAN-STARTED. 
   And I want my android device should detect the miraclecast rather than miraclecast device detect my android device.

Please tell me how to achieve this

Thanks

**Comment by albfan** [comment]
Did you resolve this issue then?

For different problems, open different issues.

**Comment by albfan** [comment]
If this is still a problem I can reopen issue. Meanwhile you post logs I will close this
