### ISSUE TITLE
miraclecast for Beaglebone Black

### ISSUE THREAD

**Issue by leonliuxin** [albfan/miraclecast#74]
I want to transplant miraclecast on Beaglebone Black。Do you have any good suggestions。

**Comment by albfan** [comment]
What OS runs beaglebone? Here on #66 

https://github.com/albfan/miraclecast/issues/66#issue-135069752

you can find instructions for raspbian and archarm

See for archarm you have an AUR package for systemd with kdbus ready to compile and install.

Don't know your skills so ask anything you want at any level.

**Comment by leonliuxin** [comment]
Environment is ti-processor-sdk-linux-am335x-evm-02.00.01.07.Beaglebone Black runs debian OS.
The prompts that no package 'libsystemd' found when cross-compiler.I don't know how should I do!

**Comment by albfan** [comment]
you can follow this instructions for debian based OS (like ubuntu)

https://github.com/albfan/systemd-ubuntu-with-dbus/blob/master/README.md

Anyway, for debian OS, I think you should checkout a tag debian/XXX-X version, check your system to find exactly one. Feel free to open issues on that repo.

**Comment by leonliuxin** [comment]
Thank you, I have successfully transplanted miracle to BeagleBoneBlack.Excuse me, how to add HDCP and UIBC functions to miraclecast. Or have any good suggestions?

**Comment by albfan** [comment]
Great. Please provide a PR with info about it (on README.md) At least expose any details here and I will add in proper place.

About UIBC, I'm finishing the implementation. I'm testing it with fake data (I will upload a branch when it is stable) but I didn't analyze either how to capture mouse events. I suppose a simple gtk window will do the work. Follow #57 to stay tuned.

**Comment by Vadiml1024** [comment]
I'm having problems to build miracle cast for beagleboneblack:  
I'm using debian stretch and iǘe sucessfully installed gstreamer with all plugins
i've built miracle cast ...  but when i run res/testv-viewer.sh  i get:
testing plugins required:

test udpsrc... (passed)
test rtpjitterbuffer... (passed)
test rtpmp2tdepay... (passed)
test tsdemux... (passed)
test h264parse... (passed)
test avdec_h264...
	gst plugin "avdec_h264" not available
test autovideosink... (passed)

Some plugins required for visualization are missed

Try installing packages "gst-plugins-bad, gst-plugins-base, gst-plugins-base-libs, gst-plugins-good, gst-plugins-ugly, gst-libav, gstreamer".

If that fails too, try:

$ vlc rtp://@:1991


Any advice please
