### ISSUE TITLE
miracle-wifid fails with invalid arguments 

### ISSUE THREAD

**Issue by bpipi** [albfan/miraclecast#76]
This is the reference to #70. I have enabled the kdbus while compiling systemd-220. But still following error comes

ERROR: link: invalid arguments (link_set_friendly_name() in ../../../src/wifi/wifid-link.c:190)

I am attaching the error log.
[configure-systemd-with-kdbus.txt](https://github.com/albfan/miraclecast/files/225627/configure-systemd-with-kdbus.txt)

**Comment by albfan** [comment]
As this is the same as other issue, do not open another issue. Context is important to understand problem and provide solutions
