### ISSUE TITLE
Can I connect more than one peer to a unique sink?? 

### ISSUE THREAD

**Issue by NadaLess** [albfan/miraclecast#77]
hi I am interested on connect several miracast devices to a single sink and rendering them in a multiscreen app. Could it be possible with miraclecast?

**Comment by albfan** [comment]
Sure. Once paired you have source stream avaliable on rtp://@:1991, so you can source to whatever player you want (I recommend vlc)

vlc has a wall video filter, which I guess is what you want. https://software.grok.lsu.edu/article.aspx?articleid=14623. I suppose you can create undecorated windows to minimize the padding between windows.

**Comment by albfan** [comment]
Oopps! I read it the wrong way. You want exactly the opposite. See this issue, for work needed to pair more than one source to a sink #48

**Comment by NadaLess** [comment]
Thanks Alberto, I will take a look.

**Comment by albfan** [comment]
I will close this. ask to reopen if you have further questions
