### ISSUE TITLE
miracle-gst issues | need to add some stuff under -h (help) | some lag

### ISSUE THREAD

**Issue by midi1996** [albfan/miraclecast#78]
When I start the miracle-sinkctl (with or without extra commands) it loads at is should, connect but the miracle-gst doesn't show up automatically, I should do it manually or by using VLC as you suggested. 
For some reason when I use VLC the audio is playable but on miracle-gst the audio doesn't work, lack of codec maybe?
Now the miracle-sinkctl, using "-h" to change the resolution was a bit challenging. If you could add more help, and even clean it up, like: 
`# miracle-sinkctl -h`
`<outputs the commands, no detailed help here>`
`If you want more information type --help-all`
or something like that, that would be less of a hassle when looking for something.
And add and example for --res, I see that you already did but it's not that clear, when you show `--res <n,n,n>` we assume `n` is a number, so it's kinda confusing, you may add `example : --res default,CEA,00000400`
`this will change the resolution to CEA 1280x720`
This way it's very understandable and clear, even tho not that ergonomic, as you may see you already put the numbers beside each mode, using that number instead of 00000400 would be better.
Other than that, the casting is smooth, the audio playback is without skipped frames or whatsoever, but ofc there will be a lag from 1sec to 1.5 secs, not a big deal for me, as I see the audio and video sync perfectly, no over/underlapping which is totally amazing (unlike some TVs!!) but may be a problem with other users.
There a last problem: I see a ghost command (is that how is it named?), when I type `miracle<TAB>` the suggestions show `miracle-gst.sh` and it returns `permission denied`, looking for it using `which` gives `miracle-gst.sh not found`, is that the cause the sinkctl doesn't work, is it just trying to execute an nonexistent command?

Some logs are attached here.
[msink.txt](https://github.com/albfan/miraclecast/files/233190/msink.txt)
[mwifid.txt](https://github.com/albfan/miraclecast/files/233192/mwifid.txt)
[mgst.txt](https://github.com/albfan/miraclecast/files/233195/mgst.txt)

**Comment by albfan** [comment]
I see 5 issues here:
- Enable configurable player for stream
- Problems with audio stream in gst
- Add more help or wiki examples
- Ease usage of `--res` option
- Problems with `miracle-gst.sh` install

Although you have all that problems/feature request, is better o split them on different issues, and confront each one separately.

Despite of that, all seems to be affordable and useful changes, so please split this in 5 issues and let's work on it. i will guide you on all workflow.

**Comment by albfan** [comment]
Feel free to open such issues to work on them
