### ISSUE TITLE
Update README.md for Ubuntu 16.04

### ISSUE THREAD

**Issue by supertobi** [albfan/miraclecast#83]
As Ubuntu 16.04 uses systemd 229[1] and you wrote in your last commit[2]: "Systemd >= 221 will work out of the box." do we still use that alternative repo?

[1] https://launchpad.net/ubuntu/+source/systemd
[2] https://github.com/albfan/miraclecast/commit/a95de6395eb8c9d5b8d9f81c109b5d04b08ef16f

**Comment by albfan** [comment]
If that comments feels enough, please close this issue

**Comment by supertobi** [comment]
Yes, thanks. I think that's enough.
