### ISSUE TITLE
Missing sd-event.h file

### ISSUE THREAD

**Issue by suhassumukhv** [albfan/miraclecast#85]
I get the following error: 
`fatal error: systemd/sd-event.h: No such file or directory`
I run Ubuntu 16.04 and running `systemctl --version` gives me `systemd 229`. Despite being greater than 221 as you claim, I get the error. Is there no fix?

**Comment by albfan** [comment]
I guess you need to install libsystemd-dev. Are you using cmake or autotools for compilation?

**Comment by suhassumukhv** [comment]
cmake

**Comment by suhassumukhv** [comment]
Still, after installing `libsystemd-dev` causes more errors to spawn. The following error is caused: 
`undefined reference to symbol '__pthread_unregister_cancel@@GLIBC_2.3.3'`. Perhaps some extra parameters are missing? Or is it something else?

**Comment by albfan** [comment]
See this solution. Seems there's something related to pthreads and ubuntu 16.04

https://github.com/albfan/miraclecast/pull/82

But PR is not merged yet because seems an OS related issue so it must be added only when is needed (although I though it will have no effect on distros not needing pthreads to compile miraclecast)

Please give it a try and do a quick research if you can. If you find any hint I would test myself on a VM to give a general solution.

**Comment by suhassumukhv** [comment]
Yes, but leads to following errors again: 

`/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck_pic.a(check_log.o): In function 'subunit_lfun':
(.text+0x5f4): undefined reference to 'subunit_test_start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck_pic.a(check_log.o): In function 'subunit_lfun':
(.text+0x6bf): undefined reference to 'subunit_test_fail'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck_pic.a(check_log.o): In function 'subunit_lfun':
(.text+0x6d4): undefined reference to 'subunit_test_pass'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck_pic.a(check_log.o): In function 'subunit_lfun':
(.text+0x6ef): undefined reference to 'subunit_test_error'
collect2: error: ld returned 1 exit status
`
An apparent solution seems to be [this](http://paste.ubuntu.com/16248940/) :

**Comment by suhassumukhv** [comment]
Checked by adding a couple of `-lsubunit`s, but in vain. Could you look into this issue of where this option applies? `Linking C executable test_wpas` just doesn't happen.

**Comment by albfan** [comment]
Don't worry I'm installing an ubuntu VM to test it by myself. Really want to know what's the problem. systemd is 229.4, am here on arch linux is 230 and didn't see this dependency problems

**Comment by albfan** [comment]
Uhmm. My fault:

    $ pkg-config --cflags check
    -pthread

I forgot to add that to cmake. I'll fix it right away

**Comment by suhassumukhv** [comment]
Thank you, that fixes the issue.
