### ISSUE TITLE
Allow to use external player

### ISSUE THREAD

**Issue by albfan** [albfan/miraclecast#87]
Now there's gstplayer avaliable

https://github.com/albfan/miraclecast/blob/master/res/gstplayer

and uibc needs to start a complex chain of player and controller

https://github.com/albfan/miraclecast/blob/master/res/uibc-viewer

seems that is a good option to enable your own player for specific situations

Task is only about add config on this point

https://github.com/albfan/miraclecast/blob/1e69dd6dae5f2332face744b247dbeb72036e0cf/src/ctl/sinkctl.c#L391

so if `--external-player` have been provided use its value instead of those.

example:

```
$ miracle-sinkctl --external-player vlc
```

A little trick must be done for some players, like vlc, is they need to play as normal user. Since miracle-sinkctl start as root, it's forks play as well as root. To bypass this you can use a script like

```
USER=$(who -u | awk '{print $1}')
su $USER -c vlc "rtp://@:$PORT"
```

but if that `who` command don't work maybe an option to provide directly normal user name would be handy.

Another requirement is that different players can have different configuration options, so maybe an option with placeholders should be provided too (note simple quotes)

```
$ miracle-sinkctl --external-player vlc --player-options 'rtp://@$IP:$PORT'
```

**Comment by albfan** [comment]
Relates to #113

**Comment by albfan** [comment]
Use `regex.h`

http://www.gnu.org/software/libc/manual/html_node/Regular-Expressions.html

inside config file and new options to replace predefined variables

**Comment by valinoberry** [comment]
Pleace help me. 

Miracle runs now, but only with omxplayer. 

Can you give me the correct syntax for ( https://github.com/albfan/miraclecast/blob/1e69dd6dae5f2332face744b247dbeb72036e0cf/src/ctl/sinkctl.c#L391) that sinkctl starts with omx player with this parameters (sudo omxplayer -live -b - o hdmi rtp://192.168.50.1:1991)when I start the cast. 

Give thx

**Comment by albfan** [comment]
That's enough to implement this feature. Hope to do it these week

**Comment by valinoberry** [comment]
thank you very much

**Comment by albfan** [comment]
After update miraclecast you should be able to run omxplayer with

    $ miracle-sinkctl -e miracle-omxplayer

Details about omxplayer wrapper here

https://github.com/albfan/miraclecast/blob/master/res/miracle-omxplayer

suggestions are welcomed
