### ISSUE TITLE
The best suitable Linux distro for testing miraclecast

### ISSUE THREAD

**Issue by netmindms** [albfan/miraclecast#9]
I am very interesting in this project.
For building dependencies, I have built glib and systemd with --enable-kdbus on CentOS 7.
After building the sources successfully, I installed the outputs and reboot system. 
Then, system can't boot up normally. I think this failure is caused by systemd.

What's the suitable Linux OS for testing ???

**Comment by albfan** [comment]
- Arch linux is working smoothly (there is an aur package planned for ease
testing https://github.com/albfan/miraclecast/issues/6)
- Ubuntu recently changed from upstart to systemd (There is another issue
about configure it https://github.com/albfan/miraclecast/issues/8)
- Fedora should work too, but my prior tries didn't work (It was the time
when fedora was upgrading from upstart to systemd (fedora 15), surely now
it should work)

2015-03-18 3:14 GMT+01:00 blake kim <notifications@github.com>:

**Comment by ljbhander** [comment]
I am interesting in this project too.
I am test it in Ubuntu, but not succeed yet.
So I install a arch linux system to test it.
Follow the steps https://github.com/albfan/miraclecast.
First i test the wifi and environment
----------------------------------------------------------------------
iw list:
Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
		 * mesh point
		 * P2P-client
		 * P2P-GO
[root@nbpt res]# ./res/test_viewer.sh 
testing plugins required:

test udpsrc... (passed)
test rtpjitterbuffer... (passed)
test rtpmp2tdepay... (passed)
test tsdemux... (passed)
test h264parse... (passed)
test avdec_h264... (passed)
test autovideosink... (passed)

everything installed

[root@nbpt res]# 
----------------------------------------------------------------------

I set the res/miracle-wifi.sh with the propriety wifi device name.
I add some lines at the end of res/wpa.conf:
network={
	ssid="TP-LINK_6122"
	psk="nbpt5200"
}

Then:
res/miracle-wifi.sh
miracle-dhcp --netdev wls35u1(My wifi device name)
miracle-wifid &

[root@nbpt nbpt]# miracle-sinkctl 
[ADD] Link: 3
[miraclectl] # list
  LINK INTERFACE                FRIENDLY-NAME                 
     3 wls35u1                  nbpt                          

  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 

 0 peers and 1 links listed.
[miraclectl] # run 3
now running on link 3
[miraclectl] # list
  LINK INTERFACE                FRIENDLY-NAME                 
     3 wls35u1                  nbpt                          

  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 

 0 peers and 1 links listed.
[ADD] Peer: 6a:76:4f:b4:c2:75@3   (here use my phone to mirror, My pc did recognize my phone)
[miraclectl] # help
Available commands:
  list                                      List all objects
  show <link|peer>                          Show detailed object information
  run <link>                                Run sink on given link
  bind <link>                               Like 'run' but bind the link name to run when it is hotplugged
  quit                                      Quit program
  help                                      Print help
[miraclectl] # show 3
Link=3
InterfaceIndex=3
InterfaceName=wls35u1
FriendlyName=nbpt
P2PScanning=1
WfdSubelements=000600111c4400c8
[REMOVE] Peer: 6a:76:4f:b4:c2:75@3
[miraclectl] # 


But finally my phone(Sony z1) not connected my pc, 
Is there some steps should to do?

**Comment by albfan** [comment]
See your problem is about using miraclecast. This issue is about distros
supporting miraclecast installation.

Please open another issue about your problem, and remove your comments on
this if you don't mind, so people don't get mess (this is not a forum)

Hint: You are one step behind success.
