### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:898)

### ISSUE THREAD

**Issue by pimail1501** [albfan/miraclecast#90]
Hi Alberto,
I got this ERROR when running

`$ sudo miracle-wifid --wpa-bindir /sbin &`

ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:898)

And I found #20 ,but couldn't find your answer about miracle-wifi.sh in /res dir

wifi device also supports p2p.

the system is ubuntu 16.04, systemd 229

Thanks for help

**Comment by albfan** [comment]
Nowadays you just need to stop your network service and miraclecast starts wpa_supplicant

Use the elegant:

    $ sudo systemctl stop Network.service

or the nasty:

    $ sudo killall wpa_supplicant

All them should setup your environment correctly to run miraclecast succesfully.

**Comment by pimail1501** [comment]
Thanks a lot

after this ,`sudo miracle-wifid --wpa-bindir /sbin &` no error

but I thought the wifi icon was still  gone and wifi was closed

then `sudo miracle-wifictl`

the wifi icon was still gone and wifi was cloesed

however I got nothing when I inputted p2p-scan

No peers found

**Comment by albfan** [comment]
`miracle-wifictl` is to use laptop as source. See #4 if you are interested in.

to use laptop as sink (showing screen from other device) use:

    $ sudo miracle-sinkctl

or (for control source device from sink)

    $ sudo miracle-sinkctl --uibc

**Comment by pimail1501** [comment]
Thanks again

I finally got it ,and I connected my android phone successfully.Before that ,I used my iphone,it seemed couldn't work well in IOS.

However using this `sudo miracle-sinkctl` ,connect the android phone . How can I get the andoid screen? Is it auto to  open?

**Comment by albfan** [comment]
Check the test-viewer.sh on res/ directory. Some gst plugins are needed to see the streaming. More details on README.md prerrequisites section.

About apple devices, they don't implement miracast protocol, so it's not possible to use them with miraclecast.

**Comment by albfan** [comment]
If you want to play around with iThings and airplay check https://github.com/jamesdlow/open-airplay/blob/master/README.md

**Comment by pimail1501** [comment]
OK,thank you very much ,you are so kind.

**Comment by laar789** [comment]
Hi, I'm trying to run miraclecast in fedora 24, but I'm getting the error:
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:898)
when I run miracle-wifid, I tried every all the suggestions here, but no luck, still same error.

I think the problem is with fedora...can you tell if there is a solution for miraclecast to run in fedora_

**Comment by albfan** [comment]
@laar789 Did you follow install instructions on README.md? Did you copy dbus policy on /etc?

**Comment by laar789** [comment]
Thank you a lot, that was the step I miss, sorry...
Now, I have up miracle-wifid and miracle-sinkctl running, but how I do "Pair your machine with other miracast device (mirroring)", because I put in my tablet the wifi-direct option, then select my miraclecast (localhos.localdomain) and the tablet says "Invited" and it doesn't connect. In miracle-sinkctl i do a "List" and show my device:
[miraclectl] # list
  LINK INTERFACE                FRIENDLY-NAME                 
     3 wlp2s0                   localhost.localdomain         

  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 
     3 9a:3b:16:27:0d:45@3      Pipo_p4_luis                   no        
     3 3e:bb:fd:43:bb:0a@3      Galaxy J2                      no     

But I can't find the way to accept the invitation....

**Comment by albfan** [comment]
Wifi Direct is the way both devices see each other (create a net between them) but miracast is the protocol that uses that net and do the screen mirroring.

This is the screen where I start miracast protocol on my android

![screen mirroring on android](http://img.talkandroid.com/uploads/2014/10/roku_screen_mirror_01.png)

You can install an app to take you to screen mirroring

https://play.google.com/store/apps/details?id=com.mattgmg.miracastwidget&hl=es

But some phones simply don't implement it. I can confirm for example on a samsung galaxy grand2. Where that link don't do anything at all (although it takes you to screen mirroring display).

**Comment by adam-burns** [comment]
Hi @albfan & @laar789, 

I'm also running Fedora 24 and trying to get miraclecast to work.
Stopping both NetworkManager & wpa_supplicant through systemctl, I get the same error running miracle-wifid with or without --interface wlp3s0 option
'''
# miracle-wifid
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in ../../../src/wifi/wifid-dbus.c:898)
'''
However, I've inserted the udev rule:

'''
# cat /etc/udev/rules.d/10-network.rules 
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="00:24:d7:13:9f:d4", NAME="wlp3s0", TAGS+="miracle"
'''

**Comment by albfan** [comment]
@laar789 seems fedora do not have enabled wifi p2p on wpa_supplicant. See https://github.com/albfan/miraclecast/issues/101#issuecomment-260937660
