### ISSUE TITLE
How to know my Android mobile phone support UIBC？

### ISSUE THREAD

**Issue by Tm-git** [albfan/miraclecast#95]
Hi,UIBC is an interesting function，I tried a lot of times with my Android phone, but miracle-uibcctl doesn't connect to my Android phone. I heard that it's an optional option.So,how to know my Android mobile phone support UIBC？Or when my phone does not support UIBC, the miraclecast program will be what kind of tips?

**Comment by albfan** [comment]
if you enable `--log-level trace` on `miracle-sinkctl` you must see the conversation between your device and miraclecast. Some of that messages relates to uibc capabilities. Your device will inform if it allows uibc with wfd_uibc_setting (enable/disable)

https://github.com/albfan/miraclecast/blob/1e69dd6dae5f2332face744b247dbeb72036e0cf/src/ctl/ctl-sink.c#L275

I see I forgot to check this when you enabled `--uibc` on `miracle-sinkctl` Can you provide a patch? It should provide:

- Check for compatible configuration (using s->uibc_setting)
- Log for incompatible configuration
- Fallback to simple viewer

**Comment by Tm-git** [comment]
Modify as follows:
/* M4 (or any other) can pass presentation URLs */
printf("uibc_seteing=%s\n",s->uibc_setting);
r = rtsp_message_read(m, "{<s>}", "wfd_uibc_setting", &uibc_setting);
printf("r=%d\n",r);

The results are as follows：
uibc_seteing=(null)
r=-2

And  when I enable --log-level trace on miracle-sinkctl. I did not find capabilities UIBC in the mobile phone and miracast conversations.My phone also didn't remind me(enable/disable).
I use the HTC ONE (Android 5.1), I would like to ask you what kind of mobile phone when you are doing testing？

**Comment by albfan** [comment]
Many companies has its own screen mirroring implementation

https://www.youtube.com/watch?v=eFqUXyyWfQo

I use a samsung galaxy s4.

For patch I have opened #96

**Comment by albfan** [comment]
Now miraclecast respect the configuration. `--uibc` allows to use UIBC as long as source admits it.
