### ISSUE TITLE
Is there any clear user guide for newbies ? 

### ISSUE THREAD

**Issue by tezzcan** [albfan/miraclecast#97]
Hi, 
I am using Arch and I am a newbie. I installed the miraclecast from aur using yaourt. Everything seems good. But I don't know how to use it. Like a said, is there any easy to understand user guide ? 

Thanks.

**Comment by albfan** [comment]
Using AUR, things are getting easier and easier (see dbus policy is copied now on install)

README.md is a bit overloaded but on https://github.com/albfan/miraclecast#documentation you should find minimum steps to try miraclecast. 

Pass content to the wiki is a must (Maybe time to reopen #15) or create a web page.

These days in working on #98, which should hide all that boilerplate commands to run miraclecast

**Comment by albfan** [comment]
Did you solve your questions? Can I close this issue?

**Comment by tezzcan** [comment]
Yes I did. You can close, thank you.
