### ISSUE TITLE
Add options to pass additional parameters to supplicant

### ISSUE THREAD

**Issue by zer0def** [albfan/miraclecast#99]
Given how many distinct configurations are out there, I think it would benefit everyone if they were able to pass additional parameters both to wpa_supplicant's execution, as well as pass additional keyvals to the generated configuration file, without the need to patch and recompile the entirety of the project.

**Comment by albfan** [comment]
Totally agree. A more powerful approach would be use ini files.

 I'm playing around with ini files

https://github.com/albfan/RedmineJavaCLI/commit/086e0cfac824cc3efb686ccdbfe587abc29491c8

 and a `~/.miraclecast` is the way to go for lot of features (wpa_supplicant, uibc, resolution,  layout, custom buttons)

Anyway TMTOWTDI, and I like the idea to add command line options. Feel free to send a PR.

On wpa_supplicant itself there's an `update_config=1` which allows to modify wpa config on fly. I'm sure dbus allows you to change it too, so another way would be to provide new commands to controllers like `miracle-sinkctl`. Say a command `config` to tweak whatever.

**Comment by albfan** [comment]
See #113

**Comment by albfan** [comment]
All related to this on #113
